### ISSUE TITLE
给楼主提几个小意见

### ISSUE THREAD

**Issue by wenkok** [SuperMonster003/Auto.js_Projects#10]
能不能加入倒计时功能，例如当好友成熟时间到了，能量成熟的时候自动进入森林收取
不过现在这样也挺好了，谢谢

**Comment by SuperMonster003** [comment]
感谢提出意见和反馈
这个功能属于"定时任务功能"范畴
我先写完黑名单管理配置页面
然后看Auto.js作者是否开放Pro版本的定时任务API
一旦开放 立即写这个功能
否则会继续写图形配置页面的其他功能
如果6月底还没有开放API 我将不再等待 直接写免费版Auto.js可用的定时任务功能
(免费版版本包括但不限于 4.1.0 alpha5 以及 4.1.1 alpha2)
敬请期待
:smile:

**Comment by wenkok** [comment]
快等不及了哈哈，感谢回复，期待变得更好


 
---原始邮件---
发件人: "SuperMonster003"<notifications@github.com>
发送时间: 2019年4月22日(星期一) 晚上10:36
收件人: "SuperMonster003/Ant_Forest"<Ant_Forest@noreply.github.com>;
抄送: "Author"<author@noreply.github.com>;"wenkok"<347152966@qq.com>;
主题: Re: [SuperMonster003/Ant_Forest] 给楼主提几个小意见 (#10)


感谢提出意见和反馈
 这个功能属于"定时任务功能"范畴
 我先写完黑名单管理配置页面
 然后看Auto.js作者是否开放Pro版本的定时任务API
 一旦开放 立即写这个功能
 否则会继续写图形配置页面的其他功能
 如果6月底还没有开放API 我将不再等待 直接写免费版Auto.js可用的定时任务功能
 (免费版版本包括但不限于 4.1.0 alpha5 以及 4.1.1 alpha2)
 敬请期待
 :smile:

**Comment by feitianw** [comment]
希望能写个签到的，支付宝会员签到，或者其他APP

**Comment by SuperMonster003** [comment]
@feitianw 预计6月份会启动相关项目

**Comment by SuperMonster003** [comment]
@feitianw 签到项目已废弃
@wenkok 定时任务功能不再开发 感谢支持

**Comment by wenkok** [comment]
好的，麻烦了


 
---原始邮件---
发件人: "SuperMonster003"<notifications@github.com>
发送时间: 2019年5月29日(星期三) 中午12:27
收件人: "SuperMonster003/Auto.js_Projects"<Auto.js_Projects@noreply.github.com>;
抄送: "Mention"<mention@noreply.github.com>;"wenkok"<347152966@qq.com>;
主题: Re: [SuperMonster003/Auto.js_Projects] 给楼主提几个小意见 (#10)



@feitianw 签到项目已废弃
 @wenkok 定时任务功能不再开发 感谢支持

**Comment by SuperMonster003** [comment]
@wenkok 定时任务功能目前已上线 欢迎使用并反馈

**Comment by wenkok** [comment]
好的哈哈



---原始邮件---
发件人: "SuperMonster003"<notifications@github.com>
发送时间: 2019年8月14日(星期三) 上午9:18
收件人: "SuperMonster003/Auto.js_Projects"<Auto.js_Projects@noreply.github.com>;
抄送: "Mention"<mention@noreply.github.com>;"wenkok"<347152966@qq.com>;
主题: Re: [SuperMonster003/Auto.js_Projects] 给楼主提几个小意见 (#10)



@wenkok 定时任务功能目前已上线 欢迎使用并反馈
