### ISSUE TITLE
有时出现收取好友能量时反复进入同一好友主页。

### ISSUE THREAD

**Issue by luchangharry** [SuperMonster003/Auto.js_Projects#100]
布局策略有时出现反复进入同一好友主页不能退出的情况。
ps:很喜欢大佬的项目，已打赏支持！

**Comment by SuperMonster003** [comment]
感谢支持 😄  
反复进入同一个好友的问题已经出现很久了 一直也没有精力去修复 可能要先放一放再考虑修了  
可以先暂时用图像识别策略

**Comment by SuperMonster003** [comment]
`v1.9.5` 已尝试修复上述问题 如使用后问题复现 可继续反馈

**Comment by luchangharry** [comment]
目前测试没问题，明早的定时看一下有没有问题，超开心大佬又开始更新啦，准备最近购入mate30 pro,到时候如果有问题，再给大佬提供报告~
