### ISSUE TITLE
Essential Phone Ant_Forest_Settings.js内点击异常

### ISSUE THREAD

**Issue by mnnnnnmnnn** [SuperMonster003/Auto.js_Projects#102]
Essential Phone PH1 安卓7、8、9、10均会出现Ant_Forest_Settings.js内点击异常，表现为点开Ant_Forest_Settings.js后能正常运行，但点击里面的除了关于以外的任意设置选项均会出现选项内容但立马向右自动滑入空白页面，整个过程一闪而过，只能强制关闭auto.js重启，运行日志只有运行Ant_Forest_Settings.js，运行时长为到强制关闭的所用时间，无报错。

**Comment by SuperMonster003** [comment]
在 "./Modules/MODULE_MONSTER_FUNC.js" 中 
```js
duration = duration || 180; // 约 2216 行
```
此处参数可用于控制页面滑动时长 可尝试修改次默认值 (如 200 300 800 等) 测试问题是否可消除  

另后续版本可能会考虑增加滑动控制选项  
可通过关闭滑动动画避免此问题  
也可能会考虑优化代码 增强兼容性  

感谢反馈

**Comment by mnnnnnmnnn** [comment]
修改为200后就正常了，非常感谢！
