### ISSUE TITLE
运行脚本的时候出现错误

### ISSUE THREAD

**Issue by wbg21** [SuperMonster003/Auto.js_Projects#104]
![image](https://user-images.githubusercontent.com/55861485/65738595-f8b94e00-e114-11e9-830a-28b71f605ec5.png)
![image](https://user-images.githubusercontent.com/55861485/65738624-1dadc100-e115-11e9-94f4-4e55bbd7f4d7.png)

**Comment by SuperMonster003** [comment]
首先不要使用Auto.js的导入功能  
打开Auto.js 下拉刷新一下 会看到Auto.js_Projects-Ant_Forest文件夹  
进入文件夹后再运行Ant_Forest_Launcher.js

**Comment by sorgs** [comment]
解决了么，我也是这个问题，小米8

**Comment by limaonet** [comment]
我也是这个问题....

**Comment by SuperMonster003** [comment]
@limaonet 下载项目得到Zip文件 解压后得到文件夹 (仅一个文件夹) 将文件夹整体复制到"脚本"目录中
Auto.js运行后刷新一下 出现刚刚的文件夹 进去之后运行"Ant_Forest_Launcher.js"

**Comment by limaonet** [comment]
我现在用 vs code  调试的..
![image](https://user-images.githubusercontent.com/40821195/68450156-f7576700-0224-11ea-9a52-c10d7546509c.png)

**Comment by limaonet** [comment]
@SuperMonster003   你能帮我瞅瞅不 是不是环境问题 还是咋滴了

**Comment by SuperMonster003** [comment]
@limaonet node.js环境无法运行此项目
如果使用VSC 需使用VSC下载并加载[Auto.js免费版的扩展](https://marketplace.visualstudio.com/items?itemName=hyb1996.auto-js-vscodeext)
另外VSC的AJ插件在运行时 使用的cwd() `即当前工作目录` 是读取AJ的"默认脚本目录"配置值的 如果需要改变工作目录 需要在AJ中修改相关设置

**Comment by limaonet** [comment]
三克油大熏弟

**Comment by limaonet** [comment]
@SuperMonster003  小哥哥 , 苹果 版的auto.js  有吗

**Comment by SuperMonster003** [comment]
@limaonet 仅适用于Android系统
