### ISSUE TITLE
坚果Pro2s 屏幕无法解锁

### ISSUE THREAD

**Issue by orangexw** [SuperMonster003/Auto.js_Projects#105]
请教，之前配置过一次复杂密码，成功解锁，但是之后就不行了。设备可以正常亮屏到解锁界面，之后一直停留在此，并且重复滑动点击数字8这个位置。请大神看看问题出在哪里，如何解决呢？
![Screenshot_2019-09-28-18-16-44-138_Auto js](https://user-images.githubusercontent.com/55645077/65815067-e9bdc300-e21c-11e9-841c-1fb2d49bdc75.png)
![unlock_failed_20190928180314](https://user-images.githubusercontent.com/55645077/65815068-e9bdc300-e21c-11e9-9019-462b457908af.png)

**Comment by SuperMonster003** [comment]
报错原因是没有检测到解锁页面的控件 脚本以为当前仍在提示层页面 因此一直尝试划开提示层  
可尝试回退版本 找到可以成功解锁的版本 并反馈版本号  
如尝试其他版本依旧无法解锁 可使用 Tools 文件夹内的 Inspect_Sreen_Layout.js 反馈解锁布局信息

**Comment by orangexw** [comment]
已将解锁布局信息置于附件压缩文件中，感谢大神适配。
[Inspect_Sreen_Layout.zip](https://github.com/SuperMonster003/Auto.js_Projects/files/3665545/Inspect_Sreen_Layout.zip)

**Comment by SuperMonster003** [comment]
`v1.9.3` 已尝试增加此机型适配  
此 Issue 暂时关闭  
如问题复现或出现新问题 可重新反馈 感谢支持

**Comment by orangexw** [comment]
感谢作者的更新，经测试，提交的这个问题还是没有解决，还是会重复滑动点击数字8这个位置。
但此次更新后改为复杂密码的登录方式，可以正常滑动并输入密码，但因没有添加点击‘完成’按钮，不会解锁，停留在密码输入界面，见附图一并附上解锁方式的截图。
看到作者答复后，赶紧测试，并来提交问题，惜闻作者停止更新，那请教一下，如何添加点击完成按钮，应该放在哪段js文件中，再次感谢作者的付出。
![Screenshot_2019-10-01-12-01-48-459_设置](https://user-images.githubusercontent.com/55645077/65933531-6979a680-e444-11e9-9fa4-ebf9461a589c.png)
![Screenshot_2019-10-01-12-02-00-005_锁屏](https://user-images.githubusercontent.com/55645077/65933538-71d1e180-e444-11e9-93ff-6b458daa1e5c.png)

**Comment by orangexw** [comment]
再次附上复杂密码解锁布局信息压缩文件。
[lock_screen.zip](https://github.com/SuperMonster003/Auto.js_Projects/files/3674398/lock_screen.zip)

**Comment by SuperMonster003** [comment]
`v1.9.4` 已在解锁模块中增加自动尝试点击完成按钮功能 请尝试更新版本后检查问题是否复现并欢迎再次反馈
