### ISSUE TITLE
无法从支付宝自动获取账户，设置了也无法自动登录

### ISSUE THREAD

**Issue by icyagi** [SuperMonster003/Auto.js_Projects#106]
如题
自动采集显示管道支付宝破裂？
“relativeNode的node参数为Null”

设置登录账户后也能跳到登录页面，但是不自动输入账号
“控件输入账户名失败”

**Comment by SuperMonster003** [comment]
可通过Auto.js自带的控件分析工具将clickActionsPipeline()方法中的参数做调整与适配
