### ISSUE TITLE
排行榜滑动出现错误

### ISSUE THREAD

**Issue by Love-ni** [SuperMonster003/Auto.js_Projects#107]
![Screenshot_20190930_082728](https://user-images.githubusercontent.com/55963334/65842231-96528e80-e35c-11e9-98a5-780f21b107e2.jpg)

**Comment by SuperMonster003** [comment]
可尝试将排行榜样本采集策略修改为图像识别

**Comment by Love-ni** [comment]
@SuperMonster003 改了还是不行，更新了1.9.3还是不行。以后不更新了吗？？？

**Comment by SuperMonster003** [comment]
`v1.9.5` 已尝试修复上述问题 如使用后问题复现 可继续反馈
