### ISSUE TITLE
大佬看看怎么回事

### ISSUE THREAD

**Issue by usehei** [SuperMonster003/Auto.js_Projects#108]
重试两次后，就停留在排行榜界面。但是他过一会跳出来重新执行，
![QQ图片20190930085744](https://user-images.githubusercontent.com/22762701/65842773-63aa9500-e360-11e9-82e9-823d77012c14.png)

**Comment by SuperMonster003** [comment]
Promise没有all方法的问题可尝试更新Auto.js为最新版 (4.1.1 alpha2) 来尝试解决  
另目前项目的解锁与运行结束的锁屏逻辑与上述所及相匹配 请开启开发者测试模式后查阅操作日志
