### ISSUE TITLE
进入蚂蚁森林界面，然后卡死了

### ISSUE THREAD

**Issue by aizya** [SuperMonster003/Auto.js_Projects#11]
进入蚂蚁森林界面，下一步应该是收取自己能量的，但是手机一直卡在这里，没有反应，但是后台脚本还是一直在运行的。我怀疑是不是有死循环。。 手机是红米note7. autojs版本是4.1.1

**Comment by SuperMonster003** [comment]
感谢反馈
请说明使用的项目版本号 (如1.5.14)
另外脚本卡住的时候 支付宝页面停在何处 (如蚂蚁森林主页)
脚本日志截图最好也提供一下

**Comment by aizya** [comment]
版本是最新的，v1.5.14， 然后我表述有点问题，不是卡死，而是一直没有响应

![image](https://user-images.githubusercontent.com/22078443/56577934-e3d50d80-65fe-11e9-835e-39984e8993c9.png)

停止还是我手动杀掉的。 如果主页面上有能量，那就卡在主页面上，如果没有能量，那么卡在排行榜上，是不是因为没有截图的权限导致的？ 我也不是很理解里面的机制，。

**Comment by SuperMonster003** [comment]
Auto.js版本是多少 是`Pro-7.0.1`以上吗

**Comment by aizya** [comment]
不是，Pro不是要收费吗，就没用。。

**Comment by aizya** [comment]
![image](https://user-images.githubusercontent.com/22078443/56578285-de2bf780-65ff-11e9-9ef5-70e8a07cbce6.png)

**Comment by SuperMonster003** [comment]
经测试  
`4.1.0 alpha3` 确实无法运行 卡在排行榜开始位置  
我会尽快找出问题根源 无论是代码的还是 `4.1.0 alpha3` 的  
目前可以尝试使用 `4.1.0 alpha5` 或 `4.1.1 alpha2`  
😃

**Comment by aizya** [comment]
好的，太谢谢了

**Comment by aizya** [comment]
我使用了4.1.1 alpha2，還是不行。

**Comment by SuperMonster003** [comment]
今晚发布试修版

**Comment by SuperMonster003** [comment]
已于 `v1.5.18` - `2019/04/26` 尝试修复此问题

**Comment by aizya** [comment]
已经可以收取能量了，但是在运行过程中发现了空指针。

![image](https://user-images.githubusercontent.com/22078443/57290290-b05eac80-70ef-11e9-8df8-4202c13d1806.png)

**Comment by SuperMonster003** [comment]
感谢反馈  
`2327` 在 `2330` 引用的时候才会出出现null pointer ex  
所以在 `2330` 用了 `try{} catch(e){}`  
这个应该不会报错的 因为会出现前面判断控件存在 等到获取它bounds()的时候 控件在短短几十ms内消失了 导致bounds()指向 `null` 的情况  
如果有日志报错或其他异常 欢迎继续反馈  
:smile:

**Comment by aizya** [comment]
有一个小问题，帮他人收取功能，如果存在多个代收去对象，只会帮收取一个。

**Comment by SuperMonster003** [comment]
@aizya 
感谢反馈  
初步怀疑是多个球点击间隔太快导致的  
多个绿色能量球有只点击一个的现象吗  
开启开发者测试模式 然后看一下日志里"点击帮收能量球"的个数与实际是否相符  
再看看数据稳定相关的日志有没有异常

**Comment by aizya** [comment]
多个绿色能量球有目前没有这种现象，只有帮他人收取的时候才存在。
