### ISSUE TITLE
黑名单误触

### ISSUE THREAD

**Issue by Qingtian-creat** [SuperMonster003/Auto.js_Projects#111]
脚本版本1.9.2，支付宝版本10.1.75，排行榜收集采用的是布局分析，自定义黑名单之后运行脚本经常会出现误触黑名单中好友的情况，黑名单好友在25-30人左右，采用图像识别策略之后误触率更高，麻烦大佬分析分析是什么情况，谢谢！

**Comment by SuperMonster003** [comment]
两个设备测试后均未能复现上述问题 故暂时无法解决

**Comment by SuperMonster003** [comment]
`v1.9.4` 已发布 请尝试更新版本后检查问题是否复现并欢迎再次反馈
