### ISSUE TITLE
项目停止更新通知

### ISSUE THREAD

**Issue by SuperMonster002** [SuperMonster003/Auto.js_Projects#112]
项目存活共计195天  现正式停止维护  感谢所有支持过的朋友  

目前未解决的问题: 
1. 全局变量过多  
2. 图形配置页面代码庞杂且初始加载耗时过多 
3. 布局分析时常遇到视觉库断言异常问题  
4. 部分机型能量球控件无法识别  
5. 部分机型自定义黑名单无效  
6. 部分机型项目运行过程中内存溢出 (OOM)  
7. 部分机型无法实现自动登录功能    

目前未完成的部分  
1. 统计功能  
2. 返水功能  
3. 能量球识别策略 - 图像识别  
4. 主页能量倒计时备用OCR策略优化  
5. 排行榜样本图像识别采集策略的黑名单检测优化  
6. 多语言功能  
7. 项目文档

**Comment by ljx0623** [comment]
感谢作者一直以来的努力和付出！~

**Comment by Love-ni** [comment]
感谢作者一直以来的努力和付出！

**Comment by Zhang-Ingram** [comment]
好可惜

**Comment by orangexw** [comment]
感谢作者一直以来的付出，谢谢！只是停止更新了，好可惜。

**Comment by Baninn** [comment]
感谢作者

**Comment by VergLsm** [comment]
感谢作者

**Comment by lsjiaowo** [comment]
感谢作者的脚本，非常好用，特来顶贴

**Comment by gcddxp** [comment]
停更了，真可惜啊，谢谢作者

**Comment by wangjian3021** [comment]
感谢

**Comment by Sakakibara-Hu** [comment]
感谢作者的付出。

**Comment by Big-Bubble** [comment]
感谢！

**Comment by chemboy0609** [comment]
感谢作者！

**Comment by chengtaocp741** [comment]
感谢作者！
