### ISSUE TITLE
打开Auto.js失败

### ISSUE THREAD

**Issue by koftt** [SuperMonster003/Auto.js_Projects#113]
1.9.3   日志显示 “开始蚂蚁森林任务”  然后就显示 打开Auto.js失败    就没反应了

**Comment by koftt** [comment]
> 1.9.3日志显示“开始蚂蚁森林任务”然后就显示打开Auto.js失败就没反应了

**Comment by DreamWorld110** [comment]
怎么样？请问解决了吗？我也遇到了这个问题

**Comment by SuperMonster003** [comment]
如果是小米机型 给 `Auto.js` 后台弹出权限

**Comment by DreamWorld110** [comment]
> @DreamWorld110 如果是小米机型 给 `Auto.js` 后台弹出权限

谢谢！确实解决了
