### ISSUE TITLE
运行报错，米8

### ISSUE THREAD

**Issue by sorgs** [SuperMonster003/Auto.js_Projects#115]
18:16:39.044/V: 开始运行[/storage/emulated/0/脚本/Auto.js_Projects-Ant_Forest/Ant_Forest_Launcher.js]
18:16:39.252/E: Java class "com.stardust.autojs.engine.LoopBasedJavaScriptEngine" has no public instance field or method named "execArgv". (<Ant_Forest_Launcher>#3924)
 at script.checkTasksQueue(<Ant_Forest_Launcher>:3924)
 at script(<Ant_Forest_Launcher>:69)
18:16:39.253/V: 
------------
[/storage/emulated/0/脚本/Auto.js_Projects-Ant_Forest/Ant_Forest_Launcher.js]运行结束，用时0.208000秒

**Comment by wsw87201326** [comment]
P30也出现了这个错误

**Comment by Khan-KK** [comment]
华为v10也是这个错误

**Comment by SuperMonster003** [comment]
尝试更新 `Auto.js` 版本解决上述问题
另 `v1.9.4` 完善了版本检测功能 可提示当前 `Auto.js` 的版本是否不适用于此项目

**Comment by sorgs** [comment]
thx
