### ISSUE TITLE
最近每次打开蚂蚁森林都会点左上角的双十一（浇水的喵币），然后就不动了，，偶尔几次能正常运行

### ISSUE THREAD

**Issue by usehei** [SuperMonster003/Auto.js_Projects#117]

**Comment by usehei** [comment]
![image](https://user-images.githubusercontent.com/22762701/68369371-1a2a4280-0175-11ea-922b-a24670b54256.png)
 底下提示这个

**Comment by SuperMonster003** [comment]
`v1.9.4` 已发布 请尝试更新版本后检查问题是否复现并欢迎再次反馈

**Comment by usehei** [comment]
OK。已解决。谢谢作者。
现在日志里会有这么一堆东西，但是影响使用。

![image](https://user-images.githubusercontent.com/22762701/68540368-ff9dd680-03cb-11ea-9705-f1f7b42eeceb.png)

**Comment by SuperMonster003** [comment]
`v1.9.5` 已尝试修复上述红色日志报错 如问题复现 可继续反馈
