### ISSUE TITLE
小米8 1.9.4 报错 CvExeption

### ISSUE THREAD

**Issue by sangbobo** [SuperMonster003/Auto.js_Projects#118]
![Screenshot_2019-11-08-16-40-14-945_org autojs aut](https://user-images.githubusercontent.com/5309706/68464306-5e881200-024b-11ea-88f1-15de0a77d7cb.png)

**Comment by SuperMonster003** [comment]
https://github.com/SuperMonster003/Auto.js_Projects/issues/81
关于OpenCV的问题目前将不予修复

**Comment by sangbobo** [comment]
@SuperMonster003 你的意思是OpenCV有BUG吗？那我尝试着替换Auto.js/app/libs/opencv-3.4.3.aar 为3.4.8版本 ，然后重新打包auto.js试一下？

**Comment by SuperMonster003** [comment]
不是OpenCV有Bug
因为我不想修复本身项目的代码
之前也尝试修复过 一直没成功 还会引出更多问题
现在也没有那份精力再去修复与视觉库报错相关的代码问题了

**Comment by SuperMonster003** [comment]
不是OpenCV有Bug
因为我不想修复本身项目的代码
之前也尝试修复过 一直没成功 还会引出更多问题
现在也没有那份精力再去修复与视觉库报错相关的代码问题了

**Comment by SuperMonster003** [comment]
`v1.9.5` 已尝试修复上述问题 如使用后问题复现 可继续反馈

**Comment by sangbobo** [comment]
试用了两天，暂时未发现问题，辛苦大佬了，嘿嘿
