### ISSUE TITLE
vivo nexs能识别可收取好友，但是进去后不能收取能量

### ISSUE THREAD

**Issue by Huanyueyichen** [SuperMonster003/Auto.js_Projects#119]

**Comment by SuperMonster003** [comment]
部分机型森林页面控件变更 无法获取到能量球控件 (最早发现于Jul 24, 2019)
此问题目前暂时无解 日后可能会考虑使用图像及颜色识别方式实现能量球定位
鉴于此方式实现较为复杂 且耗时很长 故无法保证完全可行性及时效

**Comment by angryhen** [comment]
@SuperMonster003 VIVO 的 iqoo也这样，而且自己的能量也没收

**Comment by SuperMonster003** [comment]
@angryhen 
1. 反馈一下脚本是否能自动点击进入好友森林
2. 自行排除是否是基于无障碍服务的方法在设备上无法使用  ( 如 click() press() gesture() swipe() 等 )

**Comment by botaozhao** [comment]
@SuperMonster003

**Comment by ObsidianBeacon** [comment]
VIVO Z1也无法收取能量球

**Comment by ObsidianBeacon** [comment]
VIVO Z1也一样，可以进入好友列表并进入可收取能量好友的森林，但是不会自动收取能量球。
