### ISSUE TITLE
脚本运行错误，求解！

### ISSUE THREAD

**Issue by zhangguangjin** [SuperMonster003/Auto.js_Projects#122]
你好，大神，之前用的是1.7.0，运行没什么问题，就是偶尔要清除下程序存储，用到今天来更新了下，1.9.4，可以解锁，但不运行程序，提示19:19:55.264/E: JavaException: java.lang.IllegalArgumentException: Path bounds must not be negative (file:///android_asset/modules/__automator__.js#17)
JavaException: java.lang.IllegalArgumentException: Path bounds must not be negative
    at <init>:43:0

因为我一直是配合TASKER定时一天3次用的，1.7.0时是直接插件就可以了，1.9.4不行了，要在前面加个启动程序AUTO.JS才行，加了是可以但完成了后auto.js不会退出。
![Screenshot_20191111_180935_com huawei android launcher](https://user-images.githubusercontent.com/5145208/68586454-a2834d00-04bf-11ea-9077-d637028f408d.jpg)
![Screenshot_20191111_200523_org autojs autojs](https://user-images.githubusercontent.com/5145208/68586464-a7e09780-04bf-11ea-9242-ec3ca5a5c56e.jpg)
![Screenshot_20191111_200545_net dinglisch android taskerm](https://user-images.githubusercontent.com/5145208/68586520-c0e94880-04bf-11ea-878c-1971e7e65875.jpg)
![Screenshot_20191111_201106_org autojs autojs](https://user-images.githubusercontent.com/5145208/68586535-c9da1a00-04bf-11ea-8a0d-40bfab2109eb.jpg)

**Comment by zhangguangjin** [comment]
启动跳板是开启的

**Comment by SuperMonster003** [comment]
尝试将 `Modules/MODULE_UNLOCK.js` 的 533 行
```js
clickAction(confirm_btn_node, "widget");
```
修改为
```js
try {
    clickAction(confirm_btn_node, "widget");
} catch (e) {}
```

**Comment by zhangguangjin** [comment]
按照您的方法修改了下，确实可以了，不再报错了。做程序的就是牛B，几下找出问题。奈何我几年前就想学编程，可现在还是一点不懂，支持！！！
另外还有个问题要反馈下，我手机是华为P30PRO，就是自动解锁后会自动打开‘运动健康’再开始蚂蚁森林，任务完成了运动健康还留在前台，不知何解，这种情况出现的概率是80%
我录下了整个过程：<iframe height=498 width=510 src='http://player.youku.com/embed/XNDQzNDk4ODQ2NA==' frameborder=0 'allowfullscreen'></iframe>
![Screenshot_20191113_182739_com huawei health](https://user-images.githubusercontent.com/5145208/68755546-9f18ce80-0643-11ea-9e48-1d134a8797a1.jpg)

**Comment by SuperMonster003** [comment]
可尝试关闭"启动跳板"功能
运行 "Ant_Forest_Settings.js" -> 运行与安全 -> 支付宝应用启动跳板 -> [ 关闭跳板 ]

可能是脚本在获取 `Auto.js` 包名的时候 误将 `运动健康` 的包名作为目标参数启动了

**Comment by zhangguangjin** [comment]
反馈问题时"启动跳板"是关闭了的，你回复后我又打开试了多次，然后又关闭试了多次还是一样！

**Comment by zhangguangjin** [comment]
今天我单独用解锁模块测下，发现仍有一定几率会打开‘运动健康’！所以我怀疑导致此问题的代码可能在解锁模块中！猜测

**Comment by SuperMonster003** [comment]
视频中看到设备解锁成功后 主页面出现"完成"字样的桌面小工具 (左侧是"xxxx步" 右上部分是"完成 xx%" 右下部分是"热量 xxx 大卡") 脚本会点击"完成" 因为有些机型 (如坚果 Pro 2s) 需要在输入密码后额外点击"完成"按钮 因而脚本误点击了桌面小工具 进入了运动健康
下一版将尝试增加兼容方案

**Comment by zhangguangjin** [comment]
感谢回复！已了解，期待下一版！

**Comment by SuperMonster003** [comment]
`v1.9.6` 已尝试修复上述问题 如使用后问题复现 可继续反馈

**Comment by zhangguangjin** [comment]
196问题解决！感谢！！！原来194解锁模块单独可解锁，就是会出现上述问题，现用196解锁模块屏幕都不点亮，我用let unlock_module = new (require("./Modules/MODULE_UNLOCK.js"))();
unlock_module.unlock();和require("./MODULE_UNLOCK").unlock();都不行！图中所示
![Screenshot_20191119_143259](https://user-images.githubusercontent.com/5145208/69124474-f05f0d00-0ade-11ea-90c0-789a714c9a0d.jpg)
![Screenshot_20191119_143833_org autojs autojs](https://user-images.githubusercontent.com/5145208/69124513-079dfa80-0adf-11ea-8753-8c5e41224e41.jpg)

**Comment by SuperMonster003** [comment]
@zhangguangjin 
```js
require("./Modules/MODULE_UNLOCK").unlock();
```

**Comment by zhangguangjin** [comment]
OK, 原来是路径错误！再次感谢！问题结束。
