### ISSUE TITLE
脚本连续运行出现错误，求解

### ISSUE THREAD

**Issue by Love-ni** [SuperMonster003/Auto.js_Projects#123]
@SuperMonster003 
你好
       大神
脚本连续运行几次后出现错误（看图），停止运行后日志是空的。
![图片](https://user-images.githubusercontent.com/55963334/68634017-faa56800-052e-11ea-888c-7213cf8274f5.png)

**Comment by Love-ni** [comment]
> 
> 
> 脚本连续运行几次后出现错误（看图），停止运行后日志是空的。
> ![图片](https://user-images.githubusercontent.com/55963334/68634017-faa56800-052e-11ea-888c-7213cf8274f5.png)

**Comment by SuperMonster003** [comment]
`v1.9.5` 已尝试修复上述问题 如使用后问题复现 可继续反馈

**Comment by yuyuen72** [comment]
> 
> 
> `v1.9.5` 已尝试修复上述问题 如使用后问题复现 可继续反馈

你好，我遇到了相同的问题，并且在更新至1.9.5之后依然出现

**Comment by SuperMonster003** [comment]
@yuyuen72 可尝试 `v1.9.6` 并提供反馈
