### ISSUE TITLE
能否检测到当前正在运行的前台应用在白名单内取消本次任务

### ISSUE THREAD

**Issue by desslee** [SuperMonster003/Auto.js_Projects#124]
经常在玩游戏过程中弹出任务提示，一不小心就GG， 能不能出个应用白名单功能，检测到前台应用在白名单内就暂时取消本次任务或延迟执行。

**Comment by SuperMonster003** [comment]
`v1.9.5` 已增加前置应用黑名单功能及配置 欢迎使用并反馈
