### ISSUE TITLE
小米9 miui11 9.11.7系统，运行大神1.9.3和1.9.4时会造成系统死机重启

### ISSUE THREAD

**Issue by ggyy8850** [SuperMonster003/Auto.js_Projects#125]
小米9 miui11 9.11.7系统，运行大神1.9.3和1.9.4时会造成系统死机重启，30%几率会造成卡死重启，如不卡死的话，运行偷取正常。
不知道是上个星期更新miui后造成的，还是脚本与系统有什么冲突。好困扰！

![微信图片_20191112155501](https://user-images.githubusercontent.com/40348521/68652623-cfd60680-0564-11ea-8f0a-52a127f9ef1e.jpg)
![微信图片_20191112155447](https://user-images.githubusercontent.com/40348521/68652626-d1073380-0564-11ea-8e0c-66391fe3c0b1.png)

**Comment by ggyy8850** [comment]
补充下：在自己界面或好友列表界面时系统卡死。解锁、进支付宝时不会。

**Comment by sangbobo** [comment]
可能和MIUI的更新有关系，我的小米8更新了系统后，也会卡死，几乎天天有

**Comment by ggyy8850** [comment]
> 可能和MIUI的更新有关系，我的小米8更新了系统后，也会卡死，几乎天天有

应该是的，最近miui更新后问题挺多。直接影响森林的产出，特别是早上7点最关键时，不停的卡死机

**Comment by SuperMonster003** [comment]
@ggyy8850 首先截图中的红色报错与此问题无关 (下一版会修复)  
另系统卡死的问题我暂时无法解决 也无法排除是否是新版系统的问题

**Comment by ggyy8850** [comment]
> @ggyy8850 首先截图中的红色报错与此问题无关 (下一版会修复)
> 另系统卡死的问题我暂时无法解决 也无法排除是否是新版系统的问题

谢谢大神回复，紧跟大神，期待更好。

**Comment by sangbobo** [comment]
@ggyy8850 更新 MIUI9.11.14后，代码是1.9.5，就不死机了，你更新试试。
