### ISSUE TITLE
关于帮收功能

### ISSUE THREAD

**Issue by githeer** [SuperMonster003/Auto.js_Projects#126]
version：1.9.4
机型：三星S9+
android：9
**问题：**
 帮忙收取的能量球是上下浮动变化透明度，采用取色的话，alpha值变化速度过快导致颜色阈值太大，识别率很低，经常错过无法点击帮忙收取。
**建议：** 
是否能改成文字识别

**Comment by SuperMonster003** [comment]
无法改成文字识别 因为控件信息没有文字可供抓取和匹配
如果你的说的OCR 可以自行添加代码并尝试效果 (MONSTER模块有baiduOcr方法可供参考和适用)  
另外可以尝试比较简单的方式提升识别率
1. 校正默认的橙色颜色色值 不同设备的橙色能量球的橙色基准值可能不同 (之前遇到过一次)  
2. 适当调整帮收功能的其他设置值 
注: 第一步开始之前 建议将已修改的配置值恢复默认 (如阈值 色值 采集密度等)

**Comment by githeer** [comment]
**问题：**
现在是进入收取界面时扫描一次未获取到色值就直接退出了。颜色变化速度快，无法保证识别，您给出的方案是基于颜色未实时变化的情况吗？
**方案：**
1、能否多加几个能量球颜色录入，现在是只有一个，可以采用录入多个颜色值来增加识别到颜色的几率；
2、扫描次数修改

**Comment by SuperMonster003** [comment]
```js
let intensity_time = config.help_collect_balls_intensity * 160 - 920;
```

限制 help_collect_balls_intensity 为 10 - 20  ( 默认 12 )  
得到 intensity_time 为 680 - 2280  ( 默认 1000 毫秒 )  

也就是在 intensity_time 内 脚本会一直快速截取屏幕 然后进行多张截图分析 判断是否有橙色能量球  
并非只采集一次 或采集一张图片
而 help_collect_balls_intensity 的设置 其实就是所谓扫描次数的设置 ( 项目中称为"采集密度" )  

因为能量球是闪烁的 因此色值不固定 但当橙色球完全亮起时 全亮的时间占比相对于整个周期来讲还是比较大的  
所以把完全亮起时的橙色值作为基准值 通过设置合适的阈值 兼容闪烁时变暗的色值情况  

恰巧 排行榜列表中出现的橙色爱心图标的橙色色值 与橙色球全亮时的基准色值是几乎相同的 ( 从配置脚本中 两项设置项的默认值即可看出 )  
因此可从排行榜中截出橙色爱心图标 取色后作为橙色球的基准值 ( 之前的回复提到过 此基准值可能因设备不同而不同 )  
修改基准值后 再次尝试运行项目 很有可能会得到相对满意的橙色球收取效果 ( 除色值外的其他相关设置值 建议先保持或恢复默认 )  

注: 可自行定位并参阅代码  
> \_\_global\_\_
-> checkEnergy()
-> checkFriendsEnergy()
-> forestPageGetReady()
-> energyBallsMonitorThread()
-> collectAndAnalyseHelpBalls()

**Comment by githeer** [comment]
好的，谢谢，我查看下具体代码
