### ISSUE TITLE
脚本运行报错信息

### ISSUE THREAD

**Issue by Hallelujah8495** [SuperMonster003/Auto.js_Projects#127]
10:58:28.905/E: Error: Can't resolve relative module ID "./Modules/__dialogs__pro_v6" when require() is used outside of a module (file:///android_asset/modules/jvm-npm.js#89)
Error: Can't resolve relative module ID "./Modules/__dialogs__pro_v6" when require() is used outside of a module
    at Require (file:///android_asset/modules/jvm-npm.js:89:0)
    at /sdcard/脚本/Ant_Forest_Launcher.js:16:0

**Comment by SuperMonster003** [comment]
项目目录结构不完整或缺失
不要使用Auto.js的导入功能
项目Zip文档下载后解压出来 将解压出来的所有内容 保持原有结构 复制或移动到"脚本"目录中
"脚本"目录位于手机内部存储的根目录下 (/storage/emulated/0/脚本)
然后在Auto.js主页面下拉刷新一下 找到项目文件再次运行

**Comment by Hallelujah8495** [comment]
首先感谢大神的建议，实测问题已解决。
建议说明一下，不要使用示例中的脚本项目运行项目文件，还有项目放置手机路径更新为/storage/emulated/0/脚本。
还有我的机型系统是miui，安卓9版本，会出现无障碍服务频繁关闭的问题，打开蚂蚁森林无法自动进行收取能力的相关操作。

**Comment by Hallelujah8495** [comment]
> 项目目录结构不完整或缺失
> 不要使用Auto.js的导入功能
> 项目Zip文档下载后解压出来 将解压出来的所有内容 保持原有结构 复制或移动到"脚本"目录中
> "脚本"目录位于手机内部存储的根目录下 (/storage/emulated/0/脚本)
> 然后在Auto.js主页面下拉刷新一下 找到项目文件再次运行

首先感谢大神的建议，实测问题已解决。
建议说明一下，不要使用示例中的脚本项目运行项目文件，还有项目放置手机路径更新为/storage/emulated/0/脚本。
还有我的机型系统是miui，安卓9版本，会出现无障碍服务频繁关闭的问题，打开蚂蚁森林无法自动进行收取能力的相关操作

**Comment by SuperMonster003** [comment]
无障碍频繁关闭可以参考此贴吧回帖
http://tieba.baidu.com/p/6180359580?pid=128308856243&cid=128308856243#128308856243
