### ISSUE TITLE
红米note7 pro 11.0.4 系统 （屏幕点亮后）上划不够充分不能进入输入密码的界面

### ISSUE THREAD

**Issue by ZhangWeiHelloWorld** [SuperMonster003/Auto.js_Projects#129]
红米note7 pro 11.0.4 系统  锁屏后，屏幕点亮，此时要上划，输入密码，但是多次尝试上滑，不充分。个人认为是滑动距离不够造成的。

**Comment by SuperMonster003** [comment]
可以尝试更换主题解决问题  
官方默认主题需要惯性滑动才能划开遮罩层页面  
此项目目前暂时无法实现可控的惯性滑动
