### ISSUE TITLE
下载代码后在电脑上调试会报错，这是什么原因呢

### ISSUE THREAD

**Issue by lds33663366** [SuperMonster003/Auto.js_Projects#131]
我下载代码PC上调试运行Ant_Forest_Launcher.js 会报错
Error: Can't resolve relative module ID "./Modules/__dialogs__pro_v6" when require() is used outside of a module (file:///android_asset/modules/jvm-npm.js#89)Error: Can't resolve relative module ID "./Modules/__dialogs__pro_v6" when require() is used outside of a module    at Require (file:///android_asset/modules/jvm-npm.js:89:0)    at [remote]Ant_Forest_Launcher.js:16:0

同样 我想移植Modules文件夹到我的项目里使用
let module_unlock = new (require("./Modules/MODULE_UNLOCK"))();
也会报同样的错误。手机下载的autojs版本4.1.1 安卓版本9.0 华为荣耀play手机

**Comment by lds33663366** [comment]
找到原因了，用VS code调试手机时，需要将Modules文件夹拷贝到手机上才行

> 我下载代码PC上调试运行Ant_Forest_Launcher.js 会报错
> Error: Can't resolve relative module ID "./Modules/__dialogs__pro_v6" when require() is used outside of a module (file:///android_asset/modules/jvm-npm.js#89)Error: Can't resolve relative module ID "./Modules/__dialogs__pro_v6" when require() is used outside of a module at Require (file:///android_asset/modules/jvm-npm.js:89:0) at [remote]Ant_Forest_Launcher.js:16:0
> 
> 同样 我想移植Modules文件夹到我的项目里使用
> let module_unlock = new (require("./Modules/MODULE_UNLOCK"))();
> 也会报同样的错误。手机下载的autojs版本4.1.1 安卓版本9.0 华为荣耀play手机

**Comment by lds33663366** [comment]
大神用的什么方法调试的

**Comment by SuperMonster003** [comment]
`Auto.js` 的APP设置页面 -> 更改脚本文件夹路径 -> ( 记录此路径为 %path% )  
`VS Code` 在安装 `Auto.js` 插件后 运行脚本的工作目录是 %path%  
可以使用 console.log(files.cwd()); 查看工作目录
所以需要将项目的所有文件和文件夹按照项目原有结构放置在 %path% 下才可正常使用 `VS Code` 调试
当然也可以通过修改 %path% 来改变默认工作目录实现其他目录的调试  

UNLOCK模块将在最近实现完全独立模块和独立配置工具 目前暂时可用模块中的JSDoc标注的方法调用  

debugInfo() 位于 Monster 模块 是一个封装好的方法 并不是 `VS Code` 的关联调试方法 
具体可参照 debugInfo() 的 JSDoc 文档
如果想在项目中开启并显示代码中设计的调试信息  
可运行 "Ant_Forest_Settings.js" -> 消息提示 -> 勾选 [ 开发者测试模式 ]
