### ISSUE TITLE
华为mate30 pro无法唤醒屏幕

### ISSUE THREAD

**Issue by luchangharry** [SuperMonster003/Auto.js_Projects#134]
大佬，今天测试了mate30Pro，发现只有极低概率可以从休眠状态唤醒屏幕，就是没法进入到解锁界面，如图所示，我设置的是7点，但是直到我过了7点01点亮屏幕，脚本才开始运行，请问这个问题有办法解决么
![1461573864961_ pic](https://user-images.githubusercontent.com/50188136/68984827-4157d280-084d-11ea-860e-6d94eea6ef02.jpg)
另外，不止一次出现了AUTOjs无法启动的奇怪bug
![1471573871623_ pic](https://user-images.githubusercontent.com/50188136/68986686-c4ccf000-085c-11ea-885d-8894b4bea4bc.jpg)

**Comment by SuperMonster003** [comment]
此问题目前无法通过代码解决  
可尝试查询并修改所有与Auto.js相关的系统设置 如节电设置 后台限制 背景程序运行 自启动 应用权限等等

另外可尝试在Auto.js软件中 随意找到一个 js 脚本  
右侧菜单 -> 更多 -> 定时任务 -> { 任意的有效设置 }  
如果是首次进行定时任务设置 Auto.js可能会提示需要开启后台运行相关的权限 点击允许  

当然其他地方很可能也需要进行额外的设置

**Comment by luchangharry** [comment]
可是其实之前已经给了所有可以给的权限了
还有昨晚起开始出现报错无法进入好友排行榜，或是极小概率进入好友排行榜，却卡在排行榜无法进入好友主页，报错及卡住的日志如下：
![2821573951799_ pic_hd](https://user-images.githubusercontent.com/50188136/69001317-441efa00-0917-11ea-9407-f9f2ab6f8774.jpg)
![2831573951800_ pic_hd](https://user-images.githubusercontent.com/50188136/69001319-47b28100-0917-11ea-9eae-7edc8ac8bff5.jpg)

**Comment by chemboy0609** [comment]
![Screenshot_20191118_201804](https://user-images.githubusercontent.com/24561009/69052663-8a24ac80-0a42-11ea-8a4f-152376025757.jpg)
设置了APP的后台运行，自动启动，并且关闭了自动管理权限后，自动亮屏解锁成功，但依然有报错，进不去好友列表，有时候正常运行的时候也进不去，求助

**Comment by luchangharry** [comment]
> ![Screenshot_20191118_201804](https://user-images.githubusercontent.com/24561009/69052663-8a24ac80-0a42-11ea-8a4f-152376025757.jpg)
> 设置了APP的后台运行，自动启动，并且关闭了自动管理权限后，自动亮屏解锁成功，但依然有报错，进不去好友列表，有时候正常运行的时候也进不去，求助

哥们能问下你都设置了哪些权限么？我这个自动解锁时灵时不灵，大部分时间都不灵，我感觉我权限都给了啊。。。

**Comment by SuperMonster003** [comment]
@chemboy0609 我无法从日志截图中得到任何能解答问题的内容 请详细描述脚本执行过程中的问题 并开启开发者测试模式 然后从头完整运行一遍脚本 中途不要手动干预 然后再提供完整的包含关键问题的日志截图

**Comment by luchangharry** [comment]
感觉我们俩问题应该差不多的，在亮屏状态下，从自己主页进到好友列表后无法滑动，也无法进入好友主页，就停在那里直到黑屏。具体完整日志如下：

![1511574085717_ pic](https://user-images.githubusercontent.com/50188136/69058995-a549e900-0a4f-11ea-9381-97b6d21682bb.jpg)

**Comment by luchangharry** [comment]
另外，我发现就是就算有时偶尔点亮了屏幕，还是无法从提示页进到解锁页，不知道是否和滑动时间有关，我看那个滑动时间都已经自己递进到2000多了。。。

**Comment by SuperMonster003** [comment]
无障碍服务异常  

辨别方式: 使用简单的基于无障碍服务的方法  ( 如 click(x, y), swipe(......) 等 )  进行设备的滑动或点击等无障碍行为测试  

可尝试将 Auto.js 卸载重新安装 安装后先不要运行 重启设备  
然后运行 Auto.js 并手动开启无障碍服务 再尝试运行项目

**Comment by luchangharry** [comment]
> 无障碍服务异常
> 
> 辨别方式: 使用简单的基于无障碍服务的方法 ( 如 click(x, y), swipe(......) 等 ) 进行设备的滑动或点击等无障碍行为测试
> 
> 可尝试将 Auto.js 卸载重新安装 安装后先不要运行 重启设备
> 然后运行 Auto.js 并手动开启无障碍服务 再尝试运行项目

目前没有问题

**Comment by luchangharry** [comment]
每天早上的收取能量进行no-time check之后不能进行继续进入好友列表收取好友能量，报错如下：
![1541574298945_ pic](https://user-images.githubusercontent.com/50188136/69291938-a2154f80-0c3f-11ea-9dfe-6593b0ab7fb4.jpg)

**Comment by SuperMonster003** [comment]
@luchangharry 
收到反馈 下一版修复  
另 如新问题与之前 Issue 的问题无关联 ( 例如此 Issue 的问题是无法唤醒屏幕 )  
则 建议重新开贴 以方便开发者查看并定位问题以及整理标签  
感谢支持

**Comment by luchangharry** [comment]
> @luchangharry
> 收到反馈 下一版修复
> 另 如新问题与之前 Issue 的问题无关联 ( 例如此 Issue 的问题是无法唤醒屏幕 )
> 则 建议重新开贴 以方便开发者查看并定位问题以及整理标签
> 感谢支持

ok，我另开一帖，感谢大佬
