### ISSUE TITLE
realmeX 能点亮屏幕，但没法解锁

### ISSUE THREAD

**Issue by caiop11** [SuperMonster003/Auto.js_Projects#135]
realmeX 能点亮屏幕，但没法解锁，一直在解锁画面点数字0

**Comment by SuperMonster003** [comment]
在图形配置脚本中开启开发者测试模式 然后看一下日志是不是划开图层失败了  
另外 RealmeX 用的是 OPPO 的 ColorOS 系统 有部分可能是经过了定制性修改 导致解锁控件 id 标识也变得特殊  
如查看日志后无异常 可运行工具文件夹中的解锁布局分析工具 然后自行分析或向开发者提供布局分析资料包

**Comment by caiop11** [comment]
[!Debug_Info  RealmeX.zip](https://github.com/SuperMonster003/Auto.js_Projects/files/3862901/Debug_Info.RealmeX.zip)
大神有空帮忙看看，没空就算了，谢谢！

**Comment by caiop11** [comment]
![f88ea8c9b5b62500c824300f0ccddb9](https://user-images.githubusercontent.com/57926752/69133429-d4fcfd80-0af0-11ea-99c1-03bdd00dcf6f.jpg)

**Comment by SuperMonster003** [comment]
1. 布局信息无效 运行布局分析工具后 按照说明操作 不要过早手动解锁  ( 或者有些设备可能支持并开启了面部解锁 解锁时需要用户移开头部避免被识别并自动解锁 ) 布局分析工具需要的是输入密码界面的控件信息  
2. Modules 文件夹内的 js 文件都是模块文件 不可直接运行 只可引入后再使用

**Comment by caiop11** [comment]
> 1. 布局信息无效 运行布局分析工具后 按照说明操作 不要过早手动解锁  ( 或者有些设备可能支持并开启了面部解锁 解锁时需要用户移开头部避免被识别并自动解锁 ) 布局分析工具需要的是输入密码界面的控件信息
> 2. Modules 文件夹内的 js 文件都是模块文件 不可直接运行 只可引入后再使用

没有开了面部识别，只开了指纹和数字密码，然后从Auto.Js里面运行的布局分析工具，但是关屏之后，可以自动亮屏、上划，到了输数字密码的界面之后就没反应了，手动输了密码之后才会长震动，没法采集布局信息
谢谢大神，费心了，不用弄了

**Comment by SuperMonster003** [comment]
工具文件夹里有一个 Inspect_Specific_Screen_Layout.js 文件
运行后在某个页面  ( 当前也包括锁屏页面 )  按 音量减  ( VOL- )  键可以将页面布局信息打印到日志中
只是可能日志会很长
如果愿意的话 可以在以下两个页面分别使用一次此工具 并反馈结果

1. 输入密码前的遮罩层页面
2. 需要输入密码的锁屏页面

**Comment by caiop11** [comment]
![1](https://user-images.githubusercontent.com/57926752/69237306-5a0b1400-0bd0-11ea-9d66-92456cf4febc.png)
![2](https://user-images.githubusercontent.com/57926752/69237308-5b3c4100-0bd0-11ea-81bf-47bb5a18508c.png)
1、输入密码前的遮罩层页面
2、需要输入密码的锁屏页面
谢谢！

**Comment by SuperMonster003** [comment]
下一版将尝试适配上述机型的解锁功能  

先说明两点
- 两张图片几乎是一样的 控件 `id` 的重叠率非常高 所以没有加遮罩层和解锁页面的特征判断 因此可能会出现在遮罩层页面就盲按数字键盘输入密码的情况 但由于按键行为采用控件方法 而非无障碍方法 因此也有一定概率实现 "即便是在遮罩层页面 脚本依然把密码全部按下并成功解锁" 的特殊情况  
- 键盘按键的 `desc` 控件属性值 只有 `1-9` 没有 `0` 为此特意加了 `0` 的特殊匹配 但点击时使用的是无障碍方法 `click()` 因此可能导致上述特殊情况被破坏

**Comment by caiop11** [comment]
虽然不懂，但感谢大神的辛苦付出

**Comment by SuperMonster003** [comment]
`v1.9.9` 已尝试增加 `PIN` 解锁方案 如使用后问题复现 可继续反馈

**Comment by caiop11** [comment]
感谢大佬，新版本可以解锁了，貌似设置了定时任务，到点不自动亮屏，我明天再试一试，再来反馈。再次感谢！

**Comment by caiop11** [comment]
大神，没有问题，感谢！

**Comment by lizhihengtt** [comment]
MIUI可以利用锁屏负一屏触发解锁界面
    gesture(40, [200, 1900], [500, 1900], [800, 1900])
    sleep(2000)
    setScreenMetrics(1080, 1920);
    click(100, 600);
    sleep(500)
MIUI11稳定使用作者可否把这个加进去
