### ISSUE TITLE
不收能量，也不收取好友的能量。

### ISSUE THREAD

**Issue by lizonggang** [SuperMonster003/Auto.js_Projects#136]
运行脚本后可以正常进入蚂蚁森林主界面。打开后会有两个提示。

Auto.js: 开始"蚂蚁森林"任务
过一会。。。
Auto.js: 打开“Auto.js”失败

不收能量，也不收取好友的能量。 MIUI 11.0.2 稳定版。

**Comment by SuperMonster003** [comment]
https://github.com/SuperMonster003/Auto.js_Projects/issues/113
