### ISSUE TITLE
设置菜单无法点击

### ISSUE THREAD

**Issue by VergLsm** [SuperMonster003/Auto.js_Projects#137]
![S91120-00301014](https://user-images.githubusercontent.com/13448810/69165904-4bb7ec00-0b2d-11ea-9691-ecc57a99a450.jpg)

如图，黑名单和下面那些菜单项无法点击和进入，前些版本都是这样了。

**Comment by SuperMonster003** [comment]
强制关闭 Auto.js 或重启设备再开启 Auto.js  
无论哪种方式 需要先运行 Auto.js 后手动开启无障碍服务再运行脚本  
上述问题原则上可以通过代码解决 但目前能力暂无法做出更好的优化或解决  
此 Issue 暂时标记 "无法完成"

**Comment by VergLsm** [comment]
我估计是不是账户功能里面需要加载什么东西，但是加载不出来，导致后面几项都没有加载，也就没有点击响应

**Comment by SuperMonster003** [comment]
才发现这里有未回复的 issue  
这个问题应该是 Auto.js 的可用资源不足导致的 我也时常遇到 尤其是多次运行配置工具之后 我都是强制关闭 Auto.js 重启解决这个问题的  
以后可能会抽出时间重新优化一下 ui 的加载逻辑

**Comment by SuperMonster003** [comment]
`v1.9.8` 已尝试修复上述问题 如使用后问题复现 可继续反馈

**Comment by VergLsm** [comment]
问题已经得到修复。

**Comment by VergLsm** [comment]
问题已经得到修复。
