### ISSUE TITLE
no-stop checking后无法继续收取好友能量

### ISSUE THREAD

**Issue by luchangharry** [SuperMonster003/Auto.js_Projects#138]
每天早上的收取能量进行no-stop checking之后不能进行继续进入好友列表收取好友能量，报错如下：
![1541574298945_ pic](https://user-images.githubusercontent.com/50188136/69292598-827f2680-0c41-11ea-9ff2-18bdf3f89d3c.jpg)

**Comment by SuperMonster003** [comment]
`v1.9.7` 已尝试修复上述问题 如使用后问题复现 可继续反馈  ( 当前最新版本为 `v1.9.8` )
