### ISSUE TITLE
MIUI11的小米6不能自动解锁

### ISSUE THREAD

**Issue by shanlanCoding** [SuperMonster003/Auto.js_Projects#139]
主要特征为，亮屏后无法上滑动进入点阵界面。手动辅助上滑动进入点阵界面后无法开始连线解锁

**Comment by SuperMonster003** [comment]
1. 上滑需要惯性滑动 暂时无法实现 可尝试更换系统主题  
2. 图案解锁断线可尝试修改滑动策略

运行 Ant_Forest_Settings.js -> 自动解锁 -> 滑动策略 -> [ 连续路径 ]

**Comment by shanlanCoding** [comment]
> 1. 上滑需要惯性滑动 暂时无法实现 可尝试更换系统主题
> 2. 图案解锁断线可尝试修改滑动策略
> 
> 运行 Ant_Forest_Settings.js -> 自动解锁 -> 滑动策略 -> [ 连续路径 ]

目前已经是系统默认主题了，后续设置我现在试试

**Comment by SuperMonster003** [comment]
官方主题可能都需要惯性滑动 可以尝试第三方主题或其他主题

**Comment by shanlanCoding** [comment]
> 官方主题可能都需要惯性滑动 可以尝试第三方主题或其他主题

感谢回复，我后续会继续反馈问题。

**Comment by shanlanCoding** [comment]
最新进展；屏幕亮起后有向上滑动的动作，但是依然不能进入解锁图案界面（我只让它尝试了3次），后面手动上滑动进入解锁界面。前几次连线解锁失败，到了4/5次的时候，解锁成功。这个解锁动作我在其它的issues里好像看到是可以自动修正延迟并保存最佳解锁延迟的，是吗？

**Comment by shanlanCoding** [comment]
附上上滑动失败视频。
![上划解锁失败](https://user-images.githubusercontent.com/44717382/69301960-eeb65600-0c52-11ea-81eb-c30ecff2b74b.jpg)

**Comment by SuperMonster003** [comment]
运行配置工具 自动解锁功能 重置滑动时长 设置滑动起点为最大值 设置滑动终点为最小值 如果依然失败 请再次尝试更换主题 或使用其他方案 
例如点击通知栏时间等方式 可在互联网搜索相关代码 并加入到解锁模块中

**Comment by shanlanCoding** [comment]
> 运行配置工具 自动解锁功能 重置滑动时长 设置滑动起点为最大值 设置滑动终点为最小值 如果依然失败 请再次尝试更换主题 或使用其他方案 例如点击通知栏时间等方式 可在互联网搜索相关代码 并加入到解锁模块中
> […](#)
> On November 21, 2019 11:35:49 shanlanCoding ***@***.***> wrote: 附上上滑动失败视频。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

我已经有思路了，等我测试后后告诉你结果。谢谢你的技术支持。

**Comment by shanlanCoding** [comment]
已经ok了。我手动测试后发现MIUI的上滑进入解锁界面，这个上滑的距离不宜太长，如果上滑距离过长即使是手动都无法进入锁屏界面。所以解决方法是在设置里尽量缩短滑动距离。
