### ISSUE TITLE
为什么华为P30锁屏后无法被唤醒？

### ISSUE THREAD

**Issue by keli1973** [SuperMonster003/Auto.js_Projects#141]
貌似如果是刚手动锁屏的话是可以起得来，我输的密码正确也能自动解锁；
但锁屏时间长了以后，定时任务就无法唤醒，时间到了屏幕连亮都不亮，然后手动解锁以后马上就提示任务准备开始执行。
这个和机子有关吗？无root

**Comment by SuperMonster003** [comment]
https://github.com/SuperMonster003/Auto.js_Projects/issues/134
