### ISSUE TITLE
更新后出现的问题 

### ISSUE THREAD

**Issue by limaonet** [SuperMonster003/Auto.js_Projects#142]
![image](https://user-images.githubusercontent.com/40821195/69612423-99bb7b00-106a-11ea-9362-3d92a3de2a78.png)

**Comment by SuperMonster003** [comment]
"/storage/emulated/0/.local/af.nfe"
"/storage/emulated/0/.local/af_cfg.nfe"
尝试以上两个文件先备份再删除  ( 或改名 )  
然后重新运行项目  
此时需要重新配置全部设置项  ( 可参考之前备份的配置文件参数 )  
如问题复现 可继续反馈

**Comment by limaonet** [comment]
大佬 删除了   还是 不行 哦 !一样的 日志

**Comment by SuperMonster003** [comment]
暂时未能确定原因 按通用方法尝试处理
卸载 Auto.js 重新安装
重启设备
启动 Auto.js 后 手动开启无障碍服务
运行图形配置工具
服务器还原最新的版本
运行项目

**Comment by limaonet** [comment]
小哥哥 啊  不行 啊 安装 你说的操作了

**Comment by SuperMonster003** [comment]
尝试回退 1-3 个版本

**Comment by limaonet** [comment]
小哥哥 能不能 发个 你 测试版本的 auto.js  用用啊

**Comment by SuperMonster003** [comment]
一直在用 4.1.1 Alpha2  
未使用其他版本

**Comment by limaonet** [comment]
我现在 删除 不了  这个项目,   直接卸载 auto.js   重新安装  这个项目还在....咋办  我想重新来过 都 搞不搞了

**Comment by SuperMonster003** [comment]
定位 `/storage/emulated/0/脚本` 后 再尝试删除本项目相关的文件或目录
