### ISSUE TITLE
"好友排行榜"初始状态失败.

### ISSUE THREAD

**Issue by wpc2333** [SuperMonster003/Auto.js_Projects#143]
支付宝更新程序后增加了周排行榜和总排行榜，程序进入后好友列表无反应
### 手动打开的界面
![TIM图片20191126180056](https://user-images.githubusercontent.com/46512490/69620419-523beb80-1078-11ea-9d23-d834c0fb3ca2.jpg)

### 程序打开的界面
![TIM图片20191126180016](https://user-images.githubusercontent.com/46512490/69620434-57009f80-1078-11ea-85d2-8e8a5513d2b6.jpg)

### 程序报错
![TIM图片20191126180040](https://user-images.githubusercontent.com/46512490/69620444-5f58da80-1078-11ea-82f9-84e84d65b007.jpg)

**Comment by SuperMonster003** [comment]
暂时无解
需等待灰测增大范围覆盖到我能测试的帐号或灰测结束正式上线才能适配新控件解决问题

另
当设备可正常使用并应用activity方式启动排行榜页面时 页面是通过支付宝jsapi提供的接口实现页面跳转的 里面加了一些自定义参数 
因此可实现几乎任意页面立即且直接跳转到排行榜的效果 这与手动点击进入排行榜的方式不同 自然也会造成页面显示的方式不同 具体可查阅项目代码

**Comment by wpc2333** [comment]
谢谢作者大大

**Comment by wpc2333** [comment]
> 暂时无解 需等待灰测增大范围覆盖到我能测试的帐号或灰测结束正式上线才能适配新控件解决问题 另 当设备可正常使用并应用activity方式启动排行榜页面时 页面是通过支付宝jsapi提供的接口实现页面跳转的 里面加了一些自定义参数 因此可实现几乎任意页面立即且直接跳转到排行榜的效果 这与手动点击进入排行榜的方式不同 自然也会造成页面显示的方式不同 具体可查阅项目代码
> […](#)
> On November 26, 2019 18:13:21 wpc2333 ***@***.***> wrote: 支付宝更新程序后增加了周排行榜和总排行榜，程序进入后好友列表无反应 手动打开的界面 程序打开的界面 程序报错 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

谢谢作者大大

**Comment by WongSongs** [comment]
哦豁~~！魅族16THPLUS也昨天也更新了这个周排行榜总排行榜，然后就获取好友列表失败了

**Comment by SuperMonster003** [comment]
`v1.9.9` 已尝试修复上述问题 如使用后问题复现 可继续反馈

**Comment by WongSongs** [comment]
好的👌感谢大师的付出



来自 魅族 16th Plus



-------- 原始邮件 --------
发件人：SuperMonster003 <notifications@github.com>
时间：2019年11月28日 13:41
收件人："SuperMonster003/Auto.js_Projects" <Auto.js_Projects@noreply.github.com>
抄送：WongSongs <hyc_luck@hotmail.com>,Comment <comment@noreply.github.com>
主题：Re: [SuperMonster003/Auto.js_Projects] "好友排行榜"初始状态失败. (#143)


v1.9.9 已尝试修复上述问题 如使用后问题复现 可继续反馈

**Comment by dwan0819** [comment]
> `v1.9.9` 已尝试修复上述问题 如使用后问题复现 可继续反馈

miui11.0.2.稳定版，支付宝10.1.8。v1.9.9后问题依旧，烦请大神关注。

**Comment by hkx303** [comment]
华为MATE20 PRO
支付宝10.1.8 
EMUI9.1.0 
问题依旧，谢谢～

**Comment by abcdelf** [comment]
华为 p20 
问题依旧

**Comment by Summer361** [comment]
作者大大
已更新到V1.9.10，好友排行榜的问题依旧
小米6
MIUI11.0.2
支付宝10.1.80

**Comment by SuperMonster003** [comment]
`v1.9.10` 已尝试修复上述问题 如使用后问题复现 可继续反馈
