### ISSUE TITLE
"好友排行榜"初始状态准备失败

### ISSUE THREAD

**Issue by wonder566** [SuperMonster003/Auto.js_Projects#144]
从昨天下午开始出现

07:38:52.489/E: "好友排行榜"初始状态准备失败

表现是好友列表无法滑动，前一步收取自己的能量是可以的。
使用1.9.7和1.9.8都是，删除了.local 下的配置也不行

**Comment by SuperMonster003** [comment]
1. 无需删除 .local 文件夹 此文件夹存放了与项目相关的配置和密码字典 绝大多数情况下不会影响项目运行  ( 之前有 issue 提到过 JSON.parse 问题才可能与 .local 文件夹有关 )
2. 此问题源于支付宝的 H5 小程序灰度测试 具体参见维基百科或查看之前的 [`issue #143`](https://github.com/SuperMonster003/Auto.js_Projects/issues/143#issuecomment-558566222)

**Comment by wonder566** [comment]
感谢回复
