### ISSUE TITLE
超时强制退出&click()方法超时。

### ISSUE THREAD

**Issue by bitqiang** [SuperMonster003/Auto.js_Projects#15]
Auto.js版本：4.1.1 Alpha2
手机：小米5
系统版本：MIUI 10.2稳定版

![image](https://user-images.githubusercontent.com/13163400/57174594-ceb87400-6e73-11e9-86d2-025f6a1dc250.png)

**Comment by SuperMonster003** [comment]
click()方法超时 是点击加载更多按钮时报的警告 因为此功能为辅助功能 即使失败也不会影响收取 因为拉动列表的时候会自动激活点击加载更多 因此已关闭此辅助功能的报警消息  
超市卡顿的问题是棘手难题 假期后我会重点研究一下解决方案 请关注更新  
强制退出是因脚本卡顿造成的 默认为5分钟 防止某个脚本卡死或无限占用任务列表 正常情况下5分钟足够运行一次了 但因卡顿问题未解决 很容易超过5分钟 卡顿解决后此问题自然消失  
日后会加入最大超时时间设置功能 可设置更大超时值

**Comment by bitqiang** [comment]
我记得你在 v2ex发帖的时候说也用过之前那个脚本。

我使用那个脚本是正常的。
滑动都是正常的，可以看下他的滑动怎么处理的。
使用你这个脚本的时候，滑动的时候也不太顺畅。

感谢~

**Comment by SuperMonster003** [comment]
好的 我再好好看一下e1399579的脚本 他的脚本识别绿色小手和橙色爱心使用的是图片匹配 我用的是颜色识别 我可以尝试把思路改一下 
但目前还没有找到滑动卡顿 以及进入好友森林后操作迟缓的根源 我再研究一下 感谢反馈
:smile:

**Comment by SuperMonster003** [comment]
问题根源已找到 排行榜列表很长时 每次滚动 Auto.js会重新抓取所有控件 刷新并检索几千甚至上万个控件信息 导致卡顿迟缓问题 目前已加入图像识别策略避免此问题 (功能初期 暂不成熟 且原布局分析策略依然保留) 此Issue暂时关闭

**Comment by bitqiang** [comment]
@SuperMonster003 辛苦了哈。
怪不得每次收到两三百就凉了。。
我好友列表有八百多人了。。
