### ISSUE TITLE
华为Nova5ipro过度返回

### ISSUE THREAD

**Issue by wth0538** [SuperMonster003/Auto.js_Projects#150]
1.99版本已更新带有周排行    脚本运行后进入排行榜 收完第一个好友一直返回 返回到支付宝首页，过度返回，然后开始下拉 ，望解决

**Comment by chenhd9** [comment]
一样~

**Comment by TooAndy** [comment]
小米手机也这样，小米6

**Comment by sangbobo** [comment]
参考#148 暂时将Ant_Forest_Launcher.js文件中jumpBackOnce方法下(大约在4401行)的keycode(4, "double");替换为back();
临时解决方案，等待大佬发布下一个版本。

**Comment by abcdelf** [comment]
临时方案不错
