### ISSUE TITLE
无黑名单，但定时时间设置有误

### ISSUE THREAD

**Issue by keli1973** [SuperMonster003/Auto.js_Projects#153]
1.99版本。
看到排行里一个好友还有10分钟可收，但运行完之后看定时时间是要50分钟之后，貌似检测不到该好友的可收状态倒计时。另外看过黑名单里面也是空的，手动进该好友里面看也没有能量罩，但不知道为什么定时不对。

**Comment by keli1973** [comment]
看了一下，貌似这个定时只检测到排行榜首个倒计时，后面即使有新的也不刷新新的倒计时。

**Comment by keli1973** [comment]
总结一下好像只保存了第一个的时间，后面即使有时间比它短的都不更新。

**Comment by SuperMonster003** [comment]
`v1.9.10` 已进行深度代码重构 关于统计倒计时的部分也做了重新结构化 如使用后问题复现 可继续反馈 此 issue 暂时关闭
