### ISSUE TITLE
好友列表中可收取好友的小手识别颜色有改动。

### ISSUE THREAD

**Issue by baocq2019** [SuperMonster003/Auto.js_Projects#156]
原先为#1da06d#，现在是#6ea01d#

**Comment by SuperMonster003** [comment]
此色值可能 (低概率) 与设备的屏幕渲染有关 某些滤镜或其他因素会影响默认的颜色 将适用于此设备的色值配置到项目中即可

PS: 
1. HEX 颜色色值串只需一个井号
2. 目前默认色值依然为 "#1da06d"

感谢提供反馈
