### ISSUE TITLE
魅族16s过度返回

### ISSUE THREAD

**Issue by Higher-Stark** [SuperMonster003/Auto.js_Projects#157]
脚本收取好友的能量后，有时会过度返回，比如 _直接退出蚂蚁森林_ 这样，然后脚本会继续继续退出来尝试重启支付宝。
系统：Flyme 8.0.0.0A

**Comment by a1103688841** [comment]
我用魅族16TH也是这样  收一个好友后就直接返回到主页

**Comment by fflzh** [comment]
我的华为P30Pro也是，收取几个之后会返回到支付宝主页
系统EMUI10.0 ，安卓10

**Comment by a1103688841** [comment]
![image](https://user-images.githubusercontent.com/44131404/69926083-0c56ab80-14ee-11ea-9122-29b3846bfab0.png)
我修改了
        function backToHeroList() {
            if (condition()) return true;

            let max_try_times = 3;
            while (max_try_times--) {
                jumpBackOnce("forcibly_back");
                sleep(800);
                if (waitForAction(condition, 2000)) return true;
                debugInfo("返回排行榜单次超时");
            }
sleep中的数字，将他增大，好像现在可以用了。

**Comment by l919898756** [comment]
小米+1

**Comment by abcdelf** [comment]
可以自己先改一下代码，改成back的方式。
具体方法参考一下其他的comment

**Comment by debugerliu** [comment]
小米6同样的问题

**Comment by jiangzIT** [comment]
小米8也出现同样的问题

**Comment by angelmengg** [comment]
诺基亚7p同样问题

**Comment by Khan-KK** [comment]
19.9 华为V10雷同

**Comment by zzliux** [comment]
自己参考代码，把4358行的keycode(4, "double")修改为无障碍的back()，其它的地方没仔细看，我的这样改就似乎没问题了

**Comment by Higher-Stark** [comment]
v1.9.10 Beta2没有过度返回的问题了

**Comment by SuperMonster003** [comment]
原先为#1da06d#，现在是#6ea01d#

**Comment by SuperMonster003** [comment]
https://github.com/SuperMonster003/Auto.js_Projects/issues/150
