### ISSUE TITLE
好友排行榜初始状态失败

### ISSUE THREAD

**Issue by Zhang-Ingram** [SuperMonster003/Auto.js_Projects#158]
1.6-1.9均出现此问题
![图片](https://user-images.githubusercontent.com/33376293/69916500-a7bc3200-1496-11ea-9117-b98a77ed0c36.png)

**Comment by Zhang-Ingram** [comment]
顺便问一下目前哪个版本比较完善，稳一点的

**Comment by VergLsm** [comment]
同样问题，应该是新版支付宝吧。

**Comment by sorgs** [comment]
+1，估计是支付宝升级了

**Comment by l919898756** [comment]
+1

**Comment by withsalt** [comment]
+1

**Comment by pan176** [comment]
+1

**Comment by Zhang-Ingram** [comment]
1.9.10beta版本成功修复
