### ISSUE TITLE
小米9 pro 打开脚本自动跳转至手机的无障碍服务

### ISSUE THREAD

**Issue by weil-f** [SuperMonster003/Auto.js_Projects#159]
![image](https://user-images.githubusercontent.com/27939942/69924997-0b6f4b00-14e9-11ea-9eaa-6aded46b5dcd.png)
无法点开啊，求帮助求指导啊~~~

**Comment by weil-f** [comment]
重启了手机，打开了脚本但是出现了新的错误，如图
![image](https://user-images.githubusercontent.com/27939942/69925253-1f677c80-14ea-11ea-8a29-75678695c4c1.png)

**Comment by LiYell** [comment]
我的 MIX 2S 有时候也会, 点更多已下载的服务, 找到 Auto.js 关掉重新打开就可以了

**Comment by weil-f** [comment]
> 我的 MIX 2S 有时候也会, 点更多已下载的服务, 找到 Auto.js 关掉重新打开就可以了

刚才的问题解决了，出现了新的问题，自动打开了蚂蚁森林但是没有自动收取能量，这个问题你遇到过吗？

**Comment by LiYell** [comment]
这个倒是没有遇到过

**Comment by iHx-rainbow** [comment]
> 刚才的问题解决了，出现了新的问题，自动打开了蚂蚁森林但是没有自动收取能量，这个问题你遇到过吗？

脚本设置里的收取功能重新开关一下然后保存 看看有效果不
