### ISSUE TITLE
启动条件检测未通过

### ISSUE THREAD

**Issue by Cheney93** [SuperMonster003/Auto.js_Projects#16]
Auto.jspro: 7.0.2-4
Auto.js: 4.1.1Alpha2
手机:一加6
Android版本:8.1.0
H2OS版本:5.1.14

启动条件检测未通过
然后结束支付宝重启又开始启动条件检测未通过
一直循环！

**Comment by SuperMonster003** [comment]
感谢反馈  
开启开发者测试模式之后 发一下日志截图

**Comment by Cheney93** [comment]
07:18:38.776/V: >> 启动条件检测未通过: (2/5)
07:18:38.779/V: >> 前置App包名不符合条件
07:18:38.781/V: >>> org.autojs.autojs
07:18:38.783/V: >> 重新启动intent

**Comment by SuperMonster003** [comment]
这个日志不是最新版的日志
这个反馈发布时的最新版本是 v1.6.10
看看新版是否问题重现
感谢反馈
:smile:

**Comment by Cheney93** [comment]
00:47
▼▲▲69%
日志
UU.43.41.0957D.
00:45:41 .693/V:>>成功接入"af_ .cfg"本地存储
00:45:41. .693/V:>>整合代码配置与本地配置
00:45:41.693/V:>>成功导入解锁模块
00:45:41.694/V:>>自己能量监测功能已关闭
00:45:41.720/V: >> Auto.js版本: Pro 7.0.2-4
00:45:41.723/V:>> Bug版本检查:正常
00:45:41.727/V:>>项目版本:v1.6.17
00:45:41.729/V:>>成功接入"af"本地存储
00:45:41.730/V:>>准备初始化
00:45:41.730/V:>>设置音量键监听器
00:45:41.768/V:>>安卓系统SDK版本: 27
00:45:41.769/:>>尝试自动解锁
00:45:41.771/V:>>自动解锁完毕
00:45:41.771/V:>>日志存储功能关闭
00:45:41.775/V:>>会话参数赋值完毕
00:45:41.776/V:>>会话参数校正完毕
00:45:41.776/V:>>单次运行最大超时设置完毕
00:45:41.776/V:>>主账户未设置
00:45:41.777/V:>>初始化完毕
00:45:41.777/D:
00:45:41.777/D:开始"蚂蚁森林"任务
00:45:41.777/D:
00:45:41.777/V:>>启动参数intent类型: object
00:45:41.778/V:>>加载intent参数启动应用
00:45:42.806/V:>>应用启动成功
00:45:42 .806/V: >>开始监测启动完成条件
00:45:42.806/V:>>开启"重新加载"按钮监测线程
00:45:55.018/V:>>重新启动Activity: (1/3)
00:46:07.613/V: >重新启动Activity: (2/3)
00:46:19.631/V: >>重新启动Activity: (3/3)
00:46:34.580/V: >>结束"重新加载”按钮监测线程
00:46:34.582/V: >>尝试关闭支付宝应用: (1/3)
00:46:34.797/V: >> shel(方法强制关闭应用成功
00:46:35.099/V: >>加载intent参数启动应用
00:46:37.602/V:>>应用启动成功
00:46:37.602/V:>>开始监测启动完成条件
00:46:37.602/V:>>开启"重新加载"按钮监测线程
X
00:46:41.708/D: -----------_______

**Comment by SuperMonster003** [comment]
已于 `v1.6.18` - `2019/05/13` 尝试修复此问题  
若问题复现 请参考  
https://github.com/SuperMonster003/Auto.js_Projects/issues/20#issue-441989541

**Comment by Cheney93** [comment]
10:39
AA85%
日志
10:38:30.561/V：>成功接入" af_cfg本地存储
10:3830.562/：>>整合代码配置与本地配置
10:38:30.562/V：>成功导入解锁模块
10:38:30.562/：>自己能量监测功能已关闭
10:38:30.585/:>> Auto. js版本:Pro7.0.2-4
10:3830.587/：>Bug版本检查：正常
10:38:30.589/V：>项目版本：V1.6.17
10:38:30.590/V：>>成功接入"af"本地存储
10:3830.591/：>>准备初始化
10:38:30.591/V：>>设置音量键监听器
10:38:30.625/V：>安卓系统SDK版本:27
10:3830.625/>>尝试自动解锁
10:38:30.627/V：>>自动解锁完毕
10:38:30.627：>>日志存储功能关闭
10:38:30.633/V>>会话参数赋值完毕
10:38:30.633/：>会话参数校正完毕
10:38:30.633/V：>>单次运行最大超时设置完毕
10:38:30.634/：>>主账户未设置
10:38:30.634/V：>>初始化完毕
10:38:30.634/D
10:38:30.634/D：开始"蚂蚁森林"任务
10:38:30.634/D
10:38:30.635/V：>启动参数 intent类型： object
10:38:30.635/：>加载 intent参数启动应用
10:38:32.048/V：>>应用启动成功
10:38:32.049/V：>>开始监测启动完成条件
10:38:32.049/：>>开启"重新加载"按钮监测线程
10:38:43.902/V：>>重新启动 Activity：(1/3
10:38:55986/：>重新启动 Activity：(2/3
10:39:08400/：>重新启动 Activity：(3/3)
10:39:23.419/V：>>结束"重新加载"按钮监测线程
10:39:23.421/：>>尝试关闭支付宝应用：(1/3)
10:39:23.657/：>she0方法强制关闭应用成功
10:39:23.960/：>加载 intent参数启动应用
10:39:26.476/：>>应用启动成功
10:39:26476/V：>>开始监测启动完成条件
10:39:26.476/：>>开启重新加载按钮监测线程
10:39:32.267/D:
10:3932268/E：强制停止所有脚本
10:39:32.268/E：->用户按下音量加NOL+键
10:39:32.269/D
10:39:32.273/V:
storage/emulated/0/Bal) zs/Auto. js_Projects/Tools,
Ant_Forest。 js运行结束，用时61.765000秒

**Comment by Cheney93** [comment]
还是这样，我卸载试试看

**Comment by Cheney93** [comment]
10:52
:44A81%
日志
10:48:25.026/V>>成功接入 af_cfg"本地存储
10:48:25.026/V：>整合代码配置与本地配置
10:48:25.027/V：>成功导入解锁模块
10:4825027N：>>自己能量监测功能已关闭
10:4825.071/:>> Auto. js版本:Pro70.24
10:48:25.079/V：>>Bug版本检查：正常
10:48:25.083/V：>>项目版本：V1.6.17
10:48:25.086/：>成功接入"af"本地存储
10:48:25.088/V：>>准备初始化
10:48:25.089/V>>设置音量键监听器
10:48:25.133/V：>>安卓系统SDK版本:2
10:48:25.134/V：>>尝试自动解锁
10:4825.143/V>>自动解锁完毕
10:48:25.145/：>日志存储功能关闭
10:48:25.155/V>>会话参数赋值完毕
10:48:25156/V：>>会话参数校正完毕
10:48:25.158/V>>单次运行最大超时设置完毕
10:48:25.158/V：>主账户未设置
10:48:25159/V：>>初始化完毕
10:48:25.160/D
10:48:25.160/D：开始"蚂蚁森林"任务
10:48:25.161/D
0:48:25.161/V：>>启动参数 Intent类型： object
10:48:25.162/V：>加载 intent参数启动应用
10:48:26.086/：>应用启动成功
10:48:26.087/V：>开始监测启动完成条件
10:48:26.088/：>>开启重新加载按钮监测线程
10:4838.223/V：>>重新启动 Activity：(1/3)
10:48:50.431/V：>>重新启动 Activity：(2/3
10:4902.585/：>重新启动 Activity：(3/3)
10:49:17.690/：>结束重新加载按钮监测线程
10:49:17.693/V：>尝试关闭支付宝应用：(1/3)
10:49:18.019/：>she0方法强制关闭应用成功
10:49:18325/V：>>加载 cIntent参数启动应用
10:49:20.861/：>>应用启动成功
10:49:20.862/V>开始监测启动完成条件
10:49:20.862/V：>>开启"重新加载按钮监测线程
10:49:33320/：>重新启动 Activity：(1/3)
10:4945.188/V：>>重新启动 Activity：(2/3
10:49:57.139/：>重新启动 Activity：(3/3
10:50:11.894/V>>结束"重新加载"按钮监测线程
10:50:11.898/V：>尝试关闭支付宝应用：(2/3)
10:5012.110/V：>>she0方法强制关闭应用成功
10:50:12.414/V>>加载 intent参数启动应用
10:50:14931/：>>应用启动成功
10:50:14.931/：>>开始监测启动完成条件
10:50:14932/V：>>开启"重新加载"按钮监测线程
10:50:27456/：>重新启动 Activity：(1/3
10:50:38.850/V：>>重新启动 Activity：(2/3
10:5050.575/V：>>重新启动 Activity：(3/3
10:51:05413/V>>结束"重新加载"按钮监测线程
10:51:05416/V：>尝试关闭支付宝应用：(3/3)
0:51:05.659/V：>>shel0方法强制关闭应用成功
10:51:05.963/E："蚂蚁森林"首页状态准备失败
10:51:05964/D:-
10:51:05.969/V
Storage/emulated/0/lzs/Auto. js_ Projects/Tools,
Ant_Forest。 js运行结束，用时161.064000秒

**Comment by SuperMonster003** [comment]
看看辅助功能是否正常开启 然后测试一下在森林主页能否用Auto.js抓取到控件  
可以使用延时 然后在延时内返回测试页面  
例如  
```js
sleep(5000);
toastLog(descMatches(/.+/).find().size(), idMatches(/.+/).find().size());
```

**Comment by xseven007** [comment]
同样的问题，之前在支付宝1.62版本没有问题，后来重装了1.59.231版本，出现了首页状态准备失败的现象，本来以为是autojs的问题，但是其他的脚本，比如星星球脚本却可以正常运行。

**Comment by SuperMonster003** [comment]
收到 明天我下载上述版本测试一下 感谢反馈

**Comment by Cheney93** [comment]
21:34:57.914/E: TypeError: Cannot call method "match" of null (/storage/emulated/0/脚本/Auto.js_Projects/Tools/!Ant_Forest.js#796)
TypeError: Cannot call method "match" of null
    at /storage/emulated/0/脚本/Auto.js_Projects/Tools/!Ant_Forest.js:796:0
    at getScreenSamples (/storage/emulated/0/脚本/Auto.js_Projects/Tools/!Ant_Forest.js:793:0)
    at getCurrentScreenTargets (/storage/emulated/0/脚本/Auto.js_Projects/Tools/!Ant_Forest.js:748:0)
    at checkFriendsEnergy (/storage/emulated/0/脚本/Auto.js_Projects/Tools/!Ant_Forest.js:581:0)
    at checkEnergy (/storage/emulated/0/脚本/Auto.js_Projects/Tools/!Ant_Forest.js:464:0)
    at antForest (/storage/emulated/0/脚本/Auto.js_Projects/Tools/!Ant_Forest.js:87:0)
    at /storage/emulated/0/脚本/Auto.js_Projects/Tools/!Ant_Forest.js:79:0

**Comment by SuperMonster003** [comment]
@Cheney93 已修复 (版本号没有改变) 感谢反馈

**Comment by Cheney93** [comment]
不客气！

**Comment by Cheney93** [comment]
@SuperMonster003

又有一个报错！

 21:48:53.766/E: TypeError: Cannot read property "rank_num" from undefined (/storage/emulated/0/脚本/Auto.js_Projects-master/Tools/!Ant_Forest.js#721)
TypeError: Cannot read property "rank_num" from undefined
    at getFriendsListData (/storage/emulated/0/脚本/Auto.js_Projects-master/Tools/!Ant_Forest.js:721:0)
    at collectFriendsListData (/storage/emulated/0/脚本/Auto.js_Projects-master/Tools/!Ant_Forest.js:693:0)
    at checkFriendsEnergy (/storage/emulated/0/脚本/Auto.js_Projects-master/Tools/!Ant_Forest.js:546:0)
    at checkEnergy (/storage/emulated/0/脚本/Auto.js_Projects-master/Tools/!Ant_Forest.js:464:0)
    at antForest (/storage/emulated/0/脚本/Auto.js_Projects-master/Tools/!Ant_Forest.js:87:0)
    at /storage/emulated/0/脚本/Auto.js_Projects-master/Tools/!Ant_Forest.js:79:0

**Comment by SuperMonster003** [comment]
这个是运行`Ant_Forest_Launcher.js`出现的错误吗 还是在设置页面采集好友列表出现的  
中间有弹出Toast提示 `正在采集好友列表数据` 吗

**Comment by Cheney93** [comment]
运行设置，刷新好友列表，没有弹出Toast

**Comment by SuperMonster003** [comment]
已于 `v1.6.22 Alpha2` - `2019/05/15` 尝试修复此问题

**Comment by SuperMonster003** [comment]
启动条件未通过 通常是因为不同设备 支付宝的森林小程序使用不同的控件文本位置导致的 目前已加入动态获取并记忆文本控件位置的function  此Issue暂时关闭
