### ISSUE TITLE
1.9.9有时候会停在支付宝首页, 下拉到最底部, 一动不动

### ISSUE THREAD

**Issue by LiYell** [SuperMonster003/Auto.js_Projects#160]

**Comment by fflzh** [comment]
那是误返回到主页了，然后继续执行了下拉，我的也是这样

**Comment by LiYell** [comment]
兄台如何解决?

**Comment by fflzh** [comment]
看“魅族16s过度返回”的那个问题，好像有人找到解决方法了，我还没试

**Comment by l919898756** [comment]
我也这样,不是有时,是经常这样

**Comment by iHx-rainbow** [comment]
>停在支付宝首页, 下拉到最底部, 一动不动

尝试临时解决方法 [Reference](https://github.com/SuperMonster003/Auto.js_Projects/issues/150#issuecomment-559911463)
修改Ant_Forest_Launcher.js文件 function jumpBackOnce() 方法中的返回操作
```js
debugInfo("模拟返回按键返回上一页");
//注释代码第4358行，并替换为back();
//keycode(4, "double"); 
back();
```
后续等大佬发布下个版本

**Comment by l919898756** [comment]
楼上的临时解决方案非常有效

**Comment by ylhbot2** [comment]
有效，感谢！

**Comment by SuperMonster003** [comment]
https://github.com/SuperMonster003/Auto.js_Projects/issues/150
