### ISSUE TITLE
1.9.9

### ISSUE THREAD

**Issue by iamjazz** [SuperMonster003/Auto.js_Projects#161]
且会误点公益林  好像退不出来？
然后会循环  循环 auto.js页面和 好友排行榜页面
#160 楼的问题我这也出现了
我不确定好友排行榜页面和auto页面循环到底正常不正常 
不知道是不是我设置问题

**Comment by iHx-rainbow** [comment]
公益林活动目测是首次打开蚂蚁森林时会自动弹出
音量上键强制停止脚本之后
重新再运行应该就不会出现误点了

> 然后会循环 循环 auto.js页面和 好友排行榜页面

尝试临时解决方法
修改Ant_Forest_Launcher.js文件 function jumpBackOnce() 方法中的返回操作
```js
debugInfo("模拟返回按键返回上一页");
//注释第4358行，并替换为back();
//keycode(4, "double"); 
back();
```
后续等大佬下个版本

**Comment by SuperMonster003** [comment]
公益林活动误触已交付遮罩层弹窗监控功能模块
以后如果再出现活动误触 可重新反馈
另外一个问题参阅 https://github.com/SuperMonster003/Auto.js_Projects/issues/150
此 issue 暂时关闭
感谢支持
