### ISSUE TITLE
延时接力配置文件报错 list_heads is not defined Vol1.99

### ISSUE THREAD

**Issue by iHx-rainbow** [SuperMonster003/Auto.js_Projects#162]
修改定时循环 延时接力配置时报错
Ant_Forest_Settings.js 第2466 2472 6158行  
```js
let arr = list_heads[data_source_key_name];
```
报错 ReferenceError: "list_heads" is not defined.

--- 
尝试添加 `let {list_heads} = $config;` 
或改写成 `let arr = $config.list_heads[data_source_key_name];`
停止报错 配置修改保存成功

**Comment by SuperMonster003** [comment]
`v1.9.10` 已尝试修复上述问题 如使用后问题复现 可继续反馈
