### ISSUE TITLE
[解决方案]1.9.9有时候会停在支付宝首页, 下拉到最底部, 一动不动

### ISSUE THREAD

**Issue by l919898756** [SuperMonster003/Auto.js_Projects#163]
>停在支付宝首页, 下拉到最底部, 一动不动

尝试临时解决方法 [Reference](https://github.com/SuperMonster003/Auto.js_Projects/issues/150#issuecomment-559911463)
修改Ant_Forest_Launcher.js文件 function jumpBackOnce() 方法中的返回操作
```js
debugInfo("模拟返回按键返回上一页");
//注释代码第4358行，并替换为back();
//keycode(4, "double"); 
back();
```
后续等大佬发布下个版本

_Originally posted by @iHx-rainbow in https://github.com/SuperMonster003/Auto.js_Projects/issues/160#issuecomment-560992261_

**Comment by ylhbot2** [comment]
有效，感谢
