### ISSUE TITLE
还是一样的问题，好友排行榜初始化准备失败，进入排行榜也不会上滑动

### ISSUE THREAD

**Issue by android-cui** [SuperMonster003/Auto.js_Projects#165]
还是一样的问题，好友排行榜初始化准备失败，进入排行榜也不会上滑动
刚刚下载的最新版本
用的autojs4.1.1_alpha2
支付宝：10.1.80 （最新版）
手机是华为mate10
android版本9
EMUI版本：9.1.0

请大神再查查

**Comment by SuperMonster003** [comment]
https://github.com/SuperMonster003/Auto.js_Projects/issues/143
