### ISSUE TITLE
bug反馈

### ISSUE THREAD

**Issue by LiaJing** [SuperMonster003/Auto.js_Projects#168]
楼主在不在，反馈几个bug.
1.oppo r17不能自动解锁，具体为不能识别密码布局，也不能收集密码布局
2.小米mix miui10需要自己设置滑动路径8%到50%时间110s才能滑动解锁到输入密码界面
3.收取黑名单不能用，
主要是不能收集支付宝好友列表
具体日志
10:51:22.809/E: TypeError: Cannot read property "common_browser_rich" from undefined (/storage/emulated/10/脚本/Auto.js_Projects-Ant_Forest/Ant_Forest_Launcher.js#4757)
TypeError: Cannot read property "common_browser_rich" from undefined
    at plans (/storage/emulated/10/脚本/Auto.js_Projects-Ant_Forest/Ant_Forest_Launcher.js:4757:0)
    at /storage/emulated/10/脚本/Auto.js_Projects-Ant_Forest/Ant_Forest_Launcher.js:1142:0
    at /storage/emulated/10/脚本/Auto.js_Projects-Ant_Forest/Ant_Forest_Launcher.js:1132:0
    at /storage/emulated/10/脚本/Auto.js_Projects-Ant_Forest/Ant_Forest_Launcher.js:1103:0
    at /storage/emulated/10/脚本/Auto.js_Projects-Ant_Forest/Ant_Forest_Launcher.js:1316:0

**Comment by LiaJing** [comment]
。

**Comment by LiaJing** [comment]
还是没有解决
黑名单
17:16:15.791/E: TypeError: Cannot read property "common_browser_rich" from undefined (/storage/emulated/10/脚本/Auto.js_Projects-Ant_Forest/Ant_Forest_Launcher.js#4806)
TypeError: Cannot read property "common_browser_rich" from undefined
    at plans (/storage/emulated/10/脚本/Auto.js_Projects-Ant_Forest/Ant_Forest_Launcher.js:4806:0)
    at /storage/emulated/10/脚本/Auto.js_Projects-Ant_Forest/Ant_Forest_Launcher.js:1284:0
    at /storage/emulated/10/脚本/Auto.js_Projects-Ant_Forest/Ant_Forest_Launcher.js:1275:0
    at /storage/emulated/10/脚本/Auto.js_Projects-Ant_Forest/Ant_Forest_Launcher.js:1246:0
    at /storage/emulated/10/脚本/Auto.js_Projects-Ant_Forest/Ant_Forest_Launcher.js:1471:0

**Comment by SuperMonster003** [comment]
`v1.9.10` 使用后问题复现 可继续反馈
