### ISSUE TITLE
小米9,1.6.6 1.6.8 1.6.9不能定时启动自动操作。

### ISSUE THREAD

**Issue by ggyy8850** [SuperMonster003/Auto.js_Projects#17]
小米9,1.6.6 1.6.8 1.6.9不能定时启动自动操作。定时任务设定后，不能自动亮屏解锁操作。

1.6.4自动亮屏解锁操作正常。更新后不行。
![微信图片_20190508155549](https://user-images.githubusercontent.com/40348521/57359256-d9437800-71a9-11e9-8ab0-75fbfa83ac44.png)

谢谢分享，更新非常快。辛苦大神

**Comment by ggyy8850** [comment]
就刚刚开始进森林后就不动了，不能进好友列表！过一会插件又重新打开一次森林，但就是不进好友列表

**Comment by SuperMonster003** [comment]
在支付宝首页 使用Auto.js布局分析 看一下能不能抓取到控件 再手动拉到底下 看能不能分析到"查看更多好友"按钮

**Comment by ggyy8850** [comment]
1.6.22 alpha3版本，问题依然，能进好友列表，但是收1个后就自动结束。下滑不完全。
![image](https://user-images.githubusercontent.com/40348521/57748958-b3b8f000-770e-11e9-8a67-f1caff701eac.png)

**Comment by SuperMonster003** [comment]
@ggyy8850 此问题源于部分设备蚂蚁森林小程序随机变更文本控件位置导致文本获取失败  
目前已修复 此Issue展示关闭
