### ISSUE TITLE
一进入蚂蚁森林就提示typeerror，截图如下

### ISSUE THREAD

**Issue by lukegood** [SuperMonster003/Auto.js_Projects#176]
一进入蚂蚁森林就提示typeerror，截图如下
![TIM图片20191207113748](https://user-images.githubusercontent.com/36125093/70368501-4527c380-18e6-11ea-991b-c4893febb6c2.jpg)

**Comment by SuperMonster003** [comment]
`v1.9.10` 已尝试修复上述问题 如使用后问题复现 可继续反馈
