### ISSUE TITLE
1.9.10Beta 5版本华为Mate20好友列表一般在200-500间会自动退出

### ISSUE THREAD

**Issue by lchongxiu** [SuperMonster003/Auto.js_Projects#178]
我有900多好友，1.9.10Beta 5版本华为Mate20好友列表一般在200-500间会自动退出，每次都无法执行完全部好友。配置自动保存beta5已经修复，beta3进入列表直接报错也修复，但每次还会有一个报错信息，但不影响执行。苦等新版已经接近2周，继续等待接近完美版本中。

**Comment by SuperMonster003** [comment]
https://github.com/SuperMonster003/Auto.js_Projects/issues/185
