### ISSUE TITLE
1.9.10Beta 5只能收自己的能量，无法上滑收取，退出时还是提示排行榜好友初始化准备失败

### ISSUE THREAD

**Issue by toneydeng** [SuperMonster003/Auto.js_Projects#179]
1.9.10Beta 5只能收自己的能量，无法上滑收取，退出时还是提示排行榜好友初始化准备失败,而且跳过设置点了不再提醒，还是会出来 ，没有作用

米8   miui11

大神查查看

**Comment by toneydeng** [comment]
觉的应该把那个跳过设置那一步删掉，没有实际意义，可以直接在加个帮助文件显示就可以了

**Comment by SuperMonster003** [comment]
`v1.9.10` 已尝试修复上述问题 如使用后问题复现 可继续反馈
