### ISSUE TITLE
1.9.10 beta5 进入setting也就是设置模块出错

### ISSUE THREAD

**Issue by luchangharry** [SuperMonster003/Auto.js_Projects#181]
mate30 pro，功能脚本运行正常，但是进入setting设置模块后报错，日志入下：
![1651575731379_ pic](https://user-images.githubusercontent.com/50188136/70376713-d9c20e00-1946-11ea-8845-f66b38bf9f37.jpg)

**Comment by SuperMonster003** [comment]
`v1.9.11` 已修复以上问题
