### ISSUE TITLE
循环运行脚本, 并且报并发修改异常

### ISSUE THREAD

**Issue by LiYell** [SuperMonster003/Auto.js_Projects#183]
机型: 小米MIX2S
支付宝版本: 10.1.80
![image](https://user-images.githubusercontent.com/34156556/70384069-e16bcc00-19b3-11ea-92ee-77c6b4c9e9eb.png)
![image](https://user-images.githubusercontent.com/34156556/70384072-e92b7080-19b3-11ea-99b2-125a649ee710.png)
还有一个偶尔会报的参数异常
![image](https://user-images.githubusercontent.com/34156556/70384075-f5afc900-19b3-11ea-9ff2-b17d2361e83b.png)

**Comment by wonder566** [comment]
+1
![Screenshot_20191212_073549_org autojs autojs](https://user-images.githubusercontent.com/923001/70670667-aa97fd80-1cb4-11ea-8932-ff9c4344735a.jpg)

**Comment by SuperMonster003** [comment]
`v1.9.10` 已尝试修复上述问题 如使用后问题复现 可继续反馈
