### ISSUE TITLE
能不能做成一次性加载完所有好友的形式？

### ISSUE THREAD

**Issue by ljaist** [SuperMonster003/Auto.js_Projects#187]
在打开好友列表时，先全部加载完所有好友，然后再判断此次列表中是否有可立即收的能量，跳到该好友进行收取。然后再判断最小倒计时，时间到时，跳到该好友收取。我自己手工收取时就是用这样的方式，省去了重复加载好友列表的操作。

**Comment by SuperMonster003** [comment]
此方案不被接受
在 好友数量过多 或 网速较差 情况下
完全加载列表需要耗费非常多的时间
而且新版控件很难在不拉动列表的情况下判断是否到达列表底部

另外最重要的一点
项目重复刷新排行榜的目的
不仅有立即到达顶部的作用
更有校正列表倒计时的作用‘
因为列表倒计时往往不准确
经常出现 列表剩余 3 分钟 
而实际只有 2 分钟甚至 1 分钟的情况
早起的森林版本还有出现僵尸 1 分钟的情况
即 1 分钟的倒计时永远出现在列表中 不会消失
因此项目采用了每次完全刷新列表 且 边滑动边扫描/采集的方案

感谢提供建议
