### ISSUE TITLE
早上六点半屏幕解锁问题

### ISSUE THREAD

**Issue by AlbertLinstan** [SuperMonster003/Auto.js_Projects#188]
白天可以自动解锁手机，定时早上6点半启动的时候，无法解锁屏幕，提示：000/E:'屏幕关闭'事件解除超时，beta2好像能正常解锁，beta5,6,7都有这个情况。
script：beta7
autojs：4.1.1 已获取root权限
android：9
system：miui10，开发板
phone：小米note3

**Comment by SuperMonster003** [comment]
尝试 v1.9.10 之后如果问题复现
请提供日志截图
感谢支持
