### ISSUE TITLE
instantMonSetter-volKeys 音量键监听问题 疑惑求解答 1.9.10 Beta7

### ISSUE THREAD

**Issue by iHx-rainbow** [SuperMonster003/Auto.js_Projects#189]
今天收取能量的时候来消息了 想强行停止脚本回消息
发现音量键监听失效了

---
自己测试了一下
- 问题是在代码重构之后的版本出现的
- 在打开脚本和收取自己能量步骤 均可以正常监听
- 但是跳转到好友排行榜之后 监听器失效了

---
不知道是不是checkFriendsEnergy里threads的问题额
自己琢磨了下然而也没有解决……

麻烦作者看下有啥解决办法告知一下😂

重构辛苦啦~👍

---
小米 MIX 2
Android P
MIUI 11

**Comment by SuperMonster003** [comment]
很难得研究如此深入
问题在于 events.recycle() 把 keysEvents 回收掉了
当初加这个在 observeToastMessage() 中是为了避免再次被调用时无法使 toast 监听生效的问题  
现在已经不记得这个 recycle() 的必要性了 
你可以试试先去掉它 看看项目运行是否有问题 
目前 observeToastMessage() 使用的唯一地方就在 自己能量的倒计时数据 toast 监控线程

看你的 ID 感觉熟悉 再看了头像基本确认了
我早期写项目的时候 看了一下给 Nick 提交 PR 的人都有哪些 大概看了一下他们的信息
所以就认出来了 很高兴能在这里看到你提出 issue

如果愿意的话 欢迎联系我 (在图像配置脚本里可找到)  
我自己建立了一个内测群 里面只有寥寥十几人 十分欢迎也十分渴望任何有识之士的加入
😃

**Comment by iHx-rainbow** [comment]
是的 我尝试注释了events.recycle()这一行 音量键监听问题完美解决了🎉

目前测试运行之后 首次运行和定时启动都正常
toast监听自己能量倒计时的结果也没有问题

打算等待自动任务再多运行几遍
观察一下后续的toast监听是否会有异常情况

👍 已经发出申请了 希望加入内测~

**Comment by peng-qiang** [comment]
可惜我学的是java  大神的代码拜读起来很吃力  现在遇到问题无法解决

**Comment by SuperMonster003** [comment]
@peng-qiang 有问题或建议可反馈
