### ISSUE TITLE
1.9.10 beta6 及之前beta碰到的问题

### ISSUE THREAD

**Issue by keli1973** [SuperMonster003/Auto.js_Projects#191]
因为才刚刚更新的beta7，不知道是否已修复，但看介绍没提及，所以来说一下。
问题就是每天早上我7点自己运行脚本，看到自己的能量还差20分钟，但不会跳出到朋友列表，并且提示“none stop checking time”。然后我查过设置主页能量的检测阈值为2min，按道理是不应该20分钟就进入这种模式才对，麻烦检查一下。
这个bug有时候多运行几次就可以跳过去。

**Comment by keli1973** [comment]
补充一下，beta7还是遇到类似问题，而且貌似是和主页的待收能量球数量有关，这几天都是5,6个待收但时间还没到的能量球，如果过了早高峰收了2个以后，貌似就正常了。

**Comment by SuperMonster003** [comment]
开启开发者测试模式后 可查看到主页能量球倒计时获取的方案
目前有两个
1. 通过捕获 toast 消息中的文本信息计算倒计时
2. 通过 baiduOcr 方法截图并上传图片到 baidu 返回数据计算倒计时

第一种方案是最高效且出错率极地的
但有些设备不支持 (也与安卓系统版本有关)
所以脚本会自动采用第二种方案
第二种方案获取截图时 经常会遇到森林树的弹出对话框影响
同时也收到 OCR 识别准确率的影响
因此导致得到的数据有很大概率不准确

在查看日志后
能获知是否采用了第二种方案
如果是 项目目前还没有更好的优化方案
如果不是 请继续反馈

感谢支持
