### ISSUE TITLE
redmi K20 PRO 出现进入好友列表只上滑一次就退出

### ISSUE THREAD

**Issue by ciyoooo** [SuperMonster003/Auto.js_Projects#192]
除了标题问题有时候出现解锁界面，上滑程度达不到激活解锁密码的界面。

**Comment by zzliux** [comment]
自己配置那个滑动起止位置的百分比

**Comment by SuperMonster003** [comment]
1. 标题问题 v1.9.10 依然存在吗
2. 滑动解锁问题可调整滑动起止位置的百分比 尽量调小距离 (即起始底部调小 结束顶部调大)
