### ISSUE TITLE
蚂蚁森林新改版

### ISSUE THREAD

**Issue by Qingtian-creat** [SuperMonster003/Auto.js_Projects#193]
蚂蚁森林最近又在改版，被好友浇水之后自己的森林页面会长出黄色的能量球，黄色能量球是重叠的，好像是多少好友浇水就有多少球，得自己点击收取，不知道新版的森林主页面对脚本控件的识别有没影响，希望大神注意下，辛苦！

**Comment by SuperMonster003** [comment]
后续会针对金色能量球进行项目改进与优化
感谢提供建议
