### ISSUE TITLE
收取自己的能量后退出到zfb主界面跳不到好友排行的界面，必须切到aj界面才能跳到好友排行

### ISSUE THREAD

**Issue by zzliux** [SuperMonster003/Auto.js_Projects#194]
不知道是不是只有我有这样的问题，4.1.1 alpha2 无root ，flyme8

**Comment by Garry24** [comment]
aj界面是什么界面

**Comment by SuperMonster003** [comment]
不是个例
而且目前仅出现在魅族设备上
尝试 v1.9.10 之后如果问题依然存在 可继续在此反馈

@Garry24 aj界面就是 Auto.js 应用的主页面

**Comment by zzliux** [comment]
> 不是个例
> 而且目前仅出现在魅族设备上
> 尝试 v1.9.10 之后如果问题依然存在 可继续在此反馈
> 
> @Garry24 aj界面就是 Auto.js 应用的主页面

更新今天的1.9.10后好像可以了

**Comment by SuperMonster003** [comment]
> 
> 
> > 不是个例
> > 而且目前仅出现在魅族设备上
> > 尝试 v1.9.10 之后如果问题依然存在 可继续在此反馈
> > @Garry24 aj界面就是 Auto.js 应用的主页面
> 
> 更新今天的1.9.10后好像可以了

好 此 issue 暂时关闭
如果以后问题复现 
可 reopen 此 issue 或开启新的 issue 反馈
感谢支持
