### ISSUE TITLE
beta7版本仍然收取好友失败

### ISSUE THREAD

**Issue by baocq2019** [SuperMonster003/Auto.js_Projects#195]
redmi k20 pro.
autojs 4.1.0alpha5.

收取自己能量正常。

进入好友列表下拉之后，画面停滞，然后脚本重启，不断重复。

想问问各位都是正常的吗？

**Comment by soupxb** [comment]
我也有类似问题，有时正常，有时就报错，然后过几分钟再自动运行一遍
手机Mate30Pro

**Comment by SuperMonster003** [comment]
`v1.9.10` 使用后问题复现 可继续反馈
此 issue 暂时关闭
