### ISSUE TITLE
关于安卓系统屏蔽4.1.1alpha2版本部分函数问题

### ISSUE THREAD

**Issue by AlbertLinstan** [SuperMonster003/Auto.js_Projects#196]
android9，MIUI开发板，已授予root
进测试返现，手机开发者的高风险功能开启提醒服务会屏蔽软件对于一些函数的方位，目前已知的函数为device函数
例如：device.height;
device.weight;

偶尔会失效的函数：
device.wakeUpIfNeeded()
失效原因进一步研究中，如果用户使用过后不久，此函数依旧有效，但是长时间息屏不使用的话，此函数可能失效。

**Comment by SuperMonster003** [comment]
感谢反馈并分享开发经验

```js
console.log(require("./Modules/MODULE_MONSTER_FUNC").getDisplayParams());
```

可查看本项目 MONSTER 模块中的方法是否可在控制台打印出正确的设备屏幕信息

**Comment by AlbertLinstan** [comment]
控制台输出如下：
18:20:03.419/D: { WIDTH: 1080,
  USABLE_WIDTH: 1080,
  HEIGHT: 1920,
  USABLE_HEIGHT: 1920,
  screen_orientation: 0,
  status_bar_height: 66,
  navigation_bar_height: 130,
  navigation_bar_height_computed: 0,
  action_bar_default_height: 132,
  cX: [Function],
  cY: [Function] }
貌似没有问题，从我的使用体验来看，第一天所有功能都很完美，但是使用两三天之后，自动解锁偶尔会失效。
device函数失效问题出现在我自己的脚本中，我目前的操作是把这些变量设置为常数，我正在尝试自己写一个唤醒手机的脚本，来解决不能正常唤醒的问题。
其他功能都很正常，感谢开发者的开源和维护。

**Comment by SuperMonster003** [comment]
自己写的话
可能需要用到电源管理服务
可能需要诸如 ACQUIRE_CAUSES_WAKEUP 的 flag
具体可参阅 Auto.js 的源码 
https://github.com/hyb1996/Auto.js/blob/master/autojs/src/main/java/com/stardust/autojs/runtime/api/Device.java

**Comment by AlbertLinstan** [comment]
非常感谢
