### ISSUE TITLE
早上起来支付宝蚂蚁森林叠加了很多的页面

### ISSUE THREAD

**Issue by youaaaaa** [SuperMonster003/Auto.js_Projects#198]
未进入好友排行榜,   有时候收自己能量,有时候不收,   应该是获取屏幕截屏失败..进入好友列表失败, 
shell()关闭支付宝失败,  只能最小化应用.   叠加过多卡死 ??？　不知道是这个原因吗？　　怎么解决呢？　　
进入auto.js看日志直接卡死在日志页, 内存占用1.9G(只有脚本跟支付宝) ;  重新运行auto.js多次后正常,
应该是运行报错, 但是日志进去会卡死 ,  看不到报错信息 . . .

**Comment by youaaaaa** [comment]
有个Wrapped CvException在opencv/modules/core/src/matrix.cpp:367的错误
(-215:Assertion failed) u! = 0 in function ' void cv::Mat::create(int, const int* int)'
能否解答一下

**Comment by SuperMonster003** [comment]
页面叠加与蚂蚁森林H5的传入参数有关
此参数部分可控 部分无法通过脚本传参去控制
因此可能无法按照预期像支付宝开发文档那样写明的可以在打开页面前关闭其他页面
只能靠脚本自己去识别页面并关闭
v1.9.10已经尝试优化了关于页面关闭的部分代码
可尝试使用 并在问题复现后 reopen issue 反馈或重新开 issue 反馈
感谢支持

另外 opencv 的问题需要提供日志截图才能分析

**Comment by youaaaaa** [comment]
最新版本暂时未发现叠加问题了, 
我更换了你项目里提供的autojs,之前一直无法下载故使用了其它渠道的autojs,也是推荐版本
不知道是autojs的问题还是新版本修复了
