### ISSUE TITLE
安卓10都不可以

### ISSUE THREAD

**Issue by LiaJing** [SuperMonster003/Auto.js_Projects#199]
安卓10大部分都是好友排行榜初始化失败，并且很多提示无障碍bug

**Comment by AlbertLinstan** [comment]
不行不用就行了，毕竟软件一年都没有更新了，不能适配新的系统新的补丁很正常。

**Comment by LiaJing** [comment]
没有呀，上个星期刚更新过

**Comment by SuperMonster003** [comment]
参加 https://github.com/SuperMonster003/Auto.js_Projects/issues/143
另排行榜初始化失败是项目本身的问题 不是设备的问题
支付宝更新控件之后 项目没有即使跟进
现在可尝试使用 v1.9.10 并在问题复现后重新反馈
此 issue 暂时关闭
感谢支持
