### ISSUE TITLE
小米9 蚂蚁森林首页状态准备失败

### ISSUE THREAD

**Issue by lwh201314** [SuperMonster003/Auto.js_Projects#20]
到蚂蚁森林首页就不动了，然后一直重新打开蚂蚁森林
![Screenshot_2019-05-09-07-38-52-381_org autojs autojspro](https://user-images.githubusercontent.com/33437578/57415211-edc95400-722d-11e9-8418-1ebd839a0696.png)

**Comment by kaixin1995** [comment]
兄弟，我们出现了同样的情况，我是从昨天下午开始就变成了这个样子。

**Comment by SuperMonster003** [comment]
感谢大家的反馈
:smile:
可以尝试一下 v1.6.12

**Comment by lwh201314** [comment]
![Screenshot_2019-05-09-17-19-29-534_org autojs autojspro](https://user-images.githubusercontent.com/33437578/57442522-c189f380-727e-11e9-8c07-448fa8be9bc7.png)

**Comment by SuperMonster003** [comment]
今晚之前会发布新版解决这个问题 请关注更新 感谢支持  
😄

**Comment by kaixin1995** [comment]
v1.6.12也是同样的问题，我的手机是mix3

**Comment by SuperMonster003** [comment]
@kaixin1995  
1.6.13暂时还没发布 我今晚会发布的 😃

**Comment by lwh201314** [comment]
13和14还是一样的问题，上面是13的日志，底下是14的
![Screenshot_2019-05-10-12-32-37-906_org autojs autojspro](https://user-images.githubusercontent.com/33437578/57502787-de2a3800-731f-11e9-89df-f56dec2cc699.png)

**Comment by SuperMonster003** [comment]
😃 
感谢反馈  
可以尝试开启开发者测试模式 然后再反馈一下错误日志  
另外脚本一次都没成功过吗 一直停在首页状态准备失败吗

**Comment by lwh201314** [comment]
![Screenshot_2019-05-10-21-56-54-288_org autojs autojspro](https://user-images.githubusercontent.com/33437578/57532731-c5953e80-736e-11e9-8627-57065edb2feb.png)
是的，试了四五次一次都没成功过

**Comment by SuperMonster003** [comment]
感谢反馈  
可以尝试在蚂蚁森林主页面 能不能用Auto.js抓取到控件  
另外我建议把Auto.js卸载重装一下 设备也重启一下  
然后打开无障碍设置 重新运行一下项目  
目前问题就是控件抓取不到

**Comment by lwh201314** [comment]
还真是autojs的问题，清除一下数据就好了
感谢
