### ISSUE TITLE
好友排行榜初始状态准备失败

### ISSUE THREAD

**Issue by Garry24** [SuperMonster003/Auto.js_Projects#201]
新版支付宝(好友排行有周榜，总榜的)，自己能量收取ok，好友能量排行榜一直加载失败，查看日志显示好友排行榜初始状态准备失败

**Comment by daxinnan** [comment]
我的beta7脚本在昨天或前天？更新支付宝后从昨天下午开始无法使用了，也是这个原因
![Screenshot_20191221-070539](https://user-images.githubusercontent.com/26436171/71298693-394aff80-23c4-11ea-8d83-026a4718cf32.jpg)

**Comment by l919898756** [comment]
+1

**Comment by SuperMonster003** [comment]
https://github.com/SuperMonster003/Auto.js_Projects/issues/143
