### ISSUE TITLE
如何设置在一个时间区间内，反复收取排行榜？

### ISSUE THREAD

**Issue by Garry24** [SuperMonster003/Auto.js_Projects#202]
如题，比如说7:00-8:00这一个小时，让脚本反复按着排行榜反复跑

**Comment by SuperMonster003** [comment]
例如 使用延时接力机制 ["07:00", "08:00"] 间隔 5 分钟
PS: 项目不支持无限无条件循环检测 每次循环或自动设置定时任务 一定要有相应的触发条件 否则项目会自动停止当前运行 最大程度保证不浪费设备的硬件资源以及不影响用户对于设备的正常使用
