### ISSUE TITLE
V1.9.10 beta7 使用BUG及建议

### ISSUE THREAD

**Issue by keli1973** [SuperMonster003/Auto.js_Projects#203]
BUG：
1.早上运行一段时间后，一定概率变成运行了2个脚本，按音量+看到停止了2个脚本；
2.主页能量球时间有一定概率倒数识别错误，有可能还有10分钟就开始non stop checking time,也有可能剩1分钟还会出去看排行榜的朋友，不知道是否和上面提到的有关联；
3.主页收能量时间为7：21分，但超过后都没返回主页收取，需要人工停止脚本重新运行才可以，否则会出现被人偷的情况；
建议：
提升接力延时机制的时间段权重，如果定时超出设置的时间段则无效，并会自动定在下一段接力延时机制的开始时间，这样的优点是可以设置一个早上的密集采集时间段（7:00~7:30），中午一次，傍晚一次，凌晨一次。这样就不会因为排行榜的其他人的零星支付影响平常的手机使用，不然可能因为帮收功能而导致手机每个10分钟都要启动一次，很困扰。

**Comment by SuperMonster003** [comment]
1 使用 v.1.9.10 之后如果问题复现可继续反馈
2 参见 https://github.com/SuperMonster003/Auto.js_Projects/issues/191
3 同 1 在 v1.9.10 正式版已经尝试修复此问题
至于延时接力 已在 #217 回复
