### ISSUE TITLE
奇数次循环好友能量排行榜卡住不动

### ISSUE THREAD

**Issue by daxinnan** [SuperMonster003/Auto.js_Projects#204]
beta7版更新最新支付宝以后，进入好友排行榜会卡住，停留在排行榜界面大概2分钟然后会自动运行再次循环排行榜会正常运行，然后第三次又会卡住这样。

**Comment by SuperMonster003** [comment]
请尝试 v1.9.10 并在问题复现后继续反馈
感谢支持

**Comment by daxinnan** [comment]
> 请尝试 v1.9.10 并在问题复现后继续反馈
> 感谢支持

哇，感谢作者大大元旦就开工了。刚刚下载使用新版本没有发现问题，自收，收好友能量和帮收功能都是正常的，等明天早上再检查下解锁和定时收能量。

**Comment by daxinnan** [comment]
emmm刚才摸索了一下，解锁功能没有问题。但是，
1. 试着修改能量球点击间隔时间失败。
2. 偶尔出现帮收能量不成功，不过影响不大。
![微信图片_20200101174118](https://user-images.githubusercontent.com/26436171/71640040-c859f080-2cbd-11ea-865b-7bf2251fb7e9.jpg)

**Comment by SuperMonster003** [comment]
v1.9.11 已尝试修复范围问题
帮收球漏收等后续版本优化
