### ISSUE TITLE
2019.12.23bug反馈

### ISSUE THREAD

**Issue by qcnhy** [SuperMonster003/Auto.js_Projects#205]
目前排行榜可以移动，可以正常进入好友森林领取能量球，但无法退回排行榜界面，要手动点返回，

**Comment by weishinexk** [comment]
同上，收完一个好友能量后，无法退回排行榜界面

**Comment by SuperMonster003** [comment]
`v1.9.10` 已尝试修复上述问题 如使用后问题复现 可继续反馈
