### ISSUE TITLE
2019/12/25 v1.9.10 Beta8 新版本bug

### ISSUE THREAD

**Issue by hello-xiao** [SuperMonster003/Auto.js_Projects#206]
获取截图权限失败，已经开启了“后台弹出权限”
![Screenshot_2019-12-25-17-51-57-868_org autojs aut](https://user-images.githubusercontent.com/50265533/71442276-36436c80-2740-11ea-96bd-ba333060699a.jpg)
![Screenshot_2019-12-25-17-57-52-655_com miui secur](https://user-images.githubusercontent.com/50265533/71442277-37749980-2740-11ea-96c8-06321b30d4e4.jpg)

**Comment by SuperMonster003** [comment]
此问题源于代码重构时
将首次申请截图权限的方法放在了 OCR 识别倒计时的线程里

OCR 识别线程在 Toast 方案正常的情况下
存活时间基本不超过 100ms
而截图权限申请到完成需要的时间通常需要 200ms 以上
在申请完成之前就随着 OCR 线程一起被强制中断
导致截图权限申请失败

v1.9.10 已经尝试修复了此问题
亦即将首次申请方法放到了合适的位置 且 非子线程内

如果问题复现 可继续反馈
感谢支持
