### ISSUE TITLE
老是会第二次进入一个好友森林，然后循环下拉

### ISSUE THREAD

**Issue by wyfang** [SuperMonster003/Auto.js_Projects#208]
小米9，miui11，4.1.1 Alpha2。
就是收取一个好友的能量后，会返回列表又瞬间再次进入该好友森林，然后一直向下滚动屏幕，看好友的历史能量信息。。

**Comment by a1103688841** [comment]
我也是

**Comment by a1103688841** [comment]
我的是有帮收的好友，就会一直在他的历史收取记录中下拉

**Comment by SuperMonster003** [comment]
`v1.9.10` 已尝试修复上述问题 如使用后问题复现 可继续反馈
