### ISSUE TITLE
关于升级

### ISSUE THREAD

**Issue by zhangguangjin** [SuperMonster003/Auto.js_Projects#21]
如何自动更新？你发布的更新太快，老是手动下来覆盖更文件，麻烦

**Comment by zhangguangjin** [comment]
如何自动更新？你发布的更新太快，老是手动下来覆盖更文件，麻烦

**Comment by SuperMonster003** [comment]
感谢反馈  
😃 
自动更新暂时没有实现  
最近更新主要是修复各种bug  
如果当前版本运行良好 而且版本升级说明上没有新增功能 是没必要升级的  
自动升级功能以后会考虑加入 前提是修复完主要bug  
感谢支持

**Comment by zhangguangjin** [comment]
谢谢回复，我用Nick的怎么弄都无法解锁，也许是我不会配置，后来找到你的项目，设置密码就能解锁了，挺方便的！

**Comment by SuperMonster003** [comment]
密码解锁的原理其实没有特别复杂 只是需要收集不同设备的控件样本 做适度匹配  
这种控件的方式 想要实现万能解锁 是不可能的  
大多数安卓系统没有深度定制修改 控件名称和布局都是遵循安卓原生的设定的 因此这样的机型解锁起来也相对容易  
否则就要在代码中加入特定机型的解锁代码了
