### ISSUE TITLE
Beta8返回排行榜失败

### ISSUE THREAD

**Issue by withsalt** [SuperMonster003/Auto.js_Projects#210]
机型：小米6X  
系统：MIUI11  
问题：
1、进入好友能量收取页面后，无法重新返回排行榜，提示返回排行榜失败。  
用back();替换$app.page.back()后可以返回好友列表，但是有时候返回失败，会在好友动态页面持续下拉(在back();后面加一句sleep(500)似乎可以解决这个问题？？？)。  
2、某些帮收能量球收取不到。  
日志：  
![01.jpg](https://i.loli.net/2019/12/26/IF6NJtDPA8ZsBhQ.jpg)  
  
无法收取的能量球：  
![02.jpg](https://i.loli.net/2019/12/26/wAD3yYKCvdEkXtp.jpg)

**Comment by debugerliu** [comment]
嗯，差不多是这样，我好好像也会重现这个

**Comment by SuperMonster003** [comment]
https://github.com/SuperMonster003/Auto.js_Projects/issues/205
