### ISSUE TITLE
荣耀10设备，beta10，截图权限申请失败！

### ISSUE THREAD

**Issue by todoitnow** [SuperMonster003/Auto.js_Projects#213]
![00](https://user-images.githubusercontent.com/48546827/71494498-9a6e4980-2882-11ea-9bb3-260375f09b84.jpg)

**Comment by stilltheearth** [comment]
荣耀9也是这个问题

**Comment by SuperMonster003** [comment]
https://github.com/SuperMonster003/Auto.js_Projects/issues/206
