### ISSUE TITLE
beta10 截图有权限，但收朋友第一个后出现这个错误

### ISSUE THREAD

**Issue by keli1973** [SuperMonster003/Auto.js_Projects#216]
![微信图片_20191227103720](https://user-images.githubusercontent.com/40602529/71497831-e6c28500-2894-11ea-9a09-44a851e80e4f.jpg)

**Comment by abcdelf** [comment]
p20pro 安卓10  beta10 没有 截图权限

**Comment by sangbobo** [comment]
在项目文件夹下手动创建   Test  文件夹

**Comment by sangbobo** [comment]
https://github.com/SuperMonster003/Auto.js_Projects/issues/214#issuecomment-569174447
#214
