### ISSUE TITLE
beta10依然截图申请失败，总是进入昵称修改的页面

### ISSUE THREAD

**Issue by LeonWLeon** [SuperMonster003/Auto.js_Projects#218]
![1577419404(1)](https://user-images.githubusercontent.com/59272725/71500720-2becb400-28a1-11ea-83ab-4da9e29cc45f.png)
 华为MATE10 进入蚂蚁森林任务后总是跳到昵称修改的页面，然后显示截图权限申请失败

**Comment by abcdelf** [comment]
我也是。。。

**Comment by SuperMonster003** [comment]
https://github.com/SuperMonster003/Auto.js_Projects/issues/228
https://github.com/SuperMonster003/Auto.js_Projects/issues/206
