### ISSUE TITLE
点击 跳过 去配置 都没有反应

### ISSUE THREAD

**Issue by chenyusheng** [SuperMonster003/Auto.js_Projects#219]
在开始脚本的时，提示可以去配置个性化设置的dualog,然后我点了跳过或者去配置都没反应，一直卡着一动不动，机型小米9

**Comment by SuperMonster003** [comment]
`v1.9.10` 已尝试修复上述问题 如使用后问题复现 可继续反馈

**Comment by chenyusheng** [comment]
你好，我已经更新到最新版了这个问题还是一样存在

**Comment by chenyusheng** [comment]
这个是我现在用的版本
![image](https://user-images.githubusercontent.com/11496107/71974275-16d23680-324c-11ea-93dc-ec84504d1696.png)
这个是卡住我的页面，点击 跳过 现在配置 都没有反应，点击手机的返回键也关闭不了这个弹窗，只能直接kill掉Auto.js
![image](https://user-images.githubusercontent.com/11496107/71974283-1a65bd80-324c-11ea-9921-64edd28aedcb.png)
