### ISSUE TITLE
v1.9.10 Beta12 截图权限申请失败

### ISSUE THREAD

**Issue by FelixFeli** [SuperMonster003/Auto.js_Projects#220]
使用MIUI11 9.12.26 开发版，支付宝10.1.82版本。后台弹出界面权限确认已打开，多次尝试后，在某些个别情况下，miui系统会在屏幕下方弹出申请截图权限的框，但是一闪而过，无法及时确认并勾选不再提醒。请作者关注一下是否是这个特殊情况导致的bug，感谢大佬的辛勤工作。

**Comment by qcnhy** [comment]
同上小米6

**Comment by xanderlau** [comment]
MIUI11同截图失败，更新昨天晚上和第二天早上可以用（后台打错误日志但不严重），但是中午就不行了，卡在截图弹窗（日志报截图权限申请结果: 失败）

**Comment by toneydeng** [comment]
同样。beta12截图权限申请失败，跳不过去

**Comment by qcnhy** [comment]
bate13仍然失败

**Comment by SuperMonster003** [comment]
https://github.com/SuperMonster003/Auto.js_Projects/issues/206
