### ISSUE TITLE
自动解锁亮屏bug,安卓10无障碍经常出现故障

### ISSUE THREAD

**Issue by LiaJing** [SuperMonster003/Auto.js_Projects#221]
OPPOr17 和华为手机安卓10系统很多不能自动亮屏
好多安卓10系统无障碍自动关闭，或者无障碍已启用但是无法运行

**Comment by SuperMonster003** [comment]
无障碍服务自动关闭问题我无法通过代码解决
无法自动亮屏的问题可尝试使用 device.wakeUp() 方法自行测试设备是否支持该方式唤醒
如果不支持 则设备可能无法使用此项目
感谢反馈
