### ISSUE TITLE
v1.9.10 beta13 截图权限申请失败，跳到获取当前用户昵称页面之后反复重启

### ISSUE THREAD

**Issue by luchangharry** [SuperMonster003/Auto.js_Projects#223]
日志截图如下，试了所有新版本几乎都是截图权限申请失败，只有beta7还能用，但是每天早上会报打开auto.js失败
![3511577587410_ pic_hd](https://user-images.githubusercontent.com/50188136/71551696-10f87c00-2a28-11ea-83d8-86b31ad69a87.jpg)

**Comment by abcdelf** [comment]
一样的

**Comment by wth0538** [comment]
一样的

**Comment by abcdelf** [comment]
找到解决办法，就是回退支付宝的版本。最新的支付宝版本，跑beta3还是截图权限失败。停在昵称界面。

**Comment by SuperMonster003** [comment]
https://github.com/SuperMonster003/Auto.js_Projects/issues/228
https://github.com/SuperMonster003/Auto.js_Projects/issues/206
