### ISSUE TITLE
存在可收取能量但程序不收

### ISSUE THREAD

**Issue by wpc2333** [SuperMonster003/Auto.js_Projects#224]
我也存在他们说的自收取后返回会进入更名页面。尝试关闭自收取功能后，可以跳过这个错误，进入好友排行榜页面，但程序只能识别极个别好友进行收取（例如我有20个好友，10个可收取，程序只收取2个后就进入休眠，日志不存在错误信息，循环检测也会对其他可收取好友自动忽略，PS：白名单黑名单均为空）

**Comment by budenghao** [comment]
阀值调高点，调成20就好了

**Comment by wpc2333** [comment]
> 阀值调高点，调成20就好了
谢谢

**Comment by SuperMonster003** [comment]
`v1.9.10` 已尝试修复上述问题 如使用后问题复现 可继续反馈

**Comment by hot226** [comment]
> 阀值调高点，调成20就好了

请问阀值在哪里调，谢谢。

**Comment by budenghao** [comment]
> > 阀值调高点，调成20就好了
> 
> 请问阀值在哪里调，谢谢。

运行Settings文件-》收取功能-》收取图标颜色阀值  值改大一点，我的是30

**Comment by hot226** [comment]
> > > 阀值调高点，调成20就好了
> > 
> > 
> > 请问阀值在哪里调，谢谢。
> 
> 运行Settings文件-》收取功能-》收取图标颜色阀值 值改大一点，我的是30

谢谢
