### ISSUE TITLE
好友排行榜问题

### ISSUE THREAD

**Issue by Garry24** [SuperMonster003/Auto.js_Projects#225]
有个疑问，获取蚂蚁自带的周榜和总榜也有全部好友，为什么要单拉一个好友排行榜页面出来？这个好友排行榜拉取慢，还经常卡死

**Comment by Garry24** [comment]
经常报TypeError:Cannnot call method "childCount" of null(storage /elmuted/0/脚本/Ant_Forest_Launcher.js$4697)

**Comment by SuperMonster003** [comment]
单独拿一个排行榜出来
1. 便于排行榜页面定位
2. 便于统计倒计时
3. 便于在排行榜样本池差异检测模块定位并存储底部条件

用Auto.js的布局分局工具能看出
新排行榜页面明显控件数量少的多
但脚本的主要核心就在于控件分析
没有控件 脚本只能靠图像识别和单点/多点颜色匹配
如果用新的排行榜页面
倒计时统计和列表底部判断都是很大的问题

childCount 空指针的问题 v1.9.10 已经尝试修复了
如果问题复现 可继续反馈

感谢支持
