### ISSUE TITLE
1.9.9版本运行Ant_ Forest_ Settings. js就报错

### ISSUE THREAD

**Issue by sundi117** [SuperMonster003/Auto.js_Projects#226]
运行Ant_ Forest_ Settings. js文件就报错。
错误： Wrapped android. view. InflateException: org. xml. sax. SAXParseException: Unexpected end of document(__ ui__. js#32) at script(__ ui__. js:32) at script. setPage(:4576) at script. setHomePage(:4554) at script(:151)
安卓版本是8.1.0

**Comment by SuperMonster003** [comment]
1. 确保 Auto.js 版本为最新版 (免费版为 4.1.1 Alpha2)
2. 尝试重新将项目完整下载并解压到设备对应目录中 避免出现文件损坏或不完整的情况
