### ISSUE TITLE
关于好友排行榜的问题

### ISSUE THREAD

**Issue by Garry24** [SuperMonster003/Auto.js_Projects#227]
为什么好友排行榜要单独拉一个页面，而不是用支付宝本身的排行榜(周榜月榜)。每次滑动到第300多位好友时，就卡住不动，无法继续加载。支付宝自带的页面500个多好友都很流畅

**Comment by SuperMonster003** [comment]
https://github.com/SuperMonster003/Auto.js_Projects/issues/225
https://github.com/SuperMonster003/Auto.js_Projects/issues/185
