### ISSUE TITLE
beta14版本问题依然存在

### ISSUE THREAD

**Issue by LeonWLeon** [SuperMonster003/Auto.js_Projects#228]
不知道为什么，总要进入昵称界面，进入排行榜后也不动，更新自动定时任务以后，报a fruitless attempt，任务结束，为什么总要进支付宝-我的 界面作为过渡

**Comment by SuperMonster003** [comment]
昵称页面主要是为了点击好友能量球之后做统计用的
在动态列表里面 会有 xxx 收取了 yyy 克这样的文本
通过这个信息计算出收取量或者帮收量
而xxx就是用户当前的昵称
目前还没有更好的方案
避免跳转到昵称页面影响用户体验
未来可能会把昵称的获取作为一个辅助功能放到配置工具里面
而辅助功能又归属于"统计功能"里
统计功能 -> 能量统计方案 -> 动态列表 -> 昵称设置 -> [A. 手动填入] [B. 支付宝应用采集]
这个支付宝应用采集就是所说的辅助功能
另外还考虑了在用户收取能量之后
脚本尝试自动拿到当前用户昵称
采用类似可信度的方式等等
后续版本将尽量避免才能当前影响用户体验的方式采集昵称

**Comment by SuperMonster003** [comment]
v1.9.16 统计功能已上线
昵称跳转已转变为备选方案
首选方案从排行榜控件获取 失败后再使用备选方案
从而避免每次运行时的昵称页面跳转

上述问题如果依然存在
或对统计功能有其他建议
欢迎继续反馈
此Issue暂时关闭
