### ISSUE TITLE
EMUI9.1华为p30pro无法解锁

### ISSUE THREAD

**Issue by zhangguangjin** [SuperMonster003/Auto.js_Projects#23]
锁屏界面可以弹出键盘，可以正确输入密码，但无法开锁，我怀疑是不是因为输完密码不用按确认键的原因？我正常解锁是输完密码就开锁了的，不用按确认的。有一张图没截到我手动截了在包里。
[!Debug_Info.zip](https://github.com/SuperMonster003/Ant_Forest/files/3163112/Debug_Info.zip)

**Comment by zhangguangjin** [comment]
刚刚又试了几次，在密码解锁界面自己多输一个数字然后删掉可以解锁，或直接删掉最后一个数字再输入也能解锁，得出结论在没有回车键的键盘输入密码可以多输一个然后用删除键达到回车键的效果！但代码是真不会，求解

**Comment by SuperMonster003** [comment]
收到反馈 今晚之前尝试修复此问题  
问题原因在于 EditText控件在setText()方法输入文本后 有些设备是通过input_change方式监测是否输入的 这个时候就会立即响应输入 但如果是通过检测虚拟按键响应事件 没有触发键盘按键事件的话 是不会检测输入的 所以这个设备的密码检测必须通过按键响应事件才行  
我下午研究一下

**Comment by zhangguangjin** [comment]
感谢研究，辛苦了！

**Comment by zhangguangjin** [comment]
刚上来看到你更新了代码，下来试了下，还是不解不了锁。。。
![Screenshot_20190510_164321_org autojs autojs](https://user-images.githubusercontent.com/5145208/57514532-4d655380-7343-11e9-918e-c0fb5cae91b8.jpg)

**Comment by SuperMonster003** [comment]
已于 `v1.6.16` - `2019/05/10` 尝试修复此问题

**Comment by zhangguangjin** [comment]
刚刚下载试了下，解锁时仔细观察了下，程序有删除了一位数，所以没解开，后来我设置密码时多加了一个数字，再试就可以了。这样是解决了问题，就怕后来同机型的人可能不知道会解不开锁。在此备注下！
感谢大佬的热心！

**Comment by SuperMonster003** [comment]
`v1.6.17` - `2019/05/10` 在密码之后自动加了一位数字 然后点击删除键 所以可以尝试在设置密码的时候不用多加一位

**Comment by zhangguangjin** [comment]
刚刚试了，已经完美！辛苦了，继续支持你！
