### ISSUE TITLE
Settings文件闪退问题依然存在

### ISSUE THREAD

**Issue by Qingtian-creat** [SuperMonster003/Auto.js_Projects#230]
#212提到的问题正式版1.9.10依然存在，而且每次进入自己主页收取能量时会点击一次金色能量球

**Comment by SuperMonster003** [comment]
#181 的问题将在后续修复
另外金色能量球也会在后续进行适配和优化
感谢反馈

**Comment by Qingtian-creat** [comment]
@SuperMonster003 1.9.11版本settings文件闪退已修复，我今天测试正常
但是现在收取能量时黑名单中误触的现象十分频繁，现在的排行榜采集方法好像是图像分析？之前版本的布局分析方法精度相对来说好点

**Comment by SuperMonster003** [comment]
现在的逻辑是进入好友森林 匹配到标题后立即返回
你说的误触是上述现象吗
还是在黑名单好友森林点击了能量球

**Comment by Qingtian-creat** [comment]
@SuperMonster003 
是在黑名单好友的森林点击了能量球

**Comment by SuperMonster003** [comment]
日志中能正确显示黑名单好友的昵称吗
类似这样的
`[ Nickname ]`

**Comment by Qingtian-creat** [comment]
日志可以正常显示黑名单好友的昵称 @SuperMonster003
