### ISSUE TITLE
QQ前台会导致打开支付宝失败

### ISSUE THREAD

**Issue by mackerel-12138** [SuperMonster003/Auto.js_Projects#237]
如果自动解锁后是QQ聊天的界面， 支付宝打开会失败
![Screenshot_20200103_211821_org autojs autojs](https://user-images.githubusercontent.com/41133329/71763619-d8b9d780-2f18-11ea-98b9-53fb1a3032b6.jpg)

**Comment by lizhihengtt** [comment]
MIUI11可以利用锁屏负一屏触发解锁界面
    gesture(40, [200, 1900], [500, 1900], [800, 1900])
    sleep(2000)
    setScreenMetrics(1080, 1920);
    click(100, 600);
    sleep(500)
MIUI11稳定
手机型号：小米 cc9 Pro可用
我觉得所有MIUi都可以使用这条划开图层触发密码界面

**Comment by SuperMonster003** [comment]
@mackerel-12138 运行Ant_Forest_Settings.js -> 运行与安全 -> 启动跳板 -> [开启]
@lizhihengtt 感谢提供方案 (虽然此方案与此 issue 没有关联)
此方案不被接受 因为任何涉及到精确点坐标的模拟操作均不具备通用性 (特殊机型除外)
