### ISSUE TITLE
能否实现循环采集？

### ISSUE THREAD

**Issue by AndresFeng** [SuperMonster003/Auto.js_Projects#24]
大佬的脚本是用过里最好用的，我有用过一个类似的，可以循环采集，第一次进入森立后，获取到下次采集最小时间，然后再次打开森林采集，但是效率功能等没有大佬的好，希望大佬后期做个

**Comment by AndresFeng** [comment]
https://github.com/Nick-Hopps/Ant-Forest-autoscript
看能否借鉴下

**Comment by SuperMonster003** [comment]
感谢支持  
😄 

当前项目启动还不到两个月 很多问题和功能缺陷正在解决 
另外还有几个诸如 `账户功能` `定时任务功能` `运行提示` 等大块功能没有开发   
账户功能时独立的 而运行提示 循环收取等都是要依赖于定时任务功能的  
当前Pro版本还没有开放TimedTask模块的API 所以一直没有动力做定时任务功能  
等把该解决的bug解决差不多 (尤其是好友数量很多时滑动卡顿问题) 账户功能也做好 即使Pro版本还没开放API 也不等了 直接做普通版的定时任务功能  

另外Nick的项目我研究过 我这里也有不少灵感和思路是解决于他的 (偷偷感谢一下 😁)  
项目中的循环收取功能利用的是延时函数sleep()  
这就有一些缺陷和不便  
首先我认为一个任务一直停留在任务列表中 让人感觉不安  
一个音量加键 一个Auto.js崩溃/重启/强关 一个设备关机/重启  
都会让这个任务丢失  
而且如果在sleep()的过程中 我想再单独运行一次项目 就会出现冲突  
而未来实现的定时任务功能是基于Auto.js定时任务的  
任务会记录到系统内并以广播的形式激活任务运行  
这样不仅保证低耗电量 还能保证任务不会丢失  管理起来也更加方便快捷  

再次感谢支持

**Comment by AndresFeng** [comment]
大佬辛苦了，持续关注你哦

**Comment by guohuatai** [comment]
新版能加上定时循环多少次吗？  每次设置定时都只能执行一次。不能指定解锁后循环多少次，感谢大佬

**Comment by SuperMonster003** [comment]
@guohuatai  
定时任务功能暂时还未开发 另外auto.js里可以设置每日或每周定时执行
