### ISSUE TITLE
4.1.1 Alpha2 Auto.js软件问题

### ISSUE THREAD

**Issue by wyfang** [SuperMonster003/Auto.js_Projects#241]
在小米9上运行，似乎是autojs的问题，会出现无障碍出错，只能重启手机解决。不知道有没其他版本autojs可以正常使用？

**Comment by baocq2019** [comment]
同问

**Comment by eqshen** [comment]
我也是，遇到了同样的问题，mix2s，经常出现无障碍开启了还报错，让我开启无障碍。只有重启才能解决

**Comment by Sq-List** [comment]
在小米9上  给Auto.js 打开自启动。  就好了。  之前我也是这样。
