### ISSUE TITLE
MIUI11 滑开图层方式有可以改进的地方

### ISSUE THREAD

**Issue by lizhihengtt** [SuperMonster003/Auto.js_Projects#244]
MIUI11可以利用锁屏负一屏触发解锁界面
手势（40，[ 200，1900 ]，[ 500，1900 ]，[ 800，1900 ]）
sleep（2000）
setScreenMetrics（1080，1920）;
点击（100，600）;
sleep（500）
命令利用锁屏界面负一屏极简模式下米家功能触发密码界面完成上滑操作
适配2k屏
MIUI11稳定
手机型号：小米cc9 Pro可用
所有小米手机应该都可以使用这条划开触发触发密码界面

**Comment by SuperMonster003** [comment]
https://github.com/SuperMonster003/Auto.js_Projects/issues/237#issuecomment-576263273
