### ISSUE TITLE
无障碍服务启用但没有运行问题

### ISSUE THREAD

**Issue by LeonWLeon** [SuperMonster003/Auto.js_Projects#245]
我的是华为mate10 安卓10版本，1.9.11版本，在运行过程中很容易发生无障碍服务启用但没有运行的报错，特别是早上集中收取的时间段，长时间运行就会发生，必须重启机器才能解决，支付宝最近的两个版本都会发生这样的问题，请大神判断一下是设置的问题还是版本兼容性的问题

**Comment by xzhlksh** [comment]
不一定得重启，彻底退出autojs，然后关掉无障碍服务再重新打开就能用了
感觉像是脚本问题，我用其他简易脚本就没这个问题

**Comment by SuperMonster003** [comment]
https://github.com/SuperMonster003/Auto.js_Projects/issues/241
