### ISSUE TITLE
华为p30好友排榜初始化失败

### ISSUE THREAD

**Issue by Carry00** [SuperMonster003/Auto.js_Projects#249]
手机型号:华为p30 
支付宝版本:10.1.85
步骤重现:能调起支付宝蚂蚁森林，能进去排行榜，能收取自己的能量。
但是初始化排行榜失败。
- 
 
17:39:15.342/E: "好友排行榜"初始状态准备失败

**Comment by SuperMonster003** [comment]
1. 确保项目版本为最新 (v1.9.11)
2. 使用配置工具开启消息提示的开发者测试模式
3. 提供详细的日志截图

**Comment by Carry00** [comment]
你好，谢谢您的提醒，是因为版本的原因，升级到最新版本之后，问题解决了
