### ISSUE TITLE
蚂蚁森林无限进入退出

### ISSUE THREAD

**Issue by fflzh** [SuperMonster003/Auto.js_Projects#25]
支付宝版本：10.1.62
Auto版本：4.1.1 Alpha2
脚本版本：1.6.19
启动脚本后，重复进入蚂蚁森林，过一会又退出重新进入，脚本昨天还好用，今天突然就不行了。
![TIM图片20190514160111](https://user-images.githubusercontent.com/50615048/57681418-3c2d8700-7662-11e9-8481-a6aa72d656b0.jpg)

**Comment by SuperMonster003** [comment]
感谢反馈 请尝试新版

**Comment by xseven007** [comment]
![photo_2019-05-14_21-11-28](https://user-images.githubusercontent.com/1797318/57700726-1ff30f80-768d-11e9-8577-5e6fde319298.jpg)
新版本出现这样的问题。支付宝1.59.231

**Comment by SuperMonster003** [comment]
刚刚已修复 感谢反馈

**Comment by fflzh** [comment]
![微信图片_20190515083952](https://user-images.githubusercontent.com/50615048/57740978-0da8be00-76ed-11e9-89df-a24f116f5783.jpg)
大佬，用最新版本v1.6.21脚本，能够成功进入好友列表，但是收了一两个能量之后，列表还没拉到底就退出了

**Comment by SuperMonster003** [comment]
感谢反馈 请尝试 `v1.6.22 Alpha5` 版本

**Comment by xseven007** [comment]
![photo_2019-05-16_14-20-04](https://user-images.githubusercontent.com/1797318/57830784-c94d1900-77e5-11e9-95ea-ea7de5318509.jpg)
最新1.6.23 Alpha2

**Comment by fflzh** [comment]
![微信图片_20190520154121](https://user-images.githubusercontent.com/50615048/58004428-c7e95c80-7b15-11e9-87c9-07619de10ff2.jpg)

在有能量罩时，会在该界面停留一分钟，然后退出继续收能量。有没有什么方法能快速退出

**Comment by SuperMonster003** [comment]
@fflzh 收到反馈 此问题源于黑名单检测线程异常中断 导致无法及时发送结束信号  
我会在22号统一尝试修复目前所有反馈的问题 感谢支持

**Comment by SuperMonster003** [comment]
能量罩采集异常目前已修复 此Issue暂时关闭
