### ISSUE TITLE
oppo reno无法自动亮屏和解锁

### ISSUE THREAD

**Issue by heilvr** [SuperMonster003/Auto.js_Projects#251]
在没有解锁密码的情况下 定时任务也同样不会亮屏解锁
有数字密码的情况下也不行
安卓10
![微信图片_20200127012246](https://user-images.githubusercontent.com/36231639/73138888-b42dc700-40a2-11ea-882e-b4306ff8feb9.jpg)
![微信图片_20200127012258](https://user-images.githubusercontent.com/36231639/73138917-da536700-40a2-11ea-9395-118727f15198.jpg)
![微信图片_20200127012303](https://user-images.githubusercontent.com/36231639/73138931-01aa3400-40a3-11ea-8982-12ba7262cb87.jpg)

**Comment by SuperMonster003** [comment]
v1.9.12 进行了解锁模块的深度代码重构
因此最好能在开启开发者测试模式的条件下提供解锁日志
以便确定问题

**Comment by heilvr** [comment]
> v1.9.12 进行了解锁模块的深度代码重构
> 因此最好能在开启开发者测试模式的条件下提供解锁日志
> 以便确定问题

![微信图片_20200129015540](https://user-images.githubusercontent.com/36231639/73290434-66979280-4239-11ea-8f74-be856913c608.jpg)
![微信图片_20200129015740](https://user-images.githubusercontent.com/36231639/73290513-84fd8e00-4239-11ea-963f-632c51866f27.jpg)
![微信图片_20200129015750](https://user-images.githubusercontent.com/36231639/73290542-92b31380-4239-11ea-9be1-d1ac60d80f35.jpg)
![微信图片_20200129015816](https://user-images.githubusercontent.com/36231639/73290599-b1b1a580-4239-11ea-876f-f7466822b53a.jpg)

**Comment by heilvr** [comment]
开启定时任务后 不会自动亮屏
开启系统锁屏抬起亮屏后 一直输入数字8
手动解锁后其他正常 密码6位

**Comment by heilvr** [comment]
> v1.9.12 进行了解锁模块的深度代码重构
> 因此最好能在开启开发者测试模式的条件下提供解锁日志
> 以便确定问题

大佬我这个是个什么情况

**Comment by SuperMonster003** [comment]
一直输入数字8是因为脚本没有检测到可匹配的解锁页面的控件
从而一直尝试滑开遮罩层 而数字8正好处于滑动起点位置
需要提供解锁页面 (非遮罩层页面) 的控件信息
将控件的特征值 (通常是id值) 加入项目中 从而识别到解锁页面并尝试解锁
具体参阅 #135

**Comment by heilvr** [comment]
输入密码前的遮罩层页面
![微信图片_20200129015540](https://user-images.githubusercontent.com/36231639/73464136-64f4d880-43b9-11ea-9a3a-d7b510335cb0.jpg)


> 一直输入数字8是因为脚本没有检测到可匹配的解锁页面的控件
> 从而一直尝试滑开遮罩层 而数字8正好处于滑动起点位置
> 需要提供解锁页面 (非遮罩层页面) 的控件信息
> 将控件的特征值 (通常是id值) 加入项目中 从而识别到解锁页面并尝试解锁
> 具体参阅 #135

**Comment by heilvr** [comment]
需要输入密码的锁屏页面
![微信图片_20200130234528](https://user-images.githubusercontent.com/36231639/73464245-8fdf2c80-43b9-11ea-91cf-f87e166c6256.jpg)

**Comment by heilvr** [comment]
大佬 定时任务而且不会自动点亮屏幕，只有手动点亮才会输入数字8

**Comment by SuperMonster003** [comment]
[MODULE_UNLOCK.zip](https://github.com/SuperMonster003/Auto.js_Projects/files/4140325/MODULE_UNLOCK.zip)
可尝试将压缩文档中包含的解锁模块替换原有模块 测试解锁功能 然后再次提供反馈
感谢支持

**Comment by heilvr** [comment]
> [MODULE_UNLOCK.zip](https://github.com/SuperMonster003/Auto.js_Projects/files/4140325/MODULE_UNLOCK.zip)
> 可尝试将压缩文档中包含的解锁模块替换原有模块 测试解锁功能 然后再次提供反馈
> 感谢支持

可以了 但是不会自动亮屏 密码输入正确

**Comment by heilvr** [comment]
> [MODULE_UNLOCK.zip](https://github.com/SuperMonster003/Auto.js_Projects/files/4140325/MODULE_UNLOCK.zip)
> 可尝试将压缩文档中包含的解锁模块替换原有模块 测试解锁功能 然后再次提供反馈
> 感谢支持

意思就是 添加定时任务后锁屏后 到指定时间手机不会自动亮屏，必须手动亮屏后，会自动输入密码解锁

**Comment by SuperMonster003** [comment]
自行排查是定时任务无法唤醒还是亮屏功能无效
前者看日志中的项目运行时间戳与预定时间的差值是否大于预期 (通常不应大于3分钟)
后者测试device.wakeUp()或device.wakeUpIfNeeded();

**Comment by heilvr** [comment]
> 自行排查是定时任务无法唤醒还是亮屏功能无效
> 前者看日志中的项目运行时间戳与预定时间的差值是否大于预期 (通常不应大于3分钟)
> 后者测试device.wakeUp()或device.wakeUpIfNeeded();

找到问题在哪了

**Comment by SuperMonster003** [comment]
欢迎提供问题解决方案

**Comment by fauthor** [comment]
> > 自行排查是定时任务无法唤醒还是亮屏功能无效
> > 前者看日志中的项目运行时间戳与预定时间的差值是否大于预期 (通常不应大于3分钟)
> > 后者测试device.wakeUp()或device.wakeUpIfNeeded();
> 
> 找到问题在哪了

楼主你是怎么解决无法亮屏的问题的？我也遇到了
