### ISSUE TITLE
v1.9.12 无法解锁

### ISSUE THREAD

**Issue by VergLsm** [SuperMonster003/Auto.js_Projects#252]
之前版本正常。
v1.9.12版本在关闭屏幕时，不能解锁，密码四个数，只输入了两个。

**Comment by SuperMonster003** [comment]
https://github.com/SuperMonster003/Auto.js_Projects/issues/251#issuecomment-579202639

**Comment by VergLsm** [comment]
![S00129-01100433](https://user-images.githubusercontent.com/13448810/73287448-3ef1fb80-4234-11ea-8266-cfb1aca10ace.jpg)
这是更新了v1.9.13再尝试的，同样问题，无法解锁。

**Comment by SuperMonster003** [comment]
[MODULE_UNLOCK.zip](https://github.com/SuperMonster003/Auto.js_Projects/files/4123726/MODULE_UNLOCK.zip)

**Comment by VergLsm** [comment]
@SuperMonster003 大哥你发错地方了吧

**Comment by SuperMonster003** [comment]
是给你测试用的用于替换的解锁模块文件

**Comment by VergLsm** [comment]
这是v1.9.13替换了MODULE_UNLOCK之后失败的日志
![S00203-13403073](https://user-images.githubusercontent.com/13448810/73628568-87be1000-468b-11ea-8866-cb2c46ffac55.jpg)


这是v1.9.14，没有换任何文件，解锁失败的日志
![S00203-01352530](https://user-images.githubusercontent.com/13448810/73628624-b50abe00-468b-11ea-9c36-c300d5b834b4.jpg)

**Comment by SuperMonster003** [comment]
尝试将解锁模块 `MODULE_UNLOCK.js` 的 `2844` 行

由
```js
let _node = _aim.findOnce();
```
修改为
```js
let _node = idMatches(_aim).findOnce();
```

**Comment by VergLsm** [comment]
v1.9.14 测试成功
