### ISSUE TITLE
大神，miui11屏幕点亮后无法解锁，用的红米K20PRO

### ISSUE THREAD

**Issue by yxhdr** [SuperMonster003/Auto.js_Projects#254]
![Screenshot_2020-02-08-20-14-06-804_org autojs autojs](https://user-images.githubusercontent.com/39489948/74085048-314c3980-4ab0-11ea-8733-a0bdef2f7bf9.jpg)

**Comment by ciyoooo** [comment]
我也一样

**Comment by SuperMonster003** [comment]
参阅 https://github.com/SuperMonster003/Auto.js_Projects/issues/105

**Comment by zhangguangjin** [comment]
我的红米30pro是可以上划，可以输密码，但不按确认键，我自己按下确认键就解锁了，求解

**Comment by zhangguangjin** [comment]
> 我的红米30pro是可以上划，可以输密码，但不按确认键，我自己按下确认键就解锁了，求解

自己解决了，麻烦开发者把解锁模块的3073行 
let _rex = /OK|确定|好.?/;
加上个确认              >>>>
let _rex = /OK|确定|确认|好.?/;

以便同机型的可以正常使用！不走弯路了，谢谢啦！
