### ISSUE TITLE
华为mate9无法亮屏解锁

### ISSUE THREAD

**Issue by kennyhou001** [SuperMonster003/Auto.js_Projects#255]
制定好定时任务后，华为mate9无法亮屏解锁，手动点亮屏幕后，能自动输入密码解锁。
尝试过无密码，数字密码，手势密码，均不能自动亮屏。唯有手动亮屏后，才能自动输入密码开始执行任务。
我这个问题跟https://github.com/SuperMonster003/Auto.js_Projects/issues/23 这哥们的还不一样，没有共同性。
有点不太好定位故障问题所在。

机型 Mate9
Android版本 9
EMUI 9.1.0

开发者解锁日志如何如何获取？

**Comment by SuperMonster003** [comment]
https://github.com/SuperMonster003/Auto.js_Projects/issues/134#issuecomment-554606656
https://github.com/SuperMonster003/Auto.js_Projects/issues/89#issuecomment-526391345

**Comment by kennyhou001** [comment]
https://github.com/SuperMonster003/Auto.js_Projects/issues/134#issuecomment-554997009

根据此回复中的提示，关闭了自动管理权限，手动启用“开机启动”和“后台运行”之后，再次测试成功。
设置定时任务后熄屏，到达设定时间后可以亮屏并解锁启动任务了！
我觉得这个issue基本上是个通病，是否可以添加在README.md里面，以免后人再走弯路 ^_^

非常感谢~~这个issue可以close了~~~
