### ISSUE TITLE
autojs 使用require语法，打包会出现 找不到模块的问题,未打包前是可以运行的

### ISSUE THREAD

**Issue by MeDeity** [SuperMonster003/Auto.js_Projects#256]
大神你好,仿照您的写法,想对项目进行打包发现
autojs 使用require语法，打包会出现 找不到模块的问题，未打包前是可以运行的（直接按三角箭头是可以运行的）。不知道这种问题您是怎么处理的呢

**Comment by SuperMonster003** [comment]
可参阅Auto.js的官方文档有关项目打包的内容

> #### 如何把图片和脚本一起打包，或者打包多个脚本
> 
> 如果除了单脚本以外还有其他脚本、图片、音乐等资源一起打包，则需要使用项目功能。
> 
> 点击Auto.js的"+"号，选择项目，填写项目名称、包名等信息以后，点击"√"即可新建一个项目。可以在项目中放多个脚本、模块、资源文件，点击项目工具栏的apk打包图标即可打包一个项目，点击工具栏可以重新配置项目。
> 
> 例如，主脚本要读取同一文件夹下的图片1.png，再执行找图，则可以通过images.read("./1.png")来读取，其中"./1.png"表示同一目录1.png图片；ui中的图片控件要引用同一文件夹的2.png图片则为<img src="file://2.png"/>。Auto.js内置的函数和模块都支持相对路径，但是，其他情况则需要使用files.path()函数来把相对路径转换为绝对路径。

若尝试后依然出现问题 可反馈详细的问题描述和操作方法

**Comment by MeDeity** [comment]
谢谢提供思路,我现在正在尝试使用webpack打成一个js文件.
