### ISSUE TITLE
Huawei P20 太久没运行 之后会出现无法启动辅助功能

### ISSUE THREAD

**Issue by Reid00** [SuperMonster003/Auto.js_Projects#257]
Huawei P20 太久没运行 之后会出现无法启动辅助功能， **虽然辅助功能已经开启，悬浮窗已经开启**，但是还是没把法启动项目。
日志提示重新安装auto.js ，并重启手机。
目前好像每天早晨都会这样，不太清楚什么原因？
大神可有什么建议？

**Comment by DDScam** [comment]
我的手机同样是华为P20，之前有相同症状。我是这样解决的：
1、手机升级到最新系统。
2、自启动权限和保持后台运行权限打开。
3、授权无障碍。
进行了上述操作后，除每次手动重启手机需重新授权无障碍以外，未有其它问题。

**Comment by Reid00** [comment]
感谢，自启动权限和保持后台运行权限打开。这个在哪边设置？是下面这两个地方嘛
![image](https://user-images.githubusercontent.com/38450639/75084944-09081480-555f-11ea-911a-da504b734fa2.png)
![image](https://user-images.githubusercontent.com/38450639/75084955-11604f80-555f-11ea-980d-729f50d3e975.png)

**Comment by DDScam** [comment]
是的，在第一个图里

**Comment by Reid00** [comment]
那我这边权限应该是一直开着的，奇怪。
我每次定时早晨的都没办法运行。系统也是最新的，还有可能是啥原因吗？

**Comment by fantasic-sky** [comment]
把Auto.js进程加把锁试试？Auto.js被意外关闭时无障碍会被系统关闭。

**Comment by SuperMonster003** [comment]
目前项目应用了大量的截图操作 用于对比分析以及内容分析
因此可能会导致多数设备无法实现长时间稳定运行
可能2-3天甚至几小时就会出现 Auto.js 崩溃的现象
除了设备安全限制 节点限制 后台限制之类的因素外
只能通过优化代码来解决此类问题
当前暂未想到更好的代码优化方案 
因此暂时标记为"无法解决"
