### ISSUE TITLE
导入的脚本文件总是变成0字节。

### ISSUE THREAD

**Issue by meetinnet** [SuperMonster003/Auto.js_Projects#258]
。

头一回用不太明白这个Auto.js.

按照说明把文件都放在./脚本下面之后，可以直接运行js文件，能自动调用Auto.js，但是进不到Auto,js的项目列表里面。在Auto.js里面用导入文件的方式，选中js文件导入之后，文件是空的，0字节,然后再去脚本文件夹下面看，之前正常的脚本文件也变成0字节了。不是这么导入的嘛？

**Comment by SuperMonster003** [comment]
在内部存储目录建立脚本文件夹
将项目全部文件 保留原有目录结构 放置于脚本目录下
在Auto.js软件中刷新目录后 运行启动器脚本

**Comment by meetinnet** [comment]
谢谢啊，原来这样，不是导入的啊，我之前有过一次是导入成功的，不过就那一次，后续导入的都是0字节。
