### ISSUE TITLE
请教：定时任务是如何写入Auto.js计划任务里的

### ISSUE THREAD

**Issue by meetinnet** [SuperMonster003/Auto.js_Projects#260]
js小白，自己费劲改了一个简单的点击脚本，打算每6小时运行一次。Autojs自带的定时任务没有按几小时运行这种，只能设置每天几点运行，间隔太久了，于是又想可否用那个循环次数代替，设置循环次数为0即无限循环，间隔设置为21600.0秒，即6小时，延迟运行30秒。 按预想的应该是30秒后每6小时运行一次，可是根本不运行啊。还是秒数设置21600超范围了，设置几次还是运行的。
我看您的脚本是定时运行的，还只是运行一次，这是怎么写入的，每次运行之后再写入一遍嘛，能否简单一说，代码看不太懂。谢谢。

**Comment by meetinnet** [comment]
今天又观察了一下，发现设置短时间如600秒也会执行，主要是这段唤醒的代码时好时不好，一会好用一会不好用，开始的时候是好用，后面就不好用，不知道为啥，可是代码很简单啊，好用应该每次都好用吧，搞不懂，代码如下：

if (!device.isScreenOn()) {
device.wakeUp();
sleep(1000); 
swipe(366,866,506,596);
sleep(1000);
desc(6).findOne().click();
desc(6).findOne().click();
desc(6).findOne().click();
desc(6).findOne().click();

**Comment by SuperMonster003** [comment]
参阅 https://github.com/SuperMonster003/Auto.js_Projects/issues/263
如果想使用定时任务功能 可参考使用项目中的TIMERS扩展模块 (EXT_TIMERS.js)
