### ISSUE TITLE
Bug反馈: 打开日志时崩溃，并自动关闭无障碍服务

### ISSUE THREAD

**Issue by meetinnet** [SuperMonster003/Auto.js_Projects#261]
不知道怎么出来的，过程大概是这样，开始总报一个Wrapped CvExpetion错误，在什么Matrx.cpp里，打开Ant_Forest_Launcher.js，再打开日志大概看了一下，当然也看不懂，重启Autojs之后，报无障碍服务没开启(之前是开启的)，于是又开启无障碍服务，再进去打开日志的时候就报崩溃错误了，错误信息在下面，然后我又试了几次，每次打开日志必然崩溃，每次崩溃无障碍服务必被关闭，屡试不爽，原因未知，EMUI 9.1.

错误信息：

Version: 461
Android: 28
android.os.TransactionTooLargeException: data parcel size 1374288 bytes
java.lang.RuntimeException:android.os.TransactionTooLargeException: data parcel size 1374288 bytes
android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:160)
......
Caused by:
android.os.TransactionTooLargeException:data parcel size 1374288 bytes
android.os.BinderProxy.transactNative(Native Method)
android.os.BinderProxy.transact(Binder.java:1149)
android.app.IActivityManager$Stub$Proxy.activityStopped(IActivityManager.java:4005)
android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:144)
android.os.Handler.handleCallback(Handler.java:907)
android.os.Handler.dispatchMessage(Handler.java:105)
android.os.Looper.loop(Looper.java:216)
android.app.ActivityThread.main(ActivityThread.java:7625)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

**Comment by SuperMonster003** [comment]
https://github.com/SuperMonster003/Auto.js_Projects/issues/257#issuecomment-591798783
https://github.com/SuperMonster003/Auto.js_Projects/issues/85
