### ISSUE TITLE
Auto.js自带的循环运行不能被执行的原因

### ISSUE THREAD

**Issue by meetinnet** [SuperMonster003/Auto.js_Projects#263]
_偶然在贴吧找到了作者SuperMonster在回复别人时候的解释：
---------------------------------------------------------
自带的循环就是execScript()方法的图形化操作 设置好循环时间后 会在任务列表中设置一个循环任务 但这个任务是常驻任务列表的 有以下缺陷
 
1. 如果auto.js设置中开启音量键停止脚本 按音量键的时候会把此任务清除掉 
2. 重启设备 重启auto.js进程 auto.js意外退出等等 都会导致任务被清除 
3. 不够智能 可以使用auto.js自带的定时任务功能 避免以上问题 

项目不能循环运行有两方面原因 循环运行的脚本中不能有exit() 另外项目脚本中加入了任务排斥代码 带有排斥标记的任务会等待所有之前带有此标记的任务完成后才开始运行 而循环运行的任务会一直停留在任务列表 因此第二次循环任务会一直循环等待
---------------------------------------------------------

这个格式很奇怪，复制的，怎么出来的加黑加粗字体。

但是Auto.js自带的定时任务也是很不智能啊，没法定时每隔几小时执行那样。。

**Comment by SuperMonster003** [comment]
AJ自带的循环运行 不是用的定时任务 后续的任务一直在排队
当前运行的任务被停止时 后续的任务都会被清除掉 否则就要一直挂在"运行中脚本"队列里
如果想实现每隔几个小时执行 而且还想用定时任务的话 可以制定多个定时任务
类似 0点 6点 12点 18点 这样的
项目之所以没有提供这样的功能 主要是考虑到"智能" 期望做到在任务队列尽量干净整洁的前提下实现项目的智能化和自动化操作
