### ISSUE TITLE
功能建议: MIUI11无法解锁问题优化以及功能建议

### ISSUE THREAD

**Issue by withsalt** [SuperMonster003/Auto.js_Projects#265]
=====================================================
优化建议：
作者你好，我的手机是MI6X MIUI11。之前一直存在唤醒屏幕后无法解锁的问题，在进行测试之后发现，将匹配屏幕解锁控件次数调大之后可以有效解决MIUI11唤醒后无法解锁的问题。个人猜测可能是MIUI动画的原因，检测时间又太短，导致无法识别控件。
```javascript
function _lmtRch() {
    if ($_und(_unlock._ctr)) {
        _unlock._ctr = 0;
    }
    if ($_und(_unlock._max)) {
        _unlock._max = 20;
    }

    let _max = _unlock._max;
    let _ctr = _unlock._ctr++;
    if (_ctr > _max) {
        return _err("解锁尝试次数已达上限");
    }
    if (_ctr) {
        let _s = " (" + _ctr + "/" + _max + ")";
        debugInfo("重试解锁" + _s);
    }
}
```
将上锁代码中_unlock._max次数修改为20后目前没有遇到过无法解锁的情况。
日志：
![3RmztO.jpg](https://s2.ax1x.com/2020/03/02/3RmztO.jpg)

=====================================================
功能建议：
希望作者可以添加一个只在指定时段运行的设置。比如只在每天早上7-9点收取能量，其它时间脚本不会运行。因为在日常使用当中，森林能量产生最多的时间就在这个时段，其它时候在使用手机时，时不时会跳出来自动运行，需要手动去关闭，很麻烦。
感谢，作者辛苦了。

**Comment by wyfang** [comment]
我也是，小米9默认主题就无法解锁。但是使用一些其他主题就可以。

我也强烈建议添加固定时间。

**Comment by toneydeng** [comment]
米8试了一楼的方法，确实完美解锁运行，高手在民间啊！

**Comment by liujiayi771** [comment]
我的小米10按这个方法还是不行

**Comment by wyfang** [comment]
> 我的小米10按这个方法还是不行

小米9也不行

**Comment by SuperMonster003** [comment]
上一版重构解锁模块的时候
把200ms左右的小缓冲遗漏了
将在下一版v1.9.16修复此问题

非常感谢提供建议与解决方案
😃

**Comment by SuperMonster003** [comment]
@withsalt 
今晚将发布v1.9.16解决上述解锁问题并增加上述时段配置功能
另外如果可以的话 欢迎联系我加入内测群 😃

**Comment by withsalt** [comment]
已经测试，小米6X MIUI11 不能解锁问题已经修复。
