### ISSUE TITLE
Bug反馈: 运行 Ant_Forest_Launcher.js后，提示：“auto.js：打开auto.js失败”

### ISSUE THREAD

**Issue by hrbagang** [SuperMonster003/Auto.js_Projects#267]
**问题描述**
如题。
详细操作及信息提示如下。
1，运行Ant_Forest_Launcher.js
2，之后，先是自动打开了支付宝的蚂蚁森林界面
3，然后显示autojs：开始运行蚂蚁森林任务。
4，过了大约一分钟。
5，出现错误提示。提示：“auto.js：打开auto.js失败”

**日志截图**
日志在哪里能看到，还请提示。

**软件硬件信息**
操作系统: MIUI11
设备型号: 小米9
Auto.js版本: 4.1.1 Alpha2

**其他**
无

**Comment by SuperMonster003** [comment]
参考 #47
