### ISSUE TITLE
Bug反馈: 个人主页有能量球的情况下卡在主页

### ISSUE THREAD

**Issue by frank142857** [SuperMonster003/Auto.js_Projects#268]
**问题描述**
个人主页有能量球的情况下，会卡在检测界面。数分钟后系统无响应，需重启解决。
如个人主页无能量球，可以在数秒后正常进入好友列表，好友列表能量检测收取均正常。

**日志截图**
![Screenshot_20200312-161019_Auto js](https://user-images.githubusercontent.com/35618259/76577460-b5645900-6482-11ea-97e5-f6e881ab4289.png)

**软件硬件信息**
操作系统: [如: 安卓10.0 (Lineage OS)]
设备型号: [如: HTC One M8]
Auto.js版本: [如: 4.1.1 Alpha2]

**Comment by frank142857** [comment]
* Auto.js已经设为系统应用并授予root权限。

**Comment by SuperMonster003** [comment]
初步判断是因为任务之间密集运行了吧
如果只运行一遍的话 是否会出现上述问题
另外是否使用了AJ自带的循环运行
