### ISSUE TITLE
进入好友的森林后无法摘取能量

### ISSUE THREAD

**Issue by VergLsm** [SuperMonster003/Auto.js_Projects#27]
![image](https://user-images.githubusercontent.com/13448810/57750775-27aac680-7716-11e9-81c3-c31348e15197.png)

**Comment by VergLsm** [comment]
v1.6.22 Alpha5 版本

**Comment by SuperMonster003** [comment]
已于 `v1.6.22 Alpha6` - `2019/05/15` 尝试修复此问题

**Comment by VergLsm** [comment]
已解决
