### ISSUE TITLE
功能建议: 希望增加给别人浇水的功能比如给合种树浇水的功能

### ISSUE THREAD

**Issue by ZhangQi1996** [SuperMonster003/Auto.js_Projects#270]
- 当前项目
当前项目已有的功能描述 [如: 当前项目在A拥有功能B 或 当前项目无此功能]
提供相关的当前项目功能截图或其他辅助信息 (如果有的话)
- 期望
期望的功能描述 [如: 期望在A拥有功能C 或 A修改为功能D 或A增强兼容性]
提供相关的期望功能截图或其他辅助信息 (如果有的话)

**Comment by ZhangQi1996** [comment]
比如每天可以定期浇固定能量的水

**Comment by SuperMonster003** [comment]
参阅 https://github.com/SuperMonster003/Auto.js_Projects/issues/283
