### ISSUE TITLE
Bug反馈: 荣耀20锁屏启动任务时报“支付宝打开失败”

### ISSUE THREAD

**Issue by d2gin** [SuperMonster003/Auto.js_Projects#271]
**问题描述**
脚本版本是最新的，也测试过其他旧版的脚本，都存在相同问题。
目前发现主要是锁屏触发任务后解锁执行的时候出现 打开“支付宝”失败 提示，亮屏时多数没问题，不过偶尔亮屏的时候也会出现这种问题。如果锁屏前保留的前置应用为支付宝的时候任务也正常执行，但仅限此次任务，后续锁屏任务也出现同样问题。

**日志截图**
日志截图
![Screenshot](https://user-images.githubusercontent.com/37645928/76716989-35354080-676d-11ea-90b6-55040f369ff6.jpg)

**软件硬件信息**
操作系统: 安卓10
设备型号: 荣耀20
Auto.js版本: 4.1.1 Alpha2

**Comment by SuperMonster003** [comment]
参阅 https://github.com/SuperMonster003/Auto.js_Projects/issues/237#issuecomment-576263273

**Comment by d2gin** [comment]
> 参阅 [#237 (comment)](https://github.com/SuperMonster003/Auto.js_Projects/issues/237#issuecomment-576263273)
