### ISSUE TITLE
Bug反馈: 小米10 pro MIUI11 默认锁屏无法自动解锁

### ISSUE THREAD

**Issue by liujiayi771** [SuperMonster003/Auto.js_Projects#272]
**问题描述**
小米10 pro MIUI11 默认锁屏无法自动解锁，解锁界面一直往上划的感觉，但是又解不开。我设置了密码，但是因为我有小米手环，可以蓝牙设备解锁，我就在自动解锁里把密码设置的是空，应该划上去就可以解锁的。锁屏换第三方主题就可以正常解锁了，但是第三方主题锁屏实在太丑了，不想用。

**解锁布局**
[Inspect_Lock_Screen_Layout.zip](https://github.com/SuperMonster003/Auto.js_Projects/files/4342651/Inspect_Lock_Screen_Layout.zip)

**软件硬件信息**
操作系统: 安卓10
设备型号: 小米10 pro
Auto.js版本: 4.1.1 Alpha2

**Comment by liujiayi771** [comment]
我把起点设置成60%，重点10%，可以划开了

**Comment by zhangguangjin** [comment]
我的是红米K30PRO，能上划输密码，可是不能点确认！自己点下确认能解锁，求解！！！

**Comment by nanshandawang** [comment]
我也是小米10 pro没法解锁屏幕，试了很多办法都不行，换了几个锁屏主题也解锁不了

**Comment by airchaoz** [comment]
把解锁位置设置为95%H试试，可能是小米手机解锁的触发位置比较下，脚本不能够成功解锁。

**Comment by SuperMonster003** [comment]
参阅 https://github.com/SuperMonster003/Auto.js_Projects/issues/265
下一版将修复此问题

**Comment by wyfang** [comment]
![Screenshot_2020-04-26-10-10-27-519_org autojs aut](https://user-images.githubusercontent.com/17900420/80295563-50509280-87a6-11ea-9a55-6f338fc3bb4b.jpg)
小米9 miui11开发版无法解锁成功

**Comment by SuperMonster003** [comment]
@wyfang 参阅 https://github.com/SuperMonster003/Auto.js_Projects/issues/284
自行调整滑动起止点位置参数 尽量将"计算滑动距离"调小 而不是调大 (即调高起点 调低终点)

**Comment by liujiayi771** [comment]
> ![Screenshot_2020-04-26-10-10-27-519_org autojs aut](https://user-images.githubusercontent.com/17900420/80295563-50509280-87a6-11ea-9a55-6f338fc3bb4b.jpg)
> 小米9 miui11开发版无法解锁成功

我小米10 pro在最新的版本这个问题已经修复了，也是miui11 开发版

**Comment by SuperMonster003** [comment]
@wyfang 如果依然有问题 请开新Issue反馈 此Issue暂时关闭
