### ISSUE TITLE
怎么设置通过收能量的广播事件启动？

### ISSUE THREAD

**Issue by weitemi** [SuperMonster003/Auto.js_Projects#273]
怎么设置通过收能量的广播事件启动？

**Comment by weitemi** [comment]
我不知道广播事件填多少

**Comment by SuperMonster003** [comment]
参阅 https://www.cnblogs.com/sanxc/archive/2012/03/14/2395344.html
例如 填写"android.intent.action.SCREEN_OFF" 则手机一关屏 就会运行制定的脚本

**Comment by weitemi** [comment]
事情是这样的，不知道是我设置的问题还是怎么回事，我定时了，自己的能量还被别人偷了。
所以我想加个监听通知启动脚本的任务进去，我看有的脚本是监听收到的通知文本为收取能量则启动。这是一个方法，收到什么具体文本可以自己自由设定。

**Comment by SuperMonster003** [comment]
监测支付宝通知需要将支付宝保留后台运行
部分用户可能只在使用支付宝时开启 其余时间均严格限制其后台运行
另通知文本可能改变 通知时间可能延迟 通知监听可能失效等等都会带来额外风险
此建议将不予采纳
感谢支持与反馈
