### ISSUE TITLE
Bug反馈: 运行无法跑通，直接报错

### ISSUE THREAD

**Issue by 747383070** [SuperMonster003/Auto.js_Projects#274]
**问题描述**
运行直接报错

**日志截图**
![bug](https://user-images.githubusercontent.com/34643340/77534649-01c48580-6ed4-11ea-9de8-67ceaf56ce81.jpg)

**软件硬件信息**
操作系统: 安卓9.0
设备型号: 华为nova3E
Auto.js版本: [如: 4.1.1 Alpha2]

**Comment by yuluu** [comment]
换个autojs，我一开始也这样
