### ISSUE TITLE
荣耀V20每天早上自动运行完成后，手机发热很严重

### ISSUE THREAD

**Issue by chenhd9** [SuperMonster003/Auto.js_Projects#275]

**Comment by SuperMonster003** [comment]
项目使用了大量的截图对比操作 相对来讲还是很耗费硬件的 尤其是长时间运行
可通过关闭某些自动定时策略 降低自动运行密度及单次运行时长缓解此类问题
目前暂时没有可通过代码实现的有效措施解决发热问题
感谢支持

**Comment by chenhd9** [comment]
好的  谢谢大佬耐心回复~
