### ISSUE TITLE
想问作者大大一些问题

### ISSUE THREAD

**Issue by zzliux** [SuperMonster003/Auto.js_Projects#276]
看了些源代码，代码量相当庞大，模块功能也相当完善，请问是不是在这个项目之前有开发过什么东西，这些模块就顺便用到了这里，还是说为了开发这个项目写的这些模块。如果是后者的话，作者写这些模块又花了多少时间呢，会不会因为写这些模块而使开发的周期拉得非常长呢，还有就是，如果我们其他人想使用这些模块的话，有没有这些模块的API文档呢。问题有点多哈哈

**Comment by SuperMonster003** [comment]
这是开发过的第一个项目 也是目前唯一一个项目 代码模块一开始想为蚂蚁庄园/签到/其他自动化功能脚本准备的 主要是方便代码复用 后来因种种原因全部放弃了
所有的模块都是有这个项目逐步创建和完善的 模块中的方法基本上都写了详细的JSDoc 有的方法标注了@example 即使用样例
开发目前有13个月了 自己的项目 就没考虑周期 想起来就维护一下 平时自己发现了问题 或者有人反馈 就修修补补 相对随意 也相对自由
模块的API基本上就是require了之后就直接用了 模块中最多的就是方法 偶尔会有构造函数 需要new一个实例出来用 有的模块甚至直接load()就好了 比如那些EXT开头的扩展模块

**Comment by Kannnnng** [comment]
同样的疑问，项目的可读性感觉不太高，对读者来说并不友好……感觉嵌套太多了，各种自定义的功能，看起来有些费劲……

**Comment by SuperMonster003** [comment]
@Kannnnng 
感谢你的建议 我会继续努力学习 逐步实现更好的项目结构和设计模式
😄

**Comment by zzliux** [comment]
@SuperMonster003 刚大概的看了下，有@example标注的方法好像并不多，我主要是觉得这个项目的配置界面的交互感太强了，以及是我用过的auto.js程序中ui做的最强的了，以前大概的看了下这个配置界面的渲染方式，感觉用法太多，里面的源码也看不太懂，所以那个时候就想要个api来用作者的轮子

**Comment by SuperMonster003** [comment]
@zzliux 
正式版加入了一些 Math 扩展方法的 `@example`  
因为不熟练 每次写 JSDoc 都是一个非常耗时的过程  
以后会尽量补充和完善更多方法的 JSDoc

配置工具的代码 冗余太多了 基本上写出来只是为了能用
期间重构了两次 基本上也没有太大的整合和复用
最近几个版本 也是在一点点重构 不然代码也会更简洁

轮子一般会在 Launcher.js 中找到具体的使用方法
拿来试试一般就能发现使用方法

Monster 模块中的方法 为了能单独拿出来使用
都在各自的方法中加入了 Raw 兼容方法
一般不会影响测试使用
常用的 `waitForAction` `messageAction` 等
都是相对容易掌握和使用的
