### ISSUE TITLE
其实我只想要解锁模块！

### ISSUE THREAD

**Issue by Cheney93** [SuperMonster003/Auto.js_Projects#28]
大佬能否单独建一个解锁的分支😳精简掉森林

**Comment by SuperMonster003** [comment]
可以的 明晚之前分离出单独可用的解锁模块

**Comment by Cheney93** [comment]
感谢大佬！！！

**Comment by VergLsm** [comment]
提个想法，可以把共用的模块抽出，然后我们可以使用这些模块做自己的程序，或者可以一起来实现一下其它功能

**Comment by SuperMonster003** [comment]
@VergLsm 我今天一整天都正在这么做呢  
![2019-05-17_170056](https://user-images.githubusercontent.com/30370009/57916492-7e0a3780-78c5-11e9-99ce-ade0eebf8b94.png)  
@Cheney93 答应你的解锁模块今晚可以做出来 但不会特别完善 而且以后还会再重新发布完善后的模块 如果急需 我可以今晚发布  否则还是建议等我分离完大多数模块之后再一起发布 主要看你需求

**Comment by Cheney93** [comment]
@SuperMonster003 不着急，我自己写了一个解锁的脚本！不过是寄生在森林里面😃

**Comment by VergLsm** [comment]
@SuperMonster003 请教个问题，vsc的代码如果直接按F5在设备上运行总是找不到其它模块文件，这个功能的正常使用姿势是怎样的？

**Comment by SuperMonster003** [comment]
@VergLsm 传送到VSC上的js文件运行时的cwd()是Auto.js的默认路径 这个路径可以在Auto.js设置里修改 默认是 /脚本/ 或 /Scripts/  但Pro版本目前还不行 改了也不起作用

**Comment by VergLsm** [comment]
@SuperMonster003 搞定了，谢谢了

**Comment by guohuatai** [comment]
另外一个脚本就是不支持解锁，需要自己写，但是小白不会啊，所以一直用你的这个。不过现在那个脚本对蚂蚁森林的更新修复好了

**Comment by SuperMonster003** [comment]
@guohuatai 解锁模块以后会分离出来 可以单独使用  
此项目将于22日重新启动 将会尝试解决目前收集到的所有Bug  
另外Nick的项目我看了下 是将一部分选择器的desc相关方法替换成了text相关方法  
支付宝更新控件并不是同步更新  
比如我的两台设备 到现在都是desc 
将全部desc更改为text 弊端就在于不能兼容还没有进行控件变更的设备  
text与desc文本转移的问题可能在日后还会复返  
另外在其他软件 (比如JD或JD Finance) 都有可能存在此类问题  
所以我暂时采用的是动态获取并记忆选择器的方式 (详见代码有关 `sel.pickup()` 以及 `memory()` 部分)  
感谢支持  
😃

**Comment by VergLsm** [comment]
@SuperMonster003 这种问题有没有可能是因为html渲染的时候随机把文字放在控件的text或desc了
不过反正不是text就是desc，结果是需要一个控件对象
可不可以尝试封装一个方法，text选择为空时则尝试desc选择
不为空时则返回对象

**Comment by SuperMonster003** [comment]
@VergLsm `sel.pickup()` 的核心代码就是先判断desc是否存在 然后再判断text是否存在 一旦发现 本次会话就存储这个值 以后便无需再判断 另外先判断desc还是先text也是可以选的 是否记忆值也是可开闭的

**Comment by VergLsm** [comment]
@SuperMonster003 可以告诉我怎样关闭使用记忆值吗？我测试一下让他每次都重新获取，看看成功率是否会比现在高

**Comment by SuperMonster003** [comment]
大概1898行 memorize()函数 第一行直接 return kn;

**Comment by SuperMonster003** [comment]
@Cheney93 抱歉拖了这么久  
```js
let unlock_module = new (require("./Modules/MODULE_UNLOCK.js"))();
unlock_module.unlock();
```
注意模块依赖 所有依赖模块都在 `Modules` 文件夹内  
另外如果需要设置或修改密码 暂时没有图形页面 (以后也不打算写了) 只能通过代码实现  
```js
let code = "123456";
let encrypt = new (require("./Modules/MODULE_PWMAP.js"))().pwmapEncrypt;
let storage_unlock = require("./Modules/MODULE_STORAGE.js").create("unlock");
storage_unlock.put("config", {
    unlock_code: encrypt(code),
});
```
修改 `code` 的值即可

**Comment by SuperMonster003** [comment]
`v1.9.5` 已深度分离出模块与工具

解锁模块: `./Modules/MODULE_UNLOCK.js`
解锁配置工具: `./Tools/Unlock_Config_Tool.js`

工具直接运行使用

模块使用方法如下
```js
require("./MODULE_UNLOCK").unlock();
```

**Comment by xseven007** [comment]
最新版的解锁如何调用。使用require("./Modules/MODULE_UNLOCK.js").unlock(); 会出错
23:21:44.906/E: ReferenceError: "$$impeded" is not defined. (file:/storage/emulated/0/Documents/AutoJs/Ant_Forest/Modules/MODULE_UNLOCK.js#316)
ReferenceError: "$$impeded" is not defined.
    at waitForAction (file:/storage/emulated/0/Documents/AutoJs/Ant_Forest/Modules/MODULE_UNLOCK.js:316:0)
    at getDisplayParams (file:/storage/emulated/0/Documents/AutoJs/Ant_Forest/Modules/MODULE_UNLOCK.js:797:0)
    at _exports (file:/storage/emulated/0/Documents/AutoJs/Ant_Forest/Modules/MODULE_UNLOCK.js:66:0)
    at file:/storage/emulated/0/Documents/AutoJs/Ant_Forest/Modules/MODULE_UNLOCK.js:19:0
    at _load (file:///android_asset/modules/jvm-npm.js:60:0)
    at /storage/emulated/0/Documents/AutoJs/Ant_Forest/Auto_Unlock.js:1:0

**Comment by SuperMonster003** [comment]
@xseven007 
尝试在解锁模块31行添加
```js
 !function _insureImpeded() {
        if (typeof $$impeded === "undefined") {
            $$impeded = () => void 0;
        }
    }();
```

**Comment by xseven007** [comment]
@SuperMonster003 不行，解锁失败。屏幕都没点亮。
