### ISSUE TITLE
小米10打开蚂蚁森林之后没有反应

### ISSUE THREAD

**Issue by 2437822678** [SuperMonster003/Auto.js_Projects#281]
运行Ant_Forest_Launcher.js时，打开支付宝中的蚂蚁森林后，没有反应

**Comment by qinxiaoxiang** [comment]
小米8 也是打开后没反应

**Comment by SuperMonster003** [comment]
通常是截图权限没有申请成功
参阅 https://github.com/SuperMonster003/Auto.js_Projects/issues/47
如果非以上情况或问题依然存在 请提供一下日志截图

**Comment by tvrcfdfe** [comment]
你们小米九宫格可以解锁成功吗. 我很简单的 笔画一直解锁不成功 458963 就这么简单的.
