### ISSUE TITLE
关于解锁

### ISSUE THREAD

**Issue by decike** [SuperMonster003/Auto.js_Projects#284]
**问题描述**
从当前运行情况看来，亮屏后会有个上滑的动作，默认起点刚好在屏下指纹的位置，会导致上滑失败

**日志截图**
没有截图嘿嘿，建议上调起点的默认值为0.7（自测0.7能解决这个问题）；横坐标左调或者右调应该也是可以的，不过有些主题解锁完会唤起奇怪的东西（相机，小米之家之类的东西）

**软件硬件信息**
操作系统: 安卓10
设备型号: 小米cc9
Auto.js版本: 4.1.1 Alpha2

**其他**
建议加一个小号给大号浇水的功能，这个功能我在按键精灵写了下，模拟器上能用，但是我手机没root，准备学js了，等我把c艹学完（学到析构函数了）就学js。最后，向辛勤无私的作者表示无上的感激，祝身体健康，谢谢！

**Comment by SuperMonster003** [comment]
https://github.com/SuperMonster003/Auto.js_Projects/issues/75
这里提到了类似的滑动解锁问题 因此增加了滑动起点终点的配置 不同设备有不同的合适起始点 因此无法做到完全统一使用一个默认值 即使是同一个厂牌的设备 对于此参数也可能有不同的需求

浇水功能很多人提到过 为避免此功能被用于灰产等用途 项目不会添加或涉及此类功能 希望理解

感谢支持
:heart:
