### ISSUE TITLE
想请教一下怎样在没有root的情况下锁屏/熄屏

### ISSUE THREAD

**Issue by decike** [SuperMonster003/Auto.js_Projects#286]
可以讲一下大致思路吗

**Comment by SuperMonster003** [comment]
1. 运行脚本时的屏幕状态如果是灭屏 运行结束后才会自动关屏
2. 关屏时有两种策略
a. 优先使用Root方法模拟电源键关屏
b. 如果没有Root权限 则脚本会修改屏幕超时参数间接实现关屏

注: 安卓系统设置参数的修改 需要一个权限叫"修改系统设置 (Modify system settings)"
有了如上权限后 脚本修改自动关屏时间参数 (参数通常会被用户设置成1分钟 表示1分钟内无操作 手机将自动关屏 1分钟对应的参数为60000 表示六万毫秒) 脚本修改此参数为0 手机会在尽可能短的时间内自动关屏 大概需要10秒左右 期间用户如果没有触碰屏幕或按键 则手机将灭屏 于是实现了自动关屏功能
在设置参数为0之前 脚本会记录修改前的数值 如刚刚提到的6万 在灭屏后 脚本立即恢复记录的数值 以保证不影响用户体验
