### ISSUE TITLE
帮收功能出问题了

### ISSUE THREAD

**Issue by decike** [SuperMonster003/Auto.js_Projects#287]
进入好友的蚂蚁森林界面后，帮收能量球在飘，但是检测不到，日志返还“无能量球可操作”，然后就退出了，然后返检，同样

![image](https://user-images.githubusercontent.com/63651801/79626984-2fb18880-8167-11ea-93aa-a275f57c7f66.png)

**软件硬件信息**
操作系统: andriod 10
设备型号: 小米cc9
Auto.js版本: 4.1.1 Alpha2

**Comment by SuperMonster003** [comment]
可尝试新版本 v1.9.16

如果问题依然存在 可尝试在配置工具中修改以下两项参数
1. 帮收能量球颜色阈值 -> 60
2. 帮收能量球样本采集密度 -> 13
以上仅供参考 可尝试根据实际情况进行微调

如果依然无法解决 可继续反馈
