### ISSUE TITLE
当好友主页有黄色能量时，无法识别保护罩

### ISSUE THREAD

**Issue by yuluu** [SuperMonster003/Auto.js_Projects#288]
**问题描述**
1.9.15版本

当好友主页有黄色能量时，无法识别保护罩

会在好友主页停留十秒左右，然后正常工作，此好友不会添加到保护罩黑名单中去。

**Comment by SuperMonster003** [comment]
黄色球指的是金色球 (1g/5g/10g/18g) 还是橙色球 (带有"即将消失"字样)

**Comment by yuluu** [comment]
> 黄色球指的是金色球 (1g/5g/10g/18g) 还是橙色球 (带有"即将消失"字样)

金色球。有时候保护罩识别出来了，但是不会加到保护罩黑名单中去。是不是保护罩黑名单有数量限制。还有一个问题，设置了好友排行榜最小倒计时阈值60分钟，会复检几遍，然后有60分钟以内熟的能量还是会自动停止脚本，提示已达到连续好友访问最大阈值。搞不清楚这里面是什么逻辑。（ps:大神这项目做的挺得牛逼的）

**Comment by SuperMonster003** [comment]
下次如果再遇到能量罩无法识别的情况 请提供一下好友森林页面 (包含保护罩和金色能量球 另外注意隐私信息保护)
黑名单没有数量限制的 没有加入黑名单时 日志的提示是什么 正常日志会有提示的 比如已加入黑名单 或者跳过当前黑名单好友之类的
排行榜复查的时候 有一个复查条件是样本点击记录 如果一个好友可以帮收 排行榜是橙色爱心 进入之后因为识别问题 脚本没有点击橙色球 复查之后又会发现排行榜这个好友的橙色图标 点进去之后又没有点击橙色球 如此造成死循环 因此脚本设置了访问同一个好友的最大连续次数
最小倒计时阈值一般只会设置成1-3分钟 没有人会设置60的 那样肯定会造成很多无畏的复查和资源浪费 不符合项目"智能"的初衷

**Comment by yuluu** [comment]
> 下次如果再遇到能量罩无法识别的情况 请提供一下好友森林页面 (包含保护罩和金色能量球 另外注意隐私信息保护)
> 黑名单没有数量限制的 没有加入黑名单时 日志的提示是什么 正常日志会有提示的 比如已加入黑名单 或者跳过当前黑名单好友之类的
> 排行榜复查的时候 有一个复查条件是样本点击记录 如果一个好友可以帮收 排行榜是橙色爱心 进入之后因为识别问题 脚本没有点击橙色球 复查之后又会发现排行榜这个好友的橙色图标 点进去之后又没有点击橙色球 如此造成死循环 因此脚本设置了访问同一个好友的最大连续次数
> 最小倒计时阈值一般只会设置成1-3分钟 没有人会设置60的 那样肯定会造成很多无畏的复查和资源浪费 不符合项目"智能"的初衷

![Screenshot_20200420_194112_com eg android AlipayGphone](https://user-images.githubusercontent.com/30486446/79747918-12371700-833f-11ea-8e40-fcff6b88e721.jpg)
这个就没有加进黑名单当中去。设置60，是想让他7-8点一直刷新。。。。

**Comment by yuluu** [comment]
> 下次如果再遇到能量罩无法识别的情况 请提供一下好友森林页面 (包含保护罩和金色能量球 另外注意隐私信息保护)
> 黑名单没有数量限制的 没有加入黑名单时 日志的提示是什么 正常日志会有提示的 比如已加入黑名单 或者跳过当前黑名单好友之类的
> 排行榜复查的时候 有一个复查条件是样本点击记录 如果一个好友可以帮收 排行榜是橙色爱心 进入之后因为识别问题 脚本没有点击橙色球 复查之后又会发现排行榜这个好友的橙色图标 点进去之后又没有点击橙色球 如此造成死循环 因此脚本设置了访问同一个好友的最大连续次数
> 最小倒计时阈值一般只会设置成1-3分钟 没有人会设置60的 那样肯定会造成很多无畏的复查和资源浪费 不符合项目"智能"的初衷

![Screenshot_20200420_194112_com eg android AlipayG](https://user-images.githubusercontent.com/30486446/79748796-976efb80-8340-11ea-8be6-74c2797c6e4a.jpg)

![Screenshot_20200420_194046_org autojs autojs](https://user-images.githubusercontent.com/30486446/79748811-9b028280-8340-11ea-8834-b278599acf87.jpg)

这个就没加进黑名单里面，我试了几次。设置60是想它7-8点一直刷新。。。。。确实挺费电的，哈哈哈

**Comment by SuperMonster003** [comment]
提供一下那个好友的"最新动态"列表截图 今天和昨天的都包括进去 注意保护隐私信息

**Comment by yuluu** [comment]
![Screenshot_20200420_194046_org autojs autojs](https://user-images.githubusercontent.com/30486446/79751085-92ac4680-8344-11ea-9eca-9ebb88a3f34b.jpg)
![111](https://user-images.githubusercontent.com/30486446/79751087-93dd7380-8344-11ea-88f4-963b72e3106c.jpg)
今天同样的动态太多了，差不多有上百条被保护罩阻挡的动态/

**Comment by yuluu** [comment]
> 提供一下那个好友的"最新动态"列表截图 今天和昨天的都包括进去 注意保护隐私信息

![111](https://user-images.githubusercontent.com/30486446/79751510-457ca480-8345-11ea-8721-4f451459790f.jpg)

![222](https://user-images.githubusercontent.com/30486446/79751552-5c22fb80-8345-11ea-82e2-823aad5e67f3.jpg)

今天同样的动态太多了，上百条被保护罩阻挡的动态。

**Comment by SuperMonster003** [comment]
下一版修复
