### ISSUE TITLE
Bug反馈: 进入好友列表后报OpenCV错误

### ISSUE THREAD

**Issue by Sakakibara-Hu** [SuperMonster003/Auto.js_Projects#289]
**问题描述**
1.9.15版本之前用的好好的，突然有一天就报这个错了，进到好友列表，就报这个OpenCV的错

**日志截图**
![image](https://user-images.githubusercontent.com/26788881/79767018-5801d880-835b-11ea-89ed-7092fdacc47e.png)

**软件硬件信息**
操作系统: 安卓10
设备型号: 三星 S20
Auto.js版本: 4.1.1 Alpha2

**其他**
包括但不限于建议/提案/想法/灵感...

**Comment by SuperMonster003** [comment]
https://github.com/SuperMonster003/Auto.js_Projects/issues/259
