### ISSUE TITLE
功能建议: 增加一个停止运行的悬浮窗

### ISSUE THREAD

**Issue by tagaga** [SuperMonster003/Auto.js_Projects#291]
能够增加一个停止运行的悬浮窗，有的时候自行定时任务的时候，正在用手机，希望停止执行，点击一下最上面的悬浮按钮就可以，现在每次都要杀掉autojs的进程才可以

**Comment by SuperMonster003** [comment]
项目设置了音量按键监听
音量+可停止全部队列中的脚本 (包括正在运行和排队的)
音量- 可停止当前正在运行的脚本
另外定时任务激活前 可以设置对话框提示 提供推迟/放弃/立即执行的可选操作
如果不希望自动任务的打扰
1. 设置前置应用黑名单
适用于某个或某些应用不希望被打扰的情况
如添加MX Player应用后 可避免在观看视频时自动任务的执行 (任务会自动推迟)
2. 设置自动管理机制的有效区间
适用于某个时间段不希望被打扰的情况
例如不希望白天9点到12点以及下午2点到6点的时间自动运行定时任务
可设置以下两个有效时间段 [12:00,14:00] [18:00,09:00] (第二个时间段的意思是18点到9点 也就是每天的0-9点以及18-24点)
定时任务会被限制在这两个有效时段内运行

鉴于建议所述功能的可替代性
此建议不被采纳
感谢支持
❤️

**Comment by SuperMonster003** [comment]
另外 Auto.js 软件自带悬浮窗 可以关闭运行中的脚本
可作为另一个参考方案
此 Issue 暂时关闭
