### ISSUE TITLE
Bug反馈: 无可操作能量球-不能收好友能量

### ISSUE THREAD

**Issue by liujiayi771** [SuperMonster003/Auto.js_Projects#292]
**问题描述**
最新的16版本，MIUI11解锁没问题了，很赞。但是收别人能量的时候能识别到有能量可以收，但是进去以后不点击能量，过一会自己就退出来了。每个可以收能量的能量球都不自动点击了。日志显示无可操作能量球。应该怎么设置呢。

**日志截图**
![IMG_20200422_235848](https://user-images.githubusercontent.com/13622031/80004776-54a25480-84f5-11ea-901b-46fac173fa20.jpg)

**软件硬件信息**
操作系统: [安卓10]
设备型号: [小米 10 pro]
Auto.js版本: [4.1.1 Alpha2]

**其他**
尝试了很多地方设置都没用，大神帮忙解答下。

**Comment by liujiayi771** [comment]
补充一下，自己的能量可以收，就是不能收好友的，也不能帮收

**Comment by SuperMonster003** [comment]
参阅 https://github.com/SuperMonster003/Auto.js_Projects/issues/119
目前陆续有个别人会遇到此问题 无法识别好友森林的能量球控件 导致无法收取
现在没有很好地办法解决此问题 只能等日后开发出基于图像和颜色识别的方案 但此方案会耗费大量的开发精力 外加技术难度较高 所以很可能会遥遥无期 除非出现大面积用户无法使用的情况 可能才会考虑着手开发

**Comment by liujiayi771** [comment]
我之前用的稳定版系统是可以的，现在刷到开发版了不行了，后面等MIUI12出来再观察下行不行

**Comment by Reid00** [comment]
加反馈我的也这样目前

**Comment by lpstart** [comment]
加反馈，我也遇到了同样的问题。

**Comment by yhg13** [comment]
同样的问题

**Comment by cuki8023** [comment]
荣耀 EMUI 9.1 官方无root  同样遇到不收取的问题

**Comment by liujiayi771** [comment]
小米10 pro升级到1.9.18也解决了，所以不是 @SuperMonster003 所说的那个问题吧。
