### ISSUE TITLE
Bug反馈: 有时会出现“好友倒计时数据无效”

### ISSUE THREAD

**Issue by yuluu** [SuperMonster003/Auto.js_Projects#293]
**问题描述**
这几天每天早上都会出现一次这样的问题。

**日志截图**
![Screenshot_20200423_075901_org autojs autojs](https://user-images.githubusercontent.com/30486446/80060545-66b9dc80-8561-11ea-87c7-7ac60c546896.jpg)

**软件硬件信息**
操作系统: [安卓10.0]
设备型号: [mate30 pro]
Auto.js版本: [4.1.1 Alpha2]

**其他**
包括但不限于建议/提案/想法/灵感...

**Comment by SuperMonster003** [comment]
请提供一下"排行榜样本复查"的开闭状态
如果是开启的 再提供一下复查条件的勾选状态以及设置值 (如果有的话)

**Comment by yuluu** [comment]
> 请提供一下"排行榜样本复查"的开闭状态
> 如果是开启的 再提供一下复查条件的勾选状态以及设置值 (如果有的话)

![Screenshot_20200423_143652_org autojs autojs](https://user-images.githubusercontent.com/30486446/80067377-49d8d580-8570-11ea-85a2-add5d38e3111.jpg)

**Comment by yuluu** [comment]
> 请提供一下"排行榜样本复查"的开闭状态
> 如果是开启的 再提供一下复查条件的勾选状态以及设置值 (如果有的话)

![Screenshot_20200423_143652_org autojs autojs](https://user-images.githubusercontent.com/30486446/80067410-59f0b500-8570-11ea-8b72-a06383c0b5a8.jpg)

**Comment by yuluu** [comment]
> 请提供一下"排行榜样本复查"的开闭状态
> 如果是开启的 再提供一下复查条件的勾选状态以及设置值 (如果有的话)

![Screenshot_20200423_143652_org autojs autojs](https://user-images.githubusercontent.com/30486446/80067495-7f7dbe80-8570-11ea-9f0c-65b02933e3fa.jpg)

**Comment by SuperMonster003** [comment]
收到 下一版修复此问题
