### ISSUE TITLE
Bug反馈: 在主页巡检倒计时的状态下，没有走手机解锁逻辑

### ISSUE THREAD

**Issue by weitemi** [SuperMonster003/Auto.js_Projects#294]
**问题描述**
在主页巡检倒计时的状态下，等待倒计时完成后，没有走手机解锁逻辑进行了下一步。或者说没有解锁成功。

**日志截图**
暂没有图片

**软件硬件信息**
操作系统: [如: 安卓9.0]
设备型号: [如: 三星S9]
Auto.js版本: [如: 4.1.1 Alpha2]

**其他**
建议：等待巡检的倒计时过程中，14s（这个时间小于手机一般自动锁屏时间）点一次能量球，使手机不自动锁屏。

**Comment by SuperMonster003** [comment]
关键代码
```js
let _thrd = $$af.thrd_monit_own;
let _tt = _thrd * 60000 + 3000;
let _old_em = $$af.emount_c_own;

toast("Non-stop checking time");
debugInfo("开始监测自己能量");
timeRecorder("monitor_own");

$$dev.keepOn(_tt);
while (timeRecorder("monitor_own", "L") < _tt) {
    if (_chkRipeBalls()) {
        break;
    }
    sleep(180);
}
$$dev.cancelOn();
```

keepOn方法保证监测期间设备不会灭屏 并提供3秒的右边界补偿
在_chkRipeBalls函数内部 会使用基于click的封装方法点击成熟能量球 点击时系统屏幕超时将被重置
当第二个能量球倒计时依然落在监测条件区间时 依然重复上述过程 先keepOn 然后点击球 最后cancelOn
如果执行逻辑正常 应该不会出现中途灭屏现象

如问题依然存在
请提供相关问题的关键日志截图或相关图影资料

**Comment by weitemi** [comment]
好吧 可能是我当时用手关闭的手机，我把问题关闭了。
