### ISSUE TITLE
功能建议: 是否可以增加基于偷取能量数量的自动浇水机制

### ISSUE THREAD

**Issue by xukellp** [SuperMonster003/Auto.js_Projects#295]
- 当前项目
当前项目已有的功能描述 ：当前最新版本已经有了后台统计偷取能量的功能

- 期望
期望的功能描述 ：期望增加一个基于后台统计数据的自动浇水功能，比如用户可以自己设置一个绿名单，判定当 本周 偷取 A 的能量超过了 B克 时，自动浇 C 次水。而且可设置阶梯式判定，比如第一次浇水是在 70克 浇 1 次水，140 克 浇 1 次水。
再进一步，可以判定，当单次（单次点击或者单次页面停留）偷取超过一定数值能量时，自动浇一次水。浇水次数也记录进数据库，在下次触发总偷取能量判定时检测是否在此区间已浇过水，如果已浇过，就不再浇此阶梯的水。
这个功能是防止偷的能量太多，导致被对方拉入黑名单，细水长流······

**Comment by SuperMonster003** [comment]
https://github.com/SuperMonster003/Auto.js_Projects/issues/283
感谢理解与支持
