### ISSUE TITLE
Bug反馈: 华为mate30运行报错

### ISSUE THREAD

**Issue by smalsummer** [SuperMonster003/Auto.js_Projects#296]
**问题描述*
![Screenshot_20200424_131607_com eg android AlipayGphone](https://user-images.githubusercontent.com/12507547/80178591-2de93880-8631-11ea-8705-0b404f3b8825.jpg)

**日志截图**
![Screenshot_20200424_133704_org autojs autojspro](https://user-images.githubusercontent.com/12507547/80178476-e793d980-8630-11ea-9bc9-a0d6a0359b80.jpg)

**软件硬件信息**
操作系统: [如: 安卓10.0]
设备型号: [如: 华为 mate30]
Auto.js版本: [如: 4.1.1 Alpha2]

**其他**
包括但不限于建议/提案/想法/灵感...

**Comment by SuperMonster003** [comment]
先临时关闭账户功能
此问题下一版修复

**Comment by SuperMonster003** [comment]
此问题已于v1.9.17尝试修复
欢迎试用并反馈
另账户功能请谨慎试用 仔细阅读配置工具中的功能提示
