### ISSUE TITLE
Bug反馈: 华为P30pro解锁失败

### ISSUE THREAD

**Issue by Murique11** [SuperMonster003/Auto.js_Projects#297]
**问题描述**
锁屏以后定时任务无法自动解锁

**日志截图**
![lADPD2sQrhG_rOLNCWDNBJg_1176_2400 jpg_720x720q90g](https://user-images.githubusercontent.com/43530953/80230034-ea6bea00-8683-11ea-82b3-c9ff4153760b.jpg)

**软件硬件信息**
操作系统: 安卓9.0
设备型号: 华为P30PRO
Auto.js版本:4.1.1 Alpha2

**其他**
包括但不限于建议/提案/想法/灵感...

**Comment by Murique11** [comment]
已在记录里面搜索到

**Comment by SuperMonster003** [comment]
是v1.9.16版本吗
如果是的话 说明修复未成功
