### ISSUE TITLE
就是收取能量的自我监听实现不成

### ISSUE THREAD

**Issue by 17839170745** [SuperMonster003/Auto.js_Projects#30]
设置自我能量监听时不会到时间了运行，设置完定时启动后发现早上的时候没有自我启动，而且后台也没有处理。MIUI10

**Comment by SuperMonster003** [comment]
感谢反馈  
自己监听功能是脚本运行时 如果设置的监听区间 (可以有多个) 包含了当前时间 脚本就会一直监听自己成熟的能量并及时收取 是不能自己启动的 (目前还不会)  
需要在Auto.js中设置定时任务 在js文件右侧有菜单可以设置  
可以先设置一个2分钟的做测试 看能否正常收到广播事件启动任务
