### ISSUE TITLE
Bug反馈: 运行过程中崩溃或无法运行

### ISSUE THREAD

**Issue by haoguowei98** [SuperMonster003/Auto.js_Projects#300]
**问题描述**
运行过程崩溃或无法运行，自行终止。

**日志截图**
提供与问题相关的日志截图
![Screenshot_20200427_123428_org autojs autojs](https://user-images.githubusercontent.com/64414786/80373411-9ea98280-88c7-11ea-8c2f-edcb21b0e169.jpg)
![Screenshot_20200427_200940_org autojs autojs](https://user-images.githubusercontent.com/64414786/80373471-b41eac80-88c7-11ea-9d5a-a0b088ab603f.jpg)
![Screenshot_20200427_200956_org autojs autojs](https://user-images.githubusercontent.com/64414786/80373556-d284a800-88c7-11ea-82b0-0687d0f299b3.jpg)

**软件硬件信息**
操作系统: [ 安卓9.0 ]
设备型号: [ 华为 畅想8 plus ]
Auto.js版本: [4.1.1 Alpha2 ]
项目版本: [ v1.9.15-v1.9.17 ]

**Comment by SuperMonster003** [comment]
分析了足足一小时
很疑惑为什么在显示"开始蚂蚁森林任务"不到1秒的时间就能执行到Launcher的860行
开启一下"开发者测试模式"然后再反馈一下日志
另外建议把项目单独放置在一个文件夹内再尝试运行

**Comment by haoguowei98** [comment]
之前2个手机都是一样的问题，测试了几个项目版本: [ v1.9.13-v1.9.17 ]，今天早上可以正常使用了，可能是Auto.js版本: [4.1.1 Alpha2 ]的问题！
![QQ图片20200428125838](https://user-images.githubusercontent.com/64414786/80449071-c0028100-8950-11ea-8d40-1eeeadab7955.jpg)
