### ISSUE TITLE
Bug反馈: 支付宝更新后，无法收取能量

### ISSUE THREAD

**Issue by yuluu** [SuperMonster003/Auto.js_Projects#301]
**问题描述**
其他都一切正常，就是进去好友页面后，不会点击能量球了。

**日志截图**
提供与问题相关的日志截图

**软件硬件信息**
操作系统: [ 如: 安卓8.0 ]
设备型号: [ 如: 索尼 G8441 ]
Auto.js版本: [ 如: 4.1.1 Alpha2 ]
项目版本: [ 如: v1.9.1 ]

**其他**
[ 包括但不限于 建议/提案/想法/灵感... ]

**Comment by chenhd9** [comment]
我手机也出现这个情况了！

**Comment by lchongxiu-beijing** [comment]
一样

**Comment by yhg13** [comment]
也是一样

**Comment by rony117** [comment]
![QQ图片20200430001409](https://user-images.githubusercontent.com/64546834/80620014-0acae880-8a78-11ea-9cdc-1b0a3dfe7699.jpg)
蚂蚁森林这个页面的布局被改了，猜想作者以前用的是控件查找吧，现在整个能量球那一块变成一个整的控件了

**Comment by hsw0630** [comment]
添加模拟点击还是可以收取的 但是 好麻烦  期待大佬更新下

**Comment by guke1991** [comment]
同样的问题

**Comment by yangyueyang** [comment]
小米8   安卓10  系统 MIUI12  更新支付宝后也无法收取好友能量球

**Comment by luchangharry** [comment]
mate30pro 一样的问题额

**Comment by Sq-List** [comment]
小米9 Android10 MIUI12 +1

**Comment by crb8331** [comment]
> 添加模拟点击还是可以接受的但是好麻烦期待大佬更新下

请问怎么添加模拟点击？

**Comment by TripleHHH-3** [comment]
支付宝更新后无法偷取能量和好用帮收

**Comment by YinHang119** [comment]
> 添加模拟点击还是可以收取的 但是 好麻烦 期待大佬更新下

同样问一下，怎么添加模拟点击呢？谢谢

**Comment by OCDcreator** [comment]
日志里是：01:26:52.248/D: -> 无能量球可操作

**Comment by moverzp** [comment]
加一，期待更新

**Comment by DaBee98** [comment]
荣耀8x
安卓10系统
一样只能进入界面
不能收取能量球
望老大五一休息完更新

**Comment by Sq-List** [comment]
> 荣耀8x
> 安卓10系统
> 一样只能进入界面
> 不能收取能量球
> 望老大五一休息完更新

老哥试试最新的。
