### ISSUE TITLE
功能建议: 建议在人为解锁后也添加放弃任务或推迟任务的提示框

### ISSUE THREAD

**Issue by luchangharry** [SuperMonster003/Auto.js_Projects#302]
当前项目
当前项目已有的功能描述 ：现有在手机亮屏状态下会弹出提示框，是否推迟执行，非常人性化的功能！

期望
期望的功能描述 ：当手机放在口袋中时，因为有防误触模式，所以手机屏幕是不会亮屏，脚本也不会执行，但是一旦我拿出手机，手动点亮屏幕后，脚本会自动执行，此时不会弹出是否推迟任务或放弃任务的提示框，脚本会直接执行，我就只能等待脚本运行结束才能做事。但其实在这种情况下，往往是有事才会掏出手机，比如上班扫码共享单车，或是给别人展示手机上的东西的时候，这时候没有推迟或放弃任务的选项，就会不太方便

**Comment by luchangharry** [comment]
@SuperMonster003 作者大大，我觉得这个问题是不是也可以采用这种机制，就检测到打开屏幕失败，就把该任务推迟15分钟，然后把这个功能放在设置里，可以选择打开或者关闭，这样就不至于一打开屏幕就有好几个堆积的脚本自动开始运行。

**Comment by SuperMonster003** [comment]
v1.9.21 将增加 "息屏或上锁启动时自动跳过" 选项
在配置工具中将其取消勾选 (默认为勾选)
可在息屏或未解锁状态时依然显示运行前提示对话框

**Comment by SuperMonster003** [comment]
v1.9.22 修复了上一版本此功能相关的问题
欢迎尝试并提交功能反馈

**Comment by luchangharry** [comment]
> v1.9.22 修复了上一版本此功能相关的问题
> 欢迎尝试并提交功能反馈

作者大大我好像没找到这个设置在哪里？是启动那个setting脚本来设置么

**Comment by SuperMonster003** [comment]
Ant_Forest_Settings.js
-> 消息提示
-> 息屏或上锁启动时自动跳过
取消勾选即可实现无论什么情况都显示 `运行前提示对话框`
