### ISSUE TITLE
功能建议: 发布应急版本

### ISSUE THREAD

**Issue by biosxf007** [SuperMonster003/Auto.js_Projects#303]
看了大家的讨论得知，蚂蚁森林的升级让控件寻找遇到了困难，我的是下午发现不能用了，到现在还是焦虑万分，至少今晚得12点以后睡了，老大能不能先推出一个应急版本，就是进入可收好友界面后直接模拟鼠标点击，这个应该可以的吧，虽然很土很暴力，万分感谢啊！！！

**Comment by daxinnan** [comment]
试试最新的，我的都可以用了，安卓10,一加6，作者真滴优秀！！！

**Comment by daxinnan** [comment]
向劳动者致敬

**Comment by biosxf007** [comment]
谢谢楼上的朋友，我这边也可以了！大赞作者啊，原以为一时半会解决不了的，五一节你最美！

**Comment by mymizang** [comment]
到两三百好友就停了是怎么回事？

**Comment by DaBee98** [comment]
更新到1.9.18后一样不收好友能量球

**Comment by SuperMonster003** [comment]
@DaBee98 v1.9.18为应急更新 能量球识别率和功能兼容性都无法保证 下一版将提升兼容与适配

**Comment by sanye5** [comment]
有的可以识别有的不能识别  导致有的能量不会自动收

**Comment by drp000** [comment]
有的可以识别有的不能识别 导致有的能量不会自动收，支付宝最新版本，脚本也更新到了最新版本，autojs版本4.1.1 alpha2
