### ISSUE TITLE
Bug反馈: [ 华为mate30定时任务第二天早上无法解锁

### ISSUE THREAD

**Issue by hahadsu** [SuperMonster003/Auto.js_Projects#305]
**问题描述**
定时任务第二天早上无法解锁 ，一直在尝试，但我解锁完后设置一个新的定时任务可以很容易解锁运行。

**日志截图**
![Screenshot_20200503_090741_org autojs autojs](https://user-images.githubusercontent.com/61813528/80896341-d1b4a180-8d1f-11ea-9cd5-f6068f57051e.jpg)
![Screenshot_20200503_090903_org autojs autojs](https://user-images.githubusercontent.com/61813528/80896345-d711ec00-8d1f-11ea-9000-c01169d4a06e.jpg)

**软件硬件信息**
操作系统: [ 安卓10 ]
设备型号: [  华为mate30 TAS-AL00 ]
Auto.js版本: [ 4.1.1 Alpha2 ]
项目版本: [ v1.9.18 ]

**其他**
更新后版本还是同样的问题，而且截图权限获取失败
[ 包括但不限于 建议/提案/想法/灵感... ]

**Comment by SuperMonster003** [comment]
当前项目中存在解锁最大次数限制失效的问题 导致解锁失败会一直尝试 (下一版修复)
修复后如果再次遇到解锁失败问题 脚本会将失败时的屏幕截图保存下载 可用作问题分析
另外下一版 (v1.9.19) 发布后问题复现时 希望可以附上失败过程中脚本的具体表现 比如提示层并没有被划开 或者卡在PIN解锁页面等类似的描述

**Comment by hahadsu** [comment]
更新后1.9.19版本还是同样的问题，而且截图权限获取失败

**Comment by hahadsu** [comment]
更新后1.9.19版本还是同样的问题，而且截图权限获取失败

**Comment by hahadsu** [comment]
![Screenshot_20200513_073849_org autojs autojs](https://user-images.githubusercontent.com/61813528/81772122-95e7bc00-9517-11ea-8820-69c513083651.jpg)
更新后1.9.19版本还是同样的问题，而且截图权限获取失败

**Comment by SuperMonster003** [comment]
使用解锁布局分析工具
查看分析结果中的关键布局信息是否则 UNLOCK 模块中包含
如有必要 可将布局信息反馈给开发者
参阅 https://github.com/SuperMonster003/Auto.js_Projects/issues/135

**Comment by zhangjyuan228** [comment]
操作系统: [ EMUI版本 10.1.0 ]
设备型号: [ 华为meta30pro 5g]
Auto.js版本: [ 4.1.1 Alpha2 ]
项目版本: [ v1.9.20]
锁屏后还是不能自动解锁。

**Comment by SuperMonster003** [comment]
@zhangjyuan228 
参阅此 Issue 内的 Comments 提供日志或布局信息
