### ISSUE TITLE
Bug反馈:定时任务到时间后无法自动亮屏解锁

### ISSUE THREAD

**Issue by fauthor** [SuperMonster003/Auto.js_Projects#306]
**问题描述**
定时任务到时间后不能自动亮屏，导致后面无法解锁！手动亮屏后就可以自动输入密码解锁。我自己尝试过把autojs卸载重装，功能恢复正常，不过成功几次后又是老样子
另外还有个问题：起点80%表示的是离屏幕上面80%的高度吗？
**日志截图**
![Screenshot_20200503_094755_org autojs autojs](https://user-images.githubusercontent.com/50608586/80896733-f14dc900-8d23-11ea-84a2-cedea232f4cf.jpg)

**软件硬件信息**
操作系统: [ 如: 安卓10.0 ]
设备型号: [ 如: 荣耀V10 ]
Auto.js版本: [ 如: 4.1.2 Alpha2 ]
项目版本: [ 如: v1.9.18 ]

**其他**
[ 包括但不限于 建议/提案/想法/灵感... ]

**Comment by fauthor** [comment]
![Screenshot_20200503_094755_org autojs autojs](https://user-images.githubusercontent.com/50608586/80896789-c0ba5f00-8d24-11ea-9c74-1e5f16f81eb5.jpg)

**Comment by SuperMonster003** [comment]
第一个问题 我目前无法解决
第二个问题 坐标是以屏幕左上角为零点 距离是以左边缘计算宽度 上边缘计算高度

**Comment by fauthor** [comment]
关于第一个问题还想再问问：是插件的原因还是autojs的原因呢？或者说是我手机系统的限制？

**Comment by SuperMonster003** [comment]
0. 首先开启开发者测试模式
在消息提示中勾选开发者测试模式
然后再反馈详细的日志
1. 定时任务到时间后不能自动亮屏
参阅之前的Issue 了解不能自动亮屏可能的原因
2. 解锁
如果解锁流程出现问题 (如不能输入密码等) 请反馈日志
3. 日志截图
日志中错误信息指向images.findImage()方法
很可能是项目中调用此方法的位置出现异常
出现"开始xx任务"日志 说明已经完成了$$init方法链中的解锁方法
我无法在截图中的报错与Issue问题描述之间找到关联
下次再出现的话 一定要把开发者测试模式开启 
然后再反馈日志 以方便问题定位与排除

**Comment by fauthor** [comment]
我自己用device.wakeUp()，设置1分钟后定时运行，然后手动锁屏（没有关闭autojs后台），有时候会按时执行，有时候会延迟1-2分钟，有时候一直不执行，但是我隔一段时间解锁后，查看日志，亮屏的动作执行时间就是我解锁的时间！另外我把autojs重装权限设置好后，运行你的插件，可以完美运行，但是过不了多久又不能自动亮屏，从而使后面的解锁代码无法执行-想请教下您，我这种问题应该如何解决呢？

**Comment by fauthor** [comment]
![Screenshot_20200507_110219_org autojs autojs](https://user-images.githubusercontent.com/50608586/81250366-65091200-9053-11ea-977b-a0429fac20c4.jpg)
这个是亮屏的代码

**Comment by SuperMonster003** [comment]
无法亮屏 通常是AJ的后台运行受限制
参阅 https://github.com/SuperMonster003/Auto.js_Projects/issues/134
