### ISSUE TITLE
Bug反馈: [ 自收功能异常 ]

### ISSUE THREAD

**Issue by biosxf007** [SuperMonster003/Auto.js_Projects#307]
现在的版本基本能在收好友的百忙之中准确在差不多一分钟倒计时返回主页了，但问题来了，如果还有一个未成熟的能量球，时间肯定比那个只有一分钟的长，然后又会点击一下这个，然后估计是刷新了倒计时吧，居然又跳转去收好友能量了，我了个去…

**Comment by SuperMonster003** [comment]
没看明白你的意思
是说返检监控的时候回到自己森林主页 监控并收取完成熟能量球 这时如果还有未成熟球的话 脚本没有继续等待 而是又跳转到排行榜吗

如果是这样 比如未成熟的球最小倒计时还有30分钟 你是希望脚本继续监控30分钟等它成熟吗

**Comment by biosxf007** [comment]
首先感谢老大的回应，我是说如果没有第二个能量球脚本是一直停留在主页监测那个一分钟都不到的，但有第二个的话一分钟那个都没收就跳转了

**Comment by SuperMonster003** [comment]
在消息提示中勾选开发者测试模式
然后在下次出现上述情况是 提供与主页能量球返检监控相关的主要日志

下一版将尝试在主页能量球获取之后增加一个数值稳定器 
不过确定上述问题根源的最好方法依然是实际设备的运行日志

**Comment by biosxf007** [comment]
隔了好多天，今天终于可以把日志发上来了。经过多天观察，如果是一个能量球没问题的，如果是两个能量球也是没问题的，但如果有三个能量球，奇怪的问题就一定来了，倒计时被刷新，然后就不继续监控，跳转页面了。
![Screenshot_20200512_074952_org autojs autojs](https://user-images.githubusercontent.com/61198035/81624705-62f1db00-93e6-11ea-935b-90a0997a5c4d.jpg)
![Screenshot_20200512_075052_org autojs autojs](https://user-images.githubusercontent.com/61198035/81624718-65eccb80-93e6-11ea-9730-0654cc0461b8.jpg)

**Comment by SuperMonster003** [comment]
因为当前操作系统无法获取到蚂蚁森林页面的 Toast 信息
所以使用了备用方案 BaiduOcr
使用 OCR 会导致识别率降低且不可控甚至出现识别错误和遗漏

目前暂无解决方案
