### ISSUE TITLE
Bug反馈: 魅族16s解锁后脚本陷入等待

### ISSUE THREAD

**Issue by Higher-Stark** [SuperMonster003/Auto.js_Projects#309]
**问题描述**
脚本通过数字密码解锁后，进入桌面后，脚本不会继续执行，根据日志看起来是在等待解锁页面提示层消除，最后脚本等待超时，截图结束。
这种现象时常出现，希望作者能帮助解决一下。

**日志截图**
![S00505-14455356](https://user-images.githubusercontent.com/25293291/81041967-b09bae80-8ee1-11ea-90d6-58dcaf803078.jpg)
![unlock_failed_2020071555](https://user-images.githubusercontent.com/25293291/81042007-c7da9c00-8ee1-11ea-8dfa-44693b87181a.png)

**软件硬件信息**
操作系统: 安卓9
设备型号: 魅族 16s
Auto.js版本: 4.1.1 Alpha2
项目版本: 1.9.18

**Comment by SuperMonster003** [comment]
是最新版才出现的吗

可以在屏幕解锁条件下测试以下代码
```js
toast(!context.getSystemService(context.KEYGUARD_SERVICE).isKeyguardLocked());
```
正常应该是弹出true的

另外解锁模块稍微做了些修正
可尝试使用以下解锁模块替代项目Modules目录下的同名文件
[MODULE_UNLOCK.zip](https://github.com/SuperMonster003/Auto.js_Projects/files/4580281/MODULE_UNLOCK.zip)



如果依然失败
请开启开发者测试模式
或使用以下代码测试解锁功能 (需保证在项目目录下运行)
```js
require("./Modules/MODULE_UNLOCK").unlock(true);
```
然后将详细的解锁过程日志反馈一下
