### ISSUE TITLE
自动启动失败

### ISSUE THREAD

**Issue by h237213** [SuperMonster003/Auto.js_Projects#31]
首先膜拜大神！这脚本太牛了，我给好多朋友都推荐了。
问题：设置自动启动脚本，有时候屏幕点不亮，有时候屏幕点亮了无法进入密码输入界面，有时候又能成功，V20

**Comment by SuperMonster003** [comment]
感谢反馈
屏幕无法点亮 说明Auto.js的定时任务没有激活 可以看一下在预设启动任务的时间范围附近 日志里是否有任务启动过的痕迹 文字是灰色的
比如 `07:10:02.200/V: start 
operation[/storage/emulated/0/脚本/Tools/!Ant_Forest.js]`
如果没有 就说明Auto.js被后台限制 包括但不限于电池优化策略/软件策略 (Brevent/Greenify/Ice Box等)
无法进入密码界面 可能是滑动失败 或是滑动时脚本报错 建议反馈一下日志
