### ISSUE TITLE
Bug反馈: AJ崩溃/自动锁屏

### ISSUE THREAD

**Issue by frank142857** [SuperMonster003/Auto.js_Projects#310]
1. 空闲数小时后/重启手机后第一次执行，进入个人蚂蚁森林主页，很大概率出现 Auto.js has stopped. 的问题，需等保险任务间隔时间后自动重新运行。重新运行后均正常，崩溃日志无法查到。
2. 某些反检设置后，能量高峰期有连续运行脚本的情况，连续运行多次后设备不会自动锁屏。
设备：HTC M8
系统：Lineage OS 15.1 （Android 8.1）

多谢群主！

**Comment by SuperMonster003** [comment]
1. 如果是手动重启手机 尽量在启动后手动开启一下无障碍服务
项目早期去除了本地保存日志的功能 原因不便讲述 可能以后会考虑恢复此类功能 但周期会相对较长
如果上述问题频频出现 可通过手机连接 `VS Code`  然后在电脑上查看运行日志

2. 这个问题确实存在 因影响相对较小 将考虑延期修复 (不晚于 Jul 23, 2020)

感谢反馈与建议

**Comment by frank142857** [comment]
更新到1.9.19/1.9.20后，第一次进入蚂蚁森林主页瞬间，有90%以上概率会弹出auto.js has stopped. 需要保留蚂蚁森林主页等保险任务间隔时间后自动重新运行。推测可能因为机器内存小（2G）的原因，不确定是由于618活动主页内容复杂还是新版代码造成，无法提供错误日志。望大神优化。

设备：HTC M8
系统：Lineage OS 15.1 （Android 8.1）

**Comment by SuperMonster003** [comment]
才注意到你最新的反馈
可尝试 v1.9.21 看一下问题是否复现
另外以后会考虑加入日志保存到本地文件的功能
方便崩溃后查看异常信息

**Comment by SuperMonster003** [comment]
> 某些反检设置后，能量高峰期有连续运行脚本的情况，连续运行多次后设备不会自动锁屏。

这个问题在 v1.9.23 已经做了优化
可尝试后提供反馈

另日志保存功能将于后续版本逐步实现

**Comment by SuperMonster003** [comment]
日志保存功能目前已实现
参见 配置工具 -> 本地日志 (默认关闭)
如有问题可重新发布 issue 或重开此 issue
此 issue 暂时关闭
