### ISSUE TITLE
Bug反馈: 帮收功能关闭的情况下仍旧会自动帮收好友能量

### ISSUE THREAD

**Issue by dacs6** [SuperMonster003/Auto.js_Projects#311]
升级到1.9.18后，发现在帮收功能关闭的情况下，如果好友页面中同时存在可以收取的能量和可以帮收的能量球时，脚本在收取好友能量后还会继续帮收能量。
1.19.17及之前的版本中不存在此问题。

**Comment by SuperMonster003** [comment]
v1.9.18识别能量球的准确率相对较低 很可能将橙色球识别成为成熟球
下一版将增加能量球的位置及类型的识别率

当然也不排除v.1.9.18的帮收功能与配置参数的关联问题
我会在下一版发布之前检查并测试相关代码

**Comment by dacs6** [comment]
太厉害了，谢谢！

**Comment by dacs6** [comment]
1.9.19版本此问题已解决，非常感谢！
