### ISSUE TITLE
Bug反馈: [ 自己主页能量检测不到 ]

### ISSUE THREAD

**Issue by hsw0630** [SuperMonster003/Auto.js_Projects#312]
**问题描述**
无法检测自己主页是否存在能量球，帮收倒是可以收取

**日志截图**
![微信图片_20200512084610](https://user-images.githubusercontent.com/35106174/81626112-5b095980-942d-11ea-9f8b-87e3ce2d29ac.jpg)

**软件硬件信息**
操作系统: [ 安卓10.0 ]
设备型号: [ 如: 小米9 PRO ]
Auto.js版本: [ 如: 4.1.1 Alpha2 ]
项目版本: [ 如: v1.9.1 ]

**其他**
[ 应该是昨天支付宝又更新了啥 前天还可以自收]

**Comment by yuluu** [comment]
一样的

**Comment by kennyhou001** [comment]
同样的问题，自己的不能收，好友的可以收

**Comment by TinyMaD** [comment]
我也一样，昨天开始出的问题

**Comment by fflzh** [comment]
一样的问题，自己的不收，但别人的可以正常收取

**Comment by 116boy** [comment]
我也是只收别人的不收自己的。不知道是不是下图导致的不能收取的问题，进入自己主页后会出现这样的提示。
![运行截图](https://user-images.githubusercontent.com/41381008/81890241-15d55b00-95d8-11ea-90f3-96fae6436c62.jpg

**Comment by TripleHHH-3** [comment]
我也一样，不能收自己能量，但可以收好友能量

**Comment by biosxf007** [comment]
同样的问题，这几天出现的，郁闷，每天还得闹钟   ：（

**Comment by zjfyly** [comment]
我也是，调了好多还是没调好，自己的能量中间多了条线，上下颜色不一样，得靠作者了

**Comment by zhangguangjin** [comment]
看了作者的代码好久都找不到原因，看来只有等作者处理完自家中的事再更新啦，暂时找到解决临时办法了，每次进自己森林便点击收取！来张图片，懂的自然懂，
![Screenshot_2020-05-17-11-04-43-253_net dinglisch android taskerm](https://user-images.githubusercontent.com/5145208/82134884-2b908d80-982f-11ea-939b-1c8a809a6282.jpg)

**Comment by zjfyly** [comment]
楼上的看不到你的图片啊，能再发下么？

**Comment by Sq-List** [comment]
> 看了作者的代码好久都找不到原因，看来只有等作者处理完自家中的事再更新啦，暂时找到解决临时办法了，AUTOJS每次进自己森林时便自动点击收取！来张图片，懂的自然懂，
> ![Screenshot_2020-05-17-11-04-43-253_net dinglisch android taskerm](https://user-images.githubusercontent.com/5145208/82134884-2b908d80-982f-11ea-939b-1c8a809a6282.jpg)

老哥咋弄啊？。

**Comment by terryispm** [comment]
希望作者处理完家里的事情来fix这个问题

**Comment by AngelYHY** [comment]
> **问题描述**
> 无法检测自己主页是否存在能量球，帮收倒是可以收取
> 
> **日志截图**
> ![微信图片_20200512084610](https://user-images.githubusercontent.com/35106174/81626112-5b095980-942d-11ea-9f8b-87e3ce2d29ac.jpg)
> 
> **软件硬件信息**
> 操作系统: [ 安卓10.0 ]
> 设备型号: [ 如: 小米9 PRO ]
> Auto.js版本: [ 如: 4.1.1 Alpha2 ]
> 项目版本: [ 如: v1.9.1 ]
> 
> **其他**
> [ 应该是昨天支付宝又更新了啥 前天还可以自收]

我找到了临时解决方法。好像还成功了

if (waitForAction(_getBallsNum, 10e3, 60)) {
                                let _n = $$app.tool.stabilizer(_getBallsNum, _num, 120, 180);
                                if (!isNaN(_n) && _n > _num) {
                                    _num = _n;
                                }
                                debugInfo("找到主页能量球: " + _num + "个");
                                return $$af.balls_nodes = _balls_nodes;
                            }
                            debugInfo("指定时间内未发现主页能量球");

根据 这个关键字搜索     指定时间内未发现主页能量球  
然后修改  waitForAction 方法中传入方法中的时间   
原先是  if (waitForAction(_getBallsNum, own.tt, 60)) {      
我改为了     waitForAction(_getBallsNum, 10e3, 60)

**Comment by Resuperb** [comment]
同样的问题，不知道会不会又是颜色阈值的问题。
