### ISSUE TITLE
三星s10+ 今天开始没法自收 上礼拜开始无法收好友  一直以来 无法帮收

### ISSUE THREAD

**Issue by lifetimelovez** [SuperMonster003/Auto.js_Projects#313]
**问题描述**
三星s10+ 今天开始没法自收 
上礼拜开始无法收好友  
一直以来 无法帮收

**软件硬件信息**
操作系统: 安卓9
设备型号: 三星s10+
项目版本:最新

**Comment by angelmengg** [comment]
您好请问如何解决的，我也是同样手机同样问题
