### ISSUE TITLE
Bug反馈: [ 能进入到森林页面，但是没有收取就退出来了]

### ISSUE THREAD

**Issue by BIGMONK** [SuperMonster003/Auto.js_Projects#315]
**问题描述**
能进入到森林页面，但是没有收取就退出来了

**日志截图**
提供与问题相关的日志截图

**软件硬件信息**
操作系统:安卓10
设备型号: 小米8
Auto.js版本: 4.1.1 Alpha2
项目版本: 1.9.19 Beta

**其他**
[ 包括但不限于 建议/提案/想法/灵感... ]

**Comment by yangyueyang** [comment]
相同机型  软件和脚本的版本也相同，系统是MIUI12  ，另外想问下，日志截图怎么传，找半天没找到上传图片的地方

**Comment by yangyueyang** [comment]
相同机型  相同版本 
![IMG_20200514_092246](https://user-images.githubusercontent.com/34149474/81882195-b457c100-95c4-11ea-96b1-d925d5bdecd3.jpg)

**Comment by fflzh** [comment]
一样的问题，自己的收不了，可以收别人的

**Comment by AndresFeng** [comment]
我也遇到这样的问题，自己的不收取，可以收别人的

**Comment by Santo-wiar** [comment]
同小米8 第一次可以收取他人的，自己的不能，第二次重装重启都不能收取任何能量

**Comment by iloveyou616** [comment]
一样的问题。只能收其他人的，自己的收不了

**Comment by elvadedog** [comment]
同米八，自己的和好友的都没收取就切出去了
