### ISSUE TITLE
Bug反馈: [ 分析能量球位置超出布局界外 ]

### ISSUE THREAD

**Issue by youaaaaa** [SuperMonster003/Auto.js_Projects#316]
**问题描述**
支付宝界面布局更改或其他修改导致
能量球检测出现越界错误bug;
Bug: out of region

**日志截图**
![image](https://user-images.githubusercontent.com/57583951/82133972-a3a58600-9824-11ea-99dc-993009899e92.jpg)

**软件硬件信息**
操作系统: [ 如: 安卓10.0 ]
设备型号: [ 如: 米8 ]
Auto.js版本: [ 如: 4.1.1 Alpha2 ]
项目版本: [ 如: v1.9.19 Beta ]

**其他**
[ 无 ]

**Comment by AngelYHY** [comment]
> **问题描述**
> 支付宝界面布局更改或其他修改导致
> 能量球检测出现越界错误bug;
> Bug: out of region
> 
> **日志截图**
> ![image](https://user-images.githubusercontent.com/57583951/82133972-a3a58600-9824-11ea-99dc-993009899e92.jpg)
> 
> **软件硬件信息**
> 操作系统: [ 如: 安卓10.0 ]
> 设备型号: [ 如: 米8 ]
> Auto.js版本: [ 如: 4.1.1 Alpha2 ]
> 项目版本: [ 如: v1.9.19 Beta ]
> 
> **其他**
> [ 无 ]

我找到的暂时解决办法

function _addBalls() {
                                                        _balls.forEach((o) => {
                                                            // if (_isOrangeBall(o)) {
                                                            //     return _addBall(o, "orange");
                                                            // }

找到 _addBalls 方法  把 _isOrangeBall  这几行代码注释了
