### ISSUE TITLE
功能建议: 定时任务能到秒级

### ISSUE THREAD

**Issue by oishi81** [SuperMonster003/Auto.js_Projects#317]
因为能量球成熟都是在比如7点20分，现在定时任务只能具体到分钟，如果7点20分运行，那进入后已经被别人偷了。所以建议能具体到秒，或者自收功能设置里增加重复检测次数。

**Comment by SuperMonster003** [comment]
自收功能中 主页能量球循环监测 默认阈值为 `2`
意为在进入主页后获取剩余的最小时间小于 2 分钟
将进入监控状态 知道能量球成熟并收取
收取后如果继续有其他能量球最小剩余时间小于 2 分钟
将继续上述过程

如果进入主页后 最小剩余时间值较大 如 3.2 小时
脚本会设置一个 3.2 时 外加 2 分钟的定时任务
这样脚本启动后进入主页 会找到至少一个最小剩余时间为 2 分钟的能量球进行监控
注: 上述前提为开启定时循环功能

如果进入主页后 最小剩余时间大于但接近 2 分钟 (如 3 分钟)
脚本会进入排行榜进行好友能量检测收取
在 2 分钟后 脚本会停止当前排行榜工作 返回主页监控监控能量球
此时的能量球剩余时间小于 1 分钟

上述过程均由定时任务自动管理功能完成
手动添加任务 暂未考虑到需精确到秒级的情况

此建议不被采纳
感谢建议与支持
❤️
