### ISSUE TITLE
华为应用分身导致无法使用

### ISSUE THREAD

**Issue by FuLing996** [SuperMonster003/Auto.js_Projects#319]
**问题描述**
使用华为系统自带分身出第二个支付宝,运行时会弹出如图窗口,两个支付宝包名是一样的

**日志截图**
![Screenshot_20200521_181709_com huawei android int](https://user-images.githubusercontent.com/49016732/82549462-8c052f00-9b8f-11ea-8a92-f6efd2d0174f.jpg)

**软件硬件信息**
操作系统: 安卓9.0
设备型号: Honor9

Auto.js版本: 7.0.4-1
项目版本: v1.9.19 Beta

**其他**
代码中是在哪里打开的支付宝,我是否可以在对应的代码后增加一行点击指定坐标的代码

**Comment by wedding181** [comment]
我魅族也是同样情况，系统双开支付宝，自动打开支付宝时，需要手动选择支付宝1还是支付宝2，该如何解决（需要保留支付宝双开）

**Comment by FuLing996** [comment]
> 我魅族也是同样情况，系统双开支付宝，自动打开支付宝时，需要手动选择支付宝1还是支付宝2，该如何解决（需要保留支付宝双开）
我在Modules\MODULE_MONSTER_FUNC.js
```
_debugInfo("加载intent参数启动应用");
app.startActivity(_trig);
```
307行后面增加了一个点击事件,勉强能用了

**Comment by SuperMonster003** [comment]
将于后续版本修复此类问题 (不晚于 v1.9.22)

**Comment by SuperMonster003** [comment]
v1.9.22 已发布
且尝试解决上述问题
在运行项目后
正常情况是不弹出选择列表
直接运行主支付宝应用的 (也就是非分身应用)

若实际运行情况不符合上述预期
可继续反馈
