### ISSUE TITLE
魅族系统双开支付宝导致脚本暂停

### ISSUE THREAD

**Issue by wedding181** [SuperMonster003/Auto.js_Projects#320]
**问题描述**
魅族系统双开支付宝，自动打开支付宝时，需要手动选择支付宝1还是支付宝2，该如何解决（需要保留支付宝双开）

**日志截图**
提供与问题相关的日志截图
![S00522-09485975](https://user-images.githubusercontent.com/65743309/82623063-e515a700-9c11-11ea-8715-3dd31d216ab0.png)

**软件硬件信息**
操作系统: [ 如: 安卓8.1 ]
设备型号: [ 如: 魅族16X ]
Auto.js版本: [ 如: 4.1.1 Alpha2 ]
项目版本: [ 如: v1.9.19 ]

**其他**
能否默认打开支付宝1，或者使用//launchApp("Alipay"); launchApp("支付宝");可以打开支付宝，但修改后其他的地方错误，不会弄，希望作者大大能解决，非常感谢

**Comment by SuperMonster003** [comment]
参阅 #319

**Comment by SuperMonster003** [comment]
v1.9.22 已发布
且尝试解决上述问题
在运行项目后
正常情况是不弹出选择列表
直接运行主支付宝应用的 (也就是非分身应用)

若实际运行情况不符合上述预期
可继续反馈
