### ISSUE TITLE
点击运行之后弹出参数调整提示，接下来无论点击什么都不运行

### ISSUE THREAD

**Issue by bobcc4** [SuperMonster003/Auto.js_Projects#322]
**问题描述**
点击运行之后弹出参数调整提示，接下来无论点击什么都不运行
**日志截图**
![image](https://user-images.githubusercontent.com/29281746/82775726-1c3ac100-9e7b-11ea-8df9-1610b5e4c3f9.png)

**软件硬件信息**
操作系统: [ 如: 安卓10.0 ]
设备型号: [ 如: 三星S10+ ]
Auto.js版本: [ 如: 4.1.0 Alpha5 ]
项目版本: [ 如: v1.9.9 BETA ]

**Comment by frank142857** [comment]
软件更新到readme里面提供的4.1.1 alpha2试试。
https://github.com/SuperMonster002/Hello_Sockpuppet/raw/master/%5Bauto.js%5D%5B4.1.1_alpha2%5D%5Barm-v7%5D(b69a4e23).apk?raw=true

**Comment by bobcc4** [comment]
谢谢，已解决
