### ISSUE TITLE
Bug反馈: [ 自动解锁密码不能设置]

### ISSUE THREAD

**Issue by Santo-wiar** [SuperMonster003/Auto.js_Projects#323]
**问题描述**

自动解锁设置数字密码提示错误
 
**日志截图**

![img](https://user-images.githubusercontent.com/56570863/82819991-efff5e80-9ed3-11ea-84d9-bb00ea80c223.jpg)

**软件硬件信息**
操作系统: [ 如: 安卓10.0 ]
设备型号: [ 如: 小米8 ]
Auto.js版本: [ 如: 4.1.1 Alpha2 ]
项目版本: [ 如: 1.9.19 Beta ]

**其他**
[ 包括但不限于 建议/提案/想法/灵感... ]

**Comment by vinsonzb** [comment]
同样问题。

**Comment by jackylau0219** [comment]
同样的问题
