### ISSUE TITLE
Bug反馈: [ 能进入到森林页面，但是没有收取就退出来了 ]

### ISSUE THREAD

**Issue by drp000** [SuperMonster003/Auto.js_Projects#324]
**问题描述**
能进入到好友森林页面，但是没有收取就退出来了

**日志截图**
提供与问题相关的日志截图

**软件硬件信息**
操作系统: [ 安卓10.0 ]
设备型号: [红米k30 pro ]
Auto.js版本: [ 4.1.1 Alpha2 ]
项目版本: [ v1.9.1 ]

**其他**
[ 包括但不限于 建议/提案/想法/灵感... ]

**Comment by SuperMonster003** [comment]
参阅 https://github.com/SuperMonster003/Auto.js_Projects/issues/315
v.1.9.19 正式版将修复此问题
