### ISSUE TITLE
关于脚本后台运行的建议（基于虚拟机）-增加独立计时功能（非autoj是、）

### ISSUE THREAD

**Issue by AlbertLinstan** [SuperMonster003/Auto.js_Projects#325]
本人设备小米cc9pro，安卓9（出厂版本MIUI11）。
在手机上运行一个叫vmos的app，支持在手机运行虚拟机安卓7.1（简化版系统）。实现了成本可以在虚拟机内运行，而且可以后台甚至息屏。但是问题是auto.js不会自动获取虚拟机的时间，也就是说计划任务无法按时启动即使虚拟机正常运行。查看日志，脚本运行时所获取的时间是实时时间，也就是说可以获取系统的时间。
建议：加入独立任务控制程序（主程序）常住后台以实现任务安排和启动。

**Comment by SuperMonster003** [comment]
此功能超出个人能力范围
感谢支持与建议
