### ISSUE TITLE
如何打包apk

### ISSUE THREAD

**Issue by guyancanyun** [SuperMonster003/Auto.js_Projects#326]
auto.js中怎么打包apk呢？这么多依赖的js文件，有没有办法整个文件夹打包？

**Comment by SuperMonster003** [comment]
此项目无法实现 Auto.js 的打包操作
最初没有按照 "项目" 结构来写
因此打包后会导致项目无法运行

关于如何打包 Auto.js 的项目
可参阅官方文档 "综述" 的 "Q & A" 部分
关于如何正确部署一个项目
可参阅 Auto.js Pro 版本内的脚本商城
或参考现有的开源项目
如 Nick 的 https://github.com/Nick-Hopps/Ant-Forest-autoscript
及 Tony 的 https://github.com/TonyJiangWJ/Ant-Forest
