### ISSUE TITLE
Bug反馈: [ 进入好友森林超时 ]

### ISSUE THREAD

**Issue by frank142857** [SuperMonster003/Auto.js_Projects#327]
**问题描述**
进入好友森林后，没有正常点击能量球或帮收，卡了一会提示超时返回。

**日志截图**
![image](https://user-images.githubusercontent.com/35618259/83343179-d1baa980-a2ab-11ea-9568-78cf482223f4.png)

**软件硬件信息**
操作系统:  安卓8.1 
设备型号: htc one m8
Auto.js版本: 4.1.1 Alpha2
项目版本: v1.9.19beta

**Comment by wilfordluo** [comment]
可以试试我的解决方案

**Comment by SuperMonster003** [comment]
参阅 https://github.com/SuperMonster003/Auto.js_Projects/issues/315 及 https://github.com/SuperMonster003/Auto.js_Projects/issues/324
