### ISSUE TITLE
Bug反馈: [ 进入好友森林超时 ]

### ISSUE THREAD

**Issue by zkfopen** [SuperMonster003/Auto.js_Projects#328]
**问题描述**
进入好友森林后，在好友森林有能量球可以收取的情况下，没有正常收取能量，卡在当前界面一段时间提示超时返回；

**日志截图**

**软件硬件信息**
操作系统: [ 如: 安卓9.0 ]
设备型号: [ 如: OPPO PACM00 ]
ColorOS版本：[ 如：V6.0.1 ]
Auto.js版本: [ 如: 4.1.1 Alpha2 ]
项目版本: [ 如: v1.9.18 ]
支付宝版本: [ 如: v10.1.95 ]

**其他**
[ 在项目版本: [ 如: v1.9.19beta ]中也存在“进入好友森林超时”的问题； ]

**Comment by biosxf007** [comment]
万恶的蚂蚁森林估计又更新了，有病啊，明显是故意针对脚本吧

**Comment by wilfordluo** [comment]
可以看我的解决方案

**Comment by zkfopen** [comment]
> 可以看我的解决方案

测试有效，谢谢分享！

**Comment by zkfopen** [comment]
> 万恶的蚂蚁森林估计又更新了，有病啊，明显是故意针对脚本吧

楼下有解决方案，测试可行了！

**Comment by biosxf007** [comment]
> 可以看我的解决方案

神奇啊，四两拨千斤的感觉，牛！

**Comment by SuperMonster003** [comment]
参阅 https://github.com/SuperMonster003/Auto.js_Projects/issues/315 及 https://github.com/SuperMonster003/Auto.js_Projects/issues/324
