### ISSUE TITLE
交流研讨:关于 [ 进入好友森林超时 ]BUG的临时解决方案

### ISSUE THREAD

**Issue by wilfordluo** [SuperMonster003/Auto.js_Projects#329]
由于支付宝更新了功能，删除了部分控件，导致进入好友森林超时的bug。
可按如下方式临时解决:
修改文件Ant_Forest_Launcher.js
修改内容:$$sel.pickup(/你收取TA/);(不同版本行号不同，搜索关键词即可)
改为$$sel.pickup(/成就/);

**Comment by dacs6** [comment]
测试有效，谢谢分享！

**Comment by zkfopen** [comment]
测试有效，谢谢分享！

**Comment by WICKJOHNE** [comment]
补充一下，是修改内容1393行：$$ sel.pickup（/你收取TA /）;   
 改为$$ sel.pickup（/成就/）;

**Comment by xiawang12xia** [comment]
1

> 补充一下，是修改内容1393行：$$ sel.pickup（/你收取TA /）;
> 改为$$ sel.pickup（/成就/）;

亲测可用，1433找不到，1393找的到。谢谢

**Comment by ggyy8850** [comment]
不行勒，改了错误 启动不了

**Comment by WICKJOHNE** [comment]
> 不行勒，改了错误 启动不了

我的是1.9.19 beta版本的脚本

**Comment by zkfopen** [comment]
> > 不行勒，改了错误 启动不了
> 
> 我的是1.9.19 beta版本的脚本

我的是1.9.18，亲测可行。

**Comment by wilfordluo** [comment]
> 补充一下，是修改内容1393行：$$ sel.pickup（/你收取TA /）;
> 改为$$ sel.pickup（/成就/）;
可能不同版本行号不一样。

**Comment by wilfordluo** [comment]
> 补充一下，是修改内容1393行：$$ sel.pickup（/你收取TA /）;
> 改为$$ sel.pickup（/成就/）;

可能不同版本行号也不一样。

**Comment by WICKJOHNE** [comment]
可以试着搜索关键词：你收取TA

**Comment by WICKJOHNE** [comment]
> 不行勒，改了错误 启动不了

可以去官网下载4.1.1alpha2的auto.js软件版本https://github.com/SuperMonster002/Hello_Sockpuppet/raw/master/%5Bauto.js%5D%5B4.1.1_alpha2%5D%5Barm-v7%5D(b69a4e23).apk?raw=true

**Comment by crb8331** [comment]
我的是1.9.18，在第1435行，亲测可行。

**Comment by zjfyly** [comment]
19.19亲测可用，建议使用电脑改，直接改容易报错

**Comment by HenryCeChen** [comment]
同样是1.9.18，亲测可行，感恩

**Comment by HenryCeChen** [comment]
看最近的数据感觉用脚本收能量会比别人收得少...是错觉吗...大家有没有同样的感觉...

**Comment by fflzh** [comment]
亲测有用，感谢
最好用电脑改，直接改Auto程序在编辑页面总是崩溃，改完后运行也报错

**Comment by imfokho** [comment]
有效  谢过楼主

**Comment by i23456** [comment]
亲测有效。我的是1.9.19 beta版本，在1393行修改。谢谢楼主！

**Comment by Santo-wiar** [comment]
有效，感谢，开始用autojs自带的修改 一直没用，后来用别的 就ok

**Comment by frank142857** [comment]
谢谢

**Comment by dotama** [comment]
谢谢!

**Comment by vinsonzb** [comment]
感谢分享

**Comment by Sq-List** [comment]
感谢。

**Comment by Reid00** [comment]
感谢楼主，牛啤，可以了。

**Comment by bearcai** [comment]
谢谢分享

**Comment by heshangcode** [comment]
昨天改了还可以使用，今天一使用，能点进好友森林，但是不收取，然后跳到下一个好友，也不收取，一直这样，不知道其他人是这样不

**Comment by xiaoheiyn** [comment]
哪位大佬修改好了能运行的打包发个链接，我改了一直不行。。

**Comment by ggyy8850** [comment]
不能用auto.js里面的编辑更改，这样会出错。需要用其他文本编辑工具编辑，才能使用。大家注意

**Comment by yuluu** [comment]
蚂蚁森林又改回来了，想不到吧，哈哈哈哈

**Comment by yuluu** [comment]
支付宝纯恶心人

**Comment by heshangcode** [comment]
> 蚂蚁森林又改回来了，想不到吧，哈哈哈哈

今天又不行了，不管是按照楼主的改法，还是原来的都不行了

**Comment by wilfordluo** [comment]
> > 蚂蚁森林又改回来了，想不到吧，哈哈哈哈
> 
> 今天又不行了，不管是按照楼主的改法，还是原来的都不行了

我的一直稳定运行呀，你是不是改错了。

**Comment by wilfordluo** [comment]
> 蚂蚁森林又改回来了，想不到吧，哈哈哈哈

支付宝翻脸真快

**Comment by imfokho** [comment]
> 蚂蚁森林又改回来了，想不到吧，哈哈哈哈
我是1435行的，改了之后现在也是能用的。

**Comment by SuperMonster003** [comment]
感谢提供方案

大概两天的时间 PK面板控件消失
导致项目判断进入好友森林页面的唯一条件 `/你收取TA/ ` 无法触发
上述方案将判断条件修改为页面中已有的存在描述文本的控件
可解决进入森林后判断失败的问题

PK面板上包含本周内 收取/帮收的统计量
在点击能量球后 收取/帮收统计量会增加
脚本通过增量进行收取量统计 且可以区分收取与帮收

同时脚本使用页面下方的动态列表进行另一方案的统计计量
两种方案同时执行 优先选择计算速度快的计算值作为最终统计值

新版本取消了与PK面板的全部关联
判断条件关联到标题与动态列表上
统计计量方案也放弃了PK面板方案:
- 当统计量达到"千克"级别时 无法统计"克"计量值
- 此方案曾经失效过长达 48 小时 已不具可靠性
- 动态列表方案已足够胜任统计计量工作

再次感谢提供方案
❤️
