### ISSUE TITLE
SimpleActionAutoMator 异常

### ISSUE THREAD

**Issue by 842141872** [SuperMonster003/Auto.js_Projects#33]
程序自动打开排行榜以后，便无反应 然后弹出SimpleActionAutoMator 异常

**Comment by 842141872** [comment]
图片

**Comment by 842141872** [comment]
file:///D:/842141872/MobileFile/Screenshot_20190520_123129_org.autojs.autojs.jpg

**Comment by 842141872** [comment]
具体就是上滑屏幕操作以后提示滑动功能失效，然后脚本无法继续，接下来 弹出SimpleActionAutoMator 异常

**Comment by SuperMonster003** [comment]
收到反馈  
22日会尝试修复此问题

**Comment by 842141872** [comment]
问题找到了，是我用的fooview软件的原因，好像不能同时监听屏幕，我用fooview 写了个定时脚本，关掉fooview问题就解决了，
