### ISSUE TITLE
Bug反馈: 没有悬浮窗权限

### ISSUE THREAD

**Issue by m9rco** [SuperMonster003/Auto.js_Projects#330]
**问题描述**
autoJS 是有悬浮窗权限的，但是提示没有悬浮窗权限

**日志截图**
![image](https://user-images.githubusercontent.com/18391791/83388273-bf15b100-a420-11ea-9f34-43c026ba7762.png)

**软件硬件信息**
操作系统: 安装10
设备型号: 小米9
Auto.js版本: Pro 8.0.0-5
项目版本: latest

**其他**
[ 包括但不限于 建议/提案/想法/灵感... ]

**Comment by bearcai** [comment]
请问这个问题怎么解决的？研究了一天了。小米4x
