### ISSUE TITLE
Bug反馈: [ 输入密码界面密码重复点击一个数字]

### ISSUE THREAD

**Issue by iloveyou616** [SuperMonster003/Auto.js_Projects#331]
**问题描述**
6位数字密码，输入密码界面重复点击第一个，但没点进密码内，属于轻触的无效点击。

**日志截图**
提供与问题相关的日志截图
[https://imgchr.com/i/tYL4TP
https://imgchr.com/i/tYLhwt](url)

**软件硬件信息**
操作系统: [ 如: 安卓9.0 ]
设备型号: [ 如: vivo x21 ]
Auto.js版本: [ 如: Version Pro 8.0.0-5 ]
项目版本: [ 如: v1.9.8和v1.9.9 ]

**其他**
[ 辛苦了 ]

**Comment by iloveyou616** [comment]
> **问题描述**
> 6位数字密码，输入密码界面重复点击第一个，但没点进密码内，属于轻触的无效点击。
> 
> **日志截图**
> 提供与问题相关的日志截图
[https://imgchr.com/i/tYL4TP
https://imgchr.com/i/tYLhwt](url)

> 
> **软件硬件信息**
> 操作系统: [ 如: 安卓9.0 ]
> 设备型号: [ 如: vivo x21 ]
> Auto.js版本: [ 如: Version Pro 8.0.0-5 ]
> 项目版本: [ 如: v1.9.8和v1.9.9 ]
> 
> **其他**
> [ 辛苦了 ]

**Comment by SuperMonster003** [comment]
参阅 https://github.com/SuperMonster003/Auto.js_Projects/issues/105

**Comment by iloveyou616** [comment]
> 参阅 #105

看#105帖子后恢复项目1.1.8-1.1.3 ，1.3也试过也不行， [依然会出现轻触只点击一个数字密码现象， 布局信息如下https://www.lanzoux.com/iIRbdde0a0h  目前1.1.8-9版本未设置屏幕解锁，可自动运行。但是手机出门随身携带，安全起见必须有密码，但是有密码运行脚本锁屏就解锁不了。帮看下，谢谢了

**Comment by SuperMonster003** [comment]
提供的解锁布局信息无效
在手动划开提示层之后 需要进入输入密码的页面 (九宫格/PIN码/数字密码/键盘密码等)
而不是划开后直接解锁 (这种情况很可能是开启了面容解锁/On-Body探测/基于位置或设备的智能解锁等)

需重新反馈包含密码输入页面的布局信息

**Comment by iloveyou616** [comment]
> 提供的解锁布局信息无效
> 在手动划开提示层之后 需要进入输入密码的页面 (九宫格/PIN码/数字密码/键盘密码等)
> 而不是划开后直接解锁 (这种情况很可能是开启了面容解锁/On-Body探测/基于位置或设备的智能解锁等)
> 
> 需重新反馈包含密码输入页面的布局信息

前两天有事搁置了，没来反映。按提示操作，手动熄屏后会自动亮屏，滑动屏幕到输入密码界面，之后就不动了，直到2分钟屏幕保护熄屏也没有震动，解锁后震动了，然后抓取页面，这个页面不是要求的页面。所以，卡在这了。怎么解决呀

**Comment by iloveyou616** [comment]
> 参阅 [#135 (comment)](https://github.com/SuperMonster003/Auto.js_Projects/issues/135#issuecomment-555879039)
> 使用 Inspect_Specified_Screen_Layout.js 工具抓取布局信息

[输入密码前 https://imgchr.com/i/tbJZqO
输入密码界面 https://imgchr.com/i/tbJ8QP](url)

**Comment by iloveyou616** [comment]
> 参阅 [#135 (comment)](https://github.com/SuperMonster003/Auto.js_Projects/issues/135#issuecomment-555879039)
> 使用 Inspect_Specified_Screen_Layout.js 工具抓取布局信息

输入密码前 [https://imgchr.com/i/tbJZqO](url)
输入密码界面 [https://imgchr.com/i/tbJ8QP](url)

**Comment by SuperMonster003** [comment]
[MODULE_UNLOCK.zip](https://github.com/SuperMonster003/Auto.js_Projects/files/4768921/MODULE_UNLOCK.zip)
尝试替换本地项目 Modules 目录下的同名文件

**Comment by iloveyou616** [comment]
> [MODULE_UNLOCK.zip](https://github.com/SuperMonster003/Auto.js_Projects/files/4768921/MODULE_UNLOCK.zip)
> 尝试替换本地项目 Modules 目录下的同名文件

重复输入一个数字这个问题解决了，辛苦了。谢谢

**Comment by iloveyou616** [comment]
> [MODULE_UNLOCK.zip](https://github.com/SuperMonster003/Auto.js_Projects/files/4768921/MODULE_UNLOCK.zip)
> 尝试替换本地项目 Modules 目录下的同名文件

重复输入一个数字这个问题解决了，现在可自动解锁了。麻烦了，谢谢。
