### ISSUE TITLE
交流研讨: [ 好友多了收益少了 ]

### ISSUE THREAD

**Issue by biosxf007** [SuperMonster003/Auto.js_Projects#332]
如题，我就纳闷了，支付宝加好友其实挺不容易的，结果能量的收益反而不如从前了，我甚至怀疑蚂蚁森林后台会根据你的情况修改能量球的偷取范围概率，晕啊

**Comment by yuluu** [comment]
加那么多好友没用的，你冲着偷别人能量去的，别人也抱着一样的目的才加你，大多数人的你都偷不到的，还增加了刷新下滑的时间，没必要。

**Comment by youaaaaa** [comment]
一天有个500-1000的能量
不就很香了吗

**Comment by iloveyou616** [comment]
> 一天有个500-1000的能量
> 不就很香了吗

那么问题来了，你们周围为什么那么多用支付宝的，我这边大多数都是微信，好友也没多，我羡慕了

**Comment by biosxf007** [comment]
> 一天有个500-1000的能量
> 不就很香了吗

还真不够香，呵呵，蚂蚁森林开通好多年了，但是一直没玩，直到遇见这个强大的脚本，我瞬间有了激情，现在我总能量才150kg,排前三的都快一吨了，我每天平均才1500g左右收益，你算算我得多少年才能赶上去，哈哈哈

**Comment by heshangcode** [comment]
一直好奇，你们的今天还可以收取吗？我今天的状况就是点进去好友森林，不收取，然后继续下一个了

**Comment by zwjdujin** [comment]
六七百好友，每天平均5kg，感觉没去年前年多，以前经常100g+，今年好像没遇到过。

**Comment by biosxf007** [comment]
> 六七百好友，每天平均5kg，感觉没去年前年多，以前经常100g+，今年好像没遇到过。

这么多好友怎么加的，牛叉！

**Comment by SuperMonster003** [comment]
项目主要是想通过解放用户双手 充分将节省下来的时间分配到更想做的事情上

**Comment by zwjdujin** [comment]
> > 六七百好友，每天平均5kg，感觉没去年前年多，以前经常100g +，今年好像没遇到过。
> 
> 这么多好友怎么加的，牛叉！

让他们自己加我
