### ISSUE TITLE
手机上滑才能进入密码界面

### ISSUE THREAD

**Issue by xy3217991** [SuperMonster003/Auto.js_Projects#333]
**问题描述**
小米6  miui12 手机上滑才能进入密码界面解锁，需要人工上滑，无法自动解锁

**日志截图**
提供与问题相关的日志截图

**软件硬件信息**
操作系统: [ miui12]
设备型号: [ 小米6 ]
Auto.js版本: [ 4.1.1 Alpha2 ]

**其他**
[ 建议蚂蚁森林的自动解锁加个上滑直接进入密码界面的功能]

**Comment by youaaaaa** [comment]
这本来就有啊

**Comment by xy3217991** [comment]
> 这本来就有啊

不好意思，我看到了，因为之前上滑需要七八秒才能进到密码界面，我以为没这个功能，所以每次都手动上滑了，谢谢

**Comment by SuperMonster003** [comment]
如果相关功能在使用最新版后依然出现问题
可重新开 Issue 反馈
此 Issue 暂时关闭
