### ISSUE TITLE
Bug反馈: [ 设置菜单中的收取/帮收黑名单运行后无反应 ]

### ISSUE THREAD

**Issue by dacs6** [SuperMonster003/Auto.js_Projects#334]
**问题描述**
 设置菜单-->黑名单管理-->收取/帮收黑名单-->无论是从列表中选择还是检索选择，刷新后打开一次支付宝，退出到Home界面，显示正在采集好友列表数据，然后再也没有反应了。
日志中显示的错误：Cannot call method "childCount" of null.

**日志截图**
https://sm.ms/image/XhmoK3VND5fUzSE

**软件硬件信息**
操作系统: [ 安卓10.0 ]
设备型号: [ 一加7Pro ]
Auto.js版本: [ 4.1.1 Alpha2 ]
项目版本: [ v1.9.19beta 和 v1.9.18 ]

**Comment by SuperMonster003** [comment]
列表滑动时 因没有同步配置工具中的参数
导致滑动起点过低 触发了设备的 `HOME键`
v1.9.19 正式版将修复上述问题

**Comment by dacs6** [comment]
太强大了，完美解决，列表选择和检索选择都可以使用了，赞！
