### ISSUE TITLE
Bug反馈: 小米九宫格解锁不成功 (REF #281)

### ISSUE THREAD

**Issue by SuperMonster003** [SuperMonster003/Auto.js_Projects#335]
你们小米九宫格可以解锁成功吗. 我很简单的 笔画一直解锁不成功 458963 就这么简单的.

_Originally posted by @tvrcfdfe in https://github.com/SuperMonster003/Auto.js_Projects/issues/281#issuecomment-631215985_

**Comment by SuperMonster003** [comment]
@tvrcfdfe 尝试在配置工具中更改 `图案解锁滑动策略` 为 `连续路径`

**Comment by tvrcfdfe** [comment]
我看了设置 一直是连续路径

**Comment by SuperMonster003** [comment]
@tvrcfdfe 详细描述现象
提供类似 '只能从 4 点滑动到 3 点' 的描述
另外脚本会使用增量方式尝试不同的滑动时间
如果首次滑动失败 可等待脚本自动尝试
尝试过程中图案路径可能会发生变化
最终绘制出正确的路径

使用以下代码可在解锁结束后查看过程中的日志
```js
require("./Modules/MODULE_UNLOCK").unlock(true);
```
如有必要 请反馈相关日志截图

**Comment by h7ml** [comment]
小米10青春版解锁失败，密码147852

**Comment by SuperMonster003** [comment]
@h7ml 
提供详细的解锁过程描述
参阅 https://github.com/SuperMonster003/Auto.js_Projects/issues/335#issuecomment-639193584

**Comment by tvrcfdfe** [comment]
![Screenshot_2020-06-12-14-06-03-025_org autojs aut](https://user-images.githubusercontent.com/12228316/84470786-a32ecc80-acb6-11ea-90eb-b1140280eac1.png)

**Comment by tvrcfdfe** [comment]
![Screenshot_2020-06-12-14-05-22-438_com miui secur](https://user-images.githubusercontent.com/12228316/84471617-4b916080-acb8-11ea-8908-05a702a394e2.jpg)

**Comment by SuperMonster003** [comment]
@tvrcfdfe 提示层滑动时长太长了 10多秒
改成默认值然后让脚本自动滑动几次 直到成功划开提示层

建议将图案解锁的滑动时长也设置成默认值
当到达图案解锁页面时 依然让脚本自己尝试不同的时间绘制图案
策略依然使用连续路径

**Comment by tvrcfdfe** [comment]
修改不了, 一修改就报错,
![1](https://user-images.githubusercontent.com/12228316/84473094-07538f80-acbb-11ea-9bc0-704970f3c09c.png)

**Comment by SuperMonster003** [comment]
@tvrcfdfe 确保项目为最新版本 (v1.9.20)

**Comment by tvrcfdfe** [comment]
我刚更新了最新的, 设置了九宫格密.其他设置都没动, 再观察几天看看情况,感谢!!!
