### ISSUE TITLE
自动解锁不了

### ISSUE THREAD

**Issue by Permanent-Fu** [SuperMonster003/Auto.js_Projects#336]
在配置项目里设置锁屏密码提示以下错误
08:46:08.539/E: ReferenceError: "diag" is not defined. (/storage/emulated/0/脚本/Auto.js_Projects-Ant_Forest/Ant_Forest_Settings.js#6374)
ReferenceError: "diag" is not defined.
    at /storage/emulated/0/脚本/Auto.js_Projects-Ant_Forest/Ant_Forest_Settings.js:6374:0
    at file:///android_asset/modules/__bridges__.js:10:0
请问大佬怎么解决这个错误？好久没用了，然后手机刷机之后就没用了

**Comment by SuperMonster003** [comment]
参阅 https://github.com/SuperMonster003/Auto.js_Projects/issues/323

**Comment by Permanent-Fu** [comment]
> 参阅 #323

改成d，提示以下错误
00:00:10.424/E: syntax error (/storage/emulated/0/脚本/Auto.js_Projects-Ant_Forest/Ant_Forest_Settings.js#8748)
syntax error

**Comment by SuperMonster003** [comment]
v1.9.19 正式版已发布
尝试后若问题依然存在 可继续反馈

**Comment by Permanent-Fu** [comment]
> v1.9.19 正式版已发布
> 尝试后若问题依然存在 可继续反馈

这个自动解锁好像可以了（设置里可以设置锁屏密码）但是能不能解开就不知道了，没有看到过解锁界面，但是执行launch后到支付宝界面不会自己往下滑了

**Comment by Permanent-Fu** [comment]
刚刚时间计划任务执行出现以下错误代码
10:16:30.309/E: TypeError: Cannot call method "forEach" of undefined (/storage/emulated/0/脚本/Auto.js_Projects-1.9.19/Auto.js_Projects-1.9.19/Ant_Forest_Launcher.js#3084)
TypeError: Cannot call method "forEach" of undefined
    at /storage/emulated/0/脚本/Auto.js_Projects-1.9.19/Auto.js_Projects-1.9.19/Ant_Forest_Launcher.js:3084:0
    at /storage/emulated/0/脚本/Auto.js_Projects-1.9.19/Auto.js_Projects-1.9.19/Ant_Forest_Launcher.js:3103:0
    at /storage/emulated/0/脚本/Auto.js_Projects-1.9.19/Auto.js_Projects-1.9.19/Ant_Forest_Launcher.js:3021:0
    at file:///android_asset/modules/__bridges__.js:10:0

**Comment by SuperMonster003** [comment]
推迟运行时间的键值映射错误
已在新的 Release 版本修复上述问题
可在配置工具中 使用服务器还原功能 选择 v1.9.19 覆盖更新

**Comment by Permanent-Fu** [comment]
> 推迟运行时间的键值映射错误
> 已在新的 Release 版本修复上述问题
> 可在配置工具中 使用服务器还原功能 选择 v1.9.19 覆盖更新

好的，我试试

**Comment by Permanent-Fu** [comment]
还是不行，不会自动滑

**Comment by SuperMonster003** [comment]
> 
> 
> 刚刚时间计划任务执行出现以下错误代码
> 10:16:30.309/E: TypeError: Cannot call method "forEach" of undefined (/storage/emulated/0/脚本/Auto.js_Projects-1.9.19/Auto.js_Projects-1.9.19/Ant_Forest_Launcher.js#3084)
> TypeError: Cannot call method "forEach" of undefined
> at /storage/emulated/0/脚本/Auto.js_Projects-1.9.19/Auto.js_Projects-1.9.19/Ant_Forest_Launcher.js:3084:0
> at /storage/emulated/0/脚本/Auto.js_Projects-1.9.19/Auto.js_Projects-1.9.19/Ant_Forest_Launcher.js:3103:0
> at /storage/emulated/0/脚本/Auto.js_Projects-1.9.19/Auto.js_Projects-1.9.19/Ant_Forest_Launcher.js:3021:0
> at file:///android_asset/modules/**bridges**.js:10:0

新的 Release 版本修复的是上述问题

如果有新的问题 请反馈详细的出错情况
如错误出现的页面位置 (蚂蚁森林首页还是排行榜等)
脚本的行为 (直接停止还是不断重复某个行为等)
错误日志 (如果有的话)

以便确定并排查问题

**Comment by Permanent-Fu** [comment]
> > 刚刚时间计划任务执行出现以下错误代码
> > 10:16:30.309/E: TypeError: Cannot call method "forEach" of undefined (/storage/emulated/0/脚本/Auto.js_Projects-1.9.19/Auto.js_Projects-1.9.19/Ant_Forest_Launcher.js#3084)
> > TypeError: Cannot call method "forEach" of undefined
> > at /storage/emulated/0/脚本/Auto.js_Projects-1.9.19/Auto.js_Projects-1.9.19/Ant_Forest_Launcher.js:3084:0
> > at /storage/emulated/0/脚本/Auto.js_Projects-1.9.19/Auto.js_Projects-1.9.19/Ant_Forest_Launcher.js:3103:0
> > at /storage/emulated/0/脚本/Auto.js_Projects-1.9.19/Auto.js_Projects-1.9.19/Ant_Forest_Launcher.js:3021:0
> > at file:///android_asset/modules/**bridges**.js:10:0
> 
> 新的 Release 版本修复的是上述问题
> 
> 如果有新的问题 请反馈详细的出错情况
> 如错误出现的页面位置 (蚂蚁森林首页还是排行榜等)
> 脚本的行为 (直接停止还是不断重复某个行为等)
> 错误日志 (如果有的话)
> 
> 以便确定并排查问题

我按了你的覆盖更新，现在执行就定在蚂蚁森林首页，不会动了

**Comment by SuperMonster003** [comment]
v1.9.21 已发布
测试后如果依然有问题 可继续反馈
