### ISSUE TITLE
参数调整提示无法跳过

### ISSUE THREAD

**Issue by FenghuJi** [SuperMonster003/Auto.js_Projects#337]
**问题描述**
点击启动脚本出现`参数调整提示`，点击`跳过`和`现在配置`均没有反应，过段时间后`提示等待参数调整对话框操作超时` 

**日志截图**
提供与问题相关的日志截图
![image](https://user-images.githubusercontent.com/37890568/83829673-fbddf280-a715-11ea-993c-0fc73f4dfdf8.png)

**软件硬件信息**
操作系统: [MIUI 11.0.3 ]
设备型号: [ 红米Note 8 Pro ]
Auto.js版本: [ 4.1.0 Alpha5 ]
项目版本: [ v1.9.18 ]

**其他**
无

**Comment by lishu97** [comment]
红米note7也有这个问题

**Comment by SuperMonster003** [comment]
参阅 https://github.com/SuperMonster003/Auto.js_Projects/issues/322

**Comment by FenghuJi** [comment]
新版本`v1.9.18`不再有这个问题，多谢作者。
