### ISSUE TITLE
Bug反馈: [ 好友选择界面Out of Region ]

### ISSUE THREAD

**Issue by linmeon** [SuperMonster003/Auto.js_Projects#338]
**问题描述**
好友选择界面Out of Region
**日志截图**
![ffe066b4ffe3c002ec3619e13c08f91](https://user-images.githubusercontent.com/19300213/83849095-7a9c5500-a741-11ea-9417-0aaf0eff1153.jpg)

**软件硬件信息**
操作系统: [ 安卓10]
设备型号: [ 小米mix3 ]
Auto.js版本: [  4.1.1 Alpha2 ]
项目版本: [ 1.9.19 Beta ]

**其他**
1.修改内容:$$sel.pickup(/你收取TA/);(不同版本行号不同，搜索关键词即可)
改为$$sel.pickup(/成就/);

2.注释了代码
function _addBalls() {
_balls.forEach((o) => {
// if (_isOrangeBall(o)) {
// return _addBall(o, "orange");
// }
把 _isOrangeBall 这几行代码注释了

**Comment by SuperMonster003** [comment]
参阅 https://github.com/SuperMonster003/Auto.js_Projects/issues/321#issuecomment-639314457
