### ISSUE TITLE
Bug反馈: 跳转好友列表时报错

### ISSUE THREAD

**Issue by OCDcreator** [SuperMonster003/Auto.js_Projects#339]
**问题描述**
跳转好友列表时报错TypeError:无法调用null的方法“toString”

**日志截图**
![Screenshot_20200606_064048_org autojs autojs](https://user-images.githubusercontent.com/62931432/83928242-9d6e4e00-a7c1-11ea-9973-d52e0bc53cc1.jpg)

**软件硬件信息**
操作系统: [ emui10.0 ]
设备型号: [ honor10 ]
Auto.js版本: [ 4.1.1 Alpha2 ]
项目版本: [ v1.9.19 ]

**Comment by SuperMonster003** [comment]
启动跳板的启动条件类型异常
已在新的 Release 版本修复上述问题
可在配置工具中 使用服务器还原功能 选择 `v1.9.19` 覆盖更新
