### ISSUE TITLE
Bug反馈: 排行榜上滑一次后提前退出 (Edited)

### ISSUE THREAD

**Issue by dwan0819** [SuperMonster003/Auto.js_Projects#340]
**问题描述**
每次收取好友时仅仅能够上滑一次，到第19名时即退出，且退出提示每次都不一样；日志正常。

**日志截图**
![微信图片_20200606093541](https://user-images.githubusercontent.com/57361769/83933233-673cc880-a7d9-11ea-92a1-c616ed5e7ae8.jpg)
![微信图片_20200606093546](https://user-images.githubusercontent.com/57361769/83933234-67d55f00-a7d9-11ea-9def-25f3b9a534ff.jpg)
![微信图片_20200606093549](https://user-images.githubusercontent.com/57361769/83933235-686df580-a7d9-11ea-9644-b830a3d271cb.jpg)
![微信图片_20200606093553](https://user-images.githubusercontent.com/57361769/83933239-69068c00-a7d9-11ea-9018-e225c958631c.jpg)
![微信图片_20200606093556](https://user-images.githubusercontent.com/57361769/83933240-699f2280-a7d9-11ea-9c68-8c1eed39c66a.jpg)

**软件硬件信息**
操作系统: [ MIUI 11.1.2 稳定版]
设备型号: [ 小米CC9 Pro ]
Auto.js版本: [  4.1.1 Alpha2 ]
项目版本: [ v1.9.18-19 ]

**Comment by SuperMonster003** [comment]
在配置工具中的消息提示功能下 开启开发者测试模式
看一下提前结束的触发条件 (比如可能是错误匹配到了邀请按钮的绿色)
然后提供一下与上述问题有关的日志截图

另外最后的悬浮窗仅仅是收取量的提示
0 表示本次没有收取到能量
上面的一串字符
结合了JS语言编程语法以及一些英文谚语
也只是为了增加趣味性

**Comment by dwan0819** [comment]
> 在配置工具中的消息提示功能下 开启开发者测试模式
> 看一下提前结束的触发条件 (比如可能是错误匹配到了邀请按钮的绿色)
> 然后提供一下与上述问题有关的日志截图
> 
> 另外最后的悬浮窗仅仅是收取量的提示
> 0 表示本次没有收取到能量
> 上面的一串字符
> 结合了JS语言编程语法以及一些英文谚语
> 也只是为了增加趣味性

![微信图片_20200606121818](https://user-images.githubusercontent.com/57361769/83935826-e5a46500-a7ef-11ea-9910-3781d8490b12.png)
打开了开发者测试模式，不知是否可以呢？

**Comment by SuperMonster003** [comment]
配置工具
-> 收取功能
-> 排行榜样本采集
-> 列表底部控件图片模板

按照对话框内容提示 点击"查看模板"后看一下模板是否异常
正常应该是包含"没有更多"文字的一张图片

如果有异常 可尝试点击"删除模板" 然后重新运行项目
运行后如果上述问题复现
将删除模板后的这次项目的运行日志反馈一下

**Comment by dwan0819** [comment]
> 配置工具
> -> 收取功能
> -> 排行榜样本采集
> -> 列表底部控件图片模板
> 
> 按照对话框内容提示 点击"查看模板"后看一下模板是否异常
> 正常应该是包含"没有更多"文字的一张图片
> 
> 如果有异常 可尝试点击"删除模板" 然后重新运行项目
> 运行后如果上述问题复现
> 将删除模板后的这次项目的运行日志反馈一下
太棒啦！之前的模板是空白的，删除后重新运行，自动生成了新的模板！！！感谢大神！！！
