### ISSUE TITLE
Bug反馈: [ 19版新Bug ]

### ISSUE THREAD

**Issue by biosxf007** [SuperMonster003/Auto.js_Projects#341]
**问题描述**
        历经几个版本的改良，  伤不起的主页能量自收功能，十次当中大概就会有一两次出现问题，检测完主页的几个未成熟能量球然后就卡住了，无法跳转进行好友列表检测。
**日志截图**
![Screenshot_20200606_154640_org autojs autojs](https://user-images.githubusercontent.com/61198035/83939361-d90e1580-a7cb-11ea-86cb-5d0ac9207e1d.jpg)
![Screenshot_20200606_154710_org autojs autojs](https://user-images.githubusercontent.com/61198035/83939366-e0cdba00-a7cb-11ea-9768-ab11d486010d.jpg)
![Screenshot_20200606_154748_org autojs autojs](https://user-images.githubusercontent.com/61198035/83939367-e1fee700-a7cb-11ea-883a-2088216f7b47.jpg)

**Comment by SuperMonster003** [comment]
浇水回赠能量球误检测后 脚本将陷入无限循环
此问题将在下一版本解决
