### ISSUE TITLE
Bug反馈: 启动配置工具后报错 (Edited)

### ISSUE THREAD

**Issue by yangyueyang** [SuperMonster003/Auto.js_Projects#342]
![Screenshot_2020-06-06-16-49-59-377_org autojs autojs](https://user-images.githubusercontent.com/34149474/83940282-0ed7ec00-a816-11ea-9798-3cf406b68ef0.jpg)
启动配置文件报错

**Comment by SuperMonster003** [comment]
使用配置工具还原服务器最新版本
