### ISSUE TITLE
Bug反馈: 返检监控功能异常 (Edited)

### ISSUE THREAD

**Issue by biosxf007** [SuperMonster003/Auto.js_Projects#343]
虽然入坑也就几个月，但对这个脚本以及作者真的是佩服有加，辛苦的付出，强大的功能，点一万个赞。唯一让我纠结的就是这个返检监控的功能，几个版本下来还是无法正常运作，十次估计能有个一次启动吧，唉…我每天早上都有296的步数能量要收，返检不启动要么我被别人狠狠偷一把，要么只能闹钟提前强行停止脚本。刷别人的能量不容易，这边损失就更大了，心塞…每次版本更新我都会重点观察这个功能，可惜还是不能如愿，感觉其他功能都挺正常的，就是每天早上我的296马上就到点了，可脚本还在狂刷好友列表。也许这是个难点吧，但还是希望作者能重点解决一下…

**Comment by yuluu** [comment]
你在自己能量成熟前一分钟设置个定时任务，然后把排他性任务最大排队时间设置成一分钟，开启自收功能中的循环检测就好了。

**Comment by SuperMonster003** [comment]
返检的前提是拿到主页能量球的最小剩余时间
按照默认值  如果大于 2  则进入排行榜检查好友
当依然处于排行榜页面且计算主页剩余时间等于 1 分钟时
脚本会返回主页进行监控

但依然要保证上述前提
你要重点看的是日志中关于主页最小倒计时的消息
是否是 OCR 识别不准确
或者是能量球定位/类型不准确

然后有针对性地反馈并简述问题

**Comment by biosxf007** [comment]
> 返检的前提是拿到主页能量球的最小剩余时间
> 按照默认值 如果大于 2 则进入排行榜检查好友
> 当依然处于排行榜页面且计算主页剩余时间等于 1 分钟时
> 脚本会返回主页进行监控
> 
> 但依然要保证上述前提
> 你要重点看的是日志中关于主页最小倒计时的消息
> 是否是 OCR 识别不准确
> 或者是能量球定位/类型不准确
> 
> 然后有针对性地反馈并简述问题

老大说到了问题的点子上了，经过这两天的调试我也发现了这个原因，有时候最小倒计时会取数失败，但还有个明显的bug，如果有两个未成熟能量球，看日志你还会发现最小倒计时取数居然是时间更长的那个，如此，第一个永远没机会被循环监测或者返检监控，这个问题我在之前的版本就反馈过的

**Comment by biosxf007** [comment]
> 你在自己能量成熟前一分钟设置个定时任务，然后把排他性任务最大排队时间设置成一分钟，开启自收功能中的循环检测就好了。

非常感谢提供的解决思路，但是如果有两个未成熟的能量球就会发生最小倒计时取数bug，这样循环监测还是无法启动

**Comment by SuperMonster003** [comment]
日志中看出主页能量球倒计时获取  用的是 OCR  识别率会受到影响
下一版将加入 OCR 识别过程的数据日志 (仍需开启开发者测试模式才能看到)
包括原始数据和加工数据
脚本统计最小倒计时 以加工后的数据为准
很可能与肉眼所见的能量球最小倒计时不一致
因为上述识别率很难得到保证

另外最小倒计时出现多组时 项目使用的是封装的 Math.mini 方法
可通过以下简单的代码测试检查上述方法的功能性是否异常
```js
require("./Modules/EXT_GLOBAL_OBJ").load();
console.log(Math.mini([69, 39, 93])); // 39: the minimum of nums
```
