### ISSUE TITLE
Bug反馈: 新版本主页能量球漏收现象

### ISSUE THREAD

**Issue by yuluu** [SuperMonster003/Auto.js_Projects#344]
**问题描述**
当能量球在最左边的时候，能检测到但无法收取。下图的能量球本来在最左边的，收取完其他能量球就跑中间去了。版本：1.9.19正式版

**日志截图**
![微信图片_20200607113017](https://user-images.githubusercontent.com/30486446/83959674-70e62f00-a8b2-11ea-8193-8d8ebcfbff0b.jpg)
![微信图片_20200607113021](https://user-images.githubusercontent.com/30486446/83959675-72175c00-a8b2-11ea-9f1e-403e233e6f9e.jpg)

**Comment by dandan8271** [comment]
一样的问题

**Comment by SuperMonster003** [comment]
没有看明白问题的描述

日志中说有发现了 3 个能量球
是说这 3 个都是绿色成熟球而脚本只发现了 2 个吗

另外能量球的位置在主页页面不切换的情况下
别的能量球点击收取后 是说它会发生移动吗

**Comment by yuluu** [comment]
> 没有看明白问题的描述
> 
> 日志中说有发现了 3 个能量球
> 是说这 3 个都是绿色成熟球而脚本只发现了 2 个吗
> 
> 另外能量球的位置在主页页面不切换的情况下
> 别的能量球点击收取后 是说它会发生移动吗

对的，三个成熟的能量球。靠最左边的那个没有收取。

**Comment by SuperMonster003** [comment]
明白了
是偶发的还是经常性的

另外在好友森林是否出现过最左边不点击或其他漏收的情况

**Comment by yuluu** [comment]
> 明白了 是偶发的还是经常性的 另外在好友森林是否出现过最左边不点击或其他漏收的情况
> […](#)
> On June 8, 2020 14:53:48 yuluu ***@***.***> wrote: 没有看明白问题的描述 日志中说有发现了 3 个能量球 是说这 3 个都是绿色成熟球而脚本只发现了 2 个吗另外能量球的位置在主页页面不切换的情况下 别的能量球点击收取后 是说它会发生移动吗对的，三个成熟的能量球。靠最左边的那个没有收取。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

好友森林没这种问题。第一次更新到19正式版就有这种问题，然后我就退回19beta版本了。

**Comment by yuluu** [comment]
> > 明白了 是偶发的还是经常性的 另外在好友森林是否出现过最左边不点击或其他漏收的情况
> > […](#)
> > On June 8, 2020 14:53:48 yuluu _**@**_.***> wrote: 没有看明白问题的描述 日志中说有发现了 3 个能量球 是说这 3 个都是绿色成熟球而脚本只发现了 2 个吗另外能量球的位置在主页页面不切换的情况下 别的能量球点击收取后 是说它会发生移动吗对的，三个成熟的能量球。靠最左边的那个没有收取。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> 好友森林没这种问题。第一次更新到19正式版就有这种问题，然后我就退回19beta版本了。

我特意试了三次都有这种问题才退回的。
