### ISSUE TITLE
Bug反馈: [ 进入好友列表时报错，Cannot call method "toString" ]

### ISSUE THREAD

**Issue by luchangharry** [SuperMonster003/Auto.js_Projects#345]
**问题描述**
在检测过主页能量球后，进入好友列表时出错

**日志截图**
![image](https://user-images.githubusercontent.com/50188136/83986068-16aaa400-a96e-11ea-82fa-8a4af8b1fc55.png)

**软件硬件信息**
操作系统: [ 如: 安卓10.0 ]
设备型号: [ 如: 华为mate30 pro ]
Auto.js版本: [ 如: 4.1.1 Alpha2 ]
项目版本: [ 如: v1.9.19]

**其他**
[ 包括但不限于 建议/提案/想法/灵感... ]

**Comment by SuperMonster003** [comment]
参阅 https://github.com/SuperMonster003/Auto.js_Projects/issues/339
