### ISSUE TITLE
Bug反馈: [ 自己能量球漏收及误报现象 ]

### ISSUE THREAD

**Issue by dacs6** [SuperMonster003/Auto.js_Projects#349]
**问题描述**
仍旧存在主页中自己能量球漏收的现象，但并不是每次都会这样，没有发现规律。
日志中显示找到自己未成熟能量球2个，但随后点击自己成熟能量球1个，然后就结束森林主页页面监测线程。
接着日志显示，找到自己未成熟能量球5个，而此时页面上只剩1个即将成熟的能量球。

**日志截图**
![2020-06-11_085810](https://user-images.githubusercontent.com/54759066/84333271-df343580-abc1-11ea-8035-3d2be0fc745c.png)
![2020-06-11_090057](https://user-images.githubusercontent.com/54759066/84333388-389c6480-abc2-11ea-8738-772b3ceafdc7.png)

**软件硬件信息**
操作系统: [ 安卓10.0 ]
设备型号: [ 一加7Pro ]
Auto.js版本: [ 4.1.1 Alpha2 ]
项目版本: [ v1.9.20 ]

**Comment by SuperMonster003** [comment]
可使用项目 Tools 目录下的 Energy_Balls_Recognition.js 工具测试主页能量球识别情况 查看是否出现遗漏的情况

另外当前版本存在将主页漂浮云朵的边缘识别为能量球的误判问题 导致能量球识别收到较大的干扰 将在下一版通过样本颜色分量均值的标准差筛选得到修复

**Comment by dacs6** [comment]
截取了一组图，不知道是不是白框内的都认为是可收取的能量呢？白云边缘确实有白框，但两个能量球之间的空白处也有白框，还有左上角的领挂件边缘。
![Screenshot_20200611-164047](https://user-images.githubusercontent.com/54759066/84364833-2f7fb780-ac03-11ea-9fff-477a2744a006.jpg)
![Screenshot_20200611-164053](https://user-images.githubusercontent.com/54759066/84364856-36a6c580-ac03-11ea-9570-8d02ca6ab0b3.jpg)
![Screenshot_20200611-164112](https://user-images.githubusercontent.com/54759066/84364870-3c9ca680-ac03-11ea-93bd-0ae63ee0e3a6.jpg)
![Screenshot_20200611-164116](https://user-images.githubusercontent.com/54759066/84364882-41f9f100-ac03-11ea-8fff-80a45b606ebb.jpg)
![Screenshot_20200611-164123](https://user-images.githubusercontent.com/54759066/84364902-47573b80-ac03-11ea-85af-c307265c5676.jpg)
![Screenshot_20200611-164128](https://user-images.githubusercontent.com/54759066/84364942-5b02a200-ac03-11ea-8af0-a6d5124dd5b4.jpg)
![Screenshot_20200611-164134](https://user-images.githubusercontent.com/54759066/84364983-6950be00-ac03-11ea-95fb-d6c1ce665496.jpg)

**Comment by SuperMonster003** [comment]
被方框标识的区域即为脚本识别为能量球的区域
绿色为成熟能量球
橙色/金色及白色分别对应帮收/浇水回赠及不可操作的能量球

能量球之间出现的识别区域 是脚本通过线性插值计算出来的能量球
除了线性插值 还有镜像对称
用以保证出现识别遗漏时 脚本会通过上述方案模拟出可能遗漏的能量球

容易出现的问题就是多出很多原本不存在的"假能量球"
下一版将通过样本颜色分量均值的标准差筛选排除云朵的干扰 (前 Comments 已提及)
并通过一些图像的参数调整改善主页能量球的识别准确性

**Comment by dacs6** [comment]
Energy_Balls_Recognition.js 工具测试不再检测到白云了，经过几天的观察也未发现自己能量球漏收现象。
这个工具能获得作者这么多迭代不断完善，实在太感谢了！
