### ISSUE TITLE
脚本运行出现错误

### ISSUE THREAD

**Issue by 17839170745** [SuperMonster003/Auto.js_Projects#35]
这种情况怎么回事
![Screenshot_2019-05-22-08-40-15-724_org autojs aut](https://user-images.githubusercontent.com/49069371/58139658-540e9780-7c6e-11e9-84fb-8b69b12391e6.png)

**Comment by SuperMonster003** [comment]
`clickAction()` 报错已于 `v1.6.24 Alpha2` - `2019/05/22` 修复  
另外所有Modules文件夹下的模块是不能单独运行的 模块的作用是被require 说白了就是保证共性用和可维护性

**Comment by SuperMonster003** [comment]
以上问题目前已修复 此Issue暂时关闭
