### ISSUE TITLE
Bug反馈: 执行完之后显示0

### ISSUE THREAD

**Issue by Permanent-Fu** [SuperMonster003/Auto.js_Projects#351]
**问题描述**
执行脚本之后，划着划着突然就停住了，不动了，然后我关了重新执行一次，执行结束后通知结果显示0，相关日志截图在下

**日志截图**
![Screenshot_20200612-211136](https://user-images.githubusercontent.com/55046509/84506085-5fa58400-acf1-11ea-8205-2f898560fa3e.jpg)

**软件硬件信息**
操作系统: Android 10（10.0.6稳定版）
设备型号: 一加七Pro（未root）
Auto.js版本: 4.1.1 Alpha2 
项目版本: v1.9.20

**其他**
[ 包括但不限于 建议/提案/想法/灵感... ]

**Comment by Permanent-Fu** [comment]
日志很长，图没截完

**Comment by SuperMonster003** [comment]
此问题我暂时无法解决
