### ISSUE TITLE
交流研讨: [ auto.js截屏权限，为啥每次都弹 ]

### ISSUE THREAD

**Issue by bingyang519** [SuperMonster003/Auto.js_Projects#352]
_**请教问题，非代码bug**_

这个截屏权限申请，每次都弹，不是说有个【总是允许】的隐藏选项吗？ 点了很多次，都没找到

之前Android 9 没问题，  现在Android 10  不行了吗？

请教大佬，如何处理这个问题的。

![33](https://attach.52pojie.cn/forum/202006/13/172105zzd0xttcwz5d9wz8.jpg)

**Comment by SuperMonster003** [comment]
"隐藏" 的复选框是部分小米机型的 MIUI 系统才有的
截图中的权限申请对话框没有复选框可勾选
因此需要每次都点击 "立即开始" 按钮

**Comment by bingyang519** [comment]
好的，谢谢。
