### ISSUE TITLE
Bug反馈：好友森林页能量球无法正确识别点击

### ISSUE THREAD

**Issue by yangyueyang** [SuperMonster003/Auto.js_Projects#353]
**问题描述**
好友排行榜页面点击进入好友森林页面后无法检测出待收取的能量球，会自动再返回列表

**日志截图**
![c9aa4ffc5860310d315795bc096e24a](https://user-images.githubusercontent.com/34149474/84584417-ac46a780-ae36-11ea-9e34-6670758d4700.jpg)

**软件硬件信息**
操作系统: MIUI12安卓10
设备型号: 小米8
Auto.js版本:  4.1.1 Alpha2
项目版本: v1.9.20

**Comment by SuperMonster003** [comment]
是所有的好友都不收取直接返回吗
今晚会发布 v1.9.21
可以尝试新版看问题是否复现
