### ISSUE TITLE
功能建议:使用EasyClick进行开发类似的软件

### ISSUE THREAD

**Issue by yimudi003** [SuperMonster003/Auto.js_Projects#354]
Auto.js 已经不更新了，是否可以使用EasyClick开发一个类似的软件. 
https://easyclick.gitee.io/docs/index.html

**Comment by bingyang519** [comment]
我大概看了下

这个不是开源的吧？

还要收费？

**Comment by yimudi003** [comment]
试用了，免费的

**Comment by bingyang519** [comment]
好的，看了看，没发现他是什么时候开始研发的，稳定性怎样？
而且，他还不是开源的，安全性更不知道？
你试用了，感觉怎么样，能满足一般需求吗？

**Comment by yimudi003** [comment]
> 好的，看了看，没发现他是什么时候开始研发的，稳定性怎样？
> 而且，他还不是开源的，安全性更不知道？
> 你试用了，感觉怎么样，能满足一般需求吗？

节点稳定性很强。
一般需求都能满足

**Comment by SuperMonster003** [comment]
> 节点稳定性很强。
> 一般需求都能满足

上述描述是怎样得出来的
如果有具体的数据就更好了

Auto.js 已停止更新
但停止更新不代表功能退化和变异
当然有 ECMA 标准无法跟进以及 Rhino 引擎本身的性能瓶颈
等等不足
但依然不影响多数功能的使用甚至扩展

在没有看到其他软件的突出优势之前
项目是不会考虑转移宿主环境的
否则将会对非常多的原有 API 进行重新适配
而且不一定所有的功能都能在新的宿主环境得以实现
即便能实现 项目的重构将会是非常大的工程量

鉴于上述原因
建议将不被采纳
感谢反馈
