### ISSUE TITLE
Bug反馈: [运行结果总是0  ]

### ISSUE THREAD

**Issue by biosxf007** [SuperMonster003/Auto.js_Projects#355]
如题，你们难道都能正常显示吗，这个影响倒没什么，所以我一直也没在意，时间长了今天终于感觉受不了了，呵呵

**Comment by WICKJOHNE** [comment]
我也同样遇到了类似的问题，虽然重启手机有时候能解决，但是也是暂时的，试过好几次有时候还是不行。希望能够解决。
