### ISSUE TITLE
关于auto.js 8.0.0.5pro版本完美运行求教

### ISSUE THREAD

**Issue by AlbertLinstan** [SuperMonster003/Auto.js_Projects#357]
据说auto.js 8 pro版本不可以在主流app上执行点击操作，源码看不明白，麻烦作者讲解一下如何实现的？仅运行一次（auto.js 8 pro版本 MIUI11）最后结果显示收入0 实际是300+。

**Comment by SuperMonster003** [comment]
Pro 8 的源码有开源吗
是通过反编译查看的吗

具体的实现我不清楚
但应该不是检测当前 Activity 的包名那样简单

统计结果异常将于 v1.9.21 版本修复
