### ISSUE TITLE
建议涉及具体时间长短采用随机值？

### ISSUE THREAD

**Issue by tagaga** [SuperMonster003/Auto.js_Projects#358]
[ 包括但不限于 项目功能改进/功能添加/代码优化/执行逻辑优化... ]

现在脚本被官方反制比较严重，建议涉及到“等待时间”的操作，建议不要使用固定时间，采用随机时间的方式比较好，比如收取能量界面，等待1秒，能否在这个时间的基础上再增加几点几秒的随机时间，不如1-3秒的随机事件，比如1.3秒，这样官方反制起来难度也比较大。20这个版本，每次自动采集，只能采集几个用户的能量就自动停下来不动了，只能重启机器。

**Comment by SuperMonster003** [comment]
不知道 "脚本被官方反制" 的论述来源
脚本如果真要 "反制"
对于 Alipay 是易如反掌
Alipay 最想看到的 是用户数量及用户活跃度
而脚本的存在对于上述数据的影响不言自明

因此建议中的 "采用随机时间" 就不具意义了
而且项目中的所有延迟
都坚持 "必须有具体意义" 的原则
很多都会写明此处加入延迟的原因
1 秒对于用户来讲 停顿感受是异常明显的
有时敏感的用户对于多出 300ms 都能有所察觉

20 版本会自动停止
很可能是因为图像采集频繁导致 Auto.js 崩溃
希望下次出现异常提供详细的日志截图

综上
上述建议将不被采纳
感谢反馈
