### ISSUE TITLE
退出失败

### ISSUE THREAD

**Issue by ljx0623** [SuperMonster003/Auto.js_Projects#36]
【支付宝版本】：10.1.62
【Auto.js版本】：4.1.1 Alpha2
【脚本版本】：v1.6.24 Alpha
【系统版本】：MIUI 10.2 稳定版
脚本运行至MODULE_MONSTER_FUNC.js第1090行
`if (typeof arr[0] !== "number" || typeof arr[1] !== "number")`
报错“clickAction()坐标参数非number”
此时arr[0]和arr[1]的值为：
`arr[0]:idMatches(".*nav.back|.*back.button"),
arr[1]:descMatches("关闭|返回")`

**Comment by SuperMonster003** [comment]
感谢细心解析 此问题已修复

**Comment by ljx0623** [comment]
应该我们这些伸手党要感谢作者一直以来的贡献才对~
另外发现一些小问题，就是能量统计有点问题
收取单个好友能量后，日志有时不会打印收取了多少，但是最后的统计会打印正确的总量；
帮收好友能量后，日志打印“无能量球可操作”，最后的统计也没有，但实际上是有的

**Comment by SuperMonster003** [comment]
这个问题是代码重构之前就有的问题  
另一个 [`IssueComment`](https://github.com/SuperMonster003/Auto.js_Projects/issues/26#issuecomment-494632196) 已经有人反馈了 我会尽快解决  
😃

**Comment by SuperMonster003** [comment]
此问题目前已修复 此Issue暂时关闭
