### ISSUE TITLE
小米10 pro不能自动解锁

### ISSUE THREAD

**Issue by gongchensu** [SuperMonster003/Auto.js_Projects#360]
**问题描述**
小米10 Pro不能自动解锁屏幕，在页面提示层就错误。

**日志截图**
日志说消除解锁页面提示层失败，往前翻日志，明明我是小米手机，给我匹配的是EMUI解锁提示层控件

**软件硬件信息**
操作系统: [ 如: 安卓10.0 ]
设备型号: [ 如: 小米10 pro]
Auto.js版本: [ 如: 4.1.1 Alpha2 ]
项目版本: [ 如: v1.9.20 ]

**其他**
解锁的逻辑我感觉太复杂了，可不可以简化一点啊，很早之前的版本我记得解锁我还能直接替换掉unlock函数，用我自己写的简单的，因为每次我小米手机都不能解锁，替换用找到的能用的代码很方便，现在好复杂啊，自己想解决都没得办法。

**Comment by SuperMonster003** [comment]
参阅 Issues 板块之前相关的 Issue
如 https://github.com/SuperMonster003/Auto.js_Projects/issues/139

我没能从描述中获取解锁失败的原因
是无法划开提示层还是密码无法输入
或是其他现象

项目根据用户的反馈及早期 e大 的开源模块
收集了不同设备的控件匹配样本
这些样本用来判断设备当前位于的页面位置
例如匹配到了某个机型样本的提示层规则
就认为当前在提示层页面 立即进行上滑动作
因为匹配规则 华为在小米前面
当检测华为规则时 你的设备正好匹配到了
因此日志显示了华为 但不影响脚本发出上滑动作

网络上有流传的小米解锁代码
但作为一个项目
应尽量避免特殊性
也不能满足于仅仅当前设备可用
当前设备可用后
换了型号 换了厂商 换了分辨率
功能都不受影响
这才是项目本身应有的优势

很多 IDE 支持将代码全部收起的功能
解锁模块收起之后
很容易看到解锁的关键代码
```js
while (!_isUnlk() && !_lmtRch()) {
    $_unlk.prev_cntr.handle();
    $_unlk.unlk_view.handle();
}
```
