### ISSUE TITLE
魅族16自动解锁失败

### ISSUE THREAD

**Issue by wdl5i** [SuperMonster003/Auto.js_Projects#361]
**问题描述**
魅族16消除解锁页面提示层失败

**日志截图**
![S00623-08133415](https://user-images.githubusercontent.com/16251374/85422040-b6d80e00-b5a7-11ea-9eb6-f07e6af4ca4f.png)

**软件硬件信息**
操作系统: [ 安卓8.1 ]
设备型号: [ 魅族16]
Auto.js版本: [ 4.1.1 Alpha2 ]
项目版本: [ v1.9.20 ]

**其他**
已经反复设置过解锁密码，重试了几次，仍然解锁不成功，报的错误也是一样的，上图中说的保存截图地址也去找过了，没有相应的文件夹和文件，用过作者提供的Tools去抓取Lock_Screen_Layout，相应的!Debug_info文件夹也找不到

**Comment by SuperMonster003** [comment]
`内部存储` 对应 `/storage/emulated/0`

在 `内部存储` 中
有些设备会有一个 `storage` 文件夹
这个 `storage` 其实是 `/storage/emulated/0/storage`

也可以安装一款非系统自带的文件管理器
比如 ES浏览器/RE浏览器/MT管理器/FX 等
使用管理器定位 `内部存储` (即 `/storage/emulated/0`)
里面会看到 `!Debug_Info` 文件夹
