### ISSUE TITLE
功能建议: [ 提高生产效率 ]

### ISSUE THREAD

**Issue by serfend** [SuperMonster003/Auto.js_Projects#362]
[ 包括但不限于 项目功能改进/功能添加/代码优化/执行逻辑优化... ]
因为通常情况下，能量值高的往往是活跃用户，需要尽可能敏捷的去提高收取他们能量的优先级。

- 基础：可以考虑设置一个阈值，例如发现列表已经低于100kg，则停止此轮下滑刷新。

- 高级：分段收取，当某一能量段已无可收取能量时，才扩大下一次轮询的搜查范围。

**Comment by SuperMonster003** [comment]
上述功能的实现
将依赖于排行榜控件识别每个好友的收取量
项目的目标是尽最大努力避免使用控件识别
不仅因为曾经有段时间排行榜不能识别好友昵称和倒计时
更因为图像识别可以使项目保持更好的适应性

建议提到生产效率
当前能想到的提高生产效率较便捷的方法
是删除掉那些长期收取量很小甚至为0的好友
这样的好友变少反而会提升效率
另外统计功能已经实现了收取量的统计和查询

综上
建议将不被采纳
感谢反馈
