### ISSUE TITLE
Bug反馈: Pro 7.0.4-1版本无法运行 (Edited)

### ISSUE THREAD

**Issue by hj5418** [SuperMonster003/Auto.js_Projects#363]
[ 关于项目的疑惑顾虑/心得体会/经验分享等 ]
Pro 7.0.4-1 都是报错
13:37:16.556/E: ReferenceError: "messageAction" is not defined. (/storage/emulated/0/脚本/Auto.js_Projects-1.9.20/Auto.js_Projects-1.9.20/Ant_Forest_Launcher.js#28)
ReferenceError: "messageAction" is not defined.
    at checkAlipayPackage (/storage/emulated/0/脚本/Auto.js_Projects-1.9.20/Auto.js_Projects-1.9.20/Ant_Forest_Launcher.js:28:0)
    at /storage/emulated/0/脚本/Auto.js_Projects-1.9.20/Auto.js_Projects-1.9.20/Ant_Forest_Launcher.js:15:0
    at /storage/emulated/0/脚本/Auto.js_Projects-1.9.20/Auto.js_Projects-1.9.20/Ant_Forest_Launcher.js:7314:0

4.1.1 Alpha2 可以正常运行

**Comment by xsgteamx** [comment]
同报错

**Comment by SuperMonster003** [comment]
@xsgteamx 
是 v1.9.21 版本吗

**Comment by xsgteamx** [comment]
> @xsgteamx
> 是 v1.9.21 版本吗

是V1.9.20版本，新版修改了这个错误吗？

**Comment by xsgteamx** [comment]
> @xsgteamx
> 是 v1.9.21 版本吗
不好意思没有看到，我先用21试试看，稍后反馈给您

**Comment by xsgteamx** [comment]
> @xsgteamx
> 是 v1.9.21 版本吗

您好，setting 报错
Auto.js pro 错误 Error：Module “” not found.(file:///android_asset/modules/jvm-npm.js#96
是我的PRO版本问题还是因为还是不兼容呀
同是4.1.1 Alpha2 可以正常运行
v20和v21在PRO上都会报错

**Comment by SuperMonster003** [comment]
@xsgteamx 
请提供详细的日志报错截图
以便定位并排查问题

**Comment by hj5418** [comment]
auto.js  Pro 7.0.4-1  1.9.20版
程序和配置文件都报错。
![111111111111](https://user-images.githubusercontent.com/67365319/85939767-aed2f200-b94a-11ea-8780-3e95cab6c658.jpg)
![222222222](https://user-images.githubusercontent.com/67365319/85939770-b2ff0f80-b94a-11ea-9d1f-c6ce107ed415.jpg)

auto.js  Pro 7.0.4-1  1.9.22版
程序提示没有安装支付宝
配置文件报错。
![33333](https://user-images.githubusercontent.com/67365319/85939877-767fe380-b94b-11ea-851f-7ca220d43d0b.jpg)

4.1.1 Alpha2 都可以正常运行

**Comment by SuperMonster003** [comment]
@xsgteamx @hj5418 
用的是官方版本吗
如果是修改版或破解版 可能会无法正常使用项目
此项目是基于官方版本开发的
