### ISSUE TITLE
Bug反馈:[ 定时循环无反应，只能手动启动 ]

### ISSUE THREAD

**Issue by OCDcreator** [SuperMonster003/Auto.js_Projects#364]
**问题描述**
启动程序后，60分钟后不会自动启动

**日志截图**
![Screenshot_20200625_101733](https://user-images.githubusercontent.com/62931432/85646029-c782a400-b6cd-11ea-91f3-761de2ece4cd.jpg)

**软件硬件信息**
操作系统: [ 如: emui10.0 ]
设备型号: [ 如: 荣耀 10]
Auto.js版本: [ 如: 4.1.1 Alpha2 ]
项目版本: [ 如: v1.9.21 ]

**Comment by SuperMonster003** [comment]
定时任务需要在项目中开启定时循环功能
通过自动管理机制或在控制面板手动添加才能实现定时运行
在定时任务控制面板页面可查看当前项目所有的定时任务
另外在息屏状态下 Auto.js 的运行可能收到节点机制的限制 导致运行出现延迟
具体可参阅 Issues 板块中的相关问题贴

**Comment by OCDcreator** [comment]
定时任务自动管理是开启的，设置与版本1.9.20相同，但是上个版本是正常的

**Comment by SuperMonster003** [comment]
首先还是要查看定时任务管理面板页面
自动设置的定时任务是否正确出现在列表中

然后可以尝试保持其他变量完全相同
依次更改一个 (仅一个) 变量来排查问题

全部可能的变量:
1. 项目版本 (1.9.20 / 1.9.21)
2. 屏幕状态 (屏幕亮起 / 屏幕关闭)
3. 息屏时间 (息屏 1 分钟 / 息屏 2 小时)
4. 定时任务下次运行时间 (1分钟 / 2小时)

例如想排查是否是项目版本 (序号 1) 的问题
需保持每次测试时 1 不同  但 2 3 4 相同

**Comment by OCDcreator** [comment]
修改自动定时的管理面板选项时报错
![Screenshot_20200625_120544_org autojs autojs](https://user-images.githubusercontent.com/62931432/85652122-64e4d480-b6dc-11ea-8722-fe013390ec1d.jpg)

**Comment by OCDcreator** [comment]
定时任务控制面板缺少最小倒计时的任务类型

**Comment by biosxf007** [comment]
好友还打马赛克，难道都是名人不成，呵呵

**Comment by OCDcreator** [comment]
你没有任何权利决定我的做法，无论你是否理解，不经过他人同意，暴露别人的名字是错误的。不管是否有名。

**Comment by SuperMonster003** [comment]
https://github.com/SuperMonster003/Auto.js_Projects/issues/364#issuecomment-649203097
这个"修改自动定时的管理面板选项时报错"是 v1.9.21 的问题
将在下一版修复
但报错应该是出现在延时接力区间管理页面而不是定时任务自动管理页面

定时任务控制面板里面
展示的是当前在任务队列中排队等待执行的所有任务
通常自动管理的任务只有一个
下一版将加上任务类型的顺延标志
如:
最小倒计时 (顺延)
表示被顺延的最小倒计时自动管理任务

最终还是无法确定你的定时任务无法自动启动的原因
可以尝试手动运行一下脚本
然后点击推迟运行 1 分钟
不要关闭设备
看 1 分钟后是否能自动运行
或手动添加一个定时任务
看到指定时间后能否自动运行

**Comment by SuperMonster003** [comment]
> 
> 
> 好友还打马赛克，难道都是名人不成，呵呵

@biosxf007 
做好个人信息或敏感信息的加密/隐藏/保护
是每个人应该具备的最基本安全意识

对于支付宝这样的社交类软件
则不仅涉及到自己的信息
还有其他人的账户信息

所以将这些人的头像/昵称等信息做好保护
不仅是对自己的负责 也是对其他人的负责

**Comment by OCDcreator** [comment]
是的，我没有表达清楚。
正常情况下，任务运行结束后应该是这样子的
![Screenshot_20200625_191051_org autojs autojs](https://user-images.githubusercontent.com/62931432/85709817-35ec5400-b718-11ea-9d7b-b05d2159ce3b.jpg)
但是1.19.21版任务结束后是这样子的
![Screenshot_20200625_191255_org autojs autojs](https://user-images.githubusercontent.com/62931432/85709904-4c92ab00-b718-11ea-9c0b-e1a87cbe98c2.jpg)
我认为这是定时任务不能启动的原因，推迟一分钟和手动添加定时任务都可以正常运行。

**Comment by SuperMonster003** [comment]
@OCDcreator 
我刚使用 Auto.js 4.1.1 alpha2 测试了一下
没能复现上述自动定时任务的问题

建议将配置文件改名备份
这相当于项目完全初始化
此时运行项目
所有的配置都要重新设置
设置之后看问题是否复现

注:
配置文件共计 2 项
`af.nfe` 和 `af_cfg.nfe`
位于 `/storage/emulated/0/.local/` 目录下

另外今晚会发布 v1.9.22
也可以等待新版发布后
尝试新版看问题是否复现

**Comment by biosxf007** [comment]
> > 好友还打马赛克，难道都是名人不成，呵呵
> 
> @biosxf007
> 做好个人信息或敏感信息的加密/隐藏/保护
> 是每个人应该具备的最基本安全意识
> 
> 对于支付宝这样的社交类软件
> 则不仅涉及到自己的信息
> 还有其他人的账户信息
> 
> 所以将这些人的头像/昵称等信息做好保护
> 不仅是对自己的负责 也是对其他人的负责

老大说得有道理，可能我这个人比较随性吧，为了刷能量我会主动加一些不是特别熟的人，没考虑什么隐私啊账户安全之类的，呵呵
