### ISSUE TITLE
功能建议: [有没有兴趣做一个红包浇水功能？]

### ISSUE THREAD

**Issue by 2220209876** [SuperMonster003/Auto.js_Projects#365]
[ 包括但不限于 项目功能改进/功能添加/代码优化/执行逻辑优化... ]
看到有红包标志自动浇水

**Comment by SuperMonster003** [comment]
对于新上线的功能暂时没有研究
而且项目对于浇水相关的功能比较敏感

如果发现此功能影响原有项目的功能/逻辑
则会做相关调整保证原有功能的正常或尽最大努力降低影响

此建议暂时标记为"无法完成"
并保留 Open 状态 14 天

**Comment by ljaist** [comment]
或者可以做成运行结束后有红包时给个提醒的功能也行
