### ISSUE TITLE
Bug反馈: [ 1.9.21新问题，定时循环功能错乱]

### ISSUE THREAD

**Issue by biosxf007** [SuperMonster003/Auto.js_Projects#366]
定时循环时间到了启动，如果有事我会选择推迟多少分钟，正常情况下定时任务会修改成你要推迟后的时间，现在的bug会新增一条定时任务，然后下次再推迟的话还是会增加，然后你会发现很多同一时间的定时任务
![Screenshot_20200626_103543_org autojs autojs](https://user-images.githubusercontent.com/61198035/85814643-ecbaf500-b755-11ea-931a-464e93da556d.jpg)

**Comment by SuperMonster003** [comment]
配置工具
检查更新
