### ISSUE TITLE
wrapped cvexception

### ISSUE THREAD

**Issue by yarboo** [SuperMonster003/Auto.js_Projects#368]
9.20版本突然出现错误，升级到9.22也是同样错误
org.opencv.core.CvException:
![QQ截图20200626210217](https://user-images.githubusercontent.com/66729804/85859813-5982cd80-b7f0-11ea-9d5f-359b6dc8030a.png)

**Comment by SuperMonster003** [comment]
检查排行榜列表底部模板是否异常
如果发现异常则尝试删除模板
然后重新运行项目

配置工具 -> 收取功能 -> 排行榜样本采集 -> 列表底部控件图片模板

**Comment by yarboo** [comment]
删除后重新运行，成功运行，非常感谢
日志里还有些错误，不知什么原因
![QQ图片20200626222324](https://user-images.githubusercontent.com/66729804/85867668-cea7d000-b7fb-11ea-8c49-92223745d1d2.jpg)
![QQ图片20200626222319](https://user-images.githubusercontent.com/66729804/85867695-d8c9ce80-b7fb-11ea-801c-3e68b71aa4af.jpg)
