### ISSUE TITLE
这个怎么回事

### ISSUE THREAD

**Issue by 17839170745** [SuperMonster003/Auto.js_Projects#37]
![image](https://user-images.githubusercontent.com/49069371/58146898-c1c8bc80-7c8a-11e9-96d1-bedf048ae738.png)

**Comment by SuperMonster003** [comment]
`脚本` 目录下的文件夹 `Auto.js_Projects-Ant_Forest ` 名字后面有个空格 去掉试一下

**Comment by 17839170745** [comment]
额嗯，好了，谢谢了
