### ISSUE TITLE
Bug反馈: [ 好友排行榜打开异常 ]

### ISSUE THREAD

**Issue by biosxf007** [SuperMonster003/Auto.js_Projects#370]
这个问题之前的版本也都有出现，一波排行榜刷完后无法正常重新打开排行榜，于是脚本在非好友排行榜页面不断执行下滑操作，有时候一小会后脚本能自动重新打开好友排行榜，但有时候就在这非法页面死循环了，就拿今天7点到7点半这一时间段来说就出现了三次这样的异常，这个频率还是有点高的，在这个寸秒寸能量的时间段，一旦卡死了今天的能量就凉凉了…

**Comment by biosxf007** [comment]
老大去哪了，好久没更新了

**Comment by biosxf007** [comment]
@SuperMonster003    老大，这个问题解决了，基本就完美了，虽然现在大家都难，蚂蚁森林改了规则，收到的能量很少，但我还是喜欢用这个脚本🙂

**Comment by SuperMonster003** [comment]
排行榜到底部后 脚本会模拟一次返回键 然后重新跳转到排行榜
期间是哪里出的问题 另外非好友排行榜页面指的是支付宝首页还是好友森林
另外提供一下开发者测试模式的完整日志截图
