### ISSUE TITLE
交流研讨: [ 大家有没感觉最近能量刷得越来越少了]

### ISSUE THREAD

**Issue by biosxf007** [SuperMonster003/Auto.js_Projects#371]
无耻的蚂蚁森林开发团队，连续观察好几天了，能量的收取额度被大概率限制了，一个200+的能量一口啃下去才几克甚至一克，吐血！而且大部分都是这样，这还能叫随机吗？为此我还去客服投诉了，结果他们是一口咬定就是随机的，当我们傻啊，明显的后台动了手脚！各位刷友每天都投入了不少精力，脚本作者更是无数的付出完善这个项目，结果庄家出老千，一万只草泥马送给蚂蚁森林项目组…

**Comment by iloveyou616** [comment]
这个没办法，程序是他们的，随机归随机，还是有40-60g之间的，只是概率大小问题罢了。

**Comment by biosxf007** [comment]
> 这个没办法，程序是他们的，随机归随机，还是有40-60g之间的，只是概率大小问题罢了。

现在很小的概率才能有40-60g，直接导致我每天的总收益比以前少了好几百啊，这个还是我好友数增加的前提下，不是一般的黑，无耻之极啊

**Comment by ljaist** [comment]
一个球被收取的总数是球本身的一半，比如一个200G的球，最多被好友取走100G.最多可以被几个人收取呢，以前是6个。最近好像改规则了，可以被更多好友收取，差别在这。

**Comment by biosxf007** [comment]
> 一个球被收取的总数是球本身的一半，比如一个200G的球，最多被好友取走100G.最多可以被几个人收取呢，以前是6个。最近好像改规则了，可以被更多好友收取，差别在这。

谢谢这位朋友的回复，这两天我也有点感觉是这么回事，总之现在刷得不开心啊，都没动力再去加好友了，每天的收成实在差太多了，哎…

**Comment by SuperMonster003** [comment]
特殊时期 产生能量减少 可收取量也会受影响
