### ISSUE TITLE
Bug反馈: 运行过程中跳转无障碍服务页面 自动解锁功能异常 (Edited)

### ISSUE THREAD

**Issue by Xiaoyihanfeng** [SuperMonster003/Auto.js_Projects#372]
**问题描述**
运行一段时间会显示错误跳转到无障碍服务页面，自动解锁功能图案解锁算法应该有误，只会连接第一个阵点和最后一个，或是有时候无法唤醒屏幕，不知道怎么拉取日志，没有截图

**日志截图**
无

**软件硬件信息**
操作系统: [ MIUI12 ]
设备型号: [ 红米note8  ]
Auto.js版本: [  4.1.1 Alpha2 ]
项目版本: [ 如: v1.9.21 ]

**Comment by SuperMonster003** [comment]
> 日志在 Auto.js 首页右上角点击日志图标可查看

> 无法唤醒可检查 Auto.js 是否被节电设置等限制了后台运行

> 图案解锁断线可尝试在配置工具中修改参数:
> Ant_Forest_Settings.js -> 自动解锁 -> 滑动策略 -> 连续路径
