### ISSUE TITLE
交流研讨: 日志错误wrapped exception

### ISSUE THREAD

**Issue by yarboo** [SuperMonster003/Auto.js_Projects#375]
运行日志中有很多错误，影响了运行结果的检查
![85867668-cea7d000-b7fb-11ea-8c49-92223745d1d2](https://user-images.githubusercontent.com/66729804/85973639-02eedc80-ba06-11ea-911a-4d209377c439.jpg)
![85867695-d8c9ce80-b7fb-11ea-801c-3e68b71aa4af](https://user-images.githubusercontent.com/66729804/85973761-6973fa80-ba06-11ea-839b-04ad7cee848a.jpg)

**Comment by SuperMonster003** [comment]
https://github.com/SuperMonster003/Auto.js_Projects/issues/351
