### ISSUE TITLE
Vivo iQOO pro 5G 解锁失败

### ISSUE THREAD

**Issue by tijmuzxy** [SuperMonster003/Auto.js_Projects#376]
**问题描述**
设备唤起失败，后台已加锁，高耗电已打开，谢谢大佬！

**日志截图**
![5401593668475_ pic](https://user-images.githubusercontent.com/62529919/86320724-0f736f00-bc6a-11ea-875b-f01f3f5bb08d.jpg)

**软件硬件信息**
操作系统: [ 如: 安卓10.0 ]
设备型号: [ 如: Vivo iQOO pro 5G ]
Auto.js版本: [ 如: 4.1.1 Alpha2 ]
项目版本: [ 如: v1.9.22 ]

**Comment by lezee** [comment]
vivo nex3 也不行

**Comment by ayuanet** [comment]
小米9，升级miui12后也结算一直失败，具体没看，没有升级MIUI12之前没有问题

**Comment by SuperMonster003** [comment]
参阅 https://github.com/SuperMonster003/Auto.js_Projects/issues/134
