### ISSUE TITLE
Bug反馈: [ 好友列表只滚动一次就退出 ]

### ISSUE THREAD

**Issue by leestars** [SuperMonster003/Auto.js_Projects#378]
**问题描述**
好友列表只滚动一次就退出，再次进入也是只滚动一次。开始使用是正常的，近两天出现的问题。各位有遇到吗？

**日志截图**
提供与问题相关的日志截图

**软件硬件信息**
操作系统: android 9.0
设备型号: Samsung SM-G9500
Auto.js版本: 4.1.1 Alpha2
项目版本: v1.9.1

**其他**
[ 包括但不限于 建议/提案/想法/灵感... ]

**Comment by leestars** [comment]
#377 已解决

**Comment by JiaSong1997** [comment]
我也出现这种问题了,请问怎么解决?
