### ISSUE TITLE
Bug反馈: [ 魅族16th运行触发通话事件 ]

### ISSUE THREAD

**Issue by a1103688841** [SuperMonster003/Auto.js_Projects#379]
**问题描述**
魅族16th运行会触发通话事件，然后就停止了

**日志截图**
提供与问题相关的日志截图
![S00713-20443468](https://user-images.githubusercontent.com/44131404/87306958-666f2300-c54b-11ea-93b4-098458bc819a.png)

**软件硬件信息**
操作系统: [ 如: 安卓8.1.0 ]
设备型号: [ 如: 魅族16th plus]
Auto.js版本: [ 如: 4.1.1 Alpha2 ]
项目版本: [ 如: v1.9.22 ]

**其他**
[ 包括但不限于 建议/提案/想法/灵感... ]

**Comment by bekice** [comment]
![QQ截图20200807100407](https://user-images.githubusercontent.com/7435339/89600825-8e754c00-d895-11ea-8082-07950c76be99.jpg)
作者没回复，自己也遇到这个问题，只能先把这断代码注释一下吧。

**Comment by SuperMonster003** [comment]
运行 Ant_Forest_Settings.js
-> 运行与安全
-> 通话状态监测
-> 总开关 - [ 关闭 ]

**Comment by a1103688841** [comment]
谢谢 我可以用了
