### ISSUE TITLE
Bug反馈: [ 今天突然不能偷取能量 ]

### ISSUE THREAD

**Issue by destroy3919** [SuperMonster003/Auto.js_Projects#380]
**问题描述**
最近突然就只能打开好友列表，对有能量球的好友可以有效识别到，就是不能偷取了。

**软件硬件信息**
操作系统: [ 安卓10.0 ]
设备型号: [ 三星 S10+ ]
Auto.js版本: [ 4.1.1 Alpha2 ]
项目版本: [  v1.9.22 ]

**Comment by Permanent-Fu** [comment]
我的是偷着偷着，突然就停住了，然后我想看日志，日志里面啥都没有，在日志界面停留几分钟，就会闪退出去

**Comment by destroy3919** [comment]
我也纳闷 看日志是进去了，但是说无能量球可操作，识别不到能量球，重装和重新下载都弄过了，就是没办法，不知道是不是支付宝更新了什么

**Comment by youaaaaa** [comment]
我的这些情况只要重启,或者关闭再打开无障碍就 解决

**Comment by destroy3919** [comment]
嗯嗯，后来实在束手无策了就重置了，没想重新设置下还能用了，可能是哪里突然抽风了，不过老问题还是漏收比较严重
