### ISSUE TITLE
Bug反馈: 日志获取不到

### ISSUE THREAD

**Issue by Permanent-Fu** [SuperMonster003/Auto.js_Projects#381]
**问题描述**
执行任务中会卡在好友能量树那里不动，就是偷着偷着，就定在好友树界面，然后我去看日志，日志里面啥都没有，一片空白，再之后就会闪退出去，就是在日志界面停止几秒就会闪退出去，已经开了无障碍也授权了面具。

**日志截图**

**软件硬件信息**
操作系统: 安卓10 
设备型号: 一加七Pro(刷了MIUI12) 
Auto.js版本:  4.1.1 Alpha2 
项目版本: v1.9.22 

**其他**
[ 包括但不限于 建议/提案/想法/灵感... ]

**Comment by Azhao1993** [comment]
一样的情况

**Comment by Santo-wiar** [comment]
我是自动执行，然后运行的时间比较长，就会停止运行，就报错，然后这个时候就算手动开，到了排行榜界面直接报错，然后去日志界面是空白直接闪退，闪退了再开的话就恢复正常了。同样miui不过感觉可能是miui的锅，因为我是升级了系统以后才出现的问题

**Comment by SuperMonster003** [comment]
日志被清空
说明 Auto.js 应用崩溃了
此问题我暂时无法解决
