### ISSUE TITLE
Bug反馈: 个别时段无法收取能量

### ISSUE THREAD

**Issue by dwan0819** [SuperMonster003/Auto.js_Projects#386]
**问题描述**
1、近期发现一个问题，大约早8点之前的运行无法收取能量，且不帮收，8点后的可以收取（图1、图2）。
2、解锁失败（图3）。

**日志截图**
与问题相关的日志截图
![微信图片_20200807094745](https://user-images.githubusercontent.com/57361769/89599860-35a4b400-d893-11ea-8c2d-22b18bce02cb.jpg)
![微信图片_20200807094741](https://user-images.githubusercontent.com/57361769/89599869-3b9a9500-d893-11ea-931a-b48eaaf987ac.jpg)
![微信图片_20200807094734](https://user-images.githubusercontent.com/57361769/89599873-3e958580-d893-11ea-859b-b6ed2aadc43e.jpg)

**软件硬件信息**
操作系统: [  MIUI12.0.1 ]
设备型号: [ 小米CC9 Pro ]
Auto.js版本: [ 4.1.1 Alpha2 ]
项目版本: [ v1.9.22 ]

**其他**
[ 包括但不限于 建议/提案/想法/灵感... ]

**Comment by dwan0819** [comment]
现已逐渐蔓延到的全天……不知为何

**Comment by SuperMonster003** [comment]
上述问题我暂时无法解决
另外划开提示层失败可通过更换第三方主题或在配置工具中改变起止点减少滑动距离尝试解决
