### ISSUE TITLE
荣耀magic系统，自动开机后首次解锁失败（第二次及以后可以）

### ISSUE THREAD

**Issue by NMSL-code** [SuperMonster003/Auto.js_Projects#387]
**问题描述**
想通过系统设置自启动随后脚本执行，但重启后的第一次解锁不行（autojs还没启动？）
在正常状态下，锁屏后可以自动解锁

**软件硬件信息**
操作系统: 安卓10
设备型号: 荣耀20
Auto.js版本: 4.1.1 Alpha2 
项目版本: v1.9.1

**Comment by SuperMonster003** [comment]
可以通过开启项目的开发者测试模式日志 查看首次启动解锁失败可能的原因
