### ISSUE TITLE
OnePlus 8 Pro 报错：截取当前屏幕失败

### ISSUE THREAD

**Issue by GhostWo** [SuperMonster003/Auto.js_Projects#388]
**问题描述**
截取当前屏幕失败

**日志截图**
截取当前屏幕失败

**软件硬件信息**
操作系统: [ 如: 安卓10 ]
设备型号: [ 如: OnePlus 8 Pro ]
Auto.js版本: [ 如: 8.0 ]
项目版本: [ 如: v1.9.22 ]

**其他**
[ 包括但不限于 建议/提案/想法/灵感... ]

**Comment by SuperMonster003** [comment]
v1.9.23 将尝试优化 IMAGES 扩展模块与截图相关的方法
项目版本发布后可尝试并继续反馈
