### ISSUE TITLE
魅族  16S  使用过程中崩溃了

### ISSUE THREAD

**Issue by ZhangErling** [SuperMonster003/Auto.js_Projects#389]
**问题描述**
使用过程中崩溃

**软件硬件信息**
操作系统: 9.0
设备型号: 魅族 16S
Auto.js版本: 4.1.1 Alpha2 
项目版本: 1.9.22

**日志**

Version: 461
Android: 28
android.database.CursorWindowAllocationException: Cursor window allocation of 2097152 bytes failed. # Open Cursors=1 (# cursors opened by this proc=1)
io.reactivex.exceptions.OnErrorNotImplementedException:Cursor window allocation of 2097152 bytes failed. # Open Cursors=1 (# cursors opened by this proc=1)
io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
......
Caused by:
android.database.CursorWindowAllocationException:Cursor window allocation of 2097152 bytes failed. # Open Cursors=1 (# cursors opened by this proc=1)
android.database.CursorWindow.<init>(CursorWindow.java:136)
android.database.CursorWindow.<init>(CursorWindow.java:114)
android.database.AbstractWindowedCursor.clearOrCreateWindow(AbstractWindowedCursor.java:198)
android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:143)
android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:137)
android.database.AbstractCursor.moveToPosition(AbstractCursor.java:220)
android.database.AbstractCursor.moveToNext(AbstractCursor.java:269)
org.autojs.autojs.storage.database.Database$CursorIterator.hasNext(Database.java:162)
io.reactivex.internal.operators.flowable.FlowableFromIterable.subscribe(FlowableFromIterable.java:53)
io.reactivex.internal.operators.flowable.FlowableFromIterable.subscribeActual(FlowableFromIterable.java:47)
io.reactivex.Flowable.subscribe(Flowable.java:12995)
io.reactivex.Flowable.subscribe(Flowable.java:12941)
io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.onNext(FlowableFlatMap.java:163)
io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.onNext(FlowableSubscribeOn.java:97)
io.reactivex.internal.subscriptions.DeferredScalarSubscription.complete(DeferredScalarSubscription.java:133)
io.reactivex.internal.operators.flowable.FlowableFromCallable.subscribeActual(FlowableFromCallable.java:44)
io.reactivex.Flowable.subscribe(Flowable.java:12995)
io.reactivex.Flowable.subscribe(Flowable.java:12941)
io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)
io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
java.lang.Thread.run(Thread.java:764)

**其他**
有时候解锁会失败，建议先双击点亮屏幕，在滑动解锁

**Comment by SuperMonster003** [comment]
应该是 Auto.js 可用 RAM 不足导致数据库无法操作
目前我暂时无法通过代码解决上述问题
可尝试重启设备或强制关闭并再次启动 Auto.js

**Comment by ZhangErling** [comment]
> 应该是 Auto.js 可用 RAM 不足导致数据库无法操作
> 目前我暂时无法通过代码解决上述问题
> 可尝试重启设备或强制关闭并再次启动 Auto.js
感谢回答！后续我调用手机开发模式监控 auto.js 运行情况，发现确实如你所说，它把我可用内存吃完了，导致脚本崩溃，甚至导致手机崩溃</汗>杀掉进程，重新赋予后台权限，重新赋予无障碍权限，重启 auto.js，重启脚本就好了，我100+好友，只能运行一天，有时候还不到，每次运行任务，它就吃点内存，这比谷歌浏览器还狠，光吃不吐。
