### ISSUE TITLE
如何设置排他性任务

### ISSUE THREAD

**Issue by NMSL-code** [SuperMonster003/Auto.js_Projects#392]
脚本有排他性任务等待时间，那么如何把autojs其他任务设置成排他性的？

**Comment by SuperMonster003** [comment]
通过 `com.stardust.autojs.engine.JavaScriptEngine` 的实例方法 `setTag` 实现排他性

示例代码 (设置标记)
```js
engines.myEngine().setTag("exclusive_task", "/* tag name */");
```

示例代码 (检测标记及 id 顺序)
```js
let my_e_id = engines.myEngine().id;
while (engines.all().filter((e) => e.getTag("exclusive_task") && e.id < my_e_id).length) {
    sleep(500);
}
```

**Comment by NMSL-code** [comment]
> 通过 `com.stardust.autojs.engine.JavaScriptEngine` 的实例方法 `setTag` 实现排他性
> 
> 示例代码 (设置标记)
> ```js
> engines.myEngine().setTag("exclusive_task", "/* tag name */");
> ```
> 
> 示例代码 (检测标记及 id 顺序)
> ```js
> let my_e_id = engines.myEngine().id;
> while (engines.all().filter((e) => e.getTag("exclusive_task") && e.id < my_e_id).length) {
>     sleep(500);
> }
> ```

谢谢大佬，找这个找了很久了
在此之前我自用的的方法是通过一个Flag.txt充当配置文件，褥羊毛的脚本第一行给Flag.txt写入true，最后一行写false，然后蚂蚁森林脚本第一行if判断Flag.txt若为true则exit，方法有点蠢。。。

**Comment by SuperMonster003** [comment]
代码借鉴于 e1399579 的蚂蚁森林项目 [点此跳转查阅](https://github.com/e1399579/autojs/blob/9b8addf73ecce716f8a5d175af2eab717a569466/%E8%9A%82%E8%9A%81%E6%A3%AE%E6%9E%97.js#L95)
另外也可以尝试使用 events.sendBroadcast 实现代码间的通信 详见官方文档 [点此跳转查阅](http://docs.autojs.org/#/events?id=eventsbroadcast-%e8%84%9a%e6%9c%ac%e9%97%b4%e5%b9%bf%e6%92%ad)
