### ISSUE TITLE
Bug反馈: [ 华为P30自动解锁 密码正确输入后无法进入系统 ]

### ISSUE THREAD

**Issue by szRayX** [SuperMonster003/Auto.js_Projects#393]
**问题描述**
设置自动解锁后定时任务启动，卡在输入密码界面，删除一位密码后在补上可以进入系统。
感觉和 #23 现象一致

**日志截图**
![ed360ea20599d41fc559c3ca6d3c128](https://user-images.githubusercontent.com/16751079/92091857-e99e4e00-ee03-11ea-8756-3bb07dfb8a3f.jpg)

**软件硬件信息**
操作系统: [Android 10, EMUI 10.1.0]
设备型号: [华为P30]
Auto.js版本: [4.1.1 Alpha2]
项目版本: [v1.9.22]

**Comment by SuperMonster003** [comment]
反馈一下以下代码执行结果
```js
console.log(device.release);
```

**Comment by szRayX** [comment]
> 反馈一下以下代码执行结果
> 
> ```js
> console.log(device.release);
> ```

这行代码加在哪里执行？

**Comment by SuperMonster003** [comment]
在 Auto.js 里面新建一个 js 文件
然后运行上述代码 (仅 1 行)
反馈一下日志结果

**Comment by szRayX** [comment]
> 在 Auto.js 里面新建一个 js 文件 然后运行上述代码 (仅 1 行) 反馈一下日志结果
> […](#)
> On September 4, 2020 13:12:10 Ray ***@***.***> wrote: 反馈一下以下代码执行结果 console.log(device.release); 这行代码加在哪里执行？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

![392432db3aa29aa907988ae67a4aea7](https://user-images.githubusercontent.com/16751079/92202200-0a70ad00-eeb1-11ea-8437-e384f98fb54e.jpg)
![78760b2212f0824586f2771f6cc5012](https://user-images.githubusercontent.com/16751079/92202204-0cd30700-eeb1-11ea-9044-fbe85966df29.jpg)

**Comment by SuperMonster003** [comment]
提供一下解锁页面的截图 (保证原始分辨率)
类型下面这样的 (需包含图中类似的虚拟键盘)

![Screenshot_20190509_232917_com android keyguard](https://user-images.githubusercontent.com/30370009/92202863-7869a400-eeb2-11ea-9b9c-4d80749c8527.jpg)

如果在解锁页面无法使用按键或菜单截图
可使用代码实现截图
示例代码:
```js
threads.start(function () {
    events.observeKey();
    events.setKeyInterceptionEnabled("volume_down", true);
    events.onceKeyDown("volume_down", function (e) {
        let path = files.cwd() + "/screen_capture_" + Date.now() + ".png";
        images.requestScreenCapture(false);
        sleep(300);
        images.captureScreen(path);
        toast("截图已保存");
        log("截图保存位置: " + path);
        device.vibrate(300);
        engines.myEngine().forceStop();
    });
});
```
如果使用上述示例代码
运行后脚本开始监听按键
手动到解锁页面后按 `音量减键 (VOL-)` 可完成截图 (设备会震动一下)
日志中可查看截图文件保存位置

**Comment by szRayX** [comment]
解锁页面截图如下
![1713149d086e657a2691cb8314c2731](https://user-images.githubusercontent.com/16751079/92203720-6f79d200-eeb4-11ea-97dc-5894ee5dccfc.jpg)

**Comment by SuperMonster003** [comment]
[MODULE_UNLOCK.zip](https://github.com/SuperMonster003/Auto.js_Projects/files/5173066/MODULE_UNLOCK.zip)
解压以上压缩文档后得到解锁模块
替换项目中 `./Modules/` 目录下同名文件后尝试解锁功能
替换前建议备份旧文件
如有问题可继续反馈

**Comment by szRayX** [comment]
替换完成后，自动解锁提示密码错误，我修改了3次密码还是密码错误。删除一位补上可以进入系统

**Comment by SuperMonster003** [comment]
![2020-09-04_162843](https://user-images.githubusercontent.com/30370009/92220063-0010dc00-eece-11ea-8f46-19d92a197e63.png)
解锁日志是否包含类似上述截图中的内容

**Comment by szRayX** [comment]
详细日志如下
![TIM截图20200904164713](https://user-images.githubusercontent.com/16751079/92220287-5ed65580-eece-11ea-85ad-e04e541e8439.png)

**Comment by SuperMonster003** [comment]
[MODULE_UNLOCK_v1.zip](https://github.com/SuperMonster003/Auto.js_Projects/files/5195027/MODULE_UNLOCK_v1.zip)
[MODULE_UNLOCK_v2.zip](https://github.com/SuperMonster003/Auto.js_Projects/files/5195029/MODULE_UNLOCK_v2.zip)

可分别尝试两个解锁模块能否正常工作

**Comment by SuperMonster003** [comment]
v1 / v2 中的代码
```js
let _has_root = shell("date", true).code === 0;
```
可能导致项目无任何提示直接退出

[MODULE_UNLOCK_v3.zip](https://github.com/SuperMonster003/Auto.js_Projects/files/5223132/MODULE_UNLOCK_v3.zip)
