### ISSUE TITLE
功能建议:  1、建议帮好友收取一秒后重新读取能量成熟时间。2、建议保护罩的黑名单设置成定时解除。3、...

### ISSUE THREAD

**Issue by ZhangErling** [SuperMonster003/Auto.js_Projects#395]
**功能优化**
1. 帮好友收能量后，建议等零点几秒或者让用户根据自己的网络情况自行设置，这样新的能量就可以刷新，重新读取能量成熟标志，偷取能量，之后再返回排行榜。
2. 能量的保护罩有倒计时，偷能量黑名单也可以设计成倒计时自动移除，这样会剩下很多时间用来偷真正有能量的好友。一次任务过程中，黑名单不是动态更新？我看他第一遍读取排行榜有保护罩，第二遍它还是会进那个好友的页面，后面次数也一样，有点浪费时间。
3. 同样样是保护罩问题，有些好友会设置节日套装，和好友赠送的能量球，保护罩识别速度降低数倍，建议优化。

**建议**

 1. 建议设置可选项，每天7-7:30不间断执行偷能量任务。使用过程中发现他早上有时候任务会停止并设置了一个定时任务，应该是延迟执行的，暂时不知道原因，我查看排行榜，是有能量可以偷取的。

**最后感谢作者及其贡献者的付出！伸手党表示崇高的敬意！谢谢你们！**

**Comment by SuperMonster003** [comment]
> 帮好友收能量后，建议等零点几秒或者让用户根据自己的网络情况自行设置，这样新的能量就可以刷新，重新读取能量成熟标志，偷取能量，之后再返回排行榜。

近期好友森林页面能量球确实是收取后可直接显现
之前是需要重新进入该好友森林页面才能出现新的能量球 (即六球复查)
后续版本将针对上述现象做出调整

> 帮好友收能量后，建议等零点几秒或者让用户根据自己的网络情况自行设置，这样新的能量就可以刷新，重新读取能量成熟标志，偷取能量，之后再返回排行榜。

参阅 https://github.com/SuperMonster003/Auto.js_Projects/issues/369


> 同样样是保护罩问题，有些好友会设置节日套装，和好友赠送的能量球，保护罩识别速度降低数倍，建议优化。

新版本 `v1.9.23` 优化了能量罩识别代码
但并未针对上述问题作出优化 如尝试新版本后问题复现 可继续反馈

> 建议设置可选项，每天7-7:30不间断执行偷能量任务。使用过程中发现他早上有时候任务会停止并设置了一个定时任务，应该是延迟执行的，暂时不知道原因，我查看排行榜，是有能量可以偷取的。

日志中可看到定时任务设置的相关信息
可重点关注是否包含"顺延"关键字并检查配置工具中是否设置了定时任务自动管理的有效时段
或直接在此提供日志截图供开发者分析
