### ISSUE TITLE
主页问题

### ISSUE THREAD

**Issue by wuyishan777** [SuperMonster003/Auto.js_Projects#396]
进入主页会跳转到蚂蚁森林宠爱日！

![Screenshot_20200921_115216_com eg android AlipayGphone](https://user-images.githubusercontent.com/51288685/93731822-623b3380-fb94-11ea-8125-eff9c3e8a1d4.jpg)
![Screenshot_20200921_114512_org autojs autojs](https://user-images.githubusercontent.com/51288685/93731831-6a936e80-fb94-11ea-8c34-32dbe651fb5c.jpg)

**Comment by SuperMonster003** [comment]
可尝试使用最新版本
如问题复现 可继续反馈
