### ISSUE TITLE
Bug反馈: 不进入能收取能量的好友森林，不收取能量球

### ISSUE THREAD

**Issue by Xm798** [SuperMonster003/Auto.js_Projects#397]
**问题描述**
首先，进入森林后，对可以收取的好友视而不见（有小手标志的好友不点，随机点没有好友标志的人）。
然后，即使有能量球，也会不收取。

**日志截图**
01:30:27.920/D:->无能量球可操作

**软件硬件信息**
操作系统: [ 安卓11 ]
设备型号: [ 小米 10 Pro ]
Auto.js版本: [ 4.1.1 Alpha2 ]
项目版本: [v1.9.24 ]

**Comment by SuperMonster003** [comment]
在配置工具中勾选消息提示功能下的开发者测试模式
然后提供详细的日志

**Comment by Xm798** [comment]
![Screenshot_2020-10-25-10-52-10-960_org.autojs.autojs.jpg](https://user-images.githubusercontent.com/48074861/97097797-3be74700-16b0-11eb-8141-b3e69153fdbd.jpg)![Screenshot_2020-10-25-10-52-15-739_org.autojs.autojs.jpg](https://user-images.githubusercontent.com/48074861/97097799-3f7ace00-16b0-11eb-8e8a-324c33a01134.jpg)![Screenshot_2020-10-25-10-52-27-096_org.autojs.autojs.jpg](https://user-images.githubusercontent.com/48074861/97097800-4275be80-16b0-11eb-866d-c1f58a3ebf13.jpg)
日志如图，以上三人都是有可以收取的能量球的，但是识别不到TAT

**Comment by Xm798** [comment]
目前已经更新最新版，收取功能测试正常。但是不进入可收取的好友的森林的问题依然无法解决，即有小手标志，但是被瞬间划过去了。尝试将滑动距离改为0.4或者0.6或者默认的0.75都不行。

我录制了一个屏幕录像，不知道有什么合适的方式可以发送给您？

谢谢开发者大大！
![Screenshot_2020-10-25-11-04-37-378_org.autojs.autojs.jpg](https://user-images.githubusercontent.com/48074861/97097932-004d7c80-16b2-11eb-89cd-ff98670f4051.jpg)

**Comment by SuperMonster003** [comment]
可尝试 v1.9.25 版本
如果问题复现 可重新开贴反馈
此 issue 暂时关闭
