### ISSUE TITLE
交流研讨: [ 新版 吐槽]

### ISSUE THREAD

**Issue by biosxf007** [SuperMonster003/Auto.js_Projects#400]
作为这个脚本的铁粉，我还是想说两句的…等了好久，终于上新了，昨天来这看到系统显示老大是25分钟前编辑的，那我可以算是第一时间更新了…看了新版本的说明，解决的那些问题我这一个也没有，好友列表打开错误还不停下拉循环刷新的问题依旧没解决，虽然这个不是每次都会出现，但还是有一定概率的，之前反馈过几次的…还有我以为脚本会变成“逛一逛”的模式，那个效率高很多啊，而且可以避免刷新下拉列表出现的各种问题，以为老大这么久憋大招会是这个，可惜没有，不知下个版本会不会改…啰嗦了，见谅…

**Comment by SuperMonster003** [comment]
此项目源于个人早期心愿 不存在定向服务 亦不存在任何粉丝

项目自动更新或更新提示可能在后续版本中逐步实现 但不做保证
现可通过配置工具手动检查更新 无需在项目页面查看

之前的 issue 因未能及时收到反馈信息而被关闭
这样的 issue 默认不再受理
如果仍有问题 可重新开贴 并按旧帖开发者回复中提及的需求提供反馈信息

逛一逛功能模块将在后续版本逐步实现

**Comment by TonyJiangWJ** [comment]
我那边有人反馈森林又有新版本了，先不着急开发逛一逛
![image](https://user-images.githubusercontent.com/11325805/96441048-6f9f1880-123b-11eb-9c73-8ddca9cc9915.png)

**Comment by SuperMonster003** [comment]
@TonyJiangWJ 
好的 感谢提醒
