### ISSUE TITLE
在好友页面不收取好友能量

### ISSUE THREAD

**Issue by ZhangErling** [SuperMonster003/Auto.js_Projects#401]
进入到好友页面，但是不收取好友能量，**日志显示无能量可操作**，实际上是有能量可以收取的
在支付宝更新蚂蚁森林之前是没有问题的，更新后不能正确识别绿色能量球了，蚂蚁森林此次**更新了待收取的能量球颜色，整体界面背景**，希望作者能及时更新，感谢付出！

代码使用的最新版
auto.js 4.1.1 Aplha2
支付宝 10.2.3

**Comment by EDc0754** [comment]
确实无法收取好友能量了

**Comment by SuperMonster003** [comment]
已发布 `v1.9.24 Beta` 版本解决上述问题
可尝试在配置工具 (`Ant_Forest_Settings.js`) 中检查并下载更新
Beta 版本可能存在较多问题 欢迎随时反馈

`v1.9.24 Beta` 不兼容旧版蚂蚁森林
若蚂蚁森林依然为旧版 请勿更新此版本
如不慎更新 可在配置工具中还原服务器版本 v1.9.23
或在本地还原功能中找到最新的自动备份版本并还原

**Comment by ZhangErling** [comment]
> 已发布 `v1.9.24 Beta` 版本解决上述问题
> 可尝试在配置工具 (`Ant_Forest_Settings.js`) 中检查并下载更新
> Beta 版本可能存在较多问题 欢迎随时反馈
> 
> `v1.9.24 Beta` 不兼容旧版蚂蚁森林
> 若蚂蚁森林依然为旧版 请勿更新此版本
> 如不慎更新 可在配置工具中还原服务器版本 `v1.9.23`
> 或在本地还原功能中找到最新的自动备份版本并还原

昨晚更新了，目前来看没有阻断性bug，后续遇到性能优化的问题，会开新帖继续反馈
感谢及时更新！

**Comment by biosxf007** [comment]
非常及时的更新，一如既往的给力，感谢付出😊

**Comment by fauthor** [comment]
感谢作者大大
