### ISSUE TITLE
 1.9.24 Beta 无法拾取能量球

### ISSUE THREAD

**Issue by hardis2004** [SuperMonster003/Auto.js_Projects#402]
【拾取】可以正确识别并进入到有能量球的森林页面，但没有拾取点击动作后回到列表
【自收】正常
【帮拾】正常

**Comment by SuperMonster003** [comment]
自己成熟球能收取
但好友成熟球不收取吗

运行配置工具 在消息提示中开启开发者测试模式然后运行一遍项目 并提供详细的日志截图

另外提供一下好友森林包含绿色成熟能量球的截图原图 (注意保护截图中的个人信息)

**Comment by hardis2004** [comment]
> 自己成熟球能收取 但好友成熟球不收取吗 运行配置工具 在消息提示中开启开发者测试模式然后运行一遍项目 并提供详细的日志截图 另外提供一下好友森林包含绿色成熟能量球的截图原图 (注意保护截图中的个人信息)
> […](#)
> On October 22, 2020 11:47:46 hardis2004 ***@***.***> wrote: 【拾取】可以正确识别并进入到有能量球的森林页面，但没有拾取点击动作后回到列表 【自收】正常 【帮拾】正常— You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

我给你录屏 请加我Q(BASE64)：MTIyMzI2Mzc=

**Comment by ZhangErling** [comment]
> > 自己成熟球能收取 但好友成熟球不收取吗 运行配置工具 在消息提示中开启开发者测试模式然后运行一遍项目 并提供详细的日志截图 另外提供一下好友森林包含绿色成熟能量球的截图原图 (注意保护截图中的个人信息)
> > […](#)
> > On October 22, 2020 11:47:46 hardis2004 _**@**_.***> wrote: 【拾取】可以正确识别并进入到有能量球的森林页面，但没有拾取点击动作后回到列表 【自收】正常 【帮拾】正常— You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> 我给你录屏 请加我Q(BASE64)：MTIyMzI2Mzc=

开发肯定喜欢日志，看屏看不出问题根本原因

**Comment by ZhangErling** [comment]
https://github.com/SuperMonster003/Auto.js_Projects/issues/401#issuecomment-713241227

beta不支持旧版蚂蚁森林，你的版本是否正确？你的支付宝版本是？
建议提bug之前加上自己的运行环境，这样有助于开发者定位问题

**Comment by Hxyspace** [comment]
遇到同样的情况，查看运行日志发现程序不支持支付宝语言为英文（当然，程序会尝试修改语言为中文，但由于本人设置了密码，导致切换失败），手动将支付宝语言切换成中文后，程序正常运行。

**Comment by eaglexxxm** [comment]
> 自己成熟球能收取 但好友成熟球不收取吗 运行配置工具 在消息提示中开启开发者测试模式然后运行一遍项目 并提供详细的日志截图 另外提供一下好友森林包含绿色成熟能量球的截图原图 (注意保护截图中的个人信息)
> […](#)
> On October 22, 2020 11:47:46 hardis2004 ***@***.***> wrote: 【拾取】可以正确识别并进入到有能量球的森林页面，但没有拾取点击动作后回到列表 【自收】正常 【帮拾】正常— You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

![442cf402ecbdbbde1c1141ca20d1701](https://user-images.githubusercontent.com/47687145/97274225-4e5baf00-186f-11eb-9021-e785c4c7600e.jpg)
![6a6f0a3d8fc5bc8ee8f368463437bfe](https://user-images.githubusercontent.com/47687145/97274233-50257280-186f-11eb-8b52-432db13e355a.jpg)

**Comment by SuperMonster003** [comment]
@eaglexxxm 
截图中的蚂蚁森林小程序是旧版的
可尝试使用配置工具 从服务器还原 `v1.9.23` 版本
等小程序更新后再升级至项目最新版
@hardis2004 
同上 检查一下小程序是否为旧版
@Hxyspace 
当前项目只支持将英文支付宝自动切换到中文并保持中文语言
还未实现全面化英文识别及语言自动切换功能
将在以后考虑实现上述切换功能及英文语言的控件识别
但开发周期可能较长
