### ISSUE TITLE
Bug反馈: [ 最新脚本获取好友能量罩剩余时间超时 ]

### ISSUE THREAD

**Issue by youaaaaa** [SuperMonster003/Auto.js_Projects#404]
**问题描述**
获取好友能量罩剩余时间超时导致
结束收取后会再次进入好友列表继续点击未获取能量罩的好友,再次超时后进入下一次循环,无法结束

应该是代码判定排行榜存在差异,而实际又无操作,所以会一直循环运行
或者其他原因可以讲一下吗

是不是应该加个超时次数,  达到多次就将该好友加入白名单

**日志截图**
提示获取该好友能量罩超时

**软件硬件信息**
操作系统: [ 如: 安卓8.0 ]
设备型号: [ 如: 米8 ]
Auto.js版本: [ 如: 4.1.1 Alpha2 ]
项目版本: [ 如: v1.9.1 ]

**其他**
[ 包括但不限于 建议/提案/想法/灵感... ]

**Comment by SuperMonster003** [comment]
项目版本是 v1.9.24 Beta 还是 v.1.9.23

如果是 23
尝试运行配置工具 升级至最新版后再试

如果是 24 Beta
运行配置工具 在消息提示页面下勾选开发者测试模式 然后提供完整运行日志

**Comment by youaaaaa** [comment]
日志是否有储存在某个文件夹?
没有的话只能等下次出现在反馈

**Comment by SuperMonster003** [comment]
没有存储
等下次出现再反馈

**Comment by SuperMonster003** [comment]
v1.9.24 已增加本地日志保存功能
如果能量罩相关问题浮现 可查看日志文件并重新反馈
