### ISSUE TITLE
1.9.24 收能量时翻页速度过快无法获取

### ISSUE THREAD

**Issue by oishi81** [SuperMonster003/Auto.js_Projects#405]
**问题描述**
目前用1.9.24发现收好友能量时，向下滑动时速度太快，无法正确获取好友名字的“手”。 回滚到1.9.23还是如此。

**软件硬件信息**
操作系统: 安卓11
设备型号: 小米10pro
Auto.js版本: 4.1.1 Alpha2
项目版本: 1.9.24

**Comment by SuperMonster003** [comment]
运行配置工具 -> 收取功能 (或帮收功能) -> 排行榜样本采集
尝试适当增加 `滑动时长` 及 `滑动间隔` 的值
