### ISSUE TITLE
Bug反馈: [ 定时时间到达后无法唤醒屏幕 ] (Edited)

### ISSUE THREAD

**Issue by zhongranxu** [SuperMonster003/Auto.js_Projects#406]
**问题描述**
蚂蚁森林的代码最新版在定时的时间到了之后，无法唤醒屏幕及自动解锁； 
但如果在充电模式下可以正常唤醒屏幕和自动解锁，请问是哪里设置问题吗？还是权限问题吗？

**日志截图**
提供与问题相关的日志截图

**软件硬件信息**
操作系统: [ 如: 安卓10.0 ]
设备型号: [ 如: 华为P40 ]
Auto.js版本: [ 如: 4.1.1 Alpha1 ]
项目版本: [ 如: v1.9.24 ]

**其他**
[ 包括但不限于 建议/提案/想法/灵感... ]

**Comment by SuperMonster003** [comment]
检查设备的 节电设置 自动运行白名单 等设置
防止 Auto.js 在屏幕关闭期间被限制自动运行

**Comment by sandglasstu** [comment]
我的是华为P30，其他版本都一样，关了省电模式也给了autojs所有权限，还是无法唤醒屏幕。。
