### ISSUE TITLE
Bug反馈: [ 凌晨时段屏幕无法点亮/需手动亮屏后可正常操作 ]

### ISSUE THREAD

**Issue by youaaaaa** [SuperMonster003/Auto.js_Projects#407]
**问题描述**
更新后这几天早晨发现能量为0;  查看日志发现脚本没有成功点亮屏幕; 
在手动亮屏后可进行自动解锁等运行操作

**日志截图**
![QQ图片20201028150600](https://user-images.githubusercontent.com/57583951/97403431-5b3fd780-192f-11eb-82ee-4ecba15afc27.jpg)
![QQ图片20201028150621](https://user-images.githubusercontent.com/57583951/97403439-60048b80-192f-11eb-8f00-c931e95f14a2.jpg)

**软件硬件信息**
操作系统: [ 如: 安卓8.0 ]
设备型号: [ 如: 米8 ]
Auto.js版本: [ 如: 4.1.1 Alpha2 ]
项目版本: [ 如: v1.9.24 ]

**Comment by SuperMonster003** [comment]
检查系统的屏幕超时时间是否过小
通常不应小于1分钟

如果参数为空或很小的值
说明是脚本将屏幕参数调整后没有恢复成功

脚本结束之前会按需关闭屏幕
在无 root 权限的设备上
脚本无法直接实现模拟电源键关屏
因此项目通过修改屏幕超时参数为最小
等待触发屏幕超时实现关屏功能


项目在修改屏幕超市参数之前
会备份当前系统的参数值 (如1分钟)
然后修改成最小值
检测到屏幕关屏后 立即恢复之前的参数 (如1分钟)
等待屏幕超时通常需要数秒到十几秒
如果这期间用户执行以下操作
将会有不同的结果


1. 无任何操作
脚本按上文描述成功恢复原来的参数


2. 用户触碰了屏幕或按下了按键 (不包括音量键)
脚本检测到上述行为后
停止关屏操作 立即恢复原来的参数并结束项目


3. 用户按下了音量键 (包括音音量加和音量减)
脚本被强制终止
已经修改的参数未能恢复
导致系统的屏幕超时时间很短
体现在用户不操作手机时 很短的时间久自动关屏
甚至会出现之后运行项目
很短的时间就出发屏幕关屏事件 (如楼上的反馈一样)


所以很可能是在等待屏幕关闭期间用户按下了音量键  [ 即上述情况 (2) ]
正确的做法是触碰一下屏幕任意区域来实现停止关屏操作过程


如实际情况与推测不符
可继续反馈

**Comment by youaaaaa** [comment]
确实有操作跟你推测的按下音量键强制停止运行脚本;
晚上再试试无任何操作看是否还有该情况

**Comment by youaaaaa** [comment]
**情况描述**
昨天睡前锁屏下正常解锁且结束后关屏参数正常;
我等屏幕灭了后又开手机玩,期间在亮屏下脚本运行,全程正常结束后;创建早上定时任务
早上醒来查看日志依旧未收取能量;

另一问题: 
昨晚日志显示了创建了一个6.30的延时接力任务  也未如期进行;

**日志截图**
![1](https://user-images.githubusercontent.com/57583951/97511025-064ca180-19c1-11eb-9f2e-9350c129e067.jpg)
![2](https://user-images.githubusercontent.com/57583951/97511029-08aefb80-19c1-11eb-8d9a-34250f151055.jpg)
![3](https://user-images.githubusercontent.com/57583951/97511030-09479200-19c1-11eb-863b-6e2375014677.jpg)
![4](https://user-images.githubusercontent.com/57583951/97511032-09e02880-19c1-11eb-9ef0-13fa3111263a.jpg)
![5](https://user-images.githubusercontent.com/57583951/97511033-09e02880-19c1-11eb-8eb1-b77632512fcc.jpg)

**Comment by SuperMonster003** [comment]
没有亮屏但脚本认为已经成功亮屏 说明判断是否亮屏的代码对于当前设备不适用 之前也有其他机型有上述问题 我暂时无法解决
附上关键代码 可用于自行测试

device.wakeup(); // 唤醒屏幕
device.isScreenOn(); // 是否亮屏

定时任务没有准时运行 一般是关屏后AJ后台活动收到节点设置等限制造成的 相关的issue有很多 目前也没有通用的解决方案 通常需要针对自己是用的系统检查所有可能的与AJ后台限制或背景运行等相关的设置
