### ISSUE TITLE
关于项目部署

### ISSUE THREAD

**Issue by jie-neng** [SuperMonster003/Auto.js_Projects#408]
采用导入功能导入项目，项目已经解压到/storage/emulated/0/下面了，可是好像不让你导入整个文件夹，只让你按一个一个文件导入，这怎么办？

![微信图片_20201106125433](https://user-images.githubusercontent.com/58629010/98328003-c4120880-202f-11eb-8ace-1475a451e340.jpg)

**软件硬件信息**
操作系统: 安卓7.1.2
设备型号: VIVO X9
Auto.js版本:  4.1.1 Alpha2 
项目版本: : v1.9.1

**Comment by SuperMonster003** [comment]
请参阅项目文档使用说明
不要使用导入功能
https://github.com/SuperMonster003/Auto.js_Projects/wiki/%E8%9A%82%E8%9A%81%E6%A3%AE%E6%9E%97-(Ant-Forest)

**Comment by jie-neng** [comment]
已建立"test" (作为测试文件)，/ storage / emulated / 0 /文件夹下面没有出现test，es文件浏览器搜索也没有名称是test的文件夹，这个应该是以什么为后缀的丫？

**Comment by SuperMonster003** [comment]
以 "js" 格式结尾
另外可以检查一下内部存储目录下是否有 "脚本" 文件夹
查看里面是否有 test.js 文件
因为有的手机会在 "/storage/emulated/0/" (即"内部存储") 目录下还会建立一个 "/storage/" 目录从而引起混淆
这样的条件下 用户看到的 "/storage/emulated/0" 实际上是 "/storage/emulated/0/storage/emulated/0"
