### ISSUE TITLE
请问这是怎么回事呢？

### ISSUE THREAD

**Issue by 461617504** [SuperMonster003/Auto.js_Projects#41]
![Screenshot_20190526_062739_org autojs autojs](https://user-images.githubusercontent.com/51035083/58375247-f6858e00-7f80-11e9-939c-eacd2e729489.jpg)
![Screenshot_20190526_010718_org autojs autojs](https://user-images.githubusercontent.com/51035083/58375248-f6858e00-7f80-11e9-94c8-7445ff20387c.jpg)
用2个版本的auto出现的提示

**Comment by SuperMonster003** [comment]
Modules文件夹中缺少必要项目模块 请确保项目文件完整

**Comment by 461617504** [comment]
我又重新下载，解压，还是不行，用的es文件浏览器解压

**Comment by SuperMonster003** [comment]
解压完是一个文件夹的话 需要把文件夹里面的内容复制到脚本目录中 而不是这个文件夹本身
Ant_Forest_Launcher.js文件应与Modules文件夹处于同级目录下
再看看Modules文件夹中是否有MODULE_MONSTER_FUNC.js模块文件

**Comment by 461617504** [comment]
我单独解压出来试过，然后auto导入，显示那个js文件大小是0kb，执行不了

**Comment by SuperMonster003** [comment]
不要使用Auto.js的导入功能 用ES管理器 把项目文件夹中的文件 全部解压或复制到 /sdcard/脚本/ 目录中
