### ISSUE TITLE
小米9无法解锁

### ISSUE THREAD

**Issue by SUNSTARK** [SuperMonster003/Auto.js_Projects#44]
日志提示消除解锁页面提示层失败

**Comment by SuperMonster003** [comment]
感谢反馈 亮屏之后脚本运行正常吗 可尝试Alpha6版本

**Comment by SUNSTARK** [comment]
> 感谢反馈 亮屏之后脚本运行正常吗 可尝试Alpha6版本

手动解锁屏幕之后正常执行，就是不能自动解锁了，解锁界面一直常亮。日志里显示消除解锁页面提示层失败，α6版本也是一样。

**Comment by SuperMonster003** [comment]
https://github.com/SuperMonster003/Auto.js_Projects/issues/43#issuecomment-496133983

**Comment by SUNSTARK** [comment]
> [#43 (comment)](https://github.com/SuperMonster003/Auto.js_Projects/issues/43#issuecomment-496133983)

![image](https://user-images.githubusercontent.com/51064386/58425605-c6e39c80-80cc-11e9-999c-9634b829f6fd.png)

**Comment by SuperMonster003** [comment]
新版尝试了优先使用device方法获取宽高值的方式 可以尝试一下看问题是否复现

**Comment by SuperMonster003** [comment]
https://github.com/SuperMonster003/Auto.js_Projects/issues/43#issuecomment-497550907
