### ISSUE TITLE
红米5设置界面设置不了，导致定时任务启动不成功

### ISSUE THREAD

**Issue by 35833136** [SuperMonster003/Auto.js_Projects#45]
![111](https://user-images.githubusercontent.com/25142040/58523677-03f87d80-81f8-11e9-82ee-5b64392df7bd.jpeg)
![2222](https://user-images.githubusercontent.com/25142040/58523696-0a86f500-81f8-11e9-9e18-9758ba73b188.jpeg)
![333](https://user-images.githubusercontent.com/25142040/58523701-0d81e580-81f8-11e9-83c0-dedb81177fec.png)
![444](https://user-images.githubusercontent.com/25142040/58523706-107cd600-81f8-11e9-839b-6949e9581708.png)
![555](https://user-images.githubusercontent.com/25142040/58523708-12df3000-81f8-11e9-837c-a69b50f1532c.jpeg)

**Comment by SuperMonster003** [comment]
设置页面显示异常 请尝试重新安装Auto.js或重启设备

**Comment by 35833136** [comment]
按照此方法已解决，大兄弟给力，更新频率这么快..
