### ISSUE TITLE
是要放弃这个项目了吗？

### ISSUE THREAD

**Issue by VergLsm** [SuperMonster003/Auto.js_Projects#46]

**Comment by SuperMonster003** [comment]
也不算是吧
裸辞太长时间
打算学学框架学学node就找工作了
所以不能像以前那样一两天一更新了
可能一个月更新一两次吧
如果有任何问题和bug还是可以反馈的 我会抽空找个时间同意修复
感谢支持

**Comment by VergLsm** [comment]
我也辞职一段时间了，大家都有生活压力
看样子你是做前端的？我是做后台的
大家共勉

**Comment by SuperMonster003** [comment]
😄 
感谢支持

**Comment by VergLsm** [comment]
我们也感谢你的付出
工作简历可以把这个项目写上，是个加分项
另外也建议如果可以的话写一下注释，写一些必要的文档，当做鼓励别的开发者加入进来
祝你早日找到合适的工作

**Comment by SuperMonster003** [comment]
好的  
目前在工具函数模块中 每个方法都写了详细的JSDoc 主执行脚本中的变量或方法也都使用了便于识别的命名方式 在必要的地方也加入了注释  
文档一开始项目启动的时候是打算变做功能边写的 但现在一直没动 而且功能也没做全 心思也都没有了  
感谢你的祝福

**Comment by VergLsm** [comment]
祝你工作顺利！



来自 魅蓝 Note6



-------- 原始邮件 --------
发件人：SuperMonster003 <notifications@github.com>
时间：2019年5月31日 09:22
收件人："SuperMonster003/Auto.js_Projects" <Auto.js_Projects@noreply.github.com>
抄送：VergLsm <vision.lsm.2012@gmail.com>,Author <author@noreply.github.com>
主题：Re: [SuperMonster003/Auto.js_Projects] 是要放弃这个项目了吗？ (#46)


😄
感谢支持

**Comment by coxcaifa** [comment]
楼主祝好，感谢你的项目

**Comment by DanielEcho** [comment]
祝更上一层楼，早日实现财务自由

**Comment by sunqintao** [comment]
前端工程师现在工资很高哦!

**Comment by Mahoshojocn** [comment]
大佬大佬
