### ISSUE TITLE
就是进入蚂蚁深林页面 说截图权限失败

### ISSUE THREAD

**Issue by CJW0716** [SuperMonster003/Auto.js_Projects#47]
![image](https://user-images.githubusercontent.com/49069371/58609487-4c886780-82da-11e9-9b7a-65aeb88b6649.png)

**Comment by ljx0623** [comment]
权限管理里给一下“后台弹出界面”权限就行了~

**Comment by SuperMonster003** [comment]
![2019-05-30_163924](https://user-images.githubusercontent.com/30370009/58675116-78acf280-8385-11e9-91f0-8b0bac150afa.png)

**Comment by tvrcfdfe** [comment]
小米9 pro 给了"后台弹出界面” 可以收取了
