### ISSUE TITLE
请大大开放以前旧版本下载

### ISSUE THREAD

**Issue by ggyy8850** [SuperMonster003/Auto.js_Projects#48]
请大神开放旧版本下载，现在的版本直接不能用了，几个问题并存。以前有的版本还能正常使用。
祝大神新工作顺利

**Comment by VergLsm** [comment]
建议之后更新打个版本号的tag，也方便生成release

**Comment by SuperMonster003** [comment]
@ggyy8850 旧版本没有发布release 只能通过commit自己慢慢找了  
@VergLsm 以前 `luchangharry` 也建议我release了 我一直也没发 刚已经试着发布了一版

**Comment by VergLsm** [comment]
很好，这就很方便手机党更新了

**Comment by SuperMonster003** [comment]
`v1.7.0` 已加入项目更新/备份/还原功能  
可以在图形配置页面 (即 `Ant_Forest_Settings.js` ) 回退所有GitHub上发布过的Release (虽然当前只有2个)

**Comment by SuperMonster003** [comment]
最近测试本地备份还原功能与GitHub的Releases还原功能均可用  
此Issue暂时关闭
