### ISSUE TITLE
那个解锁出现，“消除解锁页面页面提示层失败” 解不开锁怎么办

### ISSUE THREAD

**Issue by CJW0716** [SuperMonster003/Auto.js_Projects#51]
1.6.25a4版本在哪里下载。那个解锁出现，“消除解锁页面页面提示层失败” 解不开锁怎么办

**Comment by SuperMonster003** [comment]
https://github.com/SuperMonster003/Auto.js_Projects/issues/50#issuecomment-502026477

**Comment by SuperMonster003** [comment]
此Issue暂时关闭 如问题复现 请重新反馈 感谢支持
