### ISSUE TITLE
无限进入同一个好友主页

### ISSUE THREAD

**Issue by luchangharry** [SuperMonster003/Auto.js_Projects#52]
支付宝无限进入同一个人的主页，但是日志中显示的人名不同，采用的是布局分析策略，切换到图像处理策略后发现会错过有能量的好友，调了滑动时长也没用
![881559898690_ pic](https://user-images.githubusercontent.com/50188136/59093777-53048800-8947-11e9-9b42-0ae1f7ec82e7.jpg)

**Comment by SuperMonster003** [comment]
`v1.7.0` 试修了 修改了点击坐标的参照体  
另外图像匹配遗漏目标的问题 等下个版本再修  
感谢支持

**Comment by luchangharry** [comment]
> `v1.7.0` 试修了 修改了点击坐标的参照体
> 另外图像匹配遗漏目标的问题 等下个版本再修
> 感谢支持

测试1.7.1 布局分析策略滑动两次后会重复进入最下端好友页面，图像处理页面存在错过有能量好友的情况

**Comment by SuperMonster003** [comment]
@luchangharry 
滑动问题可以试试 `v1.8.0`  
错过好友的情况我暂时还没有做优化 如果新版问题依旧 可继续反馈  
感谢支持

**Comment by luchangharry** [comment]
楼主大大，滑动问题已解决，有一个问题想问一下，现在我无论如何设置和苹果开关，似乎总是会自动添加定时任务，导致我玩手机时频繁被打断，请问具体应该在哪里关闭自动设置定时任务？

**Comment by SuperMonster003** [comment]
确实有开关与代码关联的问题 正常关闭定时任务自动管理就不会自动添加任务了 我会尽快修复这个问题  另外消息提示那里有一个运行前提示 可以打开 
这样可以在一定程度上降低脚本对手机正常使用的影响 感谢支持

**Comment by SuperMonster003** [comment]
另外可以通过先关闭 意外保险机制 的开关 再关闭定时循环的总开关 的方式 实现定时循环的彻底关闭 暂时可以如此 下一版修复此问题

**Comment by SuperMonster003** [comment]
此 Issue 暂时关闭 如有问题请重新反馈 感谢支持
