### ISSUE TITLE
完善自动执行机制

### ISSUE THREAD

**Issue by wideweide** [SuperMonster003/Auto.js_Projects#54]
目前设置了几个时间点自动执行，感觉不够智能，特提出如下建议：
1. 使用定时器脚本自动执行：之前自己尝试过，定时器脚本似乎无法常驻autojs的
2. 定时机制设置更灵活一点，可以设置几组，每组设置自动执行的时间间隔
3. 自动设置下次自动执行的时间：查看自己或朋友的能量多久可以收集，定期去收集；暂时没有快到期能量，设置指定时间后再次检查。

另问下如何能够联系到你？

**Comment by VergLsm** [comment]
@wideweide 1和2，了解除下tasker;

**Comment by wideweide** [comment]
@VergLsm
tasker不熟，具体指什么？给个链接参考一下

**Comment by VergLsm** [comment]
一个应用来的，百度就行

________________________________
发件人: wideweide <notifications@github.com>
发送时间: Thursday, June 13, 2019 5:24:45 PM
收件人: SuperMonster003/Auto.js_Projects
抄送: VergLsm; Mention
主题: Re: [SuperMonster003/Auto.js_Projects] 完善自动执行机制 (#54)


@VergLsm<https://github.com/VergLsm>
tasker不熟，具体指什么？给个链接参考一下

―

**Comment by wideweide** [comment]
> 
> 
> @wideweide 1和2，了解下tasker;

感谢指点：1和2用tasker搞定了。

a. 有个提升问题：想要设置仅当手机未处于“走动”状态时，才执行此操作，没找到合适的传感器或状态，有什么好的建议？
b. 原3的问题，给指点指点，改哪块代码能实现？

**Comment by VergLsm** [comment]
@wideweide a.应该跟加速度传感器有关吧。b. 这个项目里没有这方面的代码，可以参考https://github.com/Nick-Hopps/Ant-Forest-autoscript

**Comment by wideweide** [comment]
@VergLsm 看上去那边有这个功能啊，跟当前这个对比如何？

**Comment by VergLsm** [comment]
@wideweide 我的设备用那个项目解不了锁，这边解锁模块好用，收取正常，这对于我来说足够了。
自动到时收取这个功能我觉得在AutoJs不稳定，因为要一直挂后台延时，而且浪费电，再加上收得太狠，人家分分钟就把你拉黑了。

**Comment by wideweide** [comment]
@VergLsm 体验了一下：卡在森林界面，收取不了其他人的能量。

**Comment by SuperMonster003** [comment]
@wideweide  感谢提供修改意见或功能建议  
这些全部属于定时任务功能  
所有的建议均包含在功能初期设想中  
只是此功能暂时没有近期实现的计划  
感谢支持

**Comment by wideweide** [comment]
https://github.com/wideweide/AntForest
