### ISSUE TITLE
设置定时任务

### ISSUE THREAD

**Issue by calvin369** [SuperMonster003/Auto.js_Projects#56]
华为mate9设置Ant_Forest_Launcher.js这个定时任务为每天7点，睡觉中都把这个程序后台运行，但第二天7时，软件只是在后台一直运行，定时任务无效没有自动打开支付宝运行收能量，哪个操作出问题，还是要添加其他步骤？

**Comment by calvin369** [comment]
还有设置定时把整个星期都选上后，例如我只设置了7点，是否运行一次，假如10点有能量收，要另外再添加10点这个时间段，这个起始时间设置7点后，是一设置就自动默认运行一天，还是其他其他时间段收就得另外设置其他时间段

**Comment by yyylly** [comment]
你把auto.js的自启改为手动管理，允许自动启动，允许关联启动，允许后台运行。记得设置开启无障碍，同时不要手动关闭auto app,否者华为系统自动关闭无障碍功能并且auto app也无法运行。
定时的话，记得开启大大的自动解锁功能。

**Comment by Gaara3** [comment]
请问

> 你把auto.js的自启改为手动管理，允许自动启动，允许关联启动，允许后台运行。记得设置开启无障碍，同时不要手动关闭auto app,否者华为系统自动关闭无障碍功能并且auto app也无法运行。
> 定时的话，记得开启大大的自动解锁功能。

请问是怎样实现定时自启动的呀，华为系统有自带？还是通过tasker之类的工具呢？

**Comment by SuperMonster003** [comment]
`v1.8.0` 已增加定时循环功能 欢迎体验 如有问题 请开新帖反馈  
感谢支持 此Issue暂时关闭
