### ISSUE TITLE
无法唤醒解锁，增加循环运行设置

### ISSUE THREAD

**Issue by zjn0628** [SuperMonster003/Auto.js_Projects#57]
定时启动无法唤醒屏幕，也无法解锁。华为EMUI9.1.用Nick-Hopps/Ant-Forest-autoscript的程序没有问题可以正常唤醒解锁，可能他是通过下拉或者不匀速上划来启动解锁界面的。,2能否在程序里实现循环运行设置可以设置次数或者时间段。aj里设置循环运行无效，会运行一次自动停止。3进入蚂蚁森林在自己界面里停留时间稍长3s，能否减少到1-1.5s

**Comment by wyfang** [comment]
是啊，循环是关键，如果可以增加处于7点-7：30，无限循环运行，那就很好了。

**Comment by SuperMonster003** [comment]
@zjn0628 欢迎体验 `v1.8.0`  
定时循环功能已实现 另外停留时间长的问题也已解决  
如果定时任务依然无法正常唤醒解锁 可继续反馈

**Comment by wyfang** [comment]
@SuperMonster003 小米9无法解锁。日志显示有截图：
![unlock_failed_20190724163000](https://user-images.githubusercontent.com/17900420/61778828-1676e800-ae32-11e9-86ba-7f8cf3c2a6d6.png)

**Comment by SuperMonster003** [comment]
用锁屏布局分析工具生成一份报告给我看一下 工具在 Tools 文件夹下

**Comment by wyfang** [comment]
@SuperMonster003 
[!Debug_Info.zip](https://github.com/SuperMonster003/Auto.js_Projects/files/3425979/Debug_Info.zip)

**Comment by SuperMonster003** [comment]
收到 明天分析

**Comment by wyfang** [comment]
我在坚果pro2s上运行，发现自动解锁第一步向上滑动没有进行。

以及看到日志说截图保存在一个路径，该路径似乎没有root权限或者说使用自带文件管理器以及连接手机，并看不到该文件夹。

**Comment by SuperMonster003** [comment]
@wyfang 已检查代码 没有发现问题 且存在匹配的控件id "com.android.systemui:id/lockPatternView" 确保开启无障碍设置再试 若仍有问题 请开启开发者测试模式后将详细日志反馈一下 感谢支持
