### ISSUE TITLE
脚本运行出错，日志如图

### ISSUE THREAD

**Issue by xiaojunheng** [SuperMonster003/Auto.js_Projects#59]
![微信图片_20190703104551](https://user-images.githubusercontent.com/16402651/60559690-d915c200-9d7f-11e9-839a-9a108d4d34ff.png)

最后停留在排行榜界面

**Comment by xiaojunheng** [comment]
getCurrentScreenTargets
这个函数抛出的错误

**Comment by xiaojunheng** [comment]
mix2s MIUI 10.3.2

**Comment by SuperMonster003** [comment]
已于 `v1.8.0` 尝试修复此问题 如果此问题复现 请重新开贴反馈  
感谢支持 此Issue暂时关闭
