### ISSUE TITLE
进到好友的收能量界面不收取能量

### ISSUE THREAD

**Issue by mrf881** [SuperMonster003/Auto.js_Projects#60]
进入好友的森林后，不收取能量，日志显示无能量球可操作

**Comment by mrf881** [comment]
<img src="https://s2.ax1x.com/2019/07/03/ZtaDdf.jpg" alt="ZtaDdf.jpg" border="0" />

**Comment by SuperMonster003** [comment]
`v1.8.0` 已尝试修复此问题  
如问题复现 可重新开贴反馈  
感谢支持 此Issue暂时关闭
