### ISSUE TITLE
设了定时任务后进入到排行榜页面不操作

### ISSUE THREAD

**Issue by sunny12005** [SuperMonster003/Auto.js_Projects#61]
autojs版本4.1.0alpha5...三星s10安卓9
![Screenshot_20190711-080034_Autojs](https://user-images.githubusercontent.com/52766964/61015532-99be2580-a3be-11e9-8a09-7b302aa3e236.jpg)
日志如图。我设置的监测时间是7分到8分，为什么有时会延迟6分钟呢？而且我自己点运行这个脚本的话是没问题的。

**Comment by SuperMonster003** [comment]
延迟是无法避免的 因为AJ的wakelock因种种原因受到限制 因此可能无法准时完成定时任务的执行  
可以尝试一下 `v1.8.0`  
如果问题复现 可继续反馈 感谢支持
