### ISSUE TITLE
v1.8.0 遇到能量罩直接退出

### ISSUE THREAD

**Issue by ljx0623** [SuperMonster003/Auto.js_Projects#64]
v1.8.0 遇到好友能量罩直接结束任务，导致后面的无法收取~

**Comment by SuperMonster003** [comment]
请反馈一下日志截图 感谢支持

**Comment by ljx0623** [comment]
就是正常那种退出~

**Comment by SuperMonster003** [comment]
好的 我这两天测试一下 尽快解决这个问题 另外可以通过回退版本 或者手动添加好友黑名单的方式尝试避免此问题 另外问一下 
你使用的排行榜样本采集策略是图像识别还是布局分析

**Comment by ljx0623** [comment]
不知道啊，应该是默认的吧，我没改过任何东西~

**Comment by SuperMonster003** [comment]
好的 明白了

**Comment by SuperMonster003** [comment]
已测试 未发现问题 也未发现其他用户反馈类似问题 建议开启开发者测试模式 然后提供详细的日志截图 感谢支持

**Comment by SuperMonster003** [comment]
此 Issue 暂时关闭 如有问题 请重新反馈 感谢支持
