### ISSUE TITLE
滑动朋友列表到收取能量时，没有点进去用户

### ISSUE THREAD

**Issue by PikachuWu** [SuperMonster003/Auto.js_Projects#68]
日志显示错误
java.lang.IllegalArgumentException:Path bounds must not be negative

**Comment by SuperMonster003** [comment]
用户在屏幕底部吗，开启开发者测试模式后提供详细的日志截图

**Comment by PikachuWu** [comment]
现在是卡住了，我打开了开发者测试模式后显示如下
![image](https://user-images.githubusercontent.com/13596426/62026023-637d0480-b20c-11e9-94ad-defb319bfa5d.png)

**Comment by SuperMonster003** [comment]
无障碍服务的功能方法无效 无法完成基于无障碍的滑动 点击 此问题无解 请查看或检查auto.js无障碍设置以及与系统的兼容性

**Comment by c939984606** [comment]
我发现向下翻页后，第一个好友有能量就无法收取，直接循环三次退出

**Comment by SuperMonster003** [comment]
@c939984606 提供一下报错日志
