### ISSUE TITLE
1.8.2版本启动进入蚂蚁森林界面点击自己能量后返回到支付宝首页

### ISSUE THREAD

**Issue by yyylly** [SuperMonster003/Auto.js_Projects#70]
Code version：1.8.2
设备：荣耀V10 EMUI 9.0
支付宝：最新版本
问题：
1、启动进入蚂蚁森林界面点击自己能量后返回到支付宝首页。
2、在首页停留约5-8s后，直接进入了排行榜，循环检测排行榜。
3、重复步骤2

不知道逻辑是不是就这样哈，1.8版本后经常自动解锁失败，等抓到日志再反馈下，大约是什么图层消除失败

**Comment by yyylly** [comment]
![TIM图片20190801111442](https://user-images.githubusercontent.com/35446057/62263085-93671a80-b44d-11e9-9323-f0918c502725.jpg)

**Comment by SuperMonster003** [comment]
第一个问题已经收录，下一版修复，第二个问题我抽空看一下解锁模块的代码变更，如果你能定位到问题根源，那再好不过

**Comment by yyylly** [comment]
![( @EW1T2Y@UZ US8BDBNMXT](https://user-images.githubusercontent.com/35446057/62595700-f8b98080-b911-11e9-9577-6b098ca5e440.png)
解锁失败原因是**匹配错解锁控件**了。设备信息请看task description

**Comment by yyylly** [comment]
按理应该匹配到emui的解锁控件，实际上匹配到了小米的。
但有时候又能解锁成功------一直没拿到这块的log。
MODULE_UNLOCK.js    function checkPreviewContainer()  line:63

**Comment by yyylly** [comment]
总结下v 1.8.2大概率出现的问题：
1、**华为手机解锁失败，原因如上述comment。**
2、排行榜滑到有好友能量可收取，一直停留再次。log显示进入好友界面耗时超时，具体得多抓些log看看先。
3、无限进入好友界面（无论是否有能量可收取），怀疑是排行榜滑动function导致，当触发单击时没有拖动导致变成了点击事件。
4、**进入蚂蚁森林后，随即返回首页，然后进入排行榜。 大大已记录问题**

**Comment by SuperMonster003** [comment]
感谢反馈  

`1`  
解锁分为三步 亮屏 消除提示层露出解锁控件 基于解锁控件点击或输入密码以解锁  
消除提示层的前提是检测到提示层控件  
通过一系列正则匹配能看出 其实很多设备即便型号不同 控件id是会出现相似甚至相同情况的  
因此无论匹配到哪个控件 都是为了识别当前所在页面是否为提示层页面 从而决定是否需要消除提示层  
消除失败的原因可能是无障碍功能失效导致滑动功能失效  
也可能是起点位置包含进了可拖动/可点击的功能性控件区域  
还有可能是滑动时间过短/滑动需要惯性/其他置顶性控件遮挡 (如QQ消息提示/音乐播放器控制控件)  
众多原因都有可能导致提示层消除失败 (消除失败后可以查看失败时的屏幕截图获取可用信息)  
建议通过日志/截图以及自行测试寻找可能的原因  

`2`  
很有可能是无障碍功能失效导致点击功能失效 (此预想与 `1` 有重叠)  

`3`  
此问题可能性较多 暂时不做过多分析 下一版会尝试增强兼容性尽量避免此问题  
如正式版发布后问题复现 可继续反馈  
另可尝试使用"图像识别"排行榜采集策略  

`4`  
此问题测试版已解决 请等待正式版发布

**Comment by yyylly** [comment]
> 可能是滑动时间过短/滑动需要惯性/其他置顶性控件遮挡 (如QQ消息提示/音乐播放器控制控件)

解锁失败在1.8版本前几乎不会出现，我早上定时了两个任务，一个run旧版本，一个run新版本，旧版本每次都成功，新版本经常失败。

**Comment by SuperMonster003** [comment]
好，我比较一下新旧版diff，下一版会尝试增强兼容性

**Comment by sanmoking** [comment]
华为手机充电时会显示充电动画，是另外的一个层，不过仅仅显示几秒，正好遇上解锁的话就无法解锁，不过这个几率太小。我自己是加了一句监测颜色来判断的：
手机屏幕1080,2340；监测坐标540,2315；充电颜色#ff00d659；如果检测坐标有这个颜色就多加一个上滑动作和点击5,10的动作。
另外极特殊的情况下，检测不到密码提示层，我加了一句右下角相机图标的白色颜色监测。

**Comment by SuperMonster003** [comment]
已于 `v1.8.3` 尝试修复此问题  
此 Issue 暂时关闭  
如问题复现或出现新问题 可重新反馈 感谢支持
