### ISSUE TITLE
荣耀9 安卓9.0.1 一直显示错误

### ISSUE THREAD

**Issue by xifan-fh** [SuperMonster003/Auto.js_Projects#71]
![image](https://user-images.githubusercontent.com/38284308/62383850-60bf3e00-b583-11e9-9b61-ba95920ed3ae.png)

**Comment by SuperMonster003** [comment]
项目文件不完整，按操作流程操作，不要使用导入功能

**Comment by yyylly** [comment]
@xifan-fh auto.js 左上角点击三行的图标，进入设置，你在《更改脚本文件夹路径》可以看到具体路径，你把代码解压到这个文件夹里面，auto.js主页界面下拉刷新就可以load出来了。

**Comment by xifan-fh** [comment]
> @ xifan -fh auto.js左上角点击三行的图标，进入设置，你在“更改脚本文件夹路径”可以看到具体路径，你把代码解压到这个文件夹里面，auto.js主页界面下拉刷新就可以负载出来了。

谢谢,我以为是自己创建文件夹,然后把文件解压进自己新建的文件夹就可以了
