### ISSUE TITLE
无限进入在顶部的同一个好友主页

### ISSUE THREAD

**Issue by Zhang-Ingram** [SuperMonster003/Auto.js_Projects#72]
![0a621d759cdd875f9e322fe219267e9](https://user-images.githubusercontent.com/33376293/62406058-d0f7af00-b5d7-11e9-8e6f-3f9d2181ba34.jpg)
![ef8a29d05453dc802edf69e22e9ff40](https://user-images.githubusercontent.com/33376293/62406060-d5bc6300-b5d7-11e9-8dfe-94b15501674f.jpg)
![c2d44e4672b2291c0f59bc22050b745](https://user-images.githubusercontent.com/33376293/62406063-d8b75380-b5d7-11e9-96a1-9ddb1b61b701.jpg)
如图所示，无限进入顶部的好友主页（林楚成），我自己滑动了一下，他无限就进入当前页面顶部的好友主页

**Comment by Zhang-Ingram** [comment]
貌似很多小问题都存在于好友列表的顶部和底部，能否通过两次不同的滑动距离降低此类错误发生？
例如：第一次滑动距离500，第二次550，这样双重检查能降低此类错误发生的概率吗？

**Comment by SuperMonster003** [comment]
开启开发者测试模式后反馈详细日志

**Comment by Zhang-Ingram** [comment]
> 
> 
> 开启开发者测试模式后反馈详细日志

是当那个好友有倒计时能量才会出现此问题，详细日志等下次出现问题我再发出来吧

**Comment by Zhang-Ingram** [comment]
> 
> 
> 开启开发者测试模式后反馈详细日志

请问怎样查看详细日志，手机是没有ROOT的

**Comment by SuperMonster003** [comment]
运行 Ant_Forest_Settings.js 然后在消息提示页面勾选开发者测试模式 运行一次脚本 
在Auto.js主页面右上角日志图标点击后可查看日志 反馈出现异常或存在潜在异常部分的日志截图

**Comment by Zhang-Ingram** [comment]
> 
> 运行 Ant_Forest_Settings.js 然后在消息提示页面勾选开发者测试模式 运行一次脚本 在Auto.js主页面右上角日志图标点击后可查看日志 反馈出现异常或存在潜在异常部分的日志截图
> […](#)
> On August 4, 2019 11:30:54 Zhang-Ingram ***@***.***> wrote: 开启开发者测试模式后反馈详细日志 请问怎样查看详细日志，手机是没有ROOT的 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

无限进入同一个好友的主页，这个好友有在倒计时的能量会出现此BUG。（日志显示他在进入不同好友的主页，显示点击的顺序是从排行榜第一个依次往下进入，但实际不是）
PS：这个好友也恰好是滑动后排在顶部的那个，不知道有没有关系
完整截图：
![图片](https://user-images.githubusercontent.com/33376293/62423585-dac30480-b6f4-11e9-8e57-aeebb00a4de3.png)

**Comment by SuperMonster003** [comment]
已记录 下一版尝试修复此问题 另外可尝试更改采集策略为图像识别 看是否可避免此问题

**Comment by Zhang-Ingram** [comment]
> 
> 已记录 下一版尝试修复此问题 另外可尝试更改采集策略为图像识别 看是否可避免此问题
> […](#)
> On August 4, 2019 20:17:28 Zhang-Ingram ***@***.***> wrote: 运行 Ant_Forest_Settings.js 然后在消息提示页面勾选开发者测试模式 运行一次脚本 在Auto.js主页面右上角日志图标点击后可查看日志 反馈出现异常或存在潜在异常部分的日志截图 … On August 4, 2019 11:30:54 Zhang-Ingram @.***> wrote: 开启开发者测试模式后反馈详细日志 请问怎样查看详细日志，手机是没有ROOT的 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread. 无限进入同一个好友的主页，这个好友有在倒计时的能量会出现此BUG。（日志显示他在进入不同好友的主页，显示点击的顺序是从排行榜第一个依次往下进入，但实际不是） PS：这个好友也恰好是滑动后排在顶部的那个，不知道有没有关系 完整截图： — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.



> 
> 已记录 下一版尝试修复此问题 另外可尝试更改采集策略为图像识别 看是否可避免此问题
> […](#)
> On August 4, 2019 20:17:28 Zhang-Ingram ***@***.***> wrote: 运行 Ant_Forest_Settings.js 然后在消息提示页面勾选开发者测试模式 运行一次脚本 在Auto.js主页面右上角日志图标点击后可查看日志 反馈出现异常或存在潜在异常部分的日志截图 … On August 4, 2019 11:30:54 Zhang-Ingram @.***> wrote: 开启开发者测试模式后反馈详细日志 请问怎样查看详细日志，手机是没有ROOT的 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread. 无限进入同一个好友的主页，这个好友有在倒计时的能量会出现此BUG。（日志显示他在进入不同好友的主页，显示点击的顺序是从排行榜第一个依次往下进入，但实际不是） PS：这个好友也恰好是滑动后排在顶部的那个，不知道有没有关系 完整截图： — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

图像识别的话不会出现，想问一下图片会保存到哪里？手机貌似没找到图片

**Comment by SuperMonster003** [comment]
图像识别原理不是存储图片

**Comment by Zhang-Ingram** [comment]
> 
> 图像识别原理不是存储图片
> […](#)
> On August 4, 2019 20:32:27 Zhang-Ingram ***@***.***> wrote: 已记录 下一版尝试修复此问题 另外可尝试更改采集策略为图像识别 看是否可避免此问题 … On August 4, 2019 20:17:28 Zhang-Ingram @.> wrote: 运行 Ant_Forest_Settings.js 然后在消息提示页面勾选开发者测试模式 运行一次脚本 在Auto.js主页面右上角日志图标点击后可查看日志 反馈出现异常或存在潜在异常部分的日志截图 … On August 4, 2019 11:30:54 Zhang-Ingram @.> wrote: 开启开发者测试模式后反馈详细日志 请问怎样查看详细日志，手机是没有ROOT的 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread. 无限进入同一个好友的主页，这个好友有在倒计时的能量会出现此BUG。（日志显示他在进入不同好友的主页，显示点击的顺序是从排行榜第一个依次往下进入，但实际不是） PS：这个好友也恰好是滑动后排在顶部的那个，不知道有没有关系 完整截图： — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread. 已记录 下一版尝试修复此问题 另外可尝试更改采集策略为图像识别 看是否可避免此问题 … On August 4, 2019 20:17:28 Zhang-Ingram @.> wrote: 运行 Ant_Forest_Settings.js 然后在消息提示页面勾选开发者测试模式 运行一次脚本 在Auto.js主页面右上角日志图标点击后可查看日志 反馈出现异常或存在潜在异常部分的日志截图 … On August 4, 2019 11:30:54 Zhang-Ingram @.> wrote: 开启开发者测试模式后反馈详细日志 请问怎样查看详细日志，手机是没有ROOT的 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread. 无限进入同一个好友的主页，这个好友有在倒计时的能量会出现此BUG。（日志显示他在进入不同好友的主页，显示点击的顺序是从排行榜第一个依次往下进入，但实际不是） PS：这个好友也恰好是滑动后排在顶部的那个，不知道有没有关系 完整截图： — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread. 图像识别的话不会出现，想问一下图片会保存到哪里？手机貌似没找到图片 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

1.83版本的仍存在此问题，图像识别可恢复正常。

**Comment by SuperMonster003** [comment]
`v1.9.5` 已尝试修复上述问题 如使用后问题复现 可继续反馈
