### ISSUE TITLE
小米Mix2S无法启动Ant_Forest_Settings，会报错

### ISSUE THREAD

**Issue by comeheres** [SuperMonster003/Auto.js_Projects#73]
![Screenshot_2019-08-03-18-13-57-361_org autojs autojspro](https://user-images.githubusercontent.com/1575451/62410685-f60e1100-b61b-11e9-87a2-b9a9d0fa442e.png)
偷能量运行正常，但一启动Ant_Forest_Settings.js就报错，日志如图

**Comment by comeheres** [comment]
这个是VSC上的另一次log记录

18:08:28.159/V: 开始运行[/storage/emulated/0/脚本/1.8.2/Ant_Forest_Launcher.js]
18:08:29.728/D: --------------------------------
18:08:29.728/V: >> com.stardust.autojs.runtime.exception.ScriptInterruptedException: null
18:08:29.729/W: 开发者测试模式已自动开启
18:08:29.728/W: 模块导入功能异常
18:08:29.731/V: 
------------
[/storage/emulated/0/脚本/1.8.2/Ant_Forest_Launcher.js]运行结束，用时1.572000秒
18:08:29.907/V: 开始运行[/storage/emulated/0/脚本/1.8.2/Ant_Forest_Settings.js]
18:08:30.809/V: 
------------
[/storage/emulated/0/脚本/1.8.2/Ant_Forest_Settings.js]运行结束，用时0.901000秒
18:08:30.809/E: java.lang.Boolean cannot be cast to android.content.pm.ApplicationInfo

java.lang.ClassCastException: java.lang.Boolean cannot be cast to android.content.pm.ApplicationInfo
	at com.stardust.autojs.engine.RhinoJavaScriptEngine$WrapFactory.wrapAsJavaObject(Unknown Source:63)
	at org.mozilla.javascript.WrapFactory.wrap(Unknown Source:93)
	at com.stardust.autojs.engine.RhinoJavaScriptEngine$WrapFactory.wrap(Unknown Source:47)
	at org.mozilla.javascript.NativeJavaArray.get(Unknown Source:22)
	at org.mozilla.javascript.ScriptableObject.getProperty(Unknown Source:1)

**Comment by SuperMonster003** [comment]
Auto.js版本是多少

**Comment by comeheres** [comment]
> Auto.js版本是多少

Pro 7.0.4-1

**Comment by SuperMonster003** [comment]
试试免费版 v4.1.1 Alpha2

**Comment by comeheres** [comment]
> 试试免费版 v4.1.1 Alpha2
> […](#)
> On August 3, 2019 19:06:13 comeheres ***@***.***> wrote: Auto.js版本是多少 Pro 7.0.4-1 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

这个版本可以，都没问题

**Comment by SuperMonster003** [comment]
Pro 7.0.4-0 有此问题 升级至7.0.4-1测试后发现问题修复 但可能需要全新安装 可尝试全新安装Pro最新版

**Comment by comeheres** [comment]
> Pro 7.0.4-0 有此问题 升级至7.0.4-1测试后发现问题修复 但可能需要全新安装 可尝试全新安装Pro最新版
> […](#)
> On August 3, 2019 19:27:04 comeheres ***@***.***> wrote: 试试免费版 v4.1.1 Alpha2 … On August 3, 2019 19:06:13 comeheres @.***> wrote: Auto.js版本是多少 Pro 7.0.4-1 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread. 这个版本可以，都没问题 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

7.0.4-1卸载重新安装下，就正常了，非常感谢！
