### ISSUE TITLE
魅族16th 好友列表有30+，但下拉最多偷取能量到第19个，不会继续向下拉列表继续偷取能量

### ISSUE THREAD

**Issue by Hope-cool** [SuperMonster003/Auto.js_Projects#74]

**Comment by SuperMonster003** [comment]
下一版尝试修复

**Comment by Hope-cool** [comment]
现在1.8.3版本不能自动解锁，我1.8.2版本还可以自动解锁。1.8.3版本它会停留在亮屏界面，不会上滑进入密码解锁界面，导致不能自动执行接下来的程序，需我手动上滑，才能自动输入密码解锁，执行接下来的程序

**Comment by SuperMonster003** [comment]
运行 `Ant_Forest_Settings.js`  
消息提示 -> 开发者测试模式 (勾选)  
然后测试自动解锁功能 (此时日志会显示详细的操作信息)  
等待 1-2 分钟后 若上滑屏幕依然无动作或上滑不成功 可强制结束脚本 然后反馈日志  
感谢支持

**Comment by SuperMonster003** [comment]
@Hope-cool 将上滑时长修改为120或130后再尝试 如果依然失败 可尝试还原全部设置后重新配置 `Ant_Forest_Settings.js`

**Comment by yeziyela** [comment]
老哥，今早更新1.9.2以后，好友页面无法自动下滑了，收了两个自动不收了，魅族16x 体验版flyme8

**Comment by SuperMonster003** [comment]
`v1.9.5` 已尝试修复上述问题 如使用后问题复现 可继续反馈
