### ISSUE TITLE
明白为什么华为手机无法解锁了

### ISSUE THREAD

**Issue by 418466788** [SuperMonster003/Auto.js_Projects#75]
![微信图片_20190805105526](https://user-images.githubusercontent.com/53737162/62443356-45c01a00-b78d-11e9-9b15-4be18974bac1.JPG)

华为手机唤醒的向上滑动是在红圈部分，可是华为手机的红圈部分向上滑动是其他功能的交互，所以无法唤醒。
*解锁办法，向上滑动换一个地方，离开底部红圈范围
图片不知道怎么无法上传，红圈部分就是黑屏界面唤醒后，屏幕底部往上大约1cm以内的范围，这个范围内向上滑动是跳到解锁功能页面（计算器，手电动这类的），手动在其他地方向上滑动正常出现解锁画面会自动输密码解锁

**Comment by SuperMonster003** [comment]
感谢提供思路

**Comment by yyylly** [comment]
我定位到是因为匹配错解锁控件了。详情请看task ID: 70

**Comment by SuperMonster003** [comment]
`v1.8.3` 已增加解锁提示层页面滑动起止点位置配置  
此 Issue 暂时关闭  
如有问题 请重新反馈 感谢支持
