### ISSUE TITLE
希望能够加入采集结束后是否关闭(退出支)付宝的选项

### ISSUE THREAD

**Issue by xseven007** [SuperMonster003/Auto.js_Projects#76]
在Ant_Forest_Launcher.js文件的第2352行。function endAlipay函数，应该可以设置为是否杀死支付宝进程，如果是，就killThisApp(alipay_pkg_name);，如果不杀死，就使用back();退出到上一级。

**Comment by Zhang-Ingram** [comment]
我也希望能自己设置是否杀掉支付宝，支付宝太耗电了，就早上6.30-8点能让我掉20%的电，看电池使用详情，支付宝耗电是AUTO.JS的5倍

**Comment by xseven007** [comment]
@Zhang-Ingram 然而，有时候你却想让它保留支付宝进程。在设置中加入是否脚本完成时结束支付宝，这样是一个好方案。

**Comment by SuperMonster003** [comment]
已记录 下一版增加脚本结束时"'支付宝'应用保留方式"选项

**Comment by SuperMonster003** [comment]
`v1.8.3` 已增加相关选项配置  
此 Issue 暂时关闭  
如有问题 请重新反馈 感谢支持
