### ISSUE TITLE
小米mix2s进入排行榜后报错

### ISSUE THREAD

**Issue by zhanggh8023** [SuperMonster003/Auto.js_Projects#77]
16:15:52.770/E: java.lang.RuntimeException: java.lang.InterruptedException

**Comment by SuperMonster003** [comment]
请反馈详细的日志截图

**Comment by zhanggh8023** [comment]
![Screenshot_2019-08-08-16-25-03-600_org autojs autojs](https://user-images.githubusercontent.com/40562196/62687299-19103a80-b9f9-11e9-84af-8415362deb8c.png)

**Comment by zhanggh8023** [comment]
![image](https://user-images.githubusercontent.com/40562196/62687374-45c45200-b9f9-11e9-8bbb-19094a44067c.png)

**Comment by SuperMonster003** [comment]
运行 `Ant_Forest_Settings.js` 后进行如下设置  
1. 消息提示 - 开发者测试模式 ( 勾选 )  
2. 脚本运行安全 - 运行失败自动重试 ( 设置 `0` 值 )    

保存后再次运行 `Ant_Forest_Launcher.js` ( 启动器脚本 )  
然后再次反馈更详细的报错日志

**Comment by zhanggh8023** [comment]
![image](https://user-images.githubusercontent.com/40562196/62687980-6e008080-b9fa-11e9-8895-9f863f31fb4f.png)

**Comment by zhanggh8023** [comment]
![image](https://user-images.githubusercontent.com/40562196/62688658-d9971d80-b9fb-11e9-9119-0345b2a102b2.png)

**Comment by SuperMonster003** [comment]
http://tieba.baidu.com/p/6155304736
试试这个能不能解决截图权限申请失败的问题

**Comment by zhanggh8023** [comment]
优秀，非常感谢你的解答，我会关注的，今后希望能帮上忙

**Comment by SuperMonster003** [comment]
感谢支持
之前做的设置修改可根据需求复原或保留
