### ISSUE TITLE
魅族16X自动解锁后打开支付宝失败

### ISSUE THREAD

**Issue by MagicYuze** [SuperMonster003/Auto.js_Projects#80]
魅族16X脚本成功解锁后没反应，日志提示打开支付宝失败。已解锁状态下脚本没问题，用脚本解锁就不行。楼主有空帮忙看下哈
![S90812-17031348](https://user-images.githubusercontent.com/24842683/62855466-e467f000-bd24-11e9-9a2f-f14f85e8db81.jpg)

![S90812-17171026](https://user-images.githubusercontent.com/24842683/62855530-1c6f3300-bd25-11e9-86ed-3927e8b82de9.png)

日志就停在红线前不动了
如果我手动打开支付宝的话就还能正常运行。

如果我锁屏前打开支付宝（保持在前台界面），解锁后可以直接运行脚本。如果支付宝在后台运行的话，也是不行的。

感觉可能是模块出了点问题，因为我引用你的解锁模块解锁以后，直接launchApp("支付宝");也是打不开的。

**Comment by SuperMonster003** [comment]
感谢反馈  
有不少人都反馈过这个问题 不过都是最近反馈的 而且其他项目也有人反馈类似问题  
感觉是Alipay增强了安全限制 其他APP使用Schema方式唤起Alipay受限制 (仅仅是猜测)  

可以尝试以下方法  

引用解锁模块解锁以后  
执行 `app.launchPackage("org.autojs.autojs");`  
或 `app.launchApp("Auto.js");`  
然后再 `launchApp("支付宝");`  
看能否按预期实现 "先唤起Auto.js然后间接唤起Alipay"

如果多次测试均可成功  
我会在下一版加入类似代码实现间接启动Alipay  
🙂

**Comment by MagicYuze** [comment]
这样就可以啦，谢谢大佬。😘

还有个问题就是，想要这个脚本调用你的时间模块。就是想运行完一次脚本之后，设置新的auto.js定时任务，之前没咋接触过auto.js，，看了下文档，好像没有提到怎样设置这种定时任务😞

**Comment by SuperMonster003** [comment]
欢迎体验测试版 看打开支付宝失败的问题是否复现  
https://github.com/SuperMonster003/Auto.js_Projects/issues/82#issuecomment-521572338
另外定时任务的使用示例可参阅Ant_Forest_Launcher.js源码 或自行研究模块中包含的方法  
感谢支持

**Comment by SuperMonster003** [comment]
`v1.8.4` 已通过"启动跳板"功能解决此类问题 欢迎体验并反馈  
如问题复现或出现新的问题 请重新反馈 此 Issue 暂时关闭 感谢支持
