### ISSUE TITLE
小米9 1.8.3 报错

### ISSUE THREAD

**Issue by wyfang** [SuperMonster003/Auto.js_Projects#81]
首先很激动发现小米9已经可以自动解锁了，之前一直用的1.8.0，不仅不能解锁，而且有概率会卡住，循环进入一个没有能量的人，这样死循环。

1.8.3刚刚下，发现可以解锁，然后就放着运行了，之后发现循环进入好友列表，然后重复这样，停止运行后，看到日志如下：
![Screenshot_2019-08-13-17-26-52-591_org autojs aut](https://user-images.githubusercontent.com/17900420/62931056-3c1f5d80-bdf0-11e9-91be-d3212d643b6f.png)

以及我想问下，如果比如晚上20点的时候运行了一下，那么第二天7点，是不是也会自动解锁？
还是说需要自己手动加个audojs的7点定时运行？

**Comment by SuperMonster003** [comment]
此错误属于视觉库断言异常 目前可暂时尝试使用"图像识别"的排行榜采集策略  
另外如果设置了定时任务自动管理 脚本会根据你的设置自动设置下次运行的定时任务  
请参阅 `Ant_Forest_Settings.js` 相关配置页面的说明 另可在 `Auto.js` 的"管理"页面查看或管理定时任务

**Comment by pc931225** [comment]
荣耀 20 pro 进入好友森林超时  是什么问题

**Comment by SuperMonster003** [comment]
`v1.9.5` 已尝试修复上述问题 如使用后问题复现 可继续反馈
