### ISSUE TITLE
重复进入排行榜

### ISSUE THREAD

**Issue by ljx0623** [SuperMonster003/Auto.js_Projects#82]
Code version：1.8.0+
设备：小米5
系统版本： MIUI 10.2
支付宝：10.1.70

现象：
1、在首页停留约5-8s，
2、进入了排行榜，滑动一页（约8人），停留2-3秒
3、重复2三次后结束程序

附件：
这是“布局分析”下的日志，因为改成“图像识别”之后，现象一样，就没有再截一遍~
[日志.zip](https://github.com/SuperMonster003/Auto.js_Projects/files/3500450/default.zip)

补充：
这次的问题其实跟[#64 ](https://github.com/SuperMonster003/Auto.js_Projects/issues/64)一样，上次是因为保护罩好友刚好在第一页，导致现象描述有误，误导了作者，并且我在还原成v1.7.1之后没有跟进。
现在v1.7.1版本也出现了点小问题，所以厚颜再反馈一遍，在此向作者致以诚恳的歉意！

**Comment by ljx0623** [comment]
> Code version：1.8.0+
> 设备：小米5
> 系统版本： MIUI 10.2
> 支付宝：10.1.70
> 
> 现象：
> 1、在首页停留约5-8s， 2、进入了排行榜，滑动一页（约8人），停留2-3秒
> 3、重复2三次后结束程序
> 
> 附件：
> 这是“布局分析”下的日志，因为改成“图像识别”之后，现象一样，就没有再截一遍~
> [日志.zip](https://github.com/SuperMonster003/Auto.js_Projects/files/3500450/default.zip)
> 
> 补充：
> 这次的问题其实跟[64](url)一样，上次是因为保护罩好友刚好在第一页，导致现象描述有误，误导了作者，并且我在还原成v1.7.1之后没有跟进。
> 现在v1.7.1版本也出现了点小问题，所以厚颜再反馈一遍，在此向作者致以诚恳的歉意！

**Comment by SuperMonster003** [comment]
首页停留 测试版我加了更详细的开发者日志 可以查看哪里导致了卡顿  
另外排行榜滑动提前结束问题 初步估计是底部图片模板的问题 可以将模板删除再运行脚本  

测试版下载: [Aug_15_a.zip](https://github.com/SuperMonster003/Auto.js_Projects/files/3504956/Aug_15_a.zip)

**Comment by ljx0623** [comment]
首页停留问题：应该是红框的地方耗时比较久
![Screenshot_2019-08-15-22-21-01-738_org autojs aut](https://user-images.githubusercontent.com/8985184/63107682-fad9aa00-bfb7-11e9-86c3-a5bec214553a.png)
排行榜提前结束问题：已解决
新问题：作者新增加了好友复查功能？满足底部条件，然后循环2、3次，每次循环就重新打开一次排行榜
![Screenshot_2019-08-15-23-57-51-568_org autojs aut](https://user-images.githubusercontent.com/8985184/63108368-42146a80-bfb9-11e9-8a7c-f483afe09e1b.png)

**Comment by SuperMonster003** [comment]
可尝试新的测试版  
[Aug_16_a.zip](https://github.com/SuperMonster003/Auto.js_Projects/files/3508150/Aug_16_a.zip)

另外复查功能请参阅 Ant_Forest_Settings.js 项目配置脚本中相关功能的"帮助与支持"内容

**Comment by SuperMonster003** [comment]
![WeChat Image_20190816131938](https://user-images.githubusercontent.com/30370009/63145140-c5b97000-c028-11e9-9518-9dd2daf92297.png)

**Comment by ljx0623** [comment]
v1.8.4 暂时没什么大问题了，衷心感谢作者！~
