### ISSUE TITLE
小米5进入好友页，出现InteruptedException

### ISSUE THREAD

**Issue by Oays** [SuperMonster003/Auto.js_Projects#83]
小米5，没root，进入好友列表出现java.lang.interuptedException

**Comment by Oays** [comment]
版本：4.1.1 Alpha2 + v1.8.3

**Comment by SuperMonster003** [comment]
https://github.com/SuperMonster003/Auto.js_Projects/issues/77#issuecomment-519432821

**Comment by Oays** [comment]
谢谢大佬，完美解决

-
