### ISSUE TITLE
vivo x20 plus 不能收取能量

### ISSUE THREAD

**Issue by sunqintao** [SuperMonster003/Auto.js_Projects#85]
进入到朋友列表后，弹出报错窗，Ant_Forest_Launcher.js #89报错。

**Comment by SuperMonster003** [comment]
请提供报错日志截图

**Comment by sunqintao** [comment]
auto.js 在编辑 Ant_Forest_launcher.js， 日志打开就报错，我也头疼。

Version: 461
Android: 27
android.os.TransactionTooLargeException: data parcel size 679648 bytes
java.lang.RuntimeException:android.os.TransactionTooLargeException: data parcel size 679648 bytes
android.app.ActivityThread$StopInfo.run(ActivityThread.java:4169)
......
Caused by:
android.os.TransactionTooLargeException:data parcel size 679648 bytes
android.os.BinderProxy.transactNative(Native Method)
android.os.BinderProxy.transact(Binder.java:802)
android.app.IActivityManager$Stub$Proxy.activityStopped(IActivityManager.java:4914)
android.app.ActivityThread$StopInfo.run(ActivityThread.java:4153)
android.os.Handler.handleCallback(Handler.java:790)
android.os.Handler.dispatchMessage(Handler.java:99)
android.os.Looper.loop(Looper.java:192)
android.app.ActivityThread.main(ActivityThread.java:6809)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:825)

**Comment by SuperMonster003** [comment]
可使用console模块的setGlobalLogConfig()方法将日志保存到指定目录  
运行项目 在出错后查看日志文件中的内容 并反馈关键日志

**Comment by sunqintao** [comment]
07:08:48.656/D: --------------------------------
07:08:48.658/D: 开始"蚂蚁森林"任务
07:08:48.659/D: --------------------------------
07:09:44.961/D: --------------------------------
07:09:44.962/D: 开始"蚂蚁森林"任务
07:09:44.964/D: --------------------------------
07:10:40.335/V: >> 开发者测试模式已自动开启
07:10:40.340/V: >> 截图权限申请结果: 失败
07:10:40.343/V: >> 重启当前引擎任务
07:10:40.347/V: >>> 当前次数: 1
07:10:40.351/V: >>> 最大次数: 3
07:10:40.356/V: >> 运行新引擎任务:
/storage/emulated/0/脚本/Auto.js_Projects-Ant_Forest/Ant_Forest_Launcher.js
07:10:40.379/V: >> 强制停止旧引擎任务
07:10:40.389/E: JavaException: java.lang.RuntimeException: java.lang.InterruptedException (/storage/emulated/0/脚本/Auto.js_Projects-Ant_Forest/Ant_Forest_Launcher.js#92)
JavaException: java.lang.RuntimeException: java.lang.InterruptedException
    at antForest (/storage/emulated/0/脚本/Auto.js_Projects-Ant_Forest/Ant_Forest_Launcher.js:92:0)
    at /storage/emulated/0/脚本/Auto.js_Projects-Ant_Forest/Ant_Forest_Launcher.js:69:0

07:10:40.393/V:

**Comment by SuperMonster003** [comment]
截图中我只看到了截图权限申请失败的问题  
以及旧任务停止时可能误杀了当前任务的问题  

第一个我无法通过代码解决 通常可能是权限设置问题  
第二个问题下一版会修复  

可尝试查看与 `Auto.js` 相关的权限设置  
然后尝试重新启动设置 或强制重启 `Auto.js` 软件  
然后重新运行项目  
如问题复现 请重新反馈  
感谢支持

**Comment by sunqintao** [comment]
15:41:07.636/D: --------------------------------
15:41:07.638/D: 开始"蚂蚁森林"任务
15:41:07.640/D: --------------------------------
15:41:34.205/V: >> 开发者测试模式已自动开启
15:41:34.210/V: >> 截图权限申请结果: 失败
15:41:34.213/V: >> 重启当前引擎任务
15:41:34.217/V: >>> 当前次数: 1
15:41:34.221/V: >>> 最大次数: 3
15:41:34.227/V: >> 运行新引擎任务:
/storage/emulated/0/脚本/Auto.js_Projects-Ant_Forest/Ant_Forest_Launcher.js
15:41:34.243/V: >> 强制停止旧引擎任务
15:41:34.263/E: JavaException: java.lang.RuntimeException: java.lang.InterruptedException (/storage/emulated/0/脚本/Auto.js_Projects-Ant_Forest/Ant_Forest_Launcher.js#89)
JavaException: java.lang.RuntimeException: java.lang.InterruptedException
    at antForest (/storage/emulated/0/脚本/Auto.js_Projects-Ant_Forest/Ant_Forest_Launcher.js:89:0)
    at /storage/emulated/0/脚本/Auto.js_Projects-Ant_Forest/Ant_Forest_Launcher.js:66:0

15:41:34.265/V: 
------------
[/storage/emulated/0/脚本/Auto.js_Projects-Ant_Forest/Ant_Forest_Launcher.js]运行结束，用时28.997000秒
15:41:34.483/V: 开始运行[/storage/emulated/0/脚本/Auto.js_Projects-Ant_Forest/Ant_Forest_Launcher.js]
15:41:40.225/D: --------------------------------
15:41:40.225/D: 开始"蚂蚁森林"任务
15:41:40.226/D: --------------------------------
15:41:46.535/V: 
------------
[/storage/emulated/0/脚本/Auto.js_Projects-Ant_Forest/Ant_Forest_Launcher.js]运行结束，用时12.050000秒

**Comment by sunqintao** [comment]
权限都给了，防截屏也关了，但还是同样的问题，

**Comment by SuperMonster003** [comment]
我也无能为力

**Comment by sunqintao** [comment]
我刚重置了下手机，把支付宝和auto.js装上，给了所有的权限，现在的问题是：到达收取好友列表，不能进入好友的页面收能量，一直卡在这里。

**Comment by SuperMonster003** [comment]
检查基于无障碍的方法是否可正常使用 如click() press() gesture()等 如基于无障碍服务的方法无问题 请反馈日志

**Comment by SuperMonster003** [comment]
此 Issue 暂时关闭  
如问题复现或出现新问题 可重新反馈 感谢支持
