### ISSUE TITLE
解锁失败无法判断当前解锁条件（小米）

### ISSUE THREAD

**Issue by CJW0716** [SuperMonster003/Auto.js_Projects#86]
![Screenshot_2019-08-21-08-12-16-114_org autojs aut](https://user-images.githubusercontent.com/49069371/63395601-cec68a80-c3f6-11e9-936f-ea9b887634d5.png)

**Comment by SuperMonster003** [comment]
可尝试使用 Tools/Inspect_Lock_Screen_Layout.js 反馈布局信息  
另外截图权限申请失败的问题 可参阅 https://github.com/SuperMonster003/Auto.js_Projects/issues/77#issuecomment-519432821

**Comment by CJW0716** [comment]
Tools/Inspect_Lock_Screen_Layout.js   找到这个了，但是没有提交反馈信息。找不到提交方式

**Comment by CJW0716** [comment]
那个截图权限是失败，那个允许后台弹出，一直是默认的，没有给关闭，就是还是在早上7点多的时候显示不出来。

**Comment by SuperMonster003** [comment]
运行后按提示上传 "!Debug_Info"

**Comment by SuperMonster003** [comment]
此 Issue 暂时关闭  
如问题复现或出现新问题 可重新反馈 感谢支持
