### ISSUE TITLE
进入好友森林超时

### ISSUE THREAD

**Issue by pc931225** [SuperMonster003/Auto.js_Projects#87]
进入好友森林超时

**Comment by SuperMonster003** [comment]
请提供报错日志截图

**Comment by pc931225** [comment]
![image](https://user-images.githubusercontent.com/20468610/63439749-37e2e800-c461-11e9-9325-6a1efc5f0c72.png)

**Comment by SuperMonster003** [comment]
控件变更 暂时无解

**Comment by wbg21** [comment]
![image](https://user-images.githubusercontent.com/55861485/65738571-e9d29b80-e114-11e9-8a9c-b8568505c855.png)
