### ISSUE TITLE
收能量球时，显示进入好友森林超时

### ISSUE THREAD

**Issue by CJW0716** [SuperMonster003/Auto.js_Projects#89]
![image](https://user-images.githubusercontent.com/49069371/63481760-23d2d100-c4c9-11e9-844b-91575e2faf51.png)

**Comment by SuperMonster003** [comment]
开启开发者测试模式后再反馈详细日志

**Comment by SuperMonster003** [comment]
运行 `Ant_Forest_Settings.js` -> ` 消息提示 ` -> 勾选 ` 开发者测试模式 `  
日志中会显示详细的操作信息 便于看到更详细的项目日志  
另重新反馈时可附上更详细的用户操作或项目运行情况等

**Comment by SuperMonster003** [comment]
此 Issue 暂时关闭  
如问题复现或出现新问题 可重新反馈 感谢支持
