### ISSUE TITLE
获取主页最小倒计时失败、列表下划出错

### ISSUE THREAD

**Issue by Zhang-Ingram** [SuperMonster003/Auto.js_Projects#90]
![图片](https://user-images.githubusercontent.com/33376293/63559900-5f7fa080-c586-11e9-8472-a29e52d9eb1f.png)
![图片](https://user-images.githubusercontent.com/33376293/63559907-64445480-c586-11e9-8c49-5391025f6290.png)

**Comment by Zhang-Ingram** [comment]
已经按提示修改了滑动的数据也是出错

**Comment by SuperMonster003** [comment]
自己倒计时不准确 通常是因为系统没有将支付宝的Toast捕获到 (例如测试得到 `Sony E6683` 可以获取`Titanium Backup` 的Toast 但无法获取 `Alipay` 的)  
目前正在寻找新的方案替代Toast方案 (暂时还没有找到)  
另外Toast与森林主页的绿树对话无关  
滑动失败的问题 请检查无障碍服务的方法是否可正常使用 如 press() click() gesture() swipe() 等  
初步估计是无障碍服务的问题
