### ISSUE TITLE
无法识别新版能量罩控件

### ISSUE THREAD

**Issue by Zhang-Ingram** [SuperMonster003/Auto.js_Projects#92]
![fc8413c2469cf7d2853acdf24455777](https://user-images.githubusercontent.com/33376293/64218819-cb9ec480-cef5-11e9-84b1-ce02cec70288.jpg)
如图所示，停留在此页面好一会才退出，日志显示“无可收集能量球”
弱弱的问一下啥时候更新下一个版本，好期待啊

**Comment by SuperMonster003** [comment]
问题已记录  
下一版约10月10日发布 感谢支持

**Comment by SuperMonster003** [comment]
已于 `v1.9.0` 尝试修复此问题  
此 Issue 暂时关闭  
如问题复现或出现新问题 可重新反馈 感谢支持
