### ISSUE TITLE
安卓10增加录屏权限确认

### ISSUE THREAD

**Issue by TakcC** [SuperMonster003/Auto.js_Projects#93]
一加7 安卓10
进入好友界面后提示需要投射/录影权限，每次都要手动去点。能否解决？
不知道其他手机的安卓10是不是也这样。

**Comment by SuperMonster003** [comment]
请提供按钮上的文字文本 (如"允许") 或截图 项目将尝试通过查找按钮文字控件实现按钮自动点击

**Comment by TakcC** [comment]
![Screenshot_20190911-123609](https://user-images.githubusercontent.com/26397391/64668970-446fc480-d492-11e9-9e9b-4b9377ccb098.png)
已补充
