### ISSUE TITLE
最新版的如何设置每天的检测到自己的能量还有1-2分钟就会自动打开收

### ISSUE THREAD

**Issue by calvin369** [SuperMonster003/Auto.js_Projects#94]
总感觉自己不会设置，定时循坏的延时接力管理，基本设置整天，间隔时间又不想设置5分钟自动频繁软件自动打开收，但是要是设置默认的60分钟，前面收了的能量还有3分钟就到了能收的时间，软件这时又不会检测到有收的能量，还是得自己手动点进去，完全不知道怎么调数据，有时候能量是时间很短，相差几分钟就能收下一个了，但由于设置几分钟后软件自动开启，这时就会错过收能量的时间

**Comment by SuperMonster003** [comment]
开启"排行榜最小倒计时机制"可根据排行榜倒计时数据自动设置下一次的定时任务

**Comment by SuperMonster003** [comment]
`v1.9.0` 已增加定时任务控制面板功能配置 可以添加 `一次性/每日/每周` 类型的定时任务
