### ISSUE TITLE
有运行完自动锁屏的功能吗

### ISSUE THREAD

**Issue by yanglihao347** [SuperMonster003/Auto.js_Projects#96]
午休或者人不在手机旁的时候，定时任务运行完手机就会处于解锁状态一直亮在那里，我手机自动锁屏时间是3分钟，这个设置太短了平常使用会很不方便。
所以有没有这种功能：判断此次定时任务，手机如果执行了解锁操作，运行完就锁屏；如果此次任务没有执行解锁操作，运行完就不锁屏。

**Comment by SuperMonster003** [comment]
锁屏需要root权限 你的设备很可能未root 因此代码中的关屏方法失效 下一版将增加使用修改provider数据的方式间接实现的自动关屏功能 其实就是将锁屏时间 (例如你的是3分钟) 通过代码修改为很小的值 等屏幕超时关闭后立即恢复之前的设置值 (如3分钟) 之前也有人有类似的需求  
https://github.com/SuperMonster003/Auto.js_Projects/issues/91#issuecomment-526104939

**Comment by yanglihao347** [comment]
好的了解，不过我和他这个情况不一样，我的日志里没有提到自动关屏这个功能，就正常提示"蚂蚁森林任务结束"。
另外我还有一个小问题我就直接在这里问一下不提新issue了。
我的定时任务有时候在锁屏状态下不会触发，我手动解锁手机以后立马触发。我考虑是autojs没有后台运行的问题，可为什么我一主动点亮屏幕脚本立马就运行了呢。

**Comment by SuperMonster003** [comment]
日志不一样可能是你没有打开开发者测试模式 运行Ant_Forest_Settings.js可以设置
第二个问题属于正常现象 一般会延迟几分钟到十几分钟不等 与安卓的后台执行限制有关 可尝试修改后台限制或节电设置等改善此情况

**Comment by SuperMonster003** [comment]
已于 `v1.9.0` 增加自动关屏备用方案  
此 Issue 暂时关闭  
如问题复现或出现新问题 可重新反馈 感谢支持
