### ISSUE TITLE
某个特定好友始终进不去

### ISSUE THREAD

**Issue by yanglihao347** [SuperMonster003/Auto.js_Projects#97]
我排行榜排名16的好友能量成熟的时候，总是会点进排名8的好友的森林。然后进去发现没有可以收获的，然后再往下时，并不会再次尝试进入16的那个好友的森林，复查时又会进入一次排名8的好友的森林，然后此次任务就会结束。
也就是说，每当我排名16的好友能量成熟时我都会自动点进排名8的好友森林两次。而排名16的好友的能量在我任务结束后还是可收获的状态，并不能被收到。
开发者详细日志我截了图，这里可以发图吗？
![Screenshot_20190920_154556_org autojs autojs](https://user-images.githubusercontent.com/43427774/65310014-e2b10800-dbbf-11e9-809a-9ccd849a9592.jpg)

**Comment by SuperMonster003** [comment]
可尝试将排行榜样本采集策略变更为"图像识别"

**Comment by SuperMonster003** [comment]
`v1.9.5` 已尝试修复上述问题 如使用后问题复现 可继续反馈
