### ISSUE TITLE
华为p30遇到了一些问题

### ISSUE THREAD

**Issue by Carry00** [SuperMonster003/Auto.js_Projects#98]
1，运行后进入森林，不能自动进入好友排行榜。（手动点击查看更多好友能进去）

2，进如排行帮之后，能准确进入好友的森林，并且能收取能量，但是必须手动退出来，才能收取下一个好友的能量。

非常感谢作者的精心设计，之前用使用过一段时间，堪称完美运行，大概从9月份开始就就出现了这个问题，我试过很过方法，重启手机 卸载重装都不能解决， 还望大佬看到后，有时间的话能给回个话， 感激不尽

**Comment by SuperMonster003** [comment]
收到反馈 下一版将针对上述问题尝试做出修复或优化 感谢支持

**Comment by SuperMonster003** [comment]
已于 `v1.9.2` 尝试修复此问题  
此 Issue 暂时关闭  
如问题复现或出现新问题 可重新反馈 感谢支持
