### ISSUE TITLE
支付宝版本10.1.75.7000，新/旧脚本跳转好友界面逻辑异常

### ISSUE THREAD

**Issue by kdc1143** [SuperMonster003/Auto.js_Projects#99]
支付宝版本10.1.75.7000，上一个脚本1.8.4和昨天更新的脚本1.9.0，都是卡在自己的界面，等待很久后，脚本操作退出支付宝，然后重新打开支付宝时直接打开蚂蚁森林好友界面，然后一切正常
支付宝软件更新前10.1.72.7000未遇到任何问题，自己能量收取后很快就会跳转好友界面
删除整个脚本目录，重试，无法解决问题

**Comment by kdc1143** [comment]
补充一下，在等待足够长的时间时，发现脚本可以从自己的树苗状态跳转到好友界面，但是跳转逻辑和之前有变化。
之前是自己没有可收取的能量后很快跳转，现在是没有可收取的能量后等待大概1分钟，然后退出支付宝，之后在打开支付宝时直接打开好友列表界面。
这个跳转的逻辑/等待时间是否还可以继续优化一下，谢谢！

**Comment by SuperMonster003** [comment]
感谢反馈  
`v1.9.1` 已尝试修复

**Comment by chbyiming** [comment]
更新支付宝后发现无法获取好友列表提示：定位“查看更多好友”超时

**Comment by kdc1143** [comment]
v1.9.1 测试正常，谢谢
